// Dense IELTS Writing Task 2 guided-builder exercise for prompt t2-twe-3
// ("Government vs. Private Science Funding").
//
// Generated as a standalone module per task instructions (writingTask2Builder.ts is not
// modified). Mirrors the authoring helpers and dense-exercise conventions already used in
// writingTask2Builder.ts (see the t2-twe-1 exercise there) so this object can later be spliced
// into WGB2_EXERCISES unchanged.
//
// Reconstructing every blank's correct answer must reproduce the essay text in
// scripts/task2-dense/all-essays.json (exId: gb2-twe-3) EXACTLY.

import type { Wgb2Exercise, Wgb2Segment, Wgb2Focus } from '../writingTask2Builder'
import { WGB2_ROLE_LABEL_TH, WGB2_NO_ARTICLE } from '../writingTask2Builder'

const t2 = (text: string): Wgb2Segment => ({ kind: 'text', text })
const sel2 = (
  id: string,
  options: string[],
  answer: string,
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'select', id, options, answer, focus, explain } })
const typ2 = (
  id: string,
  base: string,
  answers: string[],
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'type', id, base, answers, focus, explain } })

export const WGB2_EXERCISE_T2_TWE_3: Wgb2Exercise = {
  id: 'gb2-science-funding',
  promptId: 't2-twe-3',
  steps: [
    {
      id: 'gb2-sf-intro',
      role: 'intro',
      labelTh: WGB2_ROLE_LABEL_TH.intro,
      segments: [
        t2('It '),
        sel2('t2-twe-3x-i0a', ['has', 'have', 'had'], 'has', 'verb-tense', 'ประธาน "It" เอกพจน์ ตามด้วย has (present perfect passive) ไม่ใช่ have'),
        t2(' been '),
        sel2('t2-twe-3x-i0b', ['widely', 'wide', 'width'], 'widely', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argued จึงใช้ widely ไม่ใช่คำคุณศัพท์ wide'),
        t2(' '),
        typ2('t2-twe-3x-i0c', 'argue', ['argued'], 'verb-tense', 'passive voice "has been + V3" จึงใช้ argued (V3)'),
        t2(' that '),
        sel2('t2-twe-3x-i0d', ['while', 'meanwhile', 'whereas'], 'while', 'transition', '"while" ใช้เชื่อมประโยคขัดแย้งภายในประโยคเดียว (subordinating conjunction) ไม่ใช่ meanwhile ที่ต้องอยู่ต้นประโยคใหม่'),
        t2(' private '),
        typ2('t2-twe-3x-i1a', 'company', ['companies'], 'plural', '"private companies" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' can '),
        sel2('t2-twe-3x-i1b', ['drive', 'drives', 'driving'], 'drive', 'verb-tense', 'หลัง modal verb "can" ต้องใช้ base form จึงใช้ drive'),
        t2(' '),
        sel2('t2-twe-3x-i1c', ['rapid', 'rapidly', 'rapidity'], 'rapid', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย technological innovation จึงใช้ rapid ไม่ใช่ adverb rapidly'),
        t2(' '),
        sel2('t2-twe-3x-i1d', ['technological', 'technology', 'technologically'], 'technological', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย innovation จึงใช้ technological ไม่ใช่คำนาม technology'),
        t2(' innovation, scientific research '),
        typ2('t2-twe-3x-i2a', 'should', ['should'], 'verb-tense', '"should ultimately remain" เป็น modal verb ตามด้วย adverb แล้วตามด้วย base form ของกริยา'),
        t2(' '),
        sel2('t2-twe-3x-i2b', ['ultimately', 'ultimate', 'ultimateness'], 'ultimately', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย remain จึงใช้ ultimately'),
        t2(' '),
        sel2('t2-twe-3x-i2c', ['remain', 'remains', 'remained'], 'remain', 'verb-tense', 'หลัง modal verb "should" ต้องใช้ base form จึงใช้ remain'),
        t2(' under government control. Others '),
        typ2('t2-twe-3x-i3a', 'argue', ['argue'], 'verb-tense', 'ประธาน "Others" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' that private '),
        typ2('t2-twe-3x-i3b', 'company', ['companies'], 'plural', '"private companies" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' '),
        sel2('t2-twe-3x-i3c', ['are', 'is', 'was'], 'are', 'verb-tense', 'ประธาน "companies" เป็นพหูพจน์ กริยาปัจจุบันจึงใช้ are'),
        t2(' '),
        sel2('t2-twe-3x-i3d', ['better', 'more good', 'gooder'], 'better', 'participle', 'รูปเปรียบเทียบ (comparative) ของ well คือ better ไม่ใช่ more good หรือ gooder'),
        t2(' '),
        typ2('t2-twe-3x-i3e', 'position', ['positioned'], 'verb-tense', '"are better positioned" ใช้ V3 (past participle) หลัง be-verb ทำหน้าที่คุณศัพท์'),
        t2(' to '),
        sel2('t2-twe-3x-i4a', ['fund', 'funds', 'funding'], 'fund', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ fund'),
        t2(' and '),
        typ2('t2-twe-3x-i4b', 'accelerate', ['accelerate'], 'verb-tense', 'ขนานกับ "fund" ด้านหน้า (parallel base form หลัง to) จึงใช้ accelerate'),
        t2(' '),
        sel2('t2-twe-3x-i4c', ['scientific', 'science', 'scientifically'], 'scientific', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย progress จึงใช้ scientific ไม่ใช่คำนาม science'),
        t2(' progress. I '),
        sel2('t2-twe-3x-i5a', ['personally', 'personal', 'person'], 'personally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย believe จึงใช้ personally'),
        t2(' believe that '),
        typ2('t2-twe-3x-i5b', 'government', ['governments'], 'plural', '"governments" พูดถึงรัฐบาลโดยทั่วไปหลายประเทศ จึงเป็นพหูพจน์'),
        t2(' should retain '),
        sel2('t2-twe-3x-i6a', ['primary', 'primarily', 'primacy'], 'primary', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย control จึงใช้ primary ไม่ใช่คำกริยาวิเศษณ์ primarily'),
        t2(' control over scientific research, and my '),
        typ2('t2-twe-3x-i7a', 'reason', ['reasons'], 'plural', '"my reasons" หมายถึงเหตุผลหลายข้อที่จะกล่าวถึง จึงเป็นพหูพจน์'),
        t2(' will be '),
        typ2('t2-twe-3x-i7b', 'elaborate', ['elaborated'], 'verb-tense', 'passive voice "will be + V3" จึงใช้ elaborated'),
        t2(' on in '),
        sel2('t2-twe-3x-i8a', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the following paragraphs" เจาะจงย่อหน้าถัดไปในเรียงความนี้ จึงใช้ the'),
        t2(' following '),
        typ2('t2-twe-3x-i8b', 'paragraph', ['paragraphs'], 'plural', '"the following paragraphs" หมายถึงย่อหน้าถัดไปหลายย่อหน้า จึงเป็นพหูพจน์'),
        t2('.')
      ]
    },
    {
      id: 'gb2-sf-body1',
      role: 'body1',
      labelTh: WGB2_ROLE_LABEL_TH.body1,
      segments: [
        sel2('t2-twe-3x-b1start', ['To begin with', 'In this respect', 'For instance'], 'To begin with', 'transition', '"To begin with" ใช้เปิดย่อหน้าแรกเพื่อเริ่มเหตุผลข้อแรก'),
        t2(', it '),
        typ2('t2-twe-3x-b1x0', 'might', ['might'], 'verb-tense', '"might seem" เป็น modal verb แสดงความเป็นไปได้ ตามด้วย base form ของกริยา seem'),
        t2(' seem '),
        sel2('t2-twe-3x-b1x1', ['sensible', 'sensibly', 'sense'], 'sensible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง seem จึงใช้ sensible ไม่ใช่ adverb sensibly'),
        t2(' for '),
        sel2('t2-twe-3x-b1x2', ['some', 'anyone', 'anybody'], 'some', 'plural', '"for some to claim" หมายถึงคนบางกลุ่มทั่วไป ใช้รูป some ในบริบทเชิงบวกนี้'),
        t2(' to '),
        typ2('t2-twe-3x-b1x3', 'claim', ['claim'], 'verb-tense', 'หลัง "to" ต้องใช้ infinitive รูปเดิม (base form) จึงใช้ claim'),
        t2(' that private '),
        typ2('t2-twe-3x-b1x4', 'company', ['companies'], 'plural', '"private companies" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' '),
        sel2('t2-twe-3x-b1x5', ['are', 'is', 'was'], 'are', 'verb-tense', 'ประธาน "companies" เป็นพหูพจน์ กริยาปัจจุบันจึงใช้ are'),
        t2(' '),
        sel2('t2-twe-3x-b1x6', ['better', 'more good', 'gooder'], 'better', 'participle', 'รูปเปรียบเทียบ (comparative) ของ well คือ better ไม่ใช่ more good หรือ gooder'),
        t2(' '),
        typ2('t2-twe-3x-b1x7', 'suit', ['suited'], 'verb-tense', '"are better suited" ใช้ V3 (past participle) หลัง be-verb ทำหน้าที่คุณศัพท์'),
        t2(' to '),
        sel2('t2-twe-3x-b1x8', ['lead', 'leads', 'leading'], 'lead', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ lead'),
        t2(' '),
        sel2('t2-twe-3x-b1x9', ['scientific', 'science', 'scientifically'], 'scientific', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย research จึงใช้ scientific ไม่ใช่คำนาม science'),
        t2(' research. '),
        sel2('t2-twe-3x-b1mid', ['To explain it simply', 'However', 'In conclusion'], 'To explain it simply', 'transition', '"To explain it simply" ใช้ก่อนขยายความเหตุผลให้เข้าใจง่ายขึ้น'),
        t2(', '),
        sel2('t2-twe-3x-b1y1', ['this', 'these', 'that'], 'this', 'plural', '"this" อ้างถึงประโยคก่อนหน้าทั้งประโยค (เอกพจน์) จึงใช้ this ไม่ใช่ these'),
        t2(' is '),
        sel2('t2-twe-3x-b1y2', ['possibly', 'possible', 'possibility'], 'possibly', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย is จึงใช้ possibly'),
        t2(' because private '),
        typ2('t2-twe-3x-b1y3', 'firm', ['firms'], 'plural', '"private firms" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' often '),
        sel2('t2-twe-3x-b1y4', ['have', 'has', 'had'], 'have', 'verb-tense', 'ประธาน "firms" เป็นพหูพจน์ กริยาปัจจุบันจึงใช้ have'),
        t2(' '),
        sel2('t2-twe-3x-b1y5', ['greater', 'great', 'greatness'], 'greater', 'participle', 'รูปเปรียบเทียบ (comparative) ของ great คือ greater ขยาย funding'),
        t2(' '),
        typ2('t2-twe-3x-b1y6', 'fund', ['funding'], 'verb-tense', '"funding" เป็นรูป gerund/participle ทำหน้าที่คำนามนับไม่ได้ หลัง greater'),
        t2(' and '),
        sel2('t2-twe-3x-b1y7', ['stronger', 'strong', 'strongly'], 'stronger', 'participle', 'รูปเปรียบเทียบ (comparative) ของ strong คือ stronger ขยาย commercial incentives'),
        t2(' commercial '),
        typ2('t2-twe-3x-b1y8', 'incentive', ['incentives'], 'plural', '"commercial incentives" พูดถึงแรงจูงใจหลายอย่าง จึงเป็นพหูพจน์'),
        t2(' to '),
        typ2('t2-twe-3x-b1y9', 'innovate', ['innovate'], 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ innovate'),
        t2(' quickly'),
        sel2('t2-twe-3x-b1z1', [';', '.', ','], ';', 'punct', 'เชื่อม 2 ประโยคสมบูรณ์เข้าด้วยกันก่อนคำเชื่อม therefore จึงใช้ semicolon (;)'),
        t2(' therefore'),
        sel2('t2-twe-3x-b1z2', [',', '.', ''], ',', 'punct', 'หลังคำเชื่อม therefore ต้องมี comma เสมอก่อนขึ้นประโยคหลัก'),
        t2(' '),
        typ2('t2-twe-3x-b1z3', 'breakthrough', ['breakthroughs'], 'plural', '"breakthroughs" พูดถึงความก้าวหน้าทางวิทยาศาสตร์หลายอย่าง จึงเป็นพหูพจน์'),
        t2(' can '),
        sel2('t2-twe-3x-b1z4', ['reach', 'reaches', 'reached'], 'reach', 'verb-tense', 'หลัง modal verb "can" ต้องใช้ base form จึงใช้ reach'),
        t2(' the public '),
        sel2('t2-twe-3x-b1z5', ['faster', 'fast', 'fastly'], 'faster', 'participle', 'รูปเปรียบเทียบ (comparative) ของ fast คือ faster ไม่มีรูป fastly'),
        t2(' than through government-led '),
        typ2('t2-twe-3x-b1z6', 'project', ['projects'], 'plural', '"government-led projects" พูดถึงโครงการหลายโครงการ จึงเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-3x-b1e1', ['For example', 'However', 'To begin with'], 'For example', 'transition', '"For example" ยกตัวอย่างวัคซีน COVID-19 มาสนับสนุนประโยคก่อนหน้า'),
        t2(', private '),
        sel2('t2-twe-3x-b1e2', ['pharmaceutical', 'pharmacy', 'pharmaceutically'], 'pharmaceutical', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย companies จึงใช้ pharmaceutical ไม่ใช่คำนาม pharmacy'),
        t2(' '),
        typ2('t2-twe-3x-b1e3', 'company', ['companies'], 'plural', '"pharmaceutical companies" พูดถึงบริษัทยาหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-3x-b1e4', 'develop', ['developed'], 'verb-tense', 'อดีตกาล (past simple) ของเหตุการณ์ที่เกิดขึ้นแล้วในช่วงการระบาด จึงใช้ developed'),
        t2(' COVID-19 '),
        typ2('t2-twe-3x-b1e5', 'vaccine', ['vaccines'], 'plural', '"vaccines" พูดถึงวัคซีนหลายชนิด จึงเป็นพหูพจน์'),
        t2(' within less than '),
        sel2('t2-twe-3x-b1e6', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a year" พูดถึงระยะเวลาทั่วไปหนึ่งปี แบบไม่เจาะจง จึงใช้ a'),
        t2(' year of the pandemic beginning. '),
        sel2('t2-twe-3x-b1f1', ['From this perspective', 'It is undeniable', 'To begin with'], 'From this perspective', 'transition', '"From this perspective" สรุปมุมมองก่อนประโยคปิดท้ายย่อหน้า'),
        t2(', it is '),
        sel2('t2-twe-3x-b1f2', ['understandable', 'understanding', 'understood'], 'understandable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ understandable'),
        t2(' why '),
        sel2('t2-twe-3x-b1f3', ['some', 'few', 'little'], 'some', 'plural', '"some would believe" หมายถึงบางคน ใช้ some กับคนทั่วไป ไม่ใช่ few/little'),
        t2(' '),
        typ2('t2-twe-3x-b1f4', 'would', ['would'], 'verb-tense', '"would believe" เป็น modal verb ตามด้วย base form ของกริยา believe'),
        t2(' believe that private '),
        typ2('t2-twe-3x-b1f5', 'company', ['companies'], 'plural', '"private companies" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-3x-b1f6', 'drive', ['drive'], 'verb-tense', 'ประธาน "companies" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-3x-b1f7', ['scientific', 'science', 'scientifically'], 'scientific', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย progress จึงใช้ scientific ไม่ใช่คำนาม science'),
        t2(' progress more effectively than '),
        typ2('t2-twe-3x-b1f8', 'government', ['governments'], 'plural', '"governments" พูดถึงรัฐบาลโดยทั่วไปหลายประเทศ จึงเป็นพหูพจน์'),
        t2('.')
      ]
    },
    {
      id: 'gb2-sf-body2',
      role: 'body2',
      labelTh: WGB2_ROLE_LABEL_TH.body2,
      segments: [
        sel2('t2-twe-3x-b2start', ['However', 'For instance', 'To begin with'], 'However', 'transition', 'ย่อหน้านี้ขัดแย้งกับย่อหน้าก่อนหน้า (concession → rebuttal) จึงใช้ However'),
        t2(', I '),
        typ2('t2-twe-3x-b2x0', 'would', ['would'], 'verb-tense', '"would argue" เป็น modal verb ตามด้วย base form ของกริยา argue'),
        t2(' '),
        sel2('t2-twe-3x-b2x1', ['personally', 'personal', 'person'], 'personally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argue จึงใช้ personally'),
        t2(' argue '),
        sel2('t2-twe-3x-b2favor', ['in favor of', 'in favor for', 'in favor to'], 'in favor of', 'transition', '"argue in favor of" เป็นสำนวนคงที่ ใช้ preposition of เสมอ'),
        t2(' '),
        sel2('t2-twe-3x-b2x2', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the idea that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' idea '),
        sel2('t2-twe-3x-b2x3', ['that', 'which', 'what'], 'that', 'transition', '"the idea that" เป็นสำนวนคงที่ ตามด้วย that-clause เสมอ'),
        t2(' '),
        typ2('t2-twe-3x-b2x4', 'government', ['governments'], 'plural', '"governments" พูดถึงรัฐบาลโดยทั่วไปหลายประเทศ จึงเป็นพหูพจน์'),
        t2(' should '),
        sel2('t2-twe-3x-b2x5', ['retain', 'retains', 'retained'], 'retain', 'verb-tense', 'หลัง modal verb "should" ต้องใช้ base form จึงใช้ retain'),
        t2(' control over '),
        sel2('t2-twe-3x-b2x6', ['scientific', 'science', 'scientifically'], 'scientific', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย research จึงใช้ scientific ไม่ใช่คำนาม science'),
        t2(' research. '),
        sel2('t2-twe-3x-b2mid', ['To put it simply', 'For example', 'In conclusion'], 'To put it simply', 'transition', '"To put it simply" ใช้ก่อนอธิบายเหตุผลให้เข้าใจง่าย'),
        t2(', this '),
        sel2('t2-twe-3x-b2y1', ['is', 'are', 'was'], 'is', 'verb-tense', 'ประธาน "this" เป็นเอกพจน์ กริยาปัจจุบันจึงใช้ is'),
        t2(' due to '),
        sel2('t2-twe-3x-b2y2', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"due to the fact that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' fact that government '),
        typ2('t2-twe-3x-b2y3', 'fund', ['funding'], 'verb-tense', '"funding" เป็นรูป gerund/participle ทำหน้าที่คำนามนับไม่ได้ หลัง government'),
        t2(' '),
        typ2('t2-twe-3x-b2y4', 'ensure', ['ensures'], 'verb-tense', 'ประธาน "government funding" เป็นเอกพจน์ กริยาปัจจุบันจึงเติม -s'),
        t2(' research '),
        typ2('t2-twe-3x-b2y5', 'prioritize', ['prioritizes'], 'verb-tense', 'ประธาน "research" เป็นเอกพจน์ กริยาปัจจุบันจึงเติม -s'),
        t2(' '),
        sel2('t2-twe-3x-b2y6', ['public', 'publicly', 'publicity'], 'public', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย benefit จึงใช้ public ไม่ใช่ adverb publicly'),
        t2(' benefit rather than profit, '),
        typ2('t2-twe-3x-b2y7', 'which', ['which'], 'verb-tense', '"which" เป็น relative pronoun อ้างถึงประโยคก่อนหน้า ใช้รูปเดิมเสมอ'),
        t2(' private '),
        typ2('t2-twe-3x-b2y8', 'company', ['companies'], 'plural', '"private companies" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' cannot always '),
        typ2('t2-twe-3x-b2y9', 'guarantee', ['guarantee'], 'verb-tense', 'หลัง modal verb "cannot" ต้องใช้ base form จึงใช้ guarantee'),
        t2('. '),
        sel2('t2-twe-3x-b2f1', ['For instance', 'However', 'To begin with'], 'For instance', 'transition', '"For instance" ยกตัวอย่างองค์กรอย่าง NASA มาสนับสนุน'),
        t2(', '),
        sel2('t2-twe-3x-b2f2', ['publicly', 'public', 'publicity'], 'publicly', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย funded จึงใช้ publicly'),
        t2(' '),
        typ2('t2-twe-3x-b2f3', 'fund', ['funded'], 'verb-tense', '"publicly funded institutions" ใช้ V3 (past participle) ทำหน้าที่คุณศัพท์วางหน้าคำนาม'),
        t2(' '),
        typ2('t2-twe-3x-b2f4', 'institution', ['institutions'], 'plural', '"institutions" พูดถึงสถาบันหลายแห่งโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' such as NASA '),
        typ2('t2-twe-3x-b2f5', 'have', ['have'], 'verb-tense', 'ประธานพหูพจน์ "institutions" ตามด้วย have (present perfect)'),
        t2(' '),
        typ2('t2-twe-3x-b2f6', 'make', ['made'], 'verb-tense', 'present perfect "have + V3" จึงใช้ made'),
        t2(' '),
        sel2('t2-twe-3x-b2f7', ['major', 'majorly', 'majority'], 'major', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย discoveries จึงใช้ major ไม่ใช่คำนาม majority'),
        t2(' '),
        sel2('t2-twe-3x-b2f8', ['scientific', 'science', 'scientifically'], 'scientific', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย discoveries จึงใช้ scientific'),
        t2(' '),
        typ2('t2-twe-3x-b2f9', 'discovery', ['discoveries'], 'plural', '"discoveries" ลงท้าย -y เปลี่ยนเป็น -ies เมื่อเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-3x-b2g1', 'that', ['that'], 'verb-tense', '"that" เป็น relative pronoun อ้างถึง discoveries ใช้รูปเดิมเสมอ'),
        t2(' '),
        sel2('t2-twe-3x-b2g2', ['were', 'was', 'is'], 'were', 'verb-tense', 'ประธาน "discoveries" เป็นพหูพจน์ กริยา passive ในอดีตจึงใช้ were'),
        t2(' '),
        typ2('t2-twe-3x-b2g3', 'share', ['shared'], 'verb-tense', 'passive voice "were + V3" จึงใช้ shared'),
        t2(' '),
        sel2('t2-twe-3x-b2g4', ['freely', 'free', 'freedom'], 'freely', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย shared จึงใช้ freely'),
        t2(' with the world instead of '),
        sel2('t2-twe-3x-b2g5', ['being', 'been', 'be'], 'being', 'verb-tense', 'หลัง preposition "of" ต้องใช้ gerund จึงใช้ being'),
        t2(' '),
        typ2('t2-twe-3x-b2g6', 'sell', ['sold'], 'verb-tense', 'passive voice "being + V3" จึงใช้ sold'),
        t2(' for profit. '),
        sel2('t2-twe-3x-b2h1', ['In this respect', 'However', 'For example'], 'In this respect', 'transition', '"In this respect" สรุปมุมมองในย่อหน้านี้ก่อนขึ้นประโยคปิดท้าย'),
        t2(', it is '),
        sel2('t2-twe-3x-b2h2', ['evident', 'evidently', 'evidence'], 'evident', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ evident'),
        t2(' that government-controlled research '),
        sel2('t2-twe-3x-b2h3', ['better', 'more good', 'gooder'], 'better', 'participle', 'รูปเปรียบเทียบ (comparative) ของ well คือ better ไม่ใช่ more good หรือ gooder'),
        t2(' '),
        typ2('t2-twe-3x-b2h4', 'serve', ['serves'], 'verb-tense', 'ประธาน "research" เป็นเอกพจน์ กริยาปัจจุบันจึงเติม -s'),
        t2(' the '),
        typ2('t2-twe-3x-b2h5', 'interest', ['interests'], 'plural', '"the interests of society" หมายถึงผลประโยชน์หลายด้าน จึงเป็นพหูพจน์'),
        t2(' of society as a whole.')
      ]
    },
    {
      id: 'gb2-sf-conclusion',
      role: 'conclusion',
      labelTh: WGB2_ROLE_LABEL_TH.conclusion,
      segments: [
        sel2('t2-twe-3x-cstart', ['In conclusion', 'However', 'For example'], 'In conclusion', 'transition', '"In conclusion" เปิดย่อหน้าสรุปเสมอ'),
        t2(', '),
        typ2('t2-twe-3x-cx0', 'although', ['although'], 'verb-tense', '"although" เป็นคำเชื่อมแสดงความขัดแย้ง ใช้รูปเดิมเสมอ ไม่ผัน'),
        t2(' it is '),
        sel2('t2-twe-3x-cx1', ['undeniable', 'undeniably', 'deny'], 'undeniable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ undeniable'),
        t2(' that '),
        sel2('t2-twe-3x-cx2', ['private', 'privately', 'privatize'], 'private', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย companies จึงใช้ private'),
        t2(' '),
        typ2('t2-twe-3x-cx3', 'company', ['companies'], 'plural', '"private companies" พูดถึงบริษัทเอกชนโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' can '),
        sel2('t2-twe-3x-cx4', ['accelerate', 'accelerates', 'accelerated'], 'accelerate', 'verb-tense', 'หลัง modal verb "can" ต้องใช้ base form จึงใช้ accelerate'),
        t2(' '),
        sel2('t2-twe-3x-cx5', ['certain', 'certainly', 'certainty'], 'certain', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย scientific breakthroughs จึงใช้ certain ไม่ใช่ adverb certainly'),
        t2(' '),
        sel2('t2-twe-3x-cx6', ['scientific', 'science', 'scientifically'], 'scientific', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย breakthroughs จึงใช้ scientific'),
        t2(' '),
        typ2('t2-twe-3x-cx7', 'breakthrough', ['breakthroughs'], 'plural', '"breakthroughs" พูดถึงความก้าวหน้าทางวิทยาศาสตร์หลายอย่าง จึงเป็นพหูพจน์'),
        t2(', I am of '),
        sel2('t2-twe-3x-cx8', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"I am of the opinion that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' opinion that '),
        typ2('t2-twe-3x-cx9', 'government', ['governments'], 'plural', '"governments" พูดถึงรัฐบาลโดยทั่วไปหลายประเทศ จึงเป็นพหูพจน์'),
        t2(' should remain in control of scientific research, as this '),
        sel2('t2-twe-3x-cy1', ['best', 'better', 'good'], 'best', 'participle', 'ต้องการคำกริยาวิเศษณ์ขั้นสูงสุด (superlative adverb) ขยาย protects จึงใช้ best'),
        t2(' '),
        sel2('t2-twe-3x-cy2', ['protects', 'protect', 'protected'], 'protects', 'verb-tense', 'ประธาน "this" เป็นเอกพจน์ กริยาปัจจุบันจึงเติม -s'),
        t2(' the '),
        sel2('t2-twe-3x-cy3', ['public', 'publicly', 'publicity'], 'public', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย interest จึงใช้ public'),
        t2(' interest.')
      ]
    }
  ]
}
