// Dense (50 typ2 + 70 sel2) rewrite of the Writing Task 2 guided-builder exercise for
// promptId 't2-twe-5' (builder id 'gb2-responsible-tourism' in writingTask2Builder.ts).
// Reconstructing every blank's correct answer reproduces the essay text in
// scripts/task2-dense/all-essays.json (exId 'gb2-twe-5') exactly — verify with
// scripts/task2-dense/validate.py.
//
// This file is intentionally standalone (writingTask2Builder.ts is not modified): it defines
// its own copies of the t2/typ2/sel2 authoring helpers and imports only the shared Wgb2* types.

import type { Wgb2Exercise, Wgb2Segment, Wgb2Focus } from '../writingTask2Builder'
import { WGB2_ROLE_LABEL_TH, WGB2_NO_ARTICLE } from '../writingTask2Builder'

const t2 = (text: string): Wgb2Segment => ({ kind: 'text', text })

const sel2 = (
  id: string,
  options: string[],
  answer: string,
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'select', id, options, answer, focus, explain } })

const typ2 = (
  id: string,
  base: string,
  answers: string[],
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'type', id, base, answers, focus, explain } })

export const t2Twe5DenseExercise: Wgb2Exercise = {
  id: 'gb2-responsible-tourism',
  promptId: 't2-twe-5',
  steps: [
    {
      id: 'gb2-rt-intro',
      role: 'intro',
      labelTh: WGB2_ROLE_LABEL_TH.intro,
      segments: [
        t2('It '),
        sel2('t2-twe-5-i-has', ['has', 'have', 'had'], 'has', 'verb-tense', 'ประธาน "It" เอกพจน์ ตามด้วย has (present perfect passive) ไม่ใช่ have'),
        t2(' been '),
        sel2('t2-twe-5-i-widely', ['widely', 'wide', 'width'], 'widely', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argued จึงใช้ widely ไม่ใช่คำคุณศัพท์ wide'),
        t2(' '),
        typ2('t2-twe-5-i-argued', 'argue', ['argued'], 'verb-tense', 'passive voice "has been + V3" จึงใช้ argued'),
        t2(' that '),
        sel2('t2-twe-5-i-while', ['while', 'meanwhile', 'whereas'], 'while', 'transition', '"while" ใช้เชื่อมประโยคขัดแย้งภายในประโยคเดียว (subordinating conjunction) ไม่ใช่ meanwhile ที่ต้องอยู่ต้นประโยคใหม่'),
        t2(' tourism '),
        sel2('t2-twe-5-i-inevitably', ['inevitably', 'inevitable', 'inevitability'], 'inevitably', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย affects จึงใช้ inevitably ไม่ใช่คำคุณศัพท์ inevitable'),
        t2(' '),
        typ2('t2-twe-5-i-affects', 'affect', ['affects'], 'verb-tense', 'ประธาน "tourism" เป็นเอกพจน์ จึงใช้ affects'),
        t2(' the '),
        typ2('t2-twe-5-i-places', 'place', ['places'], 'plural', '"the places visited" พูดถึงสถานที่หลายแห่งโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-5-i-visited', 'visit', ['visited'], 'participle', '"the places visited" — V3 ทำหน้าที่คุณศัพท์ขยาย places แปลว่าสถานที่ที่ถูกไปเยือน'),
        t2(', it is '),
        sel2('t2-twe-5-i-impossible', ['impossible', 'impossibly', 'impossibility'], 'impossible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ impossible'),
        t2(' for any tourist to be '),
        sel2('t2-twe-5-i-truly', ['truly', 'true', 'truth'], 'truly', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย responsible จึงใช้ truly'),
        t2(' '),
        sel2('t2-twe-5-i-responsible1', ['responsible', 'responsibly', 'responsibility'], 'responsible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ responsible'),
        t2(' toward both culture and environment. Others '),
        typ2('t2-twe-5-i-argue', 'argue', ['argue'], 'verb-tense', 'ประธาน "Others" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' that with '),
        sel2('t2-twe-5-i-careful', ['careful', 'carefully', 'care'], 'careful', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย planning จึงใช้ careful'),
        t2(' '),
        typ2('t2-twe-5-i-planning', 'plan', ['planning'], 'verb-tense', '"careful planning" เป็น gerund ทำหน้าที่คำนามหลัง with'),
        t2(', '),
        typ2('t2-twe-5-i-tourists', 'tourist', ['tourists'], 'plural', '"tourists" พูดถึงนักท่องเที่ยวโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' can '),
        sel2('t2-twe-5-i-genuinely', ['genuinely', 'genuine', 'genuineness'], 'genuinely', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย reduce จึงใช้ genuinely'),
        t2(' '),
        typ2('t2-twe-5-i-reduce', 'reduce', ['reduce'], 'verb-tense', 'ขนานกับ can + base verb'),
        t2(' their '),
        sel2('t2-twe-5-i-negative', ['negative', 'negatively', 'negativity'], 'negative', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย impact จึงใช้ negative'),
        t2(' impact. I '),
        sel2('t2-twe-5-i-personally', ['personally', 'personal', 'person'], 'personally', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย believe จึงใช้ personally'),
        t2(' believe that '),
        typ2('t2-twe-5-i-being', 'be', ['being'], 'verb-tense', '"being a responsible tourist" เป็น gerund phrase ทำหน้าที่ประธานประโยค'),
        t2(' '),
        sel2('t2-twe-5-i-article-a', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a responsible tourist" พูดถึงนักท่องเที่ยวทั่วไปแบบไม่เจาะจง จึงใช้ a'),
        t2(' responsible tourist is '),
        sel2('t2-twe-5-i-possible', ['possible', 'possibly', 'possibility'], 'possible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ possible'),
        t2(', '),
        sel2('t2-twe-5-i-and', ['and', 'but', 'or'], 'and', 'transition', '"and" เชื่อมประโยคที่มีความหมายต่อเนื่องเสริมกัน ไม่ใช่ but (ขัดแย้ง) หรือ or (ทางเลือก)'),
        t2(' my '),
        sel2('t2-twe-5-i-reasons', ['reasons', 'reason', 'reasoning'], 'reasons', 'plural', '"my reasons" หมายถึงเหตุผลหลายข้อที่จะกล่าวถึง จึงเป็นพหูพจน์'),
        t2(' will be '),
        typ2('t2-twe-5-i-elaborated', 'elaborate', ['elaborated'], 'verb-tense', 'passive voice "will be + V3" จึงใช้ elaborated'),
        t2(' on in '),
        sel2('t2-twe-5-i-article-the', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the following paragraphs" เจาะจงย่อหน้าถัดไปในเรียงความนี้ จึงใช้ the'),
        t2(' following '),
        typ2('t2-twe-5-i-paragraphs', 'paragraph', ['paragraphs'], 'plural', '"the following paragraphs" หมายถึงย่อหน้าถัดไปหลายย่อหน้า จึงเป็นพหูพจน์'),
        t2('.')
      ]
    },
    {
      id: 'gb2-rt-body1',
      role: 'body1',
      labelTh: WGB2_ROLE_LABEL_TH.body1,
      segments: [
        sel2('t2-twe-5-b1start', ['To begin with', 'To explain it simply', 'For example'], 'To begin with', 'transition', '"To begin with" ใช้เปิดย่อหน้าแรกเพื่อเริ่มเหตุผลข้อแรก'),
        t2(', it '),
        typ2('t2-twe-5-b1-might', 'might', ['might'], 'verb-tense', '"might seem" เป็น modal verb แสดงความเป็นไปได้ ตามด้วย base form ของกริยา seem'),
        t2(' seem '),
        sel2('t2-twe-5-b1-sensible', ['sensible', 'sensibly', 'sense'], 'sensible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง seem จึงใช้ sensible ไม่ใช่ adverb sensibly'),
        t2(' for '),
        sel2('t2-twe-5-b1-some1', ['some', 'anyone', 'anybody'], 'some', 'plural', '"for some to claim" หมายถึงคนบางกลุ่มทั่วไป ใช้รูป some ในบริบทเชิงบวกนี้'),
        t2(' to '),
        typ2('t2-twe-5-b1-claim', 'claim', ['claim'], 'verb-tense', 'หลัง "to" ต้องใช้ infinitive รูปเดิม (base form) จึงใช้ claim'),
        t2(' that '),
        sel2('t2-twe-5-b1-responsible1', ['responsible', 'responsibly', 'responsibility'], 'responsible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย tourism จึงใช้ responsible'),
        t2(' tourism '),
        typ2('t2-twe-5-b1-is1', 'be', ['is'], 'verb-tense', 'ประธาน "responsible tourism" เป็นเอกพจน์ จึงใช้ is'),
        t2(' '),
        sel2('t2-twe-5-b1-impossible', ['impossible', 'impossibly', 'impossibility'], 'impossible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ impossible'),
        t2(' to '),
        typ2('t2-twe-5-b1-achieve', 'achieve', ['achieve'], 'verb-tense', 'ขนานกับ to + base verb'),
        t2('. '),
        sel2('t2-twe-5-b1mid', ['To explain it simply', 'To begin with', 'From this perspective'], 'To explain it simply', 'transition', '"To explain it simply" ใช้ก่อนขยายความเหตุผลให้เข้าใจง่ายขึ้น'),
        t2(', '),
        sel2('t2-twe-5-b1-this', ['this', 'these', 'that'], 'this', 'plural', '"this" อ้างถึงประโยคก่อนหน้าทั้งประโยค (เอกพจน์) จึงใช้ this ไม่ใช่ these'),
        t2(' '),
        typ2('t2-twe-5-b1-is2', 'be', ['is'], 'verb-tense', 'ประธาน "this" เป็นเอกพจน์ กริยาปัจจุบันจึงใช้ is'),
        t2(' '),
        sel2('t2-twe-5-b1-possibly', ['possibly', 'possible', 'possibility'], 'possibly', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย is จึงใช้ possibly'),
        t2(' because even eco-friendly '),
        sel2('t2-twe-5-b1-travel', ['travel', 'traveling', 'traveled'], 'travel', 'noun', 'ต้องการคำนาม (noun) เป็นประธานประโยค จึงใช้ travel ไม่ผันเป็น -ing หรือ -ed'),
        t2(' '),
        typ2('t2-twe-5-b1-requires', 'require', ['requires'], 'verb-tense', 'ประธาน "eco-friendly travel" เป็นเอกพจน์ จึงใช้ requires'),
        t2(' transportation that '),
        typ2('t2-twe-5-b1-produces', 'produce', ['produces'], 'verb-tense', 'ประธาน "transportation that" เป็นเอกพจน์ จึงใช้ produces'),
        t2(' carbon '),
        typ2('t2-twe-5-b1-emissions1', 'emission', ['emissions'], 'plural', '"carbon emissions" หมายถึงการปล่อยคาร์บอนหลายครั้ง จึงเป็นพหูพจน์'),
        sel2('t2-twe-5-b1-semicolon', [';', '.', ','], ';', 'punct', 'semicolon (;) ก่อน therefore ที่เชื่อมสองประโยคสมบูรณ์ที่เกี่ยวข้องกัน'),
        t2(' therefore'),
        sel2('t2-twe-5-b1-comma-therefore', [',', '.', ''], ',', 'punct', 'comma (,) หลัง therefore ก่อนขึ้นใจความหลักของประโยค'),
        t2(' every visit inevitably '),
        typ2('t2-twe-5-b1-damages', 'damage', ['damages'], 'verb-tense', 'ประธาน "every visit" เป็นเอกพจน์ จึงใช้ damages'),
        t2(' the environment to some '),
        sel2('t2-twe-5-b1-degree', ['degree', 'degrees', 'degreed'], 'degree', 'plural', 'สำนวน "to some degree" ใช้ degree เอกพจน์เสมอ ไม่ผันเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-5-b1e', ['For example', 'To begin with', 'In this respect'], 'For example', 'transition', '"For example" ยกตัวอย่างเที่ยวบินไปหมู่เกาะมัลดีฟส์'),
        t2(', '),
        typ2('t2-twe-5-b1-flights', 'flight', ['flights'], 'plural', '"flights" พูดถึงเที่ยวบินหลายเที่ยวโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' to '),
        sel2('t2-twe-5-b1-popular', ['popular', 'popularly', 'popularity'], 'popular', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย destinations จึงใช้ popular'),
        t2(' island '),
        typ2('t2-twe-5-b1-destinations', 'destination', ['destinations'], 'plural', '"island destinations" หมายถึงจุดหมายปลายทางหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' such as the Maldives '),
        typ2('t2-twe-5-b1-contribute', 'contribute', ['contribute'], 'verb-tense', 'ประธาน "flights" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-5-b1-significantly', ['significantly', 'significant', 'significance'], 'significantly', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย contribute จึงใช้ significantly'),
        t2(' to '),
        sel2('t2-twe-5-b1-global', ['global', 'globally', 'globe'], 'global', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย carbon emissions จึงใช้ global'),
        t2(' carbon '),
        typ2('t2-twe-5-b1-emissions2', 'emission', ['emissions'], 'plural', '"global carbon emissions" หมายถึงการปล่อยคาร์บอนหลายครั้งโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' regardless of '),
        sel2('t2-twe-5-b1-article-a', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a tourist\'s intentions" พูดถึงนักท่องเที่ยวทั่วไปแบบไม่เจาะจง จึงใช้ a'),
        t2(' tourist\'s '),
        typ2('t2-twe-5-b1-intentions', 'intention', ['intentions'], 'plural', '"intentions" หมายถึงความตั้งใจหลายอย่าง จึงเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-5-b1g', ['From this perspective', 'To explain it simply', 'For instance'], 'From this perspective', 'transition', '"From this perspective" สรุปมุมมองของฝ่ายที่เห็นต่างก่อนขึ้นย่อหน้าถัดไป'),
        t2(', it is '),
        sel2('t2-twe-5-b1-understandable', ['understandable', 'understanding', 'understood'], 'understandable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ understandable'),
        t2(' why '),
        sel2('t2-twe-5-b1-some2', ['some', 'few', 'little'], 'some', 'plural', '"some would believe" หมายถึงบางคน ใช้ some กับคนทั่วไป ไม่ใช่ few/little'),
        t2(' '),
        typ2('t2-twe-5-b1-would', 'would', ['would'], 'verb-tense', '"would believe" เป็น modal verb ตามด้วย base form ของกริยา believe'),
        t2(' '),
        typ2('t2-twe-5-b1-believe', 'believe', ['believe'], 'verb-tense', 'หลัง modal "would" ต้องใช้ base form จึงใช้ believe'),
        t2(' that no tourist can be '),
        sel2('t2-twe-5-b1-entirely', ['entirely', 'entire', 'entirety'], 'entirely', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย responsible จึงใช้ entirely'),
        t2(' '),
        sel2('t2-twe-5-b1-responsible2', ['responsible', 'responsibly', 'responsibility'], 'responsible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ responsible'),
        t2('.')
      ]
    },
    {
      id: 'gb2-rt-body2',
      role: 'body2',
      labelTh: WGB2_ROLE_LABEL_TH.body2,
      segments: [
        sel2('t2-twe-5-b2start', ['However', 'To begin with', 'For example'], 'However', 'transition', '"However" เปิดย่อหน้าเพื่อโต้แย้งมุมมองในย่อหน้าก่อนหน้า'),
        t2(', I '),
        typ2('t2-twe-5-b2-would', 'would', ['would'], 'verb-tense', '"would argue" เป็น modal verb ตามด้วย base form ของกริยา argue'),
        t2(' '),
        sel2('t2-twe-5-b2-personally', ['personally', 'personal', 'person'], 'personally', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argue จึงใช้ personally'),
        t2(' argue '),
        sel2('t2-twe-5-b2-favor', ['in favor of', 'in favor for', 'in favor to'], 'in favor of', 'transition', '"argue in favor of" เป็นสำนวนคงที่ ใช้ preposition of เสมอ'),
        t2(' '),
        sel2('t2-twe-5-b2-article-the1', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the idea that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' idea '),
        sel2('t2-twe-5-b2-that', ['that', 'which', 'what'], 'that', 'transition', '"the idea that" เป็นสำนวนคงที่ ตามด้วย that-clause เสมอ'),
        t2(' '),
        sel2('t2-twe-5-b2-responsible1', ['responsible', 'responsibly', 'responsibility'], 'responsible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย tourism จึงใช้ responsible'),
        t2(' tourism '),
        typ2('t2-twe-5-b2-is1', 'be', ['is'], 'verb-tense', 'ประธาน "responsible tourism" เป็นเอกพจน์ จึงใช้ is'),
        t2(' '),
        sel2('t2-twe-5-b2-achievable1', ['achievable', 'achieve', 'achieving'], 'achievable', 'participle', '"-able" adjective form แปลว่าสามารถทำได้ ต้องการคำคุณศัพท์หลัง be-verb'),
        t2('. '),
        sel2('t2-twe-5-b2mid', ['To put it simply', 'However', 'In this respect'], 'To put it simply', 'transition', '"To put it simply" ใช้ก่อนขยายความเหตุผลให้เข้าใจง่ายขึ้น'),
        t2(', '),
        sel2('t2-twe-5-b2-this', ['this', 'these', 'that'], 'this', 'plural', '"this" อ้างถึงประโยคก่อนหน้าทั้งประโยค (เอกพจน์) จึงใช้ this ไม่ใช่ these'),
        t2(' '),
        typ2('t2-twe-5-b2-is2', 'be', ['is'], 'verb-tense', 'ประธาน "this" เป็นเอกพจน์ กริยาปัจจุบันจึงใช้ is'),
        t2(' due to '),
        sel2('t2-twe-5-b2-article-the2', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"due to the fact that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' fact that '),
        typ2('t2-twe-5-b2-tourists', 'tourist', ['tourists'], 'plural', '"tourists" พูดถึงนักท่องเที่ยวโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' can '),
        typ2('t2-twe-5-b2-make', 'make', ['make'], 'verb-tense', 'ขนานกับ can + base verb'),
        t2(' '),
        sel2('t2-twe-5-b2-deliberate', ['deliberate', 'deliberately', 'deliberation'], 'deliberate', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย choices จึงใช้ deliberate'),
        t2(' '),
        typ2('t2-twe-5-b2-choices', 'choice', ['choices'], 'plural', '"deliberate choices" หมายถึงการเลือกหลายอย่าง จึงเป็นพหูพจน์'),
        t2(', such as '),
        typ2('t2-twe-5-b2-supporting', 'support', ['supporting'], 'verb-tense', '"such as supporting..." ตามด้วย gerund หลัง such as'),
        t2(' local '),
        typ2('t2-twe-5-b2-businesses', 'business', ['businesses'], 'plural', '"local businesses" หมายถึงธุรกิจหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' and '),
        typ2('t2-twe-5-b2-respecting', 'respect', ['respecting'], 'verb-tense', 'ขนานกับ supporting ด้านหน้า (parallel gerund)'),
        t2(' local '),
        typ2('t2-twe-5-b2-customs', 'custom', ['customs'], 'plural', '"local customs" หมายถึงประเพณีหลายอย่าง จึงเป็นพหูพจน์'),
        t2(', which '),
        sel2('t2-twe-5-b2-significantly', ['significantly', 'significant', 'significance'], 'significantly', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย reduce จึงใช้ significantly'),
        t2(' '),
        typ2('t2-twe-5-b2-reduce', 'reduce', ['reduce'], 'verb-tense', 'ประธาน "which" อ้างถึง choices ที่เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' their '),
        sel2('t2-twe-5-b2-overall', ['overall', 'overalls', 'over'], 'overall', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย impact จึงใช้ overall'),
        t2(' impact. '),
        sel2('t2-twe-5-b2e', ['For instance', 'To put it simply', 'In this respect'], 'For instance', 'transition', '"For instance" ยกตัวอย่างประเทศภูฏาน'),
        t2(', many '),
        typ2('t2-twe-5-b2-visitors', 'visitor', ['visitors'], 'plural', '"many visitors" หมายถึงนักท่องเที่ยวหลายคน จึงเป็นพหูพจน์'),
        t2(' to Bhutan '),
        typ2('t2-twe-5-b2-follow', 'follow', ['follow'], 'verb-tense', 'ประธาน "many visitors" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-5-b2-strict', ['strict', 'strictly', 'strictness'], 'strict', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย guidelines จึงใช้ strict'),
        t2(' government '),
        typ2('t2-twe-5-b2-guidelines', 'guideline', ['guidelines'], 'plural', '"government guidelines" หมายถึงแนวปฏิบัติหลายข้อ จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-5-b2-designed', 'design', ['designed'], 'participle', '"guidelines designed to protect..." — V3 ทำหน้าที่คุณศัพท์ขยาย guidelines'),
        t2(' to protect both the environment and '),
        sel2('t2-twe-5-b2-traditional', ['traditional', 'traditionally', 'tradition'], 'traditional', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย culture จึงใช้ traditional'),
        t2(' culture. '),
        sel2('t2-twe-5-b2h', ['In this respect', 'For instance', 'However'], 'In this respect', 'transition', '"In this respect" สรุปมุมมองในย่อหน้านี้ก่อนขึ้นประโยคปิดท้าย'),
        t2(', it is '),
        sel2('t2-twe-5-b2-evident', ['evident', 'evidently', 'evidence'], 'evident', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ evident'),
        t2(' that responsible tourism, while '),
        sel2('t2-twe-5-b2-not', ['not', 'no', 'none'], 'not', 'transition', '"while not perfect" ปฏิเสธคำคุณศัพท์ที่ตามมาโดยตรง จึงใช้ not'),
        t2(' '),
        sel2('t2-twe-5-b2-perfect', ['perfect', 'perfectly', 'perfection'], 'perfect', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง not จึงใช้ perfect'),
        t2(', is '),
        sel2('t2-twe-5-b2-article-a2', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a realistic and achievable goal" พูดถึงเป้าหมายทั่วไปแบบไม่เจาะจง จึงใช้ a'),
        t2(' '),
        sel2('t2-twe-5-b2-realistic', ['realistic', 'realistically', 'reality'], 'realistic', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย goal จึงใช้ realistic'),
        t2(' and '),
        sel2('t2-twe-5-b2-achievable2', ['achievable', 'achieve', 'achieving'], 'achievable', 'participle', 'ขนานกับ realistic ด้านหน้า (parallel adjective) ขยาย goal'),
        t2(' goal.')
      ]
    },
    {
      id: 'gb2-rt-conclusion',
      role: 'conclusion',
      labelTh: WGB2_ROLE_LABEL_TH.conclusion,
      segments: [
        sel2('t2-twe-5-cstart', ['In conclusion', 'However', 'For example'], 'In conclusion', 'transition', '"In conclusion" เปิดย่อหน้าสรุปเสมอ'),
        t2(', '),
        typ2('t2-twe-5-c-although', 'although', ['although'], 'verb-tense', '"although" เป็นคำเชื่อมแสดงความขัดแย้ง ใช้รูปเดิมเสมอ ไม่ผัน'),
        t2(' it is '),
        sel2('t2-twe-5-c-undeniable', ['undeniable', 'undeniably', 'deny'], 'undeniable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ undeniable'),
        t2(' that all '),
        typ2('t2-twe-5-c-tourism', 'tourism', ['tourism'], 'plural', '"tourism" เป็นนามนับไม่ได้ (uncountable) จึงไม่เติม -s'),
        t2(' '),
        typ2('t2-twe-5-c-carries', 'carry', ['carries'], 'verb-tense', 'ประธาน "tourism" เป็นเอกพจน์ จึงใช้ carries'),
        t2(' some '),
        sel2('t2-twe-5-c-environmental', ['environmental', 'environment', 'environmentally'], 'environmental', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย cost จึงใช้ environmental'),
        t2(' '),
        sel2('t2-twe-5-c-cost', ['cost', 'costs', 'costly'], 'cost', 'plural', '"some environmental cost" ใช้นามนับไม่ได้เอกพจน์ cost ไม่ใช่ costs'),
        t2(', I '),
        typ2('t2-twe-5-c-am', 'be', ['am'], 'verb-tense', 'ประธาน "I" ตามด้วย am (present simple ของ be) จึงใช้ am'),
        t2(' of '),
        sel2('t2-twe-5-c-article-the', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"I am of the opinion that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' opinion that '),
        typ2('t2-twe-5-c-being', 'be', ['being'], 'verb-tense', '"being a responsible tourist" เป็น gerund phrase ทำหน้าที่ประธานประโยค'),
        t2(' '),
        sel2('t2-twe-5-c-article-a', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a responsible tourist" พูดถึงนักท่องเที่ยวทั่วไปแบบไม่เจาะจง จึงใช้ a'),
        t2(' responsible tourist is '),
        sel2('t2-twe-5-c-possible', ['possible', 'possibly', 'possibility'], 'possible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ possible'),
        t2(', as '),
        sel2('t2-twe-5-c-thoughtful', ['thoughtful', 'thoughtfully', 'thought'], 'thoughtful', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย choices จึงใช้ thoughtful'),
        t2(' '),
        typ2('t2-twe-5-c-choices', 'choice', ['choices'], 'plural', '"thoughtful choices" หมายถึงการเลือกหลายอย่าง จึงเป็นพหูพจน์'),
        t2(' can '),
        sel2('t2-twe-5-c-greatly', ['greatly', 'great', 'greatness'], 'greatly', 'adverb', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย reduce จึงใช้ greatly'),
        t2(' '),
        typ2('t2-twe-5-c-reduce', 'reduce', ['reduce'], 'verb-tense', 'ขนานกับ can + base verb'),
        t2(' this '),
        typ2('t2-twe-5-c-impact', 'impact', ['impact'], 'plural', '"this impact" เป็นนามนับไม่ได้ในบริบทนี้ (uncountable) จึงไม่เติม -s'),
        t2('.')
      ]
    }
  ]
}

export default t2Twe5DenseExercise
