// Dense (50 typ2 + 70 sel2) draft for IELTS Writing Task 2 guided-builder exercise `t2-twe-6`
// ("Should extinction be prevented?" / builder id `gb2-prevent-extinction`).
//
// Standalone module — intentionally NOT wired into writingTask2Builder.ts's WGB2_EXERCISES yet.
// Mirrors the Wgb2Exercise shape from writingTask2Builder.ts; every blank's reconstructed
// answer must reproduce the essay text in scripts/task2-dense/all-essays.json (promptId
// `t2-twe-6`) exactly. Validate with scripts/task2-dense/validate.py.

import type { Wgb2Exercise, Wgb2Segment, Wgb2Focus } from '../writingTask2Builder'
import { WGB2_NO_ARTICLE, WGB2_ROLE_LABEL_TH } from '../writingTask2Builder'

const t2 = (text: string): Wgb2Segment => ({ kind: 'text', text })

const sel2 = (
  id: string,
  options: string[],
  answer: string,
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'select', id, options, answer, focus, explain } })

const typ2 = (
  id: string,
  base: string,
  answers: string[],
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'type', id, base, answers, focus, explain } })

export const t2Twe6DenseExercise: Wgb2Exercise = {
  id: 'gb2-prevent-extinction',
  promptId: 't2-twe-6',
  steps: [
    {
      id: 'gb2-pe-dense-intro',
      role: 'intro',
      labelTh: WGB2_ROLE_LABEL_TH.intro,
      segments: [
        t2('It '),
        sel2('t2-twe-6d-i01', ['has', 'have', 'had'], 'has', 'verb-tense', 'ประธาน "It" เอกพจน์ ตามด้วย has (present perfect passive) ไม่ใช่ have'),
        t2(' been '),
        sel2('t2-twe-6d-i02', ['widely', 'wide', 'width'], 'widely', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argued จึงใช้ widely ไม่ใช่คำคุณศัพท์ wide'),
        t2(' '),
        typ2('t2-twe-6d-i03', 'argue', ['argued'], 'verb-tense', 'passive voice "has been + V3" จึงใช้ argued (V3)'),
        t2(' that '),
        sel2('t2-twe-6d-i04', ['while', 'meanwhile', 'whereas'], 'while', 'transition', '"while" ใช้เชื่อมประโยคขัดแย้งภายในประโยคเดียว (subordinating conjunction) ไม่ใช่ meanwhile ที่ต้องอยู่ต้นประโยคใหม่'),
        t2(' extinction '),
        sel2('t2-twe-6d-i05', ['has', 'have', 'had'], 'has', 'verb-tense', 'ประธาน "extinction" เอกพจน์ ตามด้วย has (present perfect) ไม่ใช่ have'),
        t2(' '),
        typ2('t2-twe-6d-i06', 'occur', ['occurred'], 'verb-tense', 'present perfect "has + V3" จึงใช้ occurred'),
        t2(' '),
        sel2('t2-twe-6d-i07', ['naturally', 'natural', 'nature'], 'naturally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย occurred จึงใช้ naturally ไม่ใช่คำคุณศัพท์ natural'),
        t2(' throughout Earth\'s history, '),
        typ2('t2-twe-6d-i08', 'human', ['humans'], 'plural', '"humans" พูดถึงมนุษย์โดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' '),
        sel2('t2-twe-6d-i09', ['have', 'has', 'had'], 'have', 'verb-tense', 'ประธาน "humans" พหูพจน์ ตามด้วย have ไม่ใช่ has'),
        t2(' no '),
        sel2('t2-twe-6d-i10', ['obligation', 'obligations', 'obligate'], 'obligation', 'plural', '"no obligation" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2(' to '),
        sel2('t2-twe-6d-i11', ['prevent', 'prevents', 'prevented'], 'prevent', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ prevent'),
        t2(' animal species from '),
        typ2('t2-twe-6d-i12', 'die', ['dying'], 'verb-tense', '"prevent...from dying out" ตามด้วย gerund หลัง from'),
        t2(' out today. '),
        t2('Others '),
        typ2('t2-twe-6d-i13', 'argue', ['argue'], 'verb-tense', 'ประธาน "Others" พหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' that '),
        sel2('t2-twe-6d-i14', ['people', 'person', 'peoples'], 'people', 'plural', '"people" เป็นคำนามพหูพจน์ไม่ปกติ (irregular plural) ใช้รูปนี้เสมอ'),
        t2(' '),
        typ2('t2-twe-6d-i15', 'have', ['have'], 'verb-tense', 'ประธาน "people" พหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-6d-i16', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a responsibility" พูดถึงความรับผิดชอบทั่วไปแบบไม่เจาะจง จึงใช้ a'),
        t2(' responsibility to '),
        sel2('t2-twe-6d-i17', ['protect', 'protects', 'protected'], 'protect', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ protect'),
        t2(' '),
        sel2('t2-twe-6d-i18', ['endangered', 'endanger', 'endangering'], 'endangered', 'participle', '"endangered species" ใช้ V3 ทำหน้าที่คุณศัพท์ขยาย species'),
        t2(' species from '),
        typ2('t2-twe-6d-i19', 'disappear', ['disappearing'], 'verb-tense', '"protect...from disappearing" ตามด้วย gerund หลัง from'),
        t2(' '),
        sel2('t2-twe-6d-i20', ['completely', 'complete', 'completeness'], 'completely', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย disappearing จึงใช้ completely'),
        t2('. I '),
        sel2('t2-twe-6d-i21', ['personally', 'personal', 'person'], 'personally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย believe จึงใช้ personally'),
        t2(' believe that '),
        typ2('t2-twe-6d-i22', 'human', ['humans'], 'plural', '"humans" พูดถึงมนุษย์โดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' '),
        sel2('t2-twe-6d-i23', ['should', 'must', 'could'], 'should', 'verb-tense', '"should" ใช้แสดงความคิดเห็น/ข้อเสนอแนะที่เหมาะสมในเรียงความเชิงโต้แย้ง ไม่ใช่ must (ข้อบังคับ) หรือ could (ความเป็นไปได้)'),
        t2(' '),
        sel2('t2-twe-6d-i24', ['actively', 'active', 'activity'], 'actively', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย work จึงใช้ actively ไม่ใช่คำคุณศัพท์ active'),
        t2(' '),
        typ2('t2-twe-6d-i25', 'work', ['work'], 'verb-tense', 'หลัง modal "should" ต้องใช้ base form จึงใช้ work'),
        t2(' to prevent extinction, '),
        sel2('t2-twe-6d-i26', ['and', 'but', 'or'], 'and', 'transition', '"and" เชื่อมประโยคที่มีความหมายต่อเนื่องเสริมกัน ไม่ใช่ but (ขัดแย้ง) หรือ or (ทางเลือก)'),
        t2(' my '),
        sel2('t2-twe-6d-i27', ['reasons', 'reason', 'reasoning'], 'reasons', 'plural', '"my reasons" หมายถึงเหตุผลหลายข้อที่จะกล่าวถึง จึงเป็นพหูพจน์'),
        t2(' will be '),
        typ2('t2-twe-6d-i28', 'elaborate', ['elaborated'], 'verb-tense', 'passive voice "will be + V3" จึงใช้ elaborated'),
        t2(' on in '),
        sel2('t2-twe-6d-i29', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the following paragraphs" เจาะจงย่อหน้าถัดไปในเรียงความนี้ จึงใช้ the'),
        t2(' following '),
        typ2('t2-twe-6d-i30', 'paragraph', ['paragraphs'], 'plural', '"the following paragraphs" หมายถึงย่อหน้าถัดไปหลายย่อหน้า จึงเป็นพหูพจน์'),
        t2('.')
      ]
    },
    {
      id: 'gb2-pe-dense-body1',
      role: 'body1',
      labelTh: WGB2_ROLE_LABEL_TH.body1,
      segments: [
        sel2('t2-twe-6d-b101', ['To begin with', 'To explain it simply', 'For example'], 'To begin with', 'transition', '"To begin with" ใช้เปิดย่อหน้าแรกเพื่อเริ่มเหตุผลข้อแรก'),
        t2(', it '),
        typ2('t2-twe-6d-b102', 'might', ['might'], 'verb-tense', '"might seem" เป็น modal verb แสดงความเป็นไปได้ ตามด้วย base form ของกริยา seem'),
        t2(' seem '),
        sel2('t2-twe-6d-b103', ['sensible', 'sensibly', 'sense'], 'sensible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง seem จึงใช้ sensible ไม่ใช่ adverb sensibly'),
        t2(' for '),
        sel2('t2-twe-6d-b104', ['some', 'anyone', 'anybody'], 'some', 'plural', '"for some to claim" หมายถึงคนบางกลุ่มทั่วไป ใช้รูป some ในบริบทเชิงบวกนี้'),
        t2(' to '),
        typ2('t2-twe-6d-b105', 'claim', ['claim'], 'verb-tense', 'หลัง "to" ต้องใช้ infinitive รูปเดิม (base form) จึงใช้ claim'),
        t2(' that extinction '),
        typ2('t2-twe-6d-b106', 'be', ['is'], 'verb-tense', 'ประธาน "extinction" เอกพจน์ จึงใช้ is (present simple ของ be)'),
        t2(' '),
        sel2('t2-twe-6d-b107', ['simply', 'simple', 'simplicity'], 'simply', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย is จึงใช้ simply ไม่ใช่คำคุณศัพท์ simple'),
        t2(' '),
        sel2('t2-twe-6d-b108', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a natural process" พูดถึงกระบวนการทั่วไปแบบไม่เจาะจง จึงใช้ a'),
        t2(' '),
        sel2('t2-twe-6d-b109', ['natural', 'naturally', 'nature'], 'natural', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย process จึงใช้ natural ไม่ใช่คำนาม nature'),
        t2(' '),
        typ2('t2-twe-6d-b110', 'process', ['process'], 'plural', '"a natural process" มี "a" นำหน้าจึงเป็นเอกพจน์ ไม่เติม s'),
        t2(' that should not be '),
        typ2('t2-twe-6d-b111', 'interfere', ['interfered'], 'verb-tense', 'โครงสร้าง passive voice "should not be + V3" จึงต้องใช้ interfered'),
        t2(' with. '),
        sel2('t2-twe-6d-b112', ['To explain it simply', 'However', 'In conclusion'], 'To explain it simply', 'transition', '"To explain it simply" ใช้ก่อนขยายความเหตุผลให้เข้าใจง่ายขึ้น'),
        t2(', '),
        sel2('t2-twe-6d-b113', ['this', 'these', 'that'], 'this', 'plural', '"this" อ้างถึงประโยคก่อนหน้าทั้งประโยค (เอกพจน์) จึงใช้ this ไม่ใช่ these'),
        t2(' is '),
        sel2('t2-twe-6d-b114', ['possibly', 'possible', 'possibility'], 'possibly', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย is จึงใช้ possibly'),
        t2(' because countless species, including '),
        typ2('t2-twe-6d-b115', 'dinosaur', ['dinosaurs'], 'plural', '"dinosaurs" พูดถึงไดโนเสาร์หลายสายพันธุ์โดยทั่วไป จึงเป็นพหูพจน์'),
        t2(', '),
        typ2('t2-twe-6d-b116', 'vanish', ['vanished'], 'verb-tense', 'เหตุการณ์ในอดีตที่จบแล้ว (past simple) จึงใช้ vanished'),
        t2(' long before '),
        typ2('t2-twe-6d-b117', 'human', ['humans'], 'plural', '"humans" พูดถึงมนุษย์โดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-6d-b118', 'exist', ['existed'], 'verb-tense', 'เหตุการณ์ในอดีตที่จบแล้ว (past simple) จึงใช้ existed'),
        sel2('t2-twe-6d-b119', [';', '.', ','], ';', 'punct', 'semicolon ก่อน therefore ที่เชื่อมสองประโยคสมบูรณ์ที่เกี่ยวข้องกัน'),
        t2(' therefore'),
        sel2('t2-twe-6d-b120', [',', '.', ''], ',', 'punct', 'comma หลัง therefore ก่อนขึ้นใจความหลักของประโยค'),
        t2(' '),
        sel2('t2-twe-6d-b121', ['some', 'few', 'little'], 'some', 'plural', '"some believe" หมายถึงบางคน ใช้ some กับคนทั่วไป ไม่ใช่ few/little'),
        t2(' '),
        typ2('t2-twe-6d-b122', 'believe', ['believe'], 'verb-tense', 'ประธาน "some" พหูพจน์ในบริบทนี้ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-6d-b123', ['modern', 'modernly', 'modernize'], 'modern', 'participle', '"modern extinctions" ต้องการคำคุณศัพท์ (adjective) ขยาย extinctions จึงใช้ modern'),
        t2(' '),
        typ2('t2-twe-6d-b124', 'extinction', ['extinctions'], 'plural', '"modern extinctions" พูดถึงการสูญพันธุ์หลายครั้งในปัจจุบัน จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-6d-b125', 'be', ['are'], 'verb-tense', 'ประธาน "extinctions" พหูพจน์ จึงใช้ are'),
        t2(' '),
        sel2('t2-twe-6d-b126', ['merely', 'mere', 'merit'], 'merely', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย part of... จึงใช้ merely ไม่ใช่คำคุณศัพท์ mere'),
        t2(' part of '),
        sel2('t2-twe-6d-b127', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the same natural cycle" เจาะจงวัฏจักรที่กล่าวถึง จึงใช้ the'),
        t2(' same '),
        sel2('t2-twe-6d-b128', ['natural', 'naturally', 'nature'], 'natural', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย cycle จึงใช้ natural'),
        t2(' cycle. '),
        sel2('t2-twe-6d-b129', ['For example', 'To begin with', 'However'], 'For example', 'transition', '"For example" ยกตัวอย่างสัตว์เลี้ยงลูกด้วยนมในยุคน้ำแข็ง'),
        t2(', several land mammal species '),
        typ2('t2-twe-6d-b130', 'disappear', ['disappeared'], 'verb-tense', 'เหตุการณ์ในอดีตที่จบแล้ว (past simple) จึงใช้ disappeared'),
        t2(' during past ice '),
        typ2('t2-twe-6d-b131', 'age', ['ages'], 'plural', '"ice ages" พูดถึงยุคน้ำแข็งหลายยุค จึงเป็นพหูพจน์'),
        t2(' without any human '),
        sel2('t2-twe-6d-b132', ['involvement', 'involvements', 'involve'], 'involvement', 'plural', '"involvement" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2(' whatsoever. '),
        sel2('t2-twe-6d-b133', ['From this perspective', 'To explain it simply', 'For instance'], 'From this perspective', 'transition', '"From this perspective" สรุปมุมมองของฝ่ายที่เห็นต่างก่อนขึ้นประโยคปิดท้าย'),
        t2(', it is '),
        sel2('t2-twe-6d-b134', ['understandable', 'understanding', 'understood'], 'understandable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ understandable'),
        t2(' why '),
        sel2('t2-twe-6d-b135', ['some', 'few', 'little'], 'some', 'plural', '"some would believe" หมายถึงบางคน ใช้ some กับคนทั่วไป'),
        t2(' '),
        typ2('t2-twe-6d-b136', 'would', ['would'], 'verb-tense', '"would believe" เป็น modal verb ตามด้วย base form ของกริยา believe'),
        t2(' believe that '),
        sel2('t2-twe-6d-b137', ['current', 'currently', 'currency'], 'current', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย extinctions จึงใช้ current'),
        t2(' '),
        typ2('t2-twe-6d-b138', 'extinction', ['extinctions'], 'plural', '"current extinctions" พูดถึงการสูญพันธุ์หลายครั้งในปัจจุบัน จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-6d-b139', 'require', ['require'], 'verb-tense', 'ประธาน "extinctions" พหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' no special human '),
        sel2('t2-twe-6d-b140', ['intervention', 'interventions', 'intervene'], 'intervention', 'plural', '"intervention" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2('.')
      ]
    },
    {
      id: 'gb2-pe-dense-body2',
      role: 'body2',
      labelTh: WGB2_ROLE_LABEL_TH.body2,
      segments: [
        sel2('t2-twe-6d-b201', ['However', 'To begin with', 'For example'], 'However', 'transition', '"However" เปิดย่อหน้าเพื่อโต้แย้งมุมมองในย่อหน้าก่อนหน้า'),
        t2(', I '),
        typ2('t2-twe-6d-b202', 'would', ['would'], 'verb-tense', '"would argue" เป็น modal verb ตามด้วย base form ของกริยา argue'),
        t2(' '),
        sel2('t2-twe-6d-b203', ['personally', 'personal', 'person'], 'personally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argue จึงใช้ personally'),
        t2(' argue '),
        sel2('t2-twe-6d-b204', ['in favor of', 'in favor for', 'in favor to'], 'in favor of', 'transition', '"argue in favor of" เป็นสำนวนคงที่ ใช้ preposition of เสมอ'),
        t2(' '),
        sel2('t2-twe-6d-b205', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the idea that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' idea '),
        sel2('t2-twe-6d-b206', ['that', 'which', 'what'], 'that', 'transition', '"the idea that" เป็นสำนวนคงที่ ตามด้วย that-clause เสมอ'),
        t2(' '),
        typ2('t2-twe-6d-b207', 'human', ['humans'], 'plural', '"humans" พูดถึงมนุษย์โดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' should '),
        typ2('t2-twe-6d-b208', 'take', ['take'], 'verb-tense', 'ขนานกับ should + base verb'),
        t2(' '),
        sel2('t2-twe-6d-b209', ['active', 'actively', 'activate'], 'active', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย steps จึงใช้ active'),
        t2(' '),
        typ2('t2-twe-6d-b210', 'step', ['steps'], 'plural', '"active steps" หมายถึงการดำเนินการหลายขั้นตอน จึงเป็นพหูพจน์'),
        t2(' to '),
        sel2('t2-twe-6d-b211', ['prevent', 'prevents', 'prevented'], 'prevent', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ prevent'),
        t2(' extinction. '),
        sel2('t2-twe-6d-b212', ['To put it simply', 'For example', 'In conclusion'], 'To put it simply', 'transition', '"To put it simply" ใช้ก่อนอธิบายเหตุผลให้เข้าใจง่าย'),
        t2(', this '),
        sel2('t2-twe-6d-b213', ['is', 'are', 'was'], 'is', 'verb-tense', 'ประธาน "this" เอกพจน์ กริยาปัจจุบันจึงใช้ is'),
        t2(' due to '),
        sel2('t2-twe-6d-b214', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"due to the fact that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' fact that most '),
        typ2('t2-twe-6d-b215', 'extinction', ['extinctions'], 'plural', '"most extinctions today" พูดถึงการสูญพันธุ์หลายครั้งในปัจจุบัน จึงเป็นพหูพจน์'),
        t2(' today '),
        typ2('t2-twe-6d-b216', 'be', ['are'], 'verb-tense', 'ประธาน "extinctions" พหูพจน์ จึงใช้ are'),
        t2(' '),
        typ2('t2-twe-6d-b217', 'cause', ['caused'], 'verb-tense', 'passive voice "are + V3" จึงใช้ caused'),
        t2(' directly by human '),
        sel2('t2-twe-6d-b218', ['activity', 'activities', 'active'], 'activity', 'plural', '"human activity" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2(' rather than natural '),
        typ2('t2-twe-6d-b219', 'process', ['processes'], 'plural', '"natural processes" พูดถึงกระบวนการทางธรรมชาติหลายอย่าง จึงเป็นพหูพจน์'),
        t2(', which '),
        typ2('t2-twe-6d-b220', 'make', ['makes'], 'verb-tense', 'ประธาน "which" อ้างถึง fact ที่เป็นเอกพจน์ จึงใช้ makes'),
        t2(' them our '),
        sel2('t2-twe-6d-b221', ['responsibility', 'responsibilities', 'responsible'], 'responsibility', 'plural', '"our responsibility" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2(' to '),
        sel2('t2-twe-6d-b222', ['address', 'addresses', 'addressed'], 'address', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ address'),
        t2('. '),
        sel2('t2-twe-6d-b223', ['For instance', 'To put it simply', 'In this respect'], 'For instance', 'transition', '"For instance" ยกตัวอย่างรายงานของสหประชาชาติปี 2019'),
        t2(', '),
        sel2('t2-twe-6d-b224', ['a', 'the', WGB2_NO_ARTICLE], 'a', 'article', '"a 2019 United Nations report" พูดถึงรายงานฉบับหนึ่งแบบไม่เจาะจง จึงใช้ a'),
        t2(' 2019 United Nations '),
        typ2('t2-twe-6d-b225', 'report', ['report'], 'plural', '"a report" มี "a" นำหน้าจึงเป็นเอกพจน์ ไม่เติม s'),
        t2(' '),
        typ2('t2-twe-6d-b226', 'find', ['found'], 'verb-tense', 'เหตุการณ์ในอดีตที่จบแล้ว (past simple) จึงใช้ found'),
        t2(' that around one million species now '),
        typ2('t2-twe-6d-b227', 'face', ['face'], 'verb-tense', 'ประธาน "species" เป็นพหูพจน์ในบริบทนี้ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' extinction largely because of habitat '),
        sel2('t2-twe-6d-b228', ['destruction', 'destructions', 'destroy'], 'destruction', 'plural', '"habitat destruction" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2(' and pollution. '),
        sel2('t2-twe-6d-b229', ['In this respect', 'However', 'For example'], 'In this respect', 'transition', '"In this respect" สรุปมุมมองในย่อหน้านี้ก่อนขึ้นประโยคปิดท้าย'),
        t2(', it is '),
        sel2('t2-twe-6d-b230', ['evident', 'evidently', 'evidence'], 'evident', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ evident'),
        t2(' that human-driven extinction '),
        typ2('t2-twe-6d-b231', 'differ', ['differs'], 'verb-tense', 'ประธาน "human-driven extinction" เอกพจน์ จึงใช้ differs'),
        t2(' '),
        sel2('t2-twe-6d-b232', ['fundamentally', 'fundamental', 'fundamentals'], 'fundamentally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย differs จึงใช้ fundamentally'),
        t2(' from '),
        sel2('t2-twe-6d-b233', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the natural extinctions" เจาะจงการสูญพันธุ์ที่กล่าวถึงในประโยค จึงใช้ the'),
        t2(' natural '),
        typ2('t2-twe-6d-b234', 'extinction', ['extinctions'], 'plural', '"the natural extinctions" พูดถึงการสูญพันธุ์หลายครั้งในอดีต จึงเป็นพหูพจน์'),
        t2(' of '),
        sel2('t2-twe-6d-b235', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the distant past" เจาะจงอดีตที่ห่างไกล จึงใช้ the'),
        t2(' distant past.')
      ]
    },
    {
      id: 'gb2-pe-dense-conclusion',
      role: 'conclusion',
      labelTh: WGB2_ROLE_LABEL_TH.conclusion,
      segments: [
        sel2('t2-twe-6d-c01', ['In conclusion', 'However', 'For example'], 'In conclusion', 'transition', '"In conclusion" เปิดย่อหน้าสรุปเสมอ'),
        t2(', '),
        typ2('t2-twe-6d-c02', 'although', ['although'], 'verb-tense', '"although" เป็นคำเชื่อมแสดงความขัดแย้ง ใช้รูปเดิมเสมอ ไม่ผัน'),
        t2(' it is '),
        sel2('t2-twe-6d-c03', ['undeniable', 'undeniably', 'deny'], 'undeniable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ undeniable'),
        t2(' that '),
        typ2('t2-twe-6d-c04', 'extinction', ['extinction'], 'plural', '"extinction" เป็นคำนามนามธรรม (uncountable) จึงไม่เติม s'),
        t2(' has always '),
        typ2('t2-twe-6d-c05', 'occur', ['occurred'], 'verb-tense', 'present perfect "has + V3" จึงใช้ occurred'),
        t2(' '),
        sel2('t2-twe-6d-c06', ['naturally', 'natural', 'nature'], 'naturally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย occurred จึงใช้ naturally'),
        t2(', I '),
        sel2('t2-twe-6d-c07', ['am', 'is', 'are'], 'am', 'verb-tense', 'ประธาน "I" ตามด้วย am (present simple ของ be) จึงใช้ am'),
        t2(' of the '),
        sel2('t2-twe-6d-c08', ['opinion', 'opinions', 'opinionated'], 'opinion', 'plural', '"I am of the opinion that" เป็นสำนวนคงที่ ใช้เอกพจน์ opinion เสมอ'),
        t2(' that '),
        typ2('t2-twe-6d-c09', 'human', ['humans'], 'plural', '"humans" พูดถึงมนุษย์โดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' should '),
        typ2('t2-twe-6d-c10', 'work', ['work'], 'verb-tense', 'หลัง modal "should" ต้องใช้ base form จึงใช้ work'),
        t2(' to '),
        sel2('t2-twe-6d-c11', ['prevent', 'prevents', 'prevented'], 'prevent', 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ prevent'),
        t2(' it, as most '),
        sel2('t2-twe-6d-c12', ['modern', 'modernly', 'modernize'], 'modern', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย cases จึงใช้ modern'),
        t2(' '),
        typ2('t2-twe-6d-c13', 'case', ['cases'], 'plural', '"modern cases" พูดถึงกรณีการสูญพันธุ์หลายกรณีในปัจจุบัน จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-6d-c14', 'result', ['result'], 'verb-tense', 'ประธาน "cases" พหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' directly from human '),
        typ2('t2-twe-6d-c15', 'action', ['actions'], 'plural', '"human actions" พูดถึงการกระทำของมนุษย์หลายอย่าง จึงเป็นพหูพจน์'),
        t2('.')
      ]
    }
  ]
}

export default t2Twe6DenseExercise
