// Dense (50 typ2 + 70 sel2) version of the 'gb2-arts-subjects' Writing Task 2 exercise
// (promptId: t2-twe-4). Not yet wired into writingTask2Builder.ts's WGB2_EXERCISES array.
//
// Reconstructing every blank's correct answer must reproduce the essay text in
// scripts/task2-dense/all-essays.json (exId: gb2-twe-4) exactly.
import {
  WGB2_NO_ARTICLE,
  WGB2_ROLE_LABEL_TH,
  type Wgb2Exercise,
  type Wgb2Focus,
  type Wgb2Segment
} from '../writingTask2Builder'

const t2 = (text: string): Wgb2Segment => ({ kind: 'text', text })
const sel2 = (
  id: string,
  options: string[],
  answer: string,
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'select', id, options, answer, focus, explain } })
const typ2 = (
  id: string,
  base: string,
  answers: string[],
  focus: Wgb2Focus,
  explain?: string
): Wgb2Segment => ({ kind: 'blank', blank: { kind: 'type', id, base, answers, focus, explain } })

export const T2_TWE_4_DENSE: Wgb2Exercise = {
  id: 'gb2-arts-subjects',
  promptId: 't2-twe-4',
  steps: [
    {
      id: 'gb2-as-dense-intro',
      role: 'intro',
      labelTh: WGB2_ROLE_LABEL_TH.intro,
      segments: [
        t2('It '),
        sel2('t2-twe-4x-i0x', ['has', 'have', 'had'], 'has', 'verb-tense', 'ประธาน "It" เอกพจน์ ตามด้วย has (present perfect passive) ไม่ใช่ have'),
        t2(' been '),
        sel2('t2-twe-4x-i0a', ['widely', 'wide', 'width'], 'widely', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argued จึงใช้ widely ไม่ใช่คำคุณศัพท์ wide'),
        t2(' '),
        typ2('t2-twe-4x-i0', 'argue', ['argued'], 'verb-tense', 'passive voice "has been + V3" จึงใช้ argued (V3)'),
        t2(' that '),
        sel2('t2-twe-4x-i0c', ['while', 'meanwhile', 'whereas'], 'while', 'transition', '"while" ใช้เชื่อมประโยคขัดแย้งภายในประโยคเดียว (subordinating conjunction) ไม่ใช่ meanwhile ที่ต้องอยู่ต้นประโยคใหม่'),
        t2(' '),
        typ2('t2-twe-4x-i1r', 'rise', ['rising'], 'participle', '"rising tuition fees" — v-ing ทำหน้าที่คุณศัพท์วางหน้าคำนาม แปลว่าค่าเทอมที่กำลังเพิ่มขึ้น'),
        t2(' tuition '),
        typ2('t2-twe-4x-i1f', 'fee', ['fees'], 'plural', '"tuition fees" พูดถึงค่าเทอมโดยทั่วไป เป็นพหูพจน์เสมอในสำนวนนี้'),
        t2(' '),
        sel2('t2-twe-4x-i1m', ['make', 'makes', 'made'], 'make', 'verb-tense', 'ประธาน "rising tuition fees" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-4x-i1p', ['practical', 'practically', 'practice'], 'practical', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย courses จึงใช้ practical ไม่ใช่ adverb practically'),
        t2(' '),
        typ2('t2-twe-4x-i1c', 'course', ['courses'], 'plural', 'พูดถึงวิชาเชิงปฏิบัติโดยทั่วไปหลายวิชา จึงเป็นพหูพจน์'),
        t2(' more '),
        typ2('t2-twe-4x-i1a', 'appeal', ['appealing'], 'participle', '"more appealing" ใช้ -ing ทำหน้าที่คุณศัพท์หลัง more (คุณศัพท์แสดงลักษณะที่ดึงดูด)'),
        t2(', '),
        typ2('t2-twe-4x-i2u', 'university', ['universities'], 'plural', 'พูดถึงมหาวิทยาลัยโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' should stop '),
        typ2('t2-twe-4x-i2t', 'teach', ['teaching'], 'verb-tense', '"stop teaching" ตามด้วย gerund เสมอหลัง stop'),
        t2(' arts '),
        typ2('t2-twe-4x-i2s', 'subject', ['subjects'], 'plural', '"arts subjects" พูดถึงวิชาศิลปศาสตร์หลายวิชาโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' such as '),
        sel2('t2-twe-4x-i2ph', ['philosophy', 'philosophies', 'philosophical'], 'philosophy', 'noun', '"philosophy" ในความหมายวิชาปรัชญาโดยทั่วไปเป็นนามนับไม่ได้ ใช้รูปเอกพจน์เสมอ'),
        t2(' and '),
        sel2('t2-twe-4x-i2h', ['history', 'historic', 'historically'], 'history', 'noun', 'ต้องการคำนาม "history" (วิชาประวัติศาสตร์) ไม่ใช่คำคุณศัพท์ historic หรือกริยาวิเศษณ์ historically'),
        t2(' in favor of purely '),
        sel2('t2-twe-4x-i2p2', ['practical', 'practically', 'practice'], 'practical', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย courses จึงใช้ practical'),
        t2(' '),
        typ2('t2-twe-4x-i2c2', 'course', ['courses'], 'plural', 'พูดถึงวิชาเชิงปฏิบัติโดยทั่วไปหลายวิชา จึงเป็นพหูพจน์'),
        t2('. Others '),
        typ2('t2-twe-4x-i3a', 'argue', ['argue'], 'verb-tense', 'ประธาน "Others" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' that '),
        typ2('t2-twe-4x-i3f', 'focus', ['focusing'], 'verb-tense', '"focusing solely on..." เป็น gerund phrase ทำหน้าที่ประธานประโยค'),
        t2(' solely on '),
        sel2('t2-twe-4x-i3e', ['employment-focused', 'employment-focusing', 'employment-focus'], 'employment-focused', 'participle', 'ต้องการคำคุณศัพท์รูป V3 (employment-focused) ขยาย courses ไม่ใช่รูป -ing หรือคำนามเปล่า'),
        t2(' '),
        typ2('t2-twe-4x-i3c', 'course', ['courses'], 'plural', 'พูดถึงวิชาที่มุ่งเน้นการทำงานโดยทั่วไปหลายวิชา จึงเป็นพหูพจน์'),
        t2(' would '),
        sel2('t2-twe-4x-i3b', ['better', 'best', 'good'], 'better', 'participle', 'รูปเปรียบเทียบ (comparative) ของ well คือ better ส่วน best เป็นขั้นสูงสุด และ good เป็นรูปปกติ'),
        t2(' '),
        sel2('t2-twe-4x-i3p', ['prepare', 'prepares', 'prepared'], 'prepare', 'verb-tense', 'หลัง modal "would better" ต้องใช้ base form จึงใช้ prepare'),
        t2(' '),
        typ2('t2-twe-4x-i3g', 'graduate', ['graduates'], 'plural', 'พูดถึงผู้จบการศึกษาโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' for the job '),
        sel2('t2-twe-4x-i3mk', ['market', 'markets', 'marketing'], 'market', 'plural', '"the job market" เป็นสำนวนคงที่ ใช้เอกพจน์ market เสมอ'),
        t2('. I '),
        sel2('t2-twe-4x-i4p', ['personally', 'personal', 'person'], 'personally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย believe จึงใช้ personally'),
        t2(' believe that '),
        typ2('t2-twe-4x-i4u', 'university', ['universities'], 'plural', 'พูดถึงมหาวิทยาลัยโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' should continue '),
        typ2('t2-twe-4x-i4o', 'offer', ['offering'], 'verb-tense', '"continue offering" ตามด้วย gerund หลัง continue'),
        t2(' arts '),
        typ2('t2-twe-4x-i4s', 'subject', ['subjects'], 'plural', '"arts subjects" พูดถึงวิชาศิลปศาสตร์หลายวิชาโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(', '),
        sel2('t2-twe-4x-i4a', ['and', 'but', 'or'], 'and', 'transition', '"and" เชื่อมประโยคที่มีความหมายต่อเนื่องเสริมกัน ไม่ใช่ but (ขัดแย้ง) หรือ or (ทางเลือก)'),
        t2(' my '),
        sel2('t2-twe-4x-i4r', ['reasons', 'reason', 'reasoning'], 'reasons', 'plural', '"my reasons" หมายถึงเหตุผลหลายข้อที่จะกล่าวถึง จึงเป็นพหูพจน์'),
        t2(' will be '),
        typ2('t2-twe-4x-i4e', 'elaborate', ['elaborated'], 'verb-tense', 'passive voice "will be + V3" จึงใช้ elaborated'),
        t2(' on in '),
        sel2('t2-twe-4x-i4t', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the following paragraphs" เจาะจงย่อหน้าถัดไปในเรียงความนี้ จึงใช้ the'),
        t2(' following '),
        typ2('t2-twe-4x-i4pg', 'paragraph', ['paragraphs'], 'plural', '"the following paragraphs" หมายถึงย่อหน้าถัดไปหลายย่อหน้า จึงเป็นพหูพจน์'),
        t2('.'),
      ]
    },
    {
      id: 'gb2-as-dense-body1',
      role: 'body1',
      labelTh: WGB2_ROLE_LABEL_TH.body1,
      segments: [
        sel2('t2-twe-4x-b1start', ['To begin with', 'In this respect', 'For instance'], 'To begin with', 'transition', '"To begin with" ใช้เปิดย่อหน้าแรกเพื่อเริ่มเหตุผลข้อแรก'),
        t2(', it '),
        typ2('t2-twe-4x-b1x0', 'might', ['might'], 'verb-tense', '"might seem" เป็น modal verb แสดงความเป็นไปได้ ตามด้วย base form ของกริยา seem'),
        t2(' seem '),
        sel2('t2-twe-4x-b1x1', ['sensible', 'sensibly', 'sense'], 'sensible', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง seem จึงใช้ sensible ไม่ใช่ adverb sensibly'),
        t2(' for '),
        sel2('t2-twe-4x-b1x0b', ['some', 'anyone', 'anybody'], 'some', 'plural', '"for some to claim" หมายถึงคนบางกลุ่มทั่วไป ใช้รูป some ในบริบทเชิงบวกนี้'),
        t2(' to '),
        typ2('t2-twe-4x-b1x0c', 'claim', ['claim'], 'verb-tense', 'หลัง "to" ต้องใช้ infinitive รูปเดิม (base form) จึงใช้ claim'),
        t2(' that '),
        typ2('t2-twe-4x-b1a', 'university', ['universities'], 'plural', 'พูดถึงมหาวิทยาลัยโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' should '),
        typ2('t2-twe-4x-b1b', 'focus', ['focus'], 'verb-tense', 'หลัง modal "should" ต้องใช้ base form จึงใช้ focus'),
        t2(' only on '),
        sel2('t2-twe-4x-b1x1b', ['practical', 'practically', 'practice'], 'practical', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย courses จึงใช้ practical'),
        t2(' '),
        typ2('t2-twe-4x-b1cy', 'course', ['courses'], 'plural', 'พูดถึงวิชาเชิงปฏิบัติโดยทั่วไปหลายวิชา จึงเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-4x-b1mid', ['To explain it simply', 'However', 'In conclusion'], 'To explain it simply', 'transition', '"To explain it simply" ใช้ก่อนขยายความเหตุผลให้เข้าใจง่ายขึ้น'),
        t2(', '),
        sel2('t2-twe-4x-b1x3x', ['this', 'these', 'that'], 'this', 'plural', '"this" อ้างถึงประโยคก่อนหน้าทั้งประโยค (เอกพจน์) จึงใช้ this ไม่ใช่ these'),
        t2(' is '),
        sel2('t2-twe-4x-b1x3', ['possibly', 'possible', 'possibility'], 'possibly', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย is จึงใช้ possibly'),
        t2(' because '),
        typ2('t2-twe-4x-b1x3b', 'graduate', ['graduates'], 'plural', 'พูดถึงผู้จบการศึกษาโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' with technical '),
        sel2('t2-twe-4x-skilly', ['skills', 'skill', 'skillful'], 'skills', 'plural', '"technical skills" หมายถึงทักษะหลายอย่าง จึงเป็นพหูพจน์'),
        t2(' often '),
        sel2('t2-twe-4x-b1x3c', ['find', 'finds', 'found'], 'find', 'verb-tense', 'ประธาน "graduates" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' employment more '),
        sel2('t2-twe-4x-quicky', ['quickly', 'quick', 'quickness'], 'quickly', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย find จึงใช้ quickly ไม่ใช่คำคุณศัพท์ quick'),
        t2(' after '),
        sel2('t2-twe-4x-gradnouny', ['graduation', 'graduate', 'graduating'], 'graduation', 'noun', 'ต้องการคำนาม "graduation" (การจบการศึกษา) หลัง after ไม่ใช่กริยา graduate หรือ graduating'),
        sel2('t2-twe-4x-b1d', [';', '.', ','], ';', 'punct', 'เชื่อม 2 ประโยคสมบูรณ์เข้าด้วยกันก่อนคำเชื่อม therefore จึงใช้ semicolon (;)'),
        t2(' therefore'),
        sel2('t2-twe-4x-b1d2', [',', '.', ''], ',', 'punct', 'หลังคำเชื่อม therefore ต้องมี comma เสมอก่อนขึ้นประโยคหลัก'),
        t2(' '),
        typ2('t2-twe-4x-b1e0x', 'replace', ['replacing'], 'verb-tense', '"replacing arts subjects" เป็น gerund phrase ทำหน้าที่ประธานประโยค'),
        t2(' arts '),
        typ2('t2-twe-4x-subjy', 'subject', ['subjects'], 'plural', '"arts subjects" พูดถึงวิชาศิลปศาสตร์หลายวิชาโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' with practical '),
        sel2('t2-twe-4x-trainy', ['training', 'trains', 'trained'], 'training', 'noun', '"practical training" เป็นนามนับไม่ได้ (uncountable) จึงใช้รูป training ไม่ใช่กริยา trains หรือรูปอดีต trained'),
        t2(' could '),
        sel2('t2-twe-4x-reducey', ['reduce', 'reduces', 'reduced'], 'reduce', 'verb-tense', 'หลัง modal "could" ต้องใช้ base form จึงใช้ reduce'),
        t2(' graduate '),
        sel2('t2-twe-4x-unemply', ['unemployment', 'unemployed', 'unemploying'], 'unemployment', 'noun', 'ต้องการคำนาม "unemployment" (การว่างงาน) ไม่ใช่คำคุณศัพท์ unemployed'),
        t2('. '),
        sel2('t2-twe-4x-b1f', ['For example', 'However', 'To begin with'], 'For example', 'transition', '"For example" ยกตัวอย่างเงินเดือนของบัณฑิตสายวิศวกรรมมาสนับสนุนประโยคก่อนหน้า'),
        t2(', '),
        sel2('t2-twe-4x-engy', ['engineering', 'engineer', 'engineered'], 'engineering', 'noun', 'ต้องการคำนาม "engineering" (วิชาวิศวกรรม) ทำหน้าที่ขยายคำนาม graduates ไม่ใช่ engineer'),
        t2(' and computer science '),
        typ2('t2-twe-4x-gradsy2', 'graduate', ['graduates'], 'plural', 'พูดถึงผู้จบการศึกษาโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' in many countries '),
        sel2('t2-twe-4x-reporty', ['report', 'reports', 'reported'], 'report', 'verb-tense', 'ประธาน "graduates" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' considerably '),
        sel2('t2-twe-4x-highy', ['higher', 'high', 'highly'], 'higher', 'participle', 'รูปเปรียบเทียบ (comparative) ของ high คือ higher เมื่อเทียบเงินเดือนกับบัณฑิตสายศิลปศาสตร์'),
        t2(' starting '),
        typ2('t2-twe-4x-salaryy', 'salary', ['salaries'], 'plural', '"starting salaries" พูดถึงเงินเดือนเริ่มต้นโดยทั่วไปหลายกรณี จึงเป็นพหูพจน์'),
        t2(' than '),
        typ2('t2-twe-4x-gradsy3', 'graduate', ['graduates'], 'plural', 'พูดถึงผู้จบการศึกษาโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' of arts '),
        sel2('t2-twe-4x-programy', ['programs', 'program', 'programmed'], 'programs', 'plural', '"arts programs" พูดถึงหลักสูตรศิลปศาสตร์โดยทั่วไปหลายหลักสูตร จึงเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-4x-b1h', ['From this perspective', 'It is undeniable', 'To begin with'], 'From this perspective', 'transition', '"From this perspective" สรุปมุมมองของฝ่ายที่เห็นต่างก่อนขึ้นย่อหน้าถัดไป'),
        t2(', it is '),
        sel2('t2-twe-4x-b1h2', ['understandable', 'understanding', 'understood'], 'understandable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ understandable'),
        t2(' why '),
        sel2('t2-twe-4x-b1h3', ['some', 'few', 'little'], 'some', 'plural', '"some would believe" หมายถึงบางคน ใช้ some กับคนทั่วไป ไม่ใช่ few/little'),
        t2(' '),
        typ2('t2-twe-4x-b1h4', 'would', ['would'], 'verb-tense', '"would believe" เป็น modal verb ตามด้วย base form ของกริยา believe'),
        t2(' believe that '),
        sel2('t2-twe-4x-b1h5', ['practical', 'practically', 'practice'], 'practical', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย courses จึงใช้ practical'),
        t2(' '),
        typ2('t2-twe-4x-coursey2', 'course', ['courses'], 'plural', 'พูดถึงวิชาเชิงปฏิบัติโดยทั่วไปหลายวิชา จึงเป็นพหูพจน์'),
        t2(' better '),
        typ2('t2-twe-4x-preparey', 'prepare', ['prepare'], 'verb-tense', 'หลัง modal-like "would better" ต้องใช้ base form จึงใช้ prepare'),
        t2(' '),
        sel2('t2-twe-4x-studenty', ['students', 'student', 'studies'], 'students', 'plural', 'พูดถึงนักศึกษาโดยทั่วไปหลายคน จึงใช้พหูพจน์ students ไม่ใช่เอกพจน์ student หรือคำนามคนละความหมาย studies'),
        t2(' for the job '),
        sel2('t2-twe-4x-markety2', ['market', 'markets', 'marketing'], 'market', 'plural', '"the job market" เป็นสำนวนคงที่ ใช้เอกพจน์ market เสมอ'),
        t2('.'),
      ]
    },
    {
      id: 'gb2-as-dense-body2',
      role: 'body2',
      labelTh: WGB2_ROLE_LABEL_TH.body2,
      segments: [
        sel2('t2-twe-4x-b2start', ['However', 'For instance', 'To begin with'], 'However', 'transition', 'ย่อหน้านี้ขัดแย้งกับย่อหน้าก่อนหน้า (concession → rebuttal) จึงใช้ However'),
        t2(', I '),
        typ2('t2-twe-4x-b2x0', 'would', ['would'], 'verb-tense', '"would argue" เป็น modal verb ตามด้วย base form ของกริยา argue'),
        t2(' '),
        sel2('t2-twe-4x-b2x1', ['personally', 'personal', 'person'], 'personally', 'participle', 'ต้องการคำกริยาวิเศษณ์ (adverb) ขยาย argue จึงใช้ personally'),
        t2(' argue '),
        sel2('t2-twe-4x-favory', ['in favor of', 'in favor for', 'in favor to'], 'in favor of', 'transition', '"argue in favor of" เป็นสำนวนคงที่ ใช้ preposition of เสมอ'),
        t2(' '),
        sel2('t2-twe-4x-b2x1b', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"the idea that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' idea '),
        sel2('t2-twe-4x-ideay', ['that', 'which', 'what'], 'that', 'transition', '"the idea that" เป็นสำนวนคงที่ ตามด้วย that-clause เสมอ'),
        t2(' '),
        typ2('t2-twe-4x-b2x1c', 'university', ['universities'], 'plural', 'พูดถึงมหาวิทยาลัยโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' should continue '),
        typ2('t2-twe-4x-b2b', 'teach', ['teaching'], 'verb-tense', '"continue teaching" ตามด้วย gerund หลัง continue'),
        t2(' arts '),
        typ2('t2-twe-4x-subjy2', 'subject', ['subjects'], 'plural', '"arts subjects" พูดถึงวิชาศิลปศาสตร์หลายวิชาโดยทั่วไป จึงเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-4x-b2mid', ['To put it simply', 'For example', 'In conclusion'], 'To put it simply', 'transition', '"To put it simply" ใช้ก่อนอธิบายเหตุผลให้เข้าใจง่าย'),
        t2(', this '),
        sel2('t2-twe-4x-b2x2c', ['is', 'are', 'was'], 'is', 'verb-tense', 'ประธาน "this" เป็นเอกพจน์ กริยาปัจจุบันจึงใช้ is'),
        t2(' due to '),
        sel2('t2-twe-4x-b2x2b', ['the', 'a', WGB2_NO_ARTICLE], 'the', 'article', '"due to the fact that" เป็นสำนวนคงที่ ใช้ the เสมอ'),
        t2(' fact that '),
        typ2('t2-twe-4x-subjy3', 'subject', ['subjects'], 'plural', '"subjects such as philosophy and history" พูดถึงวิชาหลายวิชา จึงเป็นพหูพจน์'),
        t2(' such as philosophy and history '),
        sel2('t2-twe-4x-developy', ['develop', 'develops', 'developed'], 'develop', 'verb-tense', 'ประธาน "subjects" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' critical '),
        sel2('t2-twe-4x-thinky', ['thinking', 'think', 'thinker'], 'thinking', 'noun', 'ต้องการคำนาม "thinking" (ความคิด) ทำหน้าที่กรรมของ develop ไม่ใช่กริยา think'),
        t2(' and '),
        sel2('t2-twe-4x-commy', ['communication', 'communicate', 'communicative'], 'communication', 'noun', 'ต้องการคำนาม "communication" ขนานกับ thinking ไม่ใช่กริยา communicate'),
        t2(' '),
        typ2('t2-twe-4x-skilly2', 'skill', ['skills'], 'plural', '"critical thinking and communication skills" หมายถึงทักษะหลายอย่าง จึงเป็นพหูพจน์'),
        t2(', '),
        typ2('t2-twe-4x-b2e0', 'which', ['which'], 'verb-tense', '"which" เป็น relative pronoun อ้างถึง skills ที่กล่าวมาก่อนหน้า ใช้รูปเดิมเสมอ'),
        t2(' '),
        sel2('t2-twe-4x-employy', ['employers', 'employer', 'employed'], 'employers', 'plural', 'พูดถึงนายจ้างโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(' in every '),
        sel2('t2-twe-4x-industryy', ['industry', 'industries', 'industrial'], 'industry', 'noun', '"every industry" ตามด้วยคำนามเอกพจน์เสมอ จึงใช้ industry ไม่ใช่พหูพจน์ industries'),
        t2(' continue to '),
        typ2('t2-twe-4x-valuey2', 'value', ['value'], 'verb-tense', 'หลัง infinitive "to" ต้องใช้ base form จึงใช้ value'),
        t2('. '),
        sel2('t2-twe-4x-b2f', ['For instance', 'However', 'To begin with'], 'For instance', 'transition', '"For instance" ยกตัวอย่างผู้นำธุรกิจที่ประสบความสำเร็จมาสนับสนุนประโยคก่อนหน้า'),
        t2(', many '),
        sel2('t2-twe-4x-successy', ['successful', 'success', 'successfully'], 'successful', 'participle', 'ต้องการคำคุณศัพท์ (adjective) ขยาย business leaders จึงใช้ successful'),
        t2(' business '),
        typ2('t2-twe-4x-leadery', 'leader', ['leaders'], 'plural', 'พูดถึงผู้นำธุรกิจโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(', including several well-known technology '),
        sel2('t2-twe-4x-foundery', ['founders', 'founder', 'founded'], 'founders', 'plural', 'พูดถึงผู้ก่อตั้งบริษัทเทคโนโลยีโดยทั่วไปหลายคน จึงเป็นพหูพจน์'),
        t2(', credit their humanities education with '),
        typ2('t2-twe-4x-shapey', 'shape', ['shaping'], 'verb-tense', '"with shaping..." ตามด้วย gerund เสมอหลัง preposition with'),
        t2(' their creative and analytical '),
        typ2('t2-twe-4x-abilityy', 'ability', ['abilities'], 'plural', '"creative and analytical abilities" หมายถึงความสามารถหลายด้าน จึงเป็นพหูพจน์'),
        t2('. '),
        sel2('t2-twe-4x-b2g', ['In this respect', 'However', 'For example'], 'In this respect', 'transition', '"In this respect" สรุปมุมมองในย่อหน้านี้ก่อนขึ้นประโยคปิดท้าย'),
        t2(', it is '),
        sel2('t2-twe-4x-b2g1', ['evident', 'evidently', 'evidence'], 'evident', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ evident'),
        t2(' that arts '),
        typ2('t2-twe-4x-subjy4', 'subject', ['subjects'], 'plural', '"arts subjects" พูดถึงวิชาศิลปศาสตร์หลายวิชาโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(' '),
        typ2('t2-twe-4x-providey', 'provide', ['provide'], 'verb-tense', 'ประธาน "arts subjects" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-4x-skilly3', ['skills', 'skill', 'skillful'], 'skills', 'plural', 'พูดถึงทักษะโดยทั่วไปหลายอย่าง จึงเป็นพหูพจน์'),
        t2(' that '),
        sel2('t2-twe-4x-remainy', ['remain', 'remains', 'remained'], 'remain', 'verb-tense', 'ประธาน "skills" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' '),
        sel2('t2-twe-4x-valuabley', ['valuable', 'value', 'valuably'], 'valuable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง remain จึงใช้ valuable ไม่ใช่คำนาม value'),
        t2(' regardless of a '),
        sel2('t2-twe-4x-gradposs', ['graduate\'s', 'graduates', 'graduate'], 'graduate\'s', 'noun', '"a graduate\'s chosen career" ใช้รูปเจ้าของ (possessive) เอกพจน์ graduate\'s ขยายคำนาม career'),
        t2(' chosen '),
        sel2('t2-twe-4x-careery', ['career', 'careers', 'careering'], 'career', 'plural', '"chosen career" ของบัณฑิตหนึ่งคน เป็นเอกพจน์ career ไม่ใช่พหูพจน์ careers'),
        t2('.'),
      ]
    },
    {
      id: 'gb2-as-dense-conclusion',
      role: 'conclusion',
      labelTh: WGB2_ROLE_LABEL_TH.conclusion,
      segments: [
        sel2('t2-twe-4x-cstart', ['In conclusion', 'However', 'For example'], 'In conclusion', 'transition', '"In conclusion" เปิดย่อหน้าสรุปเสมอ'),
        t2(', '),
        typ2('t2-twe-4x-cx0', 'although', ['although'], 'verb-tense', '"although" เป็นคำเชื่อมแสดงความขัดแย้ง ใช้รูปเดิมเสมอ ไม่ผัน'),
        t2(' it is '),
        sel2('t2-twe-4x-cx1', ['undeniable', 'undeniably', 'deny'], 'undeniable', 'participle', 'ต้องการคำคุณศัพท์ (adjective) หลัง be-verb จึงใช้ undeniable'),
        t2(' that practical '),
        typ2('t2-twe-4x-coursey3', 'course', ['courses'], 'plural', 'พูดถึงวิชาเชิงปฏิบัติโดยทั่วไปหลายวิชา จึงเป็นพหูพจน์'),
        t2(' can '),
        sel2('t2-twe-4x-improvey', ['improve', 'improves', 'improved'], 'improve', 'verb-tense', 'หลัง modal "can" ต้องใช้ base form จึงใช้ improve'),
        t2(' graduates\' short-term job prospects, I am of the opinion that '),
        typ2('t2-twe-4x-univy', 'university', ['universities'], 'plural', 'พูดถึงมหาวิทยาลัยโดยทั่วไปหลายแห่ง จึงเป็นพหูพจน์'),
        t2(' should continue '),
        typ2('t2-twe-4x-offerc', 'offer', ['offering'], 'verb-tense', '"continue offering" ตามด้วย gerund หลัง continue'),
        t2(' arts '),
        typ2('t2-twe-4x-subjy5', 'subject', ['subjects'], 'plural', '"arts subjects" พูดถึงวิชาศิลปศาสตร์หลายวิชาโดยทั่วไป จึงเป็นพหูพจน์'),
        t2(', as they '),
        sel2('t2-twe-4x-buildy', ['build', 'builds', 'built'], 'build', 'verb-tense', 'ประธาน "they" เป็นพหูพจน์ กริยาปัจจุบันจึงไม่เติม -s'),
        t2(' skills that benefit graduates throughout their careers.'),
      ]
    },
  ]
}
