// Generic assembler for Normal-Reading vocab pairs.
// Usage: node scripts/assembleIntensivePairs.mjs --pairs <dir> --src <dir> --out <tsfile> --export <NAME> [--min N --max N]
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const argv = process.argv.slice(2)
const arg = (k, d) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d }
const pairsDir = join(here, arg('--pairs'))
const srcDir = join(here, arg('--src'))
const outPath = join(here, '..', 'src', arg('--out'))
const exportName = arg('--export')
const min = Number(arg('--min', '1')), max = Number(arg('--max', '999'))

const norm = (s) => String(s).toLowerCase().replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[–—]/g, '-').replace(/\s+/g, ' ').trim()
const data = {}, ungrounded = []
let files = 0, totalQ = 0
for (const f of readdirSync(pairsDir).filter((n) => n.endsWith('.json'))) {
  const d = JSON.parse(readFileSync(join(pairsDir, f), 'utf8'))
  if (!d || typeof d.stage !== 'number' || typeof d.slot !== 'number' || !Array.isArray(d.questions)) continue
  if (d.stage < min || d.stage > max) continue
  files++
  const srcPath = join(srcDir, `stage-${d.stage}-slot-${d.slot}.json`)
  const text = existsSync(srcPath) ? norm(JSON.parse(readFileSync(srcPath, 'utf8')).passageText) : ''
  const slotMap = (data[d.stage] = data[d.stage] || {})
  const numMap = (slotMap[d.slot] = slotMap[d.slot] || {})
  for (const q of d.questions) {
    if (!q || typeof q.number !== 'number' || !Array.isArray(q.pairs)) continue
    const clean = q.pairs.filter((p) => p && p.q && p.p && p.th)
      .map((p) => ({ q: String(p.q), p: String(p.p), th: String(p.th), ...(p.note ? { note: String(p.note) } : {}) }))
    if (!clean.length) continue
    for (const p of clean) {
      const ok = norm(p.p).split('...').every((seg) => !seg.trim() || text.includes(seg.trim()))
      if (text && !ok) ungrounded.push(`stage ${d.stage} slot ${d.slot} #${q.number}: "${p.p}"`)
    }
    numMap[q.number] = clean
    totalQ++
  }
}

const tsString = (s) => JSON.stringify(String(s))
const renderPair = (p) => {
  const parts = [`q: ${tsString(p.q)}`, `p: ${tsString(p.p)}`, `th: ${tsString(p.th)}`]
  if (p.note) parts.push(`note: ${tsString(p.note)}`)
  return `{ ${parts.join(', ')} }`
}
let ts = `// AUTO-GENERATED by scripts/assembleIntensivePairs.mjs — do not edit by hand.\n`
ts += `// Word-level paraphrase pairs for Normal-Reading, keyed by stage -> slot -> local question number.\n`
ts += `import type { ReadingVocabBridgePair } from './readingPassage3VocabBridge.ts'\n\n`
ts += `export const ${exportName}: Record<number, Record<1 | 2, Record<number, ReadingVocabBridgePair[]>>> = {\n`
for (const stage of Object.keys(data).map(Number).sort((a, b) => a - b)) {
  ts += `  ${stage}: {\n`
  for (const slot of [1, 2]) {
    const numMap = data[stage]?.[slot] || {}
    ts += `    ${slot}: {\n`
    for (const n of Object.keys(numMap).map(Number).sort((a, b) => a - b)) {
      ts += `      ${n}: [\n`
      for (const p of numMap[n]) ts += `        ${renderPair(p)},\n`
      ts += `      ],\n`
    }
    ts += `    },\n`
  }
  ts += `  },\n`
}
ts += `}\n`
writeFileSync(outPath, ts)
console.error(`[${exportName}] pair files: ${files} | questions: ${totalQ} -> ${arg('--out')}`)
console.error(`Ungrounded passage terms: ${ungrounded.length}`)
for (const u of ungrounded.slice(0, 40)) console.error('  ! ' + u)
