// Assemble Normal-Reading ด่าน 1–5 word-level pairs into a TS data module.
// Input:  scripts/.intensive1to5-pairs/<stage-slot>.json  (from the workflow)
//         scripts/.intensive1to5/<stage-slot>.json         (source, for verbatim check)
// Output: src/intensiveJourneyVocabPairs1to5.ts
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pairsDir = join(here, '.intensive1to5-pairs')
const srcDir = join(here, '.intensive1to5')
const outPath = join(here, '..', 'src', 'intensiveJourneyVocabPairs1to5.ts')

const norm = (s) => String(s).toLowerCase().replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[–—]/g, '-').replace(/\s+/g, ' ').trim()

// stage -> slot -> number -> pairs[]
const data = {}
const ungrounded = []
let files = 0, totalQ = 0
if (!existsSync(pairsDir)) { console.error('No pairs dir:', pairsDir); process.exit(1) }
for (const f of readdirSync(pairsDir).filter((n) => n.endsWith('.json'))) {
  const d = JSON.parse(readFileSync(join(pairsDir, f), 'utf8'))
  if (!d || typeof d.stage !== 'number' || typeof d.slot !== 'number' || !Array.isArray(d.questions)) continue
  files++
  const srcPath = join(srcDir, `stage-${d.stage}-slot-${d.slot}.json`)
  const text = existsSync(srcPath) ? norm(JSON.parse(readFileSync(srcPath, 'utf8')).passageText) : ''
  const slotMap = (data[d.stage] = data[d.stage] || {})
  const numMap = (slotMap[d.slot] = slotMap[d.slot] || {})
  for (const q of d.questions) {
    if (!q || typeof q.number !== 'number' || !Array.isArray(q.pairs)) continue
    const clean = q.pairs
      .filter((p) => p && p.q && p.p && p.th)
      .map((p) => ({ q: String(p.q), p: String(p.p), th: String(p.th), ...(p.note ? { note: String(p.note) } : {}) }))
    if (!clean.length) continue
    for (const p of clean) {
      const np = norm(p.p)
      const ok = np.split('...').every((seg) => !seg.trim() || text.includes(seg.trim()))
      if (text && !ok) ungrounded.push(`stage ${d.stage} slot ${d.slot} #${q.number}: p not verbatim -> "${p.p}"`)
    }
    numMap[q.number] = clean
    totalQ++
  }
}

const tsString = (s) => JSON.stringify(String(s))
const renderPair = (p) => {
  const parts = [`q: ${tsString(p.q)}`, `p: ${tsString(p.p)}`, `th: ${tsString(p.th)}`]
  if (p.note) parts.push(`note: ${tsString(p.note)}`)
  return `{ ${parts.join(', ')} }`
}

let ts = `// AUTO-GENERATED by scripts/assembleIntensive1to5Pairs.mjs — do not edit by hand.\n`
ts += `// Word-level paraphrase pairs for Normal-Reading ด่าน 1–5, keyed by stage -> slot -> local question number.\n`
ts += `import type { ReadingVocabBridgePair } from './readingPassage3VocabBridge.ts'\n\n`
ts += `export const INTENSIVE_PAIRS_STAGE_1_5: Record<number, Record<1 | 2, Record<number, ReadingVocabBridgePair[]>>> = {\n`
for (const stage of Object.keys(data).map(Number).sort((a, b) => a - b)) {
  ts += `  ${stage}: {\n`
  for (const slot of [1, 2]) {
    const numMap = data[stage]?.[slot] || {}
    ts += `    ${slot}: {\n`
    for (const n of Object.keys(numMap).map(Number).sort((a, b) => a - b)) {
      ts += `      ${n}: [\n`
      for (const p of numMap[n]) ts += `        ${renderPair(p)},\n`
      ts += `      ],\n`
    }
    ts += `    },\n`
  }
  ts += `  },\n`
}
ts += `}\n`

writeFileSync(outPath, ts)
console.error(`pair files: ${files} | questions: ${totalQ} -> ${outPath}`)
console.error(`Ungrounded passage terms: ${ungrounded.length}`)
for (const u of ungrounded.slice(0, 40)) console.error('  ! ' + u)
