// AUTO-GENERATED by scripts/assembleIntensive1to5Pairs.mjs — do not edit by hand.
// Word-level paraphrase pairs for Normal-Reading ด่าน 1–5, keyed by stage -> slot -> local question number.
import type { ReadingVocabBridgePair } from './readingPassage3VocabBridge.ts'

export const INTENSIVE_PAIRS_STAGE_1_5: Record<number, Record<1 | 2, Record<number, ReadingVocabBridgePair[]>>> = {
  1: {
    1: {
      1: [
        { q: "all over the world", p: "Unique to the region", th: "พบทั่วโลก เทียบกับ มีเฉพาะในภูมิภาคนี้", note: "บทความบอกว่า stepwells มีเฉพาะในภูมิภาคนี้ (Unique to the region) ขัดกับข้ออ้างว่าพบได้ทั่วโลก จึงตอบ FALSE" },
        { q: "found", p: "are often", th: "พบได้ / มีอยู่" },
        { q: "ancient stepwells", p: "stepwells", th: "บ่อน้ำขั้นบันไดโบราณ" },
      ],
      2: [
        { q: "During their heyday", p: "During their heyday", th: "ในช่วงรุ่งเรือง", note: "ข้อความตรงกับบทความทุกประการ (gathering, leisure, relaxation, worship) จึงตอบ TRUE" },
        { q: "places of gathering", p: "places of gathering", th: "สถานที่ชุมนุม" },
        { q: "leisure, of relaxation", p: "of leisure, of relaxation", th: "พักผ่อนหย่อนใจ" },
        { q: "worship", p: "worship", th: "การสักการะบูชา" },
      ],
      3: [
        { q: "existing stepwells in Delhi", p: "a few also survive in Delhi", th: "บ่อน้ำที่ยังเหลืออยู่ในเดลี", note: "บทความบอกแค่ว่ามีบ่อน้ำเหลืออยู่บ้างในเดลี แต่ไม่ได้พูดถึงความสวยงามเปรียบเทียบ จึงตอบ NOT GIVEN" },
        { q: "more attractive", p: "survive", th: "สวยงามกว่า (บทความไม่กล่าวถึง)" },
      ],
      4: [
        { q: "stone steps", p: "stone steps", th: "ขั้นบันไดหิน", note: "บทความกล่าวถึงขั้นบันไดหิน แต่ไม่ได้บอกว่าใช้เวลาสร้างหลายปี จึงตอบ NOT GIVEN" },
        { q: "characteristic of stepwells", p: "As their name suggests", th: "เป็นลักษณะเฉพาะของบ่อน้ำขั้นบันได" },
        { q: "took workers many years to build", p: "comprise a series of stone steps", th: "ใช้เวลาสร้างหลายปี (บทความไม่กล่าวถึง)" },
      ],
      5: [
        { q: "depends on the depth of the water", p: "When the water level was high ... when it was low", th: "ขึ้นอยู่กับความลึก/ระดับของน้ำ", note: "บทความระบุว่าน้ำสูงลงไม่กี่ขั้น น้ำต่ำต้องลงหลายระดับ ตรงกับข้ออ้าง จึงตอบ TRUE" },
        { q: "number of steps above the water level", p: "descend a few steps", th: "จำนวนขั้นเหนือระดับน้ำ" },
        { q: "depth", p: "several levels", th: "ความลึก / จำนวนระดับ" },
      ],
      6: [
        { q: "provided shade for people", p: "sheltered visitors from the relentless heat", th: "ให้ร่มเงาแก่ผู้คน / กำบังจากความร้อน", note: "ส่วนที่ให้ร่มเงาคือ pavilions จึงตอบ pavilions" },
        { q: "Which part of some stepwells", p: "pavilions", th: "ส่วนใดของบ่อน้ำขั้นบันได = ศาลา (pavilions)" },
      ],
      7: [
        { q: "serious climatic event", p: "drought", th: "เหตุการณ์ภูมิอากาศรุนแรง = ภัยแล้ง", note: "เหตุการณ์ภูมิอากาศรุนแรงในรัฐราชสถานตอนใต้คือ drought จึงตอบ drought" },
        { q: "southern Rajasthan", p: "southern Rajasthan", th: "ราชสถานตอนใต้" },
      ],
      8: [
        { q: "frequent visitors", p: "Tourists flock to wells", th: "ผู้มาเยือนบ่อย / แห่กันมา", note: "ผู้ที่มาเยือนบ่อยในปัจจุบันคือ tourists จึงตอบ tourists" },
        { q: "nowadays", p: "Today", th: "ในปัจจุบัน" },
      ],
      9: [
        { q: "survived an earthquake", p: "survived a devastating earthquake", th: "รอดพ้นจากแผ่นดินไหว", note: "โครงสร้างโบราณรอดจากแผ่นดินไหว จึงตอบ Earthquake" },
        { q: "7.6 on the Richter scale", p: "7.6 on the Richter scale", th: "ขนาด 7.6 ตามมาตราริกเตอร์" },
      ],
      10: [
        { q: "four … of steps", p: "four sides of steps", th: "บันไดสี่ … = สี่ด้าน", note: "ช่องว่างเติมด้วย sides ตามบทความ four sides of steps จึงตอบ sides" },
        { q: "stunning geometrical formation", p: "stunning geometrical formation", th: "รูปทรงเรขาคณิตที่งดงาม" },
      ],
      11: [
        { q: "resembles a … rather than a well", p: "resembles a tank ... rather than a well", th: "คล้าย … มากกว่าบ่อน้ำ = อ่างเก็บน้ำ", note: "ช่องว่างเติมด้วย tank จึงตอบ Tank" },
        { q: "kund means reservoir or pond", p: "kund means reservoir or pond", th: "kund หมายถึงอ่างเก็บน้ำหรือสระ" },
      ],
      12: [
        { q: "supported by ornate pillars", p: "supported by ornate pillars", th: "ค้ำด้วยเสาที่ตกแต่งวิจิตร", note: "สิ่งที่ค้ำด้วยเสาและมองลงไปยังขั้นบันไดคือ verandas จึงตอบ verandas" },
        { q: "On the fourth side", p: "On the fourth side", th: "ด้านที่สี่" },
        { q: "overlook the steps", p: "overlook the steps", th: "มองลงไปยังขั้นบันได" },
      ],
      13: [
        { q: "last two levels underwater", p: "the last two being underwater", th: "สองชั้นล่างสุดอยู่ใต้น้ำ", note: "ช่องว่างเติมด้วย underwater จึงตอบ underwater" },
        { q: "Constructed in around 1700", p: "Constructed in around 1700", th: "สร้างราวปี 1700" },
        { q: "nine storeys deep", p: "nine storeys deep", th: "ลึกเก้าชั้น" },
      ],
    },
    2: {
      1: [
        { q: "growth in car use", p: "growth in car use", th: "การเติบโตของการใช้รถยนต์", note: "หัวข้อ viii \"rapid growth of private transport\" ตรงกับ \"spectacular growth in car use\"" },
        { q: "spectacular", p: "spectacular", th: "อย่างน่าทึ่ง / รวดเร็ว" },
        { q: "passenger transport", p: "passenger transport", th: "การขนส่งผู้โดยสาร" },
      ],
      2: [
        { q: "goods transport", p: "goods transport", th: "การขนส่งสินค้า" },
        { q: "changes in production", p: "changes in the European economy and its system of production", th: "การเปลี่ยนแปลงในระบบการผลิต", note: "หัวข้อ iii เกี่ยวกับการขนส่งสินค้าและการเปลี่ยนแปลงการผลิต" },
        { q: "goods transport", p: "goods transport is concerned, growth", th: "การเติบโตของการขนส่งสินค้า" },
      ],
      3: [
        { q: "candidates for entry to the EU", p: "candidates for entry to the EU", th: "ประเทศที่รอเข้าเป็นสมาชิก EU", note: "หัวข้อ xi \"countries awaiting EU admission\" ตรงกับ candidates for entry to the EU" },
        { q: "candidates", p: "candidates", th: "ผู้สมัคร / ประเทศผู้สมัคร" },
        { q: "entry to the EU", p: "entry to the EU", th: "การเข้าร่วม EU" },
      ],
      4: [
        { q: "ambitious objective", p: "ambitious objective", th: "เป้าหมายที่ทะเยอทะยาน", note: "หัวข้อ i \"fresh important long-term goal\" ตรงกับ ambitious objective / first essential step" },
        { q: "first essential step", p: "first essential step", th: "ก้าวสำคัญก้าวแรก" },
        { q: "long-term", p: "in 30 years' time", th: "ระยะยาว" },
      ],
      5: [
        { q: "transport", p: "transport sector", th: "ภาคการขนส่ง" },
        { q: "28% of CO2 emissions", p: "28% of emissions of CO2", th: "28% ของการปล่อย CO2", note: "หัวข้อ v \"environmental costs of road transport\" ตรงกับ 28% of emissions of CO2" },
        { q: "CO2 emissions", p: "emissions of CO2, the leading greenhouse gas", th: "การปล่อยก๊าซเรือนกระจก" },
      ],
      6: [
        { q: "integrated approach", p: "integrated approach", th: "แนวทางแบบบูรณาการ" },
        { q: "shift of balance", p: "shift of balance", th: "การปรับสมดุล / เปลี่ยนสมดุล", note: "หัวข้อ iv \"steps necessary to change transport\" ตรงกับ integrated approach / shift of balance" },
        { q: "shift", p: "market shares of the other modes to return to their 1998 levels", th: "การเปลี่ยนส่วนแบ่งระหว่างรูปแบบขนส่ง" },
      ],
      7: [
        { q: "road transport solely through pricing", p: "road transport solely through pricing", th: "การจัดการถนนด้วยการตั้งราคาเพียงอย่างเดียว", note: "หัวข้อ x \"restricting road use through charging\" ตรงกับ road transport solely through pricing" },
        { q: "charging", p: "pricing", th: "การเก็บค่าธรรมเนียม / ตั้งราคา" },
        { q: "road", p: "road transport", th: "การขนส่งทางถนน" },
      ],
      8: [
        { q: "road pricing", p: "road transport pricing", th: "การตั้งราคาการขนส่งทางถนน" },
        { q: "plus efficiency of other modes", p: "increase the efficiency of the other modes", th: "เพิ่มประสิทธิภาพของรูปแบบขนส่งอื่น", note: "หัวข้อ ii \"charging plus improving other methods\" ตรงกับ pricing + efficiency of other modes" },
        { q: "improving other methods", p: "better quality of services, logistics, technology", th: "ปรับปรุงวิธีการขนส่งอื่น" },
      ],
      9: [
        { q: "The need for transport is growing", p: "the requirement for transport continues to increase", th: "ความต้องการขนส่งยังคงเพิ่มขึ้น", note: "passage ยืนยันว่าความต้องการขนส่งเพิ่มขึ้นแม้มีเทคโนโลยี จึงตอบ TRUE" },
        { q: "despite technological developments", p: "Although modern information technologies can reduce the demand", th: "แม้จะมีการพัฒนาเทคโนโลยี" },
        { q: "need for transport", p: "demand for physical transport", th: "ความต้องการการขนส่ง" },
      ],
      10: [
        { q: "To reduce production costs", p: "to reduce production costs", th: "เพื่อลดต้นทุนการผลิต" },
        { q: "moved closer to their relevant consumers", p: "thousands of kilometres away from the final assembly plant or away from users", th: "ย้ายออกห่างไกลจากผู้ใช้ ไม่ใช่เข้าใกล้", note: "passage บอกว่าย้ายห่างจากผู้ใช้หลายพันกิโลเมตร ตรงข้ามกับข้อความ จึงตอบ FALSE" },
        { q: "industries have been moved", p: "relocation of some industries", th: "การย้ายอุตสาหกรรม" },
      ],
      11: [
        { q: "EU candidate countries", p: "countries which are candidates for entry to the EU", th: "ประเทศผู้สมัครเข้า EU" },
        { q: "Cars are prohibitively expensive", p: "increase transport flows, in particular road haulage traffic", th: "ราคารถยนต์แพงเกินไป (ไม่มีการกล่าวถึงราคารถ)", note: "passage ไม่กล่าวถึงราคารถยนต์ในประเทศผู้สมัครเลย จึงตอบ NOT GIVEN" },
      ],
      12: [
        { q: "Gothenburg European Council", p: "Gothenburg European Council", th: "สภายุโรปแห่งโกเธนเบิร์ก" },
        { q: "set up 30 years ago", p: "in place in 30 years' time, that is by 2040", th: "ตั้งขึ้นเมื่อ 30 ปีก่อน (ไม่มีระบุวันก่อตั้ง)", note: "passage ไม่ได้บอกว่าสภาตั้งขึ้นเมื่อใด จึงตอบ NOT GIVEN" },
      ],
      13: [
        { q: "CO2 emissions from transport", p: "CO2 emissions from transport", th: "การปล่อย CO2 จากการขนส่ง" },
        { q: "predicted to reach 739 billion tonnes", p: "increase by around 50% to 1,113 billion tonnes by 2020", th: "คาดว่าจะถึง 1,113 พันล้านตัน ไม่ใช่ 739", note: "739 พันล้านตันคือตัวเลขปี 1990 ส่วนปลายทศวรรษคาดว่า 1,113 พันล้านตัน จึงตอบ FALSE" },
        { q: "739 billion tonnes", p: "739 billion tonnes recorded in 1990", th: "739 พันล้านตัน (ค่าของปี 1990)" },
      ],
    },
  },
  2: {
    1: {
      1: [
        { q: "time and place of Industrial Revolution", p: "happen in Britain", th: "สถานที่ของการปฏิวัติอุตสาหกรรม (อังกฤษ)" },
        { q: "end of 18th century", p: "end of the 18th century", th: "ช่วงเวลา: ปลายศตวรรษที่ 18", note: "ย่อหน้า A ถามว่าทำไมเกิดที่อังกฤษและปลายศตวรรษที่ 18 ตรงกับหัวข้อ iv (เวลาและสถานที่)" },
        { q: "why Britain", p: "world-changing birth of industry", th: "การกำเนิดของอุตสาหกรรม" },
      ],
      2: [
        { q: "conditions required for industrialisation", p: "factors and all of them need to be present", th: "เงื่อนไขที่จำเป็นต่อการเกิดอุตสาหกรรม" },
        { q: "20 factors needed", p: "20 different factors", th: "ปัจจัย 20 อย่าง", note: "ย่อหน้า B เน้นปัจจัยหลายอย่างที่ต้องมีครบก่อนเกิดการปฏิวัติ ตรงหัวข้อ viii" },
        { q: "before revolution", p: "before the revolution can happen", th: "ก่อนการปฏิวัติจะเกิดขึ้น" },
      ],
      3: [
        { q: "two keys to industrial revolution", p: "Tea and beer", th: "สองสิ่งสำคัญ: ชาและเบียร์" },
        { q: "tea and beer fuelled the revolution", p: "fuelled the revolution", th: "ขับเคลื่อน/จุดชนวนการปฏิวัติ", note: "ย่อหน้า C ชี้ว่าชาและเบียร์คือกุญแจสองดอกของการปฏิวัติ ตรงหัวข้อ vii" },
      ],
      4: [
        { q: "reasons for population increase", p: "burst in population growth", th: "การเพิ่มขึ้นของประชากร" },
        { q: "reduction in child deaths", p: "reduction in child deaths", th: "การลดลงของการตายในเด็ก", note: "ย่อหน้า D พยายามอธิบายสาเหตุการเพิ่มประชากร/ลดการตายเด็ก ตรงหัวข้อ i" },
        { q: "explain", p: "Efforts to explain", th: "ความพยายามอธิบาย" },
      ],
      5: [
        { q: "changes in drinking habits", p: "The poor turned to water and gin", th: "การเปลี่ยนพฤติกรรมการดื่ม" },
        { q: "tax on malt", p: "tax was introduced on malt", th: "ภาษีมอลต์", note: "ย่อหน้า E พูดถึงการเปลี่ยนเครื่องดื่มจากเบียร์ไปน้ำ/จิน ตรงหัวข้อ vi" },
        { q: "poor turned to water and gin", p: "turned to water and gin", th: "คนจนหันไปดื่มน้ำและจิน" },
      ],
      6: [
        { q: "comparisons with Japan", p: "Macfarlane looked to Japan", th: "การเปรียบเทียบกับญี่ปุ่น", note: "ย่อหน้า F เปรียบเทียบอังกฤษกับญี่ปุ่น ตรงหัวข้อ ix" },
        { q: "Macfarlane looked to Japan", p: "developing large cities about the same time", th: "ญี่ปุ่นพัฒนาเมืองใหญ่ในเวลาเดียวกัน" },
      ],
      7: [
        { q: "industrialisation and fear of unemployment", p: "put people out of work", th: "ความกลัวการตกงาน" },
        { q: "gave up labour-saving devices", p: "giving up labour-saving devices", th: "เลิกใช้อุปกรณ์ทุ่นแรง" },
        { q: "abandoned the wheel", p: "abandoned the wheel", th: "ละทิ้งล้อ/เทคโนโลยี", note: "ย่อหน้า G อธิบายว่าญี่ปุ่นเลิกใช้อุปกรณ์ทุ่นแรงเพราะกลัวคนตกงาน ตรงหัวข้อ ii" },
      ],
      8: [
        { q: "China's transport system", p: "direct clipper trade with China", th: "การค้า/การขนส่งกับจีน", note: "บทความกล่าวถึงการค้ากับจีนแต่ไม่ระบุว่าระบบขนส่งของจีนไม่เหมาะกับอุตสาหกรรม จึงตอบ NOT GIVEN" },
        { q: "in the 18th century", p: "early 18th century", th: "ในศตวรรษที่ 18" },
      ],
      9: [
        { q: "Tea and beer both helped to prevent", p: "antiseptic properties of tannin, the active ingredient in tea, and of hops in beer", th: "ชาและเบียร์มีฤทธิ์ฆ่าเชื้อช่วยป้องกัน" },
        { q: "prevent dysentery", p: "without succumbing to water-borne diseases such as dysentery", th: "ป้องกันโรคบิด", note: "บทความยืนยันว่าชาและเบียร์ช่วยให้ไม่ป่วยจากโรคบิด จึงตอบ TRUE" },
      ],
      10: [
        { q: "Roy Porter", p: "Roy Porter", th: "รอย พอร์เตอร์" },
        { q: "disagrees with", p: "favourable appraisal", th: "เห็นด้วย/ประเมินในแง่ดี (ตรงข้ามกับ disagree)", note: "บทความระบุว่าพอร์เตอร์เขียนชื่นชมงานวิจัย ขัดกับคำว่า disagrees จึงตอบ FALSE" },
        { q: "Macfarlane's findings", p: "his research", th: "งานวิจัยของแมคฟาร์เลน" },
      ],
      11: [
        { q: "After 1740", p: "Between about 1650 and 1740, the population in Britain was static", th: "หลังปี 1740 (เทียบกับช่วงคงที่ก่อนปี 1740)", note: "บทความระบุว่าก่อนปี 1740 ประชากรคงที่ แล้วจึงเพิ่มหลังจากนั้น แต่ข้อความบอกว่า 'after 1740' ซึ่งคลาดเคลื่อนจากไทม์ไลน์ จึงตอบ FALSE" },
        { q: "burst in population growth", p: "burst in population growth", th: "การพุ่งขึ้นของประชากร" },
      ],
      12: [
        { q: "make beer", p: "preserve the beer", th: "เกี่ยวกับการทำ/เก็บเบียร์", note: "บทความพูดถึงการดื่มเบียร์และฮ็อปส์ แต่ไม่ระบุว่าคนทำเบียร์เองที่บ้าน จึงตอบ NOT GIVEN" },
        { q: "People in Britain", p: "the English", th: "คนอังกฤษ" },
      ],
      13: [
        { q: "tax on malt", p: "tax was introduced on malt", th: "ภาษีมอลต์" },
        { q: "rise in the death rate", p: "mortality rate began to rise", th: "อัตราการตายเพิ่มขึ้น", note: "บทความเชื่อมโยงภาษีมอลต์ -> คนจนหันไปดื่มน้ำ/จิน -> อัตราตายเพิ่ม จึงตอบ TRUE" },
        { q: "indirectly caused", p: "The poor turned to water and gin", th: "เป็นเหตุทางอ้อม (ผ่านการเปลี่ยนเครื่องดื่ม)" },
      ],
    },
    2: {
      1: [
        { q: "domestic background", p: "in their home", th: "ภูมิหลังที่บ้าน / สภาพแวดล้อมในบ้าน", note: "ข้อมูลเรื่องสภาพแวดล้อมในบ้าน (verbal interactions with parents, books in their home) อยู่ในย่อหน้า A จึงตอบ A" },
        { q: "influence", p: "verbal interactions with parents", th: "อิทธิพล / ปฏิสัมพันธ์กับพ่อแม่" },
        { q: "gifted child", p: "children's IQ scores", th: "เด็กที่มีพรสวรรค์ / คะแนนไอคิวของเด็ก" },
      ],
      2: [
        { q: "too much guidance", p: "overdirect", th: "ชี้นำมากเกินไป", note: "\"overdirect\" จับคู่กับ \"too much guidance\" และ \"diminish ... autonomy\" คือสิ่งที่สูญเสียไป จึงตอบ D" },
        { q: "can be lost", p: "diminish their gifted pupils' learning autonomy", th: "สิ่งที่สูญเสียไป / ลดทอนความเป็นอิสระในการเรียนรู้" },
      ],
      3: [
        { q: "anxiety", p: "Fear", th: "ความวิตกกังวล / ความกลัว", note: "\"anxiety\" ตรงกับ \"Fear\" และผลเสีย (limit the development of curiosity) อยู่ในย่อหน้า F จึงตอบ F" },
        { q: "damaging effects", p: "limit the development of curiosity", th: "ผลเสีย / จำกัดการพัฒนาความอยากรู้" },
      ],
      4: [
        { q: "classroom techniques", p: "new methods", th: "เทคนิคในห้องเรียน / วิธีการใหม่ๆ", note: "ตัวอย่างวิธีสอน (child-initiated learning, ability-peer tutoring) ที่เหมาะกับเด็กยากจน อยู่ในย่อหน้า D จึงตอบ D" },
        { q: "socially-disadvantaged children", p: "bright children from deprived areas", th: "เด็กที่ด้อยโอกาสทางสังคม / เด็กจากพื้นที่ขาดแคลน" },
        { q: "favour", p: "particularly useful for", th: "เป็นประโยชน์ต่อ / เอื้อต่อ" },
      ],
      5: [
        { q: "Less time can be spent on exercises", p: "shorten the practice", th: "ใช้เวลาฝึกฝนน้อยลง", note: "\"produce accurate work\" = \"make fewer errors\" และ \"less time on exercises\" = \"shorten the practice\" จึงตอบ B (Shore and Kanevsky)" },
        { q: "produce accurate work", p: "make fewer errors", th: "ทำงานได้ถูกต้อง / ผิดพลาดน้อยลง" },
        { q: "gifted pupils", p: "the gifted", th: "เด็กที่มีพรสวรรค์" },
      ],
      6: [
        { q: "Self-reliance", p: "independence", th: "การพึ่งพาตนเอง / ความเป็นอิสระ", note: "\"Self-reliance\" = \"independence\" และ \"valuable quality ... benefit from\" = \"contribute more to reaching the highest levels of expertise\" จึงตอบ D (Simonton)" },
        { q: "valuable quality", p: "contribute more to reaching the highest levels of expertise", th: "คุณสมบัติที่มีค่า / ช่วยให้ถึงระดับความเชี่ยวชาญสูงสุด" },
      ],
      7: [
        { q: "channel their feelings", p: "emotional forces in harness", th: "ควบคุม/ใช้ประโยชน์จากอารมณ์", note: "\"channel their feelings to assist learning\" = \"emotional forces in harness\" จึงตอบ E (Boekaerts)" },
        { q: "Gifted children", p: "very high IQ and highly achieving children", th: "เด็กที่มีพรสวรรค์ / เด็กไอคิวสูง" },
        { q: "assist their learning", p: "review of emotion the learning", th: "ช่วยในการเรียนรู้" },
      ],
      8: [
        { q: "support from close relatives", p: "home educational provision", th: "การสนับสนุนจากคนในครอบครัว / การจัดการศึกษาที่บ้าน", note: "\"support from close relatives\" = \"home educational provision\" และ \"benefits\" = \"close positive relationship\" จึงตอบ A (Freeman)" },
        { q: "benefits from", p: "very close positive relationship", th: "ได้รับประโยชน์ / ความสัมพันธ์เชิงบวก" },
        { q: "very gifted child", p: "children's IQ scores", th: "เด็กที่มีพรสวรรค์สูง / คะแนนไอคิวของเด็ก" },
      ],
      9: [
        { q: "learnt a considerable amount", p: "know a great deal", th: "เรียนรู้/รู้เป็นจำนวนมาก", note: "\"learnt a considerable amount about their subject\" = \"know a great deal about a specific domain\" จึงตอบ C (Elshout)" },
        { q: "their subject", p: "a specific domain", th: "วิชา / สาขาเฉพาะ" },
        { q: "Really successful students", p: "achieve at a higher level", th: "นักเรียนที่ประสบความสำเร็จ / ทำได้ในระดับสูงกว่า" },
      ],
      10: [
        { q: "number of books and activities", p: "number of books and activities", th: "จำนวนหนังสือและกิจกรรม", note: "ช่องว่างเติมคำว่า \"activities\" จากวลี \"number of books and activities in their home\"" },
        { q: "home", p: "in their home", th: "ที่บ้าน" },
      ],
      11: [
        { q: "Children of average ability", p: "more average-ability or older pupils", th: "เด็กที่มีความสามารถปานกลาง", note: "ช่องว่างเติมคำว่า \"internal regulation\" จาก \"lack of internal regulation\" ที่เด็กความสามารถปานกลางขาดไป" },
        { q: "need more direction from teachers", p: "external regulation by the teacher often compensates", th: "ต้องการการชี้นำจากครูมากขึ้น" },
        { q: "do not have", p: "lack of internal regulation", th: "ไม่มี / ขาด (การควบคุมภายใน)" },
      ],
      12: [
        { q: "understanding their own learning strategies", p: "identify their own ways of learning", th: "เข้าใจกลยุทธ์การเรียนรู้ของตนเอง", note: "ช่องว่างเติมคำว่า \"emotional awareness\" จาก \"Emotional awareness is also part of metacognition\"" },
        { q: "developing", p: "Emotional awareness is also part of metacognition", th: "พัฒนา (ความตระหนักทางอารมณ์)" },
        { q: "Meta-cognition", p: "metacognition", th: "อภิปัญญา / การรู้คิด" },
      ],
      13: [
        { q: "rely on what is known as", p: "spoon-feeding", th: "พึ่งพาสิ่งที่เรียกว่า (การป้อนความรู้)", note: "ช่องว่างเติมคำว่า \"spoon-feeding\" จาก \"'spoon-feeding' can produce extremely high examination results\"" },
        { q: "impressive grades in class tests", p: "extremely high examination results", th: "เกรดที่น่าประทับใจในการสอบ" },
      ],
    },
  },
  3: {
    1: {
      1: [
        { q: "mass tourism", p: "Tourism in the mass form", th: "การท่องเที่ยวแบบมวลชน" },
        { q: "twentieth-century phenomenon", p: "distinctly twentieth-century phenomenon", th: "ปรากฏการณ์ของศตวรรษที่ 20", note: "ย่อหน้าพูดถึงการเกิดและเติบโตของการท่องเที่ยวมวลชน จึงเข้าหัวข้อ \"ii\"" },
        { q: "development", p: "rapid growth and expansion", th: "การเติบโต/พัฒนา" },
      ],
      2: [
        { q: "grown in economic and social importance", p: "grown significantly in both economic and social importance", th: "เติบโตทั้งด้านเศรษฐกิจและสังคม", note: "ตรงกับหัวข้อ \"i\" เรื่องความสำคัญทางเศรษฐกิจและสังคม" },
        { q: "economic", p: "economic measure", th: "ทางเศรษฐกิจ" },
        { q: "importance", p: "importance", th: "ความสำคัญ" },
      ],
      3: [
        { q: "diversity and fragmentation", p: "diversity and fragmentation of the industry", th: "ความหลากหลายและการกระจัดกระจาย" },
        { q: "obscure impact", p: "hidden, or obscured, its economic impact", th: "บดบังผลกระทบทางเศรษฐกิจ", note: "ปัญหาที่ทำให้มองไม่เห็นผลกระทบ ตรงหัวข้อ \"v\"" },
        { q: "problems", p: "major problems", th: "ปัญหา" },
      ],
      4: [
        { q: "largest commodity in international trade", p: "largest commodity in international trade", th: "สินค้าที่ใหญ่ที่สุดในการค้าระหว่างประเทศ", note: "แสดงผลกระทบระดับโลกของการท่องเที่ยว ตรงหัวข้อ \"vii\"" },
        { q: "world impact", p: "for many nations", th: "ผลกระทบทั่วโลก" },
        { q: "tourism", p: "tourism", th: "การท่องเที่ยว" },
      ],
      5: [
        { q: "largest employment figures in the world", p: "largest industry in the world", th: "อุตสาหกรรมที่ใหญ่ที่สุดในโลก", note: "บทความระบุว่าใหญ่ที่สุดในทุกตัวชี้วัดรวมถึงการจ้างงาน จึงตอบ TRUE" },
        { q: "employment", p: "employment", th: "การจ้างงาน" },
        { q: "travel and tourism industry", p: "Travel and tourism", th: "อุตสาหกรรมท่องเที่ยว" },
      ],
      6: [
        { q: "over six per cent", p: "over 6 per cent", th: "มากกว่าหกเปอร์เซ็นต์" },
        { q: "gross national product", p: "world’s national product", th: "ผลิตภัณฑ์มวลรวมประชาชาติ" },
        { q: "Australian", p: "world’s", th: "ของออสเตรเลีย vs ของโลก", note: "บทความพูดถึงระดับโลกไม่ใช่ออสเตรเลียโดยเฉพาะ จึงตอบ NOT GIVEN" },
      ],
      7: [
        { q: "social effect", p: "on society itself", th: "ผลกระทบต่อสังคม" },
        { q: "economic one", p: "on the world economy", th: "ผลกระทบทางเศรษฐกิจ" },
        { q: "as well as", p: "both ... and", th: "ทั้ง...และ", note: "บทความระบุว่ามีผลทั้งเศรษฐกิจและสังคม จึงตอบ TRUE" },
      ],
      8: [
        { q: "Two main features", p: "diversity and fragmentation", th: "สองลักษณะหลัก", note: "diversity และ fragmentation คือสองลักษณะที่ทำให้ประเมินยาก จึงตอบ TRUE" },
        { q: "economic significance difficult to ascertain", p: "hidden, or obscured, its economic impact", th: "ทำให้ความสำคัญทางเศรษฐกิจประเมินได้ยาก" },
        { q: "travel and tourism industry", p: "travel and tourism industry", th: "อุตสาหกรรมท่องเที่ยว" },
      ],
      9: [
        { q: "Visitor spending", p: "spending by visitors", th: "การใช้จ่ายของนักท่องเที่ยว" },
        { q: "residents in tourist areas", p: "local residents", th: "ผู้อยู่อาศัยในพื้นที่" },
        { q: "always greater than", p: "overlooked or underestimated", th: "มากกว่าเสมอ", note: "บทความไม่ได้เปรียบเทียบว่าใครใช้จ่ายมากกว่า จึงตอบ NOT GIVEN" },
      ],
      10: [
        { q: "easy to show statistically", p: "not possible with any degree of certainty to provide precise, valid or reliable data", th: "แสดงด้วยสถิติได้ง่าย vs ทำไม่ได้", note: "บทความบอกว่าทำได้ยาก/ไม่ได้ ขัดกับข้อความ จึงตอบ FALSE" },
        { q: "affects individual economies", p: "its economic impact", th: "ผลต่อเศรษฐกิจ" },
        { q: "statistically", p: "statistical measurement", th: "ทางสถิติ" },
      ],
      11: [
        { q: "Greece", p: "Greece", th: "ประเทศกรีซ" },
        { q: "the most important", p: "the major", th: "ที่สำคัญที่สุด", note: "เติมคำว่า \"source of income\" ตามบทความ" },
        { q: "tourism", p: "tourism", th: "การท่องเที่ยว" },
      ],
      12: [
        { q: "Jamaica", p: "Jamaica", th: "ประเทศจาเมกา" },
        { q: "the major", p: "number one ranked", th: "อันดับหนึ่ง/หลัก", note: "เติมคำว่า \"employer\" ตามบทความ" },
        { q: "travel and tourism industry", p: "travel and tourism industry", th: "อุตสาหกรรมท่องเที่ยว" },
      ],
      13: [
        { q: "problems associated with measuring international tourism", p: "similar difficulties arise when attempts are made to measure", th: "ปัญหาในการวัดการท่องเที่ยว" },
        { q: "reflected in the measurement of", p: "measure domestic tourism", th: "สะท้อนในการวัดของ", note: "เติมคำว่า \"domestic tourism\" ตามบทความ" },
      ],
    },
    2: {
      1: [
        { q: "the substance responsible for the red colouration", p: "it is created by anthocyanins", th: "สารที่ทำให้ใบเป็นสีแดงคือแอนโทไซยานิน", note: "ย่อหน้า C อธิบายสารที่ทำให้ใบแดง (anthocyanins) จึงตอบ C" },
        { q: "a description of the substance", p: "water-soluble plant pigments", th: "รงควัตถุพืชที่ละลายน้ำได้" },
        { q: "red colouration of leaves", p: "reflecting the red to blue range of the visible spectrum", th: "สะท้อนแสงในช่วงสีแดง" },
      ],
      2: [
        { q: "the reason why trees drop their leaves", p: "the best strategy is to abandon photosynthesis", th: "เหตุผลที่ต้นไม้ทิ้งใบ คือเลิกการสังเคราะห์แสง", note: "ย่อหน้า B อธิบายเหตุผลที่ต้นไม้ทิ้งใบในฤดูใบไม้ร่วง จึงตอบ B" },
        { q: "drop their leaves", p: "the tree saves its precious resources and discards them", th: "ต้นไม้ทิ้งใบเพื่อรักษาทรัพยากร" },
        { q: "in autumn", p: "throughout the winter", th: "ในช่วงฤดูหนาว/ใบไม้ร่วง" },
      ],
      3: [
        { q: "some evidence to confirm a theory", p: "there are clues out there", th: "หลักฐาน/เบาะแสยืนยันทฤษฎี", note: "ย่อหน้า H ให้เบาะแสยืนยันทฤษฎี (ใบที่แดงสุดอยู่ด้านที่โดนแดดมากสุด) จึงตอบ H" },
        { q: "the purpose of the red leaves", p: "the leaves that are the reddest", th: "จุดประสงค์ของใบสีแดง" },
        { q: "to confirm a theory", p: "those on the side of the tree which gets most sun", th: "ยืนยันด้วยข้อสังเกตจริง" },
      ],
      4: [
        { q: "the function of chlorophyll", p: "the molecule that captures sunlight", th: "หน้าที่ของคลอโรฟิลล์คือจับแสงอาทิตย์", note: "ย่อหน้า B อธิบายหน้าที่ของคลอโรฟิลล์ จึงตอบ B" },
        { q: "an explanation of the function", p: "converts that energy into new building materials", th: "เปลี่ยนพลังงานเป็นวัสดุสร้างเซลล์" },
        { q: "chlorophyll", p: "they are full of chlorophyll", th: "คลอโรฟิลล์" },
      ],
      5: [
        { q: "could serve as a warning signal", p: "to convince herbivorous insects that they are healthy and robust", th: "เป็นสัญญาณเตือนแมลงว่าต้นไม้แข็งแรง", note: "ย่อหน้า E เสนอว่าสีแดงเป็นสัญญาณเตือนแมลง จึงตอบ E" },
        { q: "a suggestion", p: "It has also been proposed", th: "ข้อเสนอ/สมมติฐาน" },
        { q: "the red colouration in leaves", p: "trees may produce vivid red colours", th: "สีแดงสดในใบ" },
      ],
      6: [
        { q: "The most vividly coloured red leaves", p: "the leaves that are the reddest", th: "ใบที่แดงเข้มที่สุด" },
        { q: "the side of the tree facing the", p: "the side of the tree which gets most sun", th: "ด้านของต้นไม้ที่หันรับแดด", note: "ช่องว่างเติมด้วย \"sun\" ตรงกับ \"gets most sun\"" },
      ],
      7: [
        { q: "surfaces of leaves contain the most red pigment", p: "the red is brighter on the upper side of the leaf", th: "ด้านบนของใบมีสีแดงมากที่สุด", note: "ช่องว่างเติมด้วย \"upper\" ตรงกับ \"upper side\"" },
        { q: "the most red pigment", p: "the red is brighter", th: "สีแดงเข้มที่สุด" },
      ],
      8: [
        { q: "Red leaves are most abundant", p: "the best conditions for intense red colours", th: "สภาพที่ทำให้ใบแดงเข้มที่สุด" },
        { q: "daytime weather conditions are … and sunny", p: "dry, sunny days and cool nights", th: "กลางวันแห้งและแดดจัด", note: "ช่องว่างเติมด้วย \"dry\" ตรงกับ \"dry, sunny days\"" },
      ],
      9: [
        { q: "The intensity of the red colour", p: "get much redder", th: "ความเข้มของสีแดง" },
        { q: "as you go further", p: "the more north you travel in the northern hemisphere", th: "ยิ่งไปทางเหนือ", note: "ช่องว่างเติมด้วย \"north\" ตรงกับ \"more north you travel\"" },
      ],
      10: [
        { q: "the red pigments help to protect", p: "the red pigment is made in autumn leaves to protect chlorophyll", th: "รงควัตถุสีแดงช่วยปกป้อง", note: "บทความระบุว่าสีแดงปกป้องคลอโรฟิลล์จากแสงมากเกินไป ไม่ใช่จากความหนาวเย็น จึงตอบ FALSE" },
        { q: "from freezing temperatures", p: "from too much light", th: "จากแสงมากเกินไป (ไม่ใช่จากความหนาว)" },
      ],
      11: [
        { q: "would initially seem to contradict", p: "It sounds paradoxical", th: "ดูเหมือนขัดแย้งในตอนแรก", note: "บทความบอกว่าสมมติฐานนี้ \"sounds paradoxical\" ยืนยันข้อความ จึงตอบ TRUE" },
        { q: "what is known about chlorophyll", p: "the natural world's supreme light absorber", th: "สิ่งที่รู้กันเกี่ยวกับคลอโรฟิลล์" },
      ],
      12: [
        { q: "Leaves which turn colours other than red", p: "simply reveal their orange or yellow hues", th: "ใบที่เปลี่ยนเป็นสีอื่นนอกจากแดง", note: "บทความไม่ได้บอกว่าใบสีอื่นเสียหายจากแดดมากกว่า จึงตอบ NOT GIVEN" },
        { q: "more likely to be damaged by sunlight", p: "prevent overexposure to light", th: "เสียหายจากแสงแดดได้ง่ายกว่า" },
      ],
      13: [
        { q: "the writer offer an explanation", p: "This unmasking explains the autumn colours of yellow and orange", th: "ผู้เขียนให้คำอธิบาย", note: "ผู้เขียนอธิบายว่าทำไมใบเปลี่ยนเป็นเหลือง/ส้ม จึงตอบ B" },
        { q: "questions does the writer", p: "As chlorophyll is depleted, other colours … begin to be revealed", th: "คลอโรฟิลล์ลดลงทำให้สีอื่นปรากฏ" },
      ],
    },
  },
  4: {
    1: {
      1: [
        { q: "movement", p: "spread", th: "การเคลื่อนที่/ลุกลาม" },
        { q: "more unpredictably", p: "more erratically", th: "อย่างคาดเดาไม่ได้มากขึ้น", note: "\"more unpredictably\" = \"spread more erratically\" ดังนั้นคำที่เติมในช่องว่างคือ \"spread\"" },
      ],
      2: [
        { q: "size of fires", p: "the size of the average forest fire", th: "ขนาดของไฟ" },
        { q: "greater on average", p: "10 times the size of the average", th: "ใหญ่กว่าโดยเฉลี่ย", note: "\"greater on average than two decades ago\" = \"10 times the size of the average forest fire of 20 years ago\" คำตอบคือ \"10\"" },
        { q: "two decades ago", p: "20 years ago", th: "เมื่อสองทศวรรษก่อน" },
      ],
      3: [
        { q: "rainfall", p: "precipitation", th: "ปริมาณน้ำฝน" },
        { q: "average", p: "normal", th: "ค่าเฉลี่ย/ปกติ", note: "\"below average rainfall\" = \"below normal precipitation\" คำตอบคือ \"below\"" },
      ],
      4: [
        { q: "brush", p: "underbrush", th: "พุ่มไม้/ไม้พุ่มเตี้ย" },
        { q: "act as", p: "primary fuel", th: "ทำหน้าที่เป็น", note: "\"more brush to act as ___\" = \"underbrush, now the primary fuel\" คำตอบคือ \"fuel\"" },
      ],
      5: [
        { q: "extended", p: "78 days longer", th: "ยาวนานขึ้น", note: "\"extended fire ___\" = \"fire seasons that on average are 78 days longer\" คำตอบคือ \"seasons\"" },
        { q: "fire", p: "fire seasons", th: "ไฟ/ฤดูไฟ" },
      ],
      6: [
        { q: "more building of", p: "more residential housing is being built", th: "การก่อสร้างที่มากขึ้น", note: "\"more building of ___ in vulnerable places\" = \"more residential housing is being built\" คำตอบคือ \"housing\"" },
        { q: "vulnerable places", p: "fire-prone ecosystems", th: "พื้นที่เสี่ยงภัย" },
      ],
      7: [
        { q: "open space", p: "open space", th: "พื้นที่ว่าง" },
        { q: "has diminished", p: "is now residential homes", th: "ลดลง", note: "พื้นที่ว่างกลายเป็นบ้านที่อยู่อาศัย ยืนยันว่าพื้นที่ว่างลดลง จึงตอบ TRUE" },
        { q: "over the last ten years", p: "for at least a decade", th: "ในช่วงสิบปีที่ผ่านมา" },
      ],
      8: [
        { q: "little progress", p: "high marks for making progress", th: "ความคืบหน้าเพียงเล็กน้อย", note: "บทความบอกว่าได้คะแนนสูงเรื่องความคืบหน้า ขัดกับ \"little progress\" จึงตอบ FALSE" },
        { q: "readying itself to fight fires", p: "progress on preparedness", th: "เตรียมพร้อมรับมือไฟ" },
      ],
      9: [
        { q: "criticised", p: "criticism", th: "ถูกวิจารณ์" },
        { q: "mishandling", p: "bungling", th: "จัดการผิดพลาด", note: "\"criticised for mishandling fire containment\" = \"criticism of bungling that allowed fires to spread when they might have been contained\" จึงตอบ TRUE" },
        { q: "fire containment", p: "fires to spread when they might have been contained", th: "การควบคุมไฟ" },
      ],
      10: [
        { q: "replaced older fire-fighting tools", p: "more up-to-date engines, planes", th: "เปลี่ยนอุปกรณ์เก่าเป็นของใหม่" },
        { q: "helicopter-style machines", p: "helicopters", th: "เฮลิคอปเตอร์ดับไฟ" },
        { q: "California has", p: "have been fulfilled", th: "ได้ดำเนินการแล้ว", note: "คำมั่นจัดหาเครื่องบิน เฮลิคอปเตอร์ที่ทันสมัยได้ทำสำเร็จแล้ว จึงตอบ TRUE" },
      ],
      11: [
        { q: "improve fire-fighting capacity", p: "upgrade the fire engines", th: "เพิ่มขีดความสามารถดับไฟ" },
        { q: "More firefighters have been hired", p: "the state has invested in better command-and-control facilities", th: "การจ้างนักดับเพลิงเพิ่ม", note: "บทความพูดถึงงบประมาณ อุปกรณ์ และระบบบัญชาการ แต่ไม่ได้กล่าวถึงการจ้างนักดับเพลิงเพิ่ม จึงตอบ NOT GIVEN" },
      ],
      12: [
        { q: "Citizens and government groups", p: "both government officials and residents", th: "ประชาชนและหน่วยงานรัฐ" },
        { q: "disapprove of", p: "resulting in greater efficiency", th: "ไม่เห็นด้วย", note: "บทความบอกว่าความร่วมมือทำให้มีประสิทธิภาพมากขึ้น ตรงข้ามกับ \"disapprove\" จึงตอบ FALSE" },
        { q: "different states and agencies working together", p: "coordination of firefighters from several states and jurisdictions", th: "การทำงานร่วมกันของหลายรัฐและหน่วยงาน" },
      ],
      13: [
        { q: "loss of life from fires will continue at the same levels", p: "we will no longer suffer the loss of life endured in the past", th: "การสูญเสียชีวิตจะยังคงเท่าเดิม", note: "Randy Jacobs บอกว่าจะไม่สูญเสียชีวิตเหมือนในอดีตอีก ขัดกับข้อความ จึงตอบ FALSE" },
        { q: "despite changes made", p: "because of the fire prevention and firefighting measures that have been put in place", th: "แม้จะมีการเปลี่ยนแปลง" },
      ],
    },
    2: {
      1: [
        { q: "a person's character", p: "a person's character", th: "อุปนิสัย/บุคลิกของคน" },
        { q: "cannot undergo a", p: "cannot undergo a", th: "ไม่สามารถผ่าน/เกิดการ" },
        { q: "in any meaningful way", p: "in any meaningful way", th: "ในทางที่มีความหมายใดๆ", note: "ช่องว่างเติมคำว่า \"transformation\" ตรงกับข้อความใน passage" },
      ],
      2: [
        { q: "the key traits of personality", p: "the key traits of personality", th: "ลักษณะสำคัญของบุคลิกภาพ" },
        { q: "are determined", p: "are determined", th: "ถูกกำหนด" },
        { q: "at a very", p: "at a very", th: "ตั้งแต่...มากๆ", note: "ช่องว่างเติมคำว่า \"young age\" ตามข้อความใน passage" },
      ],
      3: [
        { q: "Some qualities", p: "Some qualities", th: "คุณสมบัติบางอย่าง" },
        { q: "less challenging to develop", p: "less challenging to develop", th: "พัฒนาได้ยากน้อยกว่า" },
        { q: "being one of them", p: "being one of them", th: "เป็นหนึ่งในนั้น", note: "ช่องว่างเติมคำว่า \"optimism\" ตามข้อความใน passage" },
      ],
      4: [
        { q: "developing qualities", p: "developing qualities", th: "การพัฒนาคุณสมบัติ" },
        { q: "mastering a range of", p: "mastering a range of", th: "ฝึกฝนจนเชี่ยวชาญหลากหลาย" },
        { q: "diverse and sometimes surprising", p: "diverse and sometimes surprising", th: "หลากหลายและบางครั้งน่าประหลาดใจ", note: "ช่องว่างเติมคำว่า \"skills\" ตามข้อความใน passage" },
      ],
      5: [
        { q: "increase their happiness", p: "bring more joy and passion into your life", th: "เพิ่มความสุข/ความสุขมากขึ้น" },
        { q: "feel some", p: "open to experiencing negative emotions", th: "ยอมรับ/รู้สึกถึงอารมณ์ด้านลบ", note: "ช่องว่างเติมคำว่า \"negative emotions\" ตามข้อความใน passage" },
      ],
      6: [
        { q: "accept that they do not know much", p: "tolerate and laugh at your own ignorance", th: "ยอมรับว่าตนยังรู้น้อย" },
        { q: "first trying something new", p: "taking up a new passion", th: "เริ่มลองสิ่งใหม่" },
        { q: "first trying", p: "a newcomer", th: "ผู้เริ่มต้น/มือใหม่", note: "ตรงกับคำแนะนำของ Todd Kashdan จึงตอบ E" },
      ],
      7: [
        { q: "actively notice", p: "pay attention to", th: "ใส่ใจสังเกต" },
        { q: "good things happen", p: "good fortune", th: "เรื่องดีๆ ที่เกิดขึ้น" },
        { q: "important for people", p: "writing down three positive things", th: "สิ่งที่ควรทำ/จดบันทึก", note: "ตรงกับคำแนะนำของ Suzanne Segerstrom จึงตอบ C" },
      ],
      8: [
        { q: "Courage can be learned", p: "people can acquire courage", th: "ความกล้าหาญสามารถเรียนรู้ได้" },
        { q: "a sense of responsibility", p: "moral obligation", th: "สำนึกในหน้าที่/ความรับผิดชอบทางศีลธรรม", note: "ตรงกับมุมมองของ Cynthia Pury จึงตอบ G" },
      ],
      9: [
        { q: "overcome shyness", p: "Inherently introverted, he... learned to be more outgoing", th: "เอาชนะความขี้อาย" },
        { q: "speak in public", p: "entertain his classes", th: "พูดต่อหน้าคน/ในห้องเรียน" },
        { q: "speak in public", p: "the lecture hall", th: "การพูดในที่สาธารณะ", note: "ตรงกับเรื่องของ Christopher Peterson จึงตอบ A" },
      ],
      10: [
        { q: "rational thinking", p: "untangle her fears from her judgment", th: "การคิดอย่างมีเหตุผล/แยกความกลัวออกจากการตัดสินใจ" },
        { q: "achieve physical goals", p: "what her body and mind could do", th: "ทำเป้าหมายทางกายให้สำเร็จ", note: "ตรงกับเรื่องของ Tanya Streeter ในย่อหน้า E จึงตอบ E" },
      ],
      11: [
        { q: "overcame", p: "took action despite", th: "เอาชนะ/ลงมือทำแม้จะมี" },
        { q: "their own negative feelings", p: "his own pain", th: "ความรู้สึกด้านลบของตนเอง", note: "ตรงกับเรื่องของ David Fajgenbaum ในย่อหน้า C จึงตอบ C" },
      ],
      12: [
        { q: "rethink their academic career path", p: "switched labs", th: "เปลี่ยน/ทบทวนเส้นทางอาชีพในวงการวิชาการ" },
        { q: "academic career path", p: "study how cerebrospinal fluid nourishes the developing nervous system", th: "สายงานวิจัย/วิชาการ", note: "ตรงกับเรื่องของ Mauro Zappaterra ในย่อหน้า G จึงตอบ G" },
      ],
      13: [
        { q: "risked his career", p: "his own job security would be threatened", th: "เสี่ยงต่อหน้าที่การงานของตน" },
        { q: "a sense of duty", p: "took the evidence to a senior director", th: "สำนึกในหน้าที่/ทำสิ่งที่ถูกต้อง", note: "ตรงกับเรื่องของ Kenneth Pedeleose ในย่อหน้า H จึงตอบ H" },
      ],
    },
  },
  5: {
    1: {
      1: [
        { q: "food plants", p: "produce", th: "พืชผล/ผลผลิตทางการเกษตร" },
        { q: "already grown indoors", p: "indoor farming is not new", th: "ปลูกในร่มอยู่แล้ว" },
        { q: "including", p: "hothouse production of tomatoes", th: "เช่น มะเขือเทศที่ปลูกในเรือนกระจก", note: "ช่องว่างเติมคำว่า \"tomatoes\" เพราะ passage ระบุการผลิตมะเขือเทศในเรือนกระจกเป็นการปลูกในร่ม" },
      ],
      2: [
        { q: "located in", p: "Situated in", th: "ตั้งอยู่ใน" },
        { q: "less need to take them long distances", p: "reduce the amount of transportation required", th: "ลดความจำเป็นในการขนส่งระยะไกล" },
        { q: "customers", p: "consumers", th: "ผู้บริโภค/ลูกค้า" },
        { q: "Vertical farms would be located in urban", p: "the heart of urban centres", th: "ใจกลางเมือง", note: "ช่องว่างเติม \"centres\" จากวลี urban centres ใน passage" },
      ],
      3: [
        { q: "methane from plants", p: "methane generation from composting nonedible parts of plants", th: "ก๊าซมีเทนจากการหมักส่วนของพืช" },
        { q: "to produce", p: "return energy to the grid", th: "ผลิต/ส่งคืนพลังงาน", note: "ช่องว่างเติม \"energy\" เพราะมีเทนถูกใช้คืนพลังงานสู่โครงข่ายไฟฟ้า" },
      ],
      4: [
        { q: "consumption of", p: "use", th: "การใช้/การบริโภค" },
        { q: "would be cut", p: "dramatically reduce", th: "จะถูกลดลง" },
        { q: "agricultural vehicles would be unnecessary", p: "cutting out the need for tractors, ploughs and shipping", th: "ไม่จำเป็นต้องใช้ยานพาหนะการเกษตร" },
        { q: "fossil fuel", p: "fossil fuel", th: "เชื้อเพลิงฟอสซิล", note: "ช่องว่างเติม \"fossil fuel\" ตรงกับ fossil fuel use ที่จะลดลงเพราะเลิกใช้รถแทรกเตอร์" },
      ],
      5: [
        { q: "disadvantage", p: "drawback", th: "ข้อเสีย" },
        { q: "would need", p: "would require", th: "จะต้องการ" },
        { q: "artificial", p: "artificial", th: "เทียม/ประดิษฐ์ขึ้น", note: "ช่องว่างเติม \"artificial\" เพราะ passage ว่าพืชต้องใช้แสงประดิษฐ์ ซึ่งเป็นข้อเสีย" },
      ],
      6: [
        { q: "One form of vertical farming", p: "One variation on vertical farming", th: "รูปแบบหนึ่งของการทำฟาร์มแนวตั้ง" },
        { q: "planting", p: "grow plants", th: "การปลูกพืช" },
        { q: "which are not fixed", p: "move on rails", th: "ที่ไม่ได้ถูกตรึงอยู่กับที่ (เคลื่อนได้)" },
        { q: "trays", p: "stacked trays", th: "ถาดที่วางซ้อนกัน", note: "ช่องว่างเติม \"trays\" เพราะ passage พูดถึงถาดที่เคลื่อนบนราง" },
      ],
      7: [
        { q: "most probable development", p: "far more likely", th: "แนวโน้มที่เป็นไปได้มากที่สุด" },
        { q: "food will be grown on", p: "use the space available", th: "อาหารจะถูกปลูกบน" },
        { q: "in towns and cities", p: "urban", th: "ในเมือง" },
        { q: "rooftops", p: "rooftops", th: "ดาดฟ้า/หลังคา", note: "ช่องว่างเติม \"rooftops\" เพราะผู้เชี่ยวชาญเชื่อว่าจะใช้พื้นที่ดาดฟ้าในเมือง" },
      ],
      8: [
        { q: "predicting the Earth's population", p: "current demographic trends", th: "การคาดการณ์ประชากรโลก" },
        { q: "Methods", p: "the most conservative estimates", th: "วิธีการ/การประมาณการ" },
        { q: "have recently changed", p: "will increase by about three billion people", th: "เพิ่งเปลี่ยนแปลงไป", note: "บทความพูดถึงการคาดการณ์ประชากรแต่ไม่กล่าวว่าวิธีการเปลี่ยนไป จึงตอบ NOT GIVEN" },
      ],
      9: [
        { q: "Human beings are responsible", p: "poor management practices", th: "มนุษย์เป็นผู้รับผิดชอบ (การจัดการที่ไม่ดี)" },
        { q: "destruction to food-producing land", p: "laid waste", th: "การทำลายที่ดินผลิตอาหาร", note: "บทความระบุว่า 15% ของที่ดินถูกทำลายเพราะการจัดการที่ไม่ดีของมนุษย์ จึงตอบ TRUE" },
      ],
      10: [
        { q: "crops produced in vertical farms", p: "crops would be produced", th: "พืชผลที่ผลิตในฟาร์มแนวตั้ง" },
        { q: "depend on the season", p: "all year round", th: "ขึ้นกับฤดูกาล (แต่จริงคือตลอดทั้งปี)" },
        { q: "season", p: "artificially controlled, optimum growing conditions", th: "สภาพควบคุมเทียมไม่ขึ้นกับฤดูกาล", note: "บทความว่าพืชผลผลิตได้ตลอดปีในสภาพควบคุม ขัดกับข้อความว่าขึ้นกับฤดูกาล จึงตอบ FALSE" },
      ],
      11: [
        { q: "damage to food crops", p: "destroying millions of tons of valuable crops", th: "ความเสียหายต่อพืชผลอาหาร" },
        { q: "climate change", p: "rapidly changing climate", th: "การเปลี่ยนแปลงสภาพภูมิอากาศ", note: "บทความระบุว่าสภาพภูมิอากาศที่เปลี่ยนแปลงอย่างรวดเร็วทำลายพืชผล จึงตอบ TRUE" },
      ],
      12: [
        { q: "Fertilisers will be needed", p: "eliminating the need for herbicides, pesticides and fertilisers", th: "จะต้องใช้ปุ๋ย (แต่จริงคือไม่ต้อง)" },
        { q: "crops in vertical farms", p: "All the food could be grown organically", th: "พืชผลในฟาร์มแนวตั้ง (ปลูกแบบออร์แกนิก)", note: "บทความว่าปลูกแบบออร์แกนิกโดยไม่ต้องใช้ปุ๋ย ขัดกับข้อความ จึงตอบ FALSE" },
      ],
      13: [
        { q: "less likely to be affected", p: "greatly reduce the incidence", th: "มีโอกาสได้รับผลกระทบน้อยลง" },
        { q: "infectious diseases", p: "infectious diseases", th: "โรคติดเชื้อ", note: "บทความระบุว่าระบบนี้ลดการเกิดโรคติดเชื้อได้มาก จึงตอบ TRUE" },
      ],
    },
    2: {
      1: [
        { q: "linked", p: "joined", th: "เชื่อมต่อกัน" },
        { q: "Forth & Clyde Canal with the Union Canal", p: "the two canals", th: "คลองสองสาย" },
        { q: "for the first time in their history", p: "Historically, the two canals had been joined", th: "ในอดีตเคยเชื่อมกันมาก่อน (ไม่ใช่ครั้งแรก)", note: "บทความบอกว่าในอดีตคลองสองสายเคยถูกเชื่อมด้วยประตูน้ำ 11 ชุดมาแล้ว จึงไม่ใช่การเชื่อมครั้งแรก ตอบ FALSE" },
      ],
      2: [
        { q: "design of the Falkirk Wheel", p: "a plan for the huge rotating steel boat lift", th: "แบบของล้อฟอลเคิร์ก" },
        { q: "some opposition", p: "Numerous ideas were submitted", th: "การคัดค้าน (เทียบกับการเสนอไอเดียจำนวนมาก)", note: "บทความพูดถึงไอเดียที่ถูกเสนอและผู้ชนะ แต่ไม่ได้กล่าวถึงการคัดค้านแบบใด ๆ จึงตอบ NOT GIVEN" },
      ],
      3: [
        { q: "initially put together", p: "constructed and assembled", th: "ประกอบขึ้นในตอนแรก" },
        { q: "the location where its components were manufactured", p: "Butterley Engineering's Steelworks in Derbyshire", th: "สถานที่ที่ผลิตชิ้นส่วน", note: "ชิ้นส่วนทั้งหมดถูกผลิตและประกอบที่โรงงาน Steelworks เดียวกัน ตรงกับข้อความ จึงตอบ TRUE" },
      ],
      4: [
        { q: "steel sections bolted together by hand", p: "the steel sections were bolted rather than welded together", th: "ส่วนเหล็กยึดด้วยสลักเกลียวด้วยมือ" },
        { q: "the only boat lift in the world", p: "the steel sections were bolted", th: "เครื่องยกเรือเพียงเครื่องเดียวในโลก", note: "บทความบอกว่ายึดด้วยสลักเกลียวด้วยมือ แต่ไม่ได้เปรียบเทียบว่าเป็นเครื่องเดียวในโลก จึงตอบ NOT GIVEN" },
      ],
      5: [
        { q: "weight of the gondolas", p: "gondolas always weigh the same", th: "น้ำหนักของกอนโดลา" },
        { q: "varies according to the size of boat", p: "whether or not they are carrying boats", th: "เปลี่ยนตามขนาดเรือ (แต่จริง ๆ ไม่เปลี่ยน)", note: "บทความบอกว่ากอนโดลาหนักเท่ากันเสมอไม่ว่าจะบรรทุกเรือหรือไม่ ขัดกับข้อความ จึงตอบ FALSE" },
      ],
      6: [
        { q: "took into account the presence of", p: "owing to the presence of", th: "คำนึงถึงการมีอยู่ของ" },
        { q: "Roman structure", p: "Antonine Wall, which was built by the Romans", th: "สิ่งก่อสร้างของชาวโรมัน", note: "ล้อไม่สามารถสร้างให้ยกเรือเต็มระยะ 35 เมตรได้เพราะกำแพง Antonine ของชาวโรมัน ตรงกับข้อความ จึงตอบ TRUE" },
      ],
      7: [
        { q: "raised", p: "are raised", th: "ถูกยกขึ้น" },
        { q: "shut out water from the canal basin", p: "seal the gondola off from the water in the canal basin", th: "กั้นน้ำจากอ่างคลอง" },
        { q: "A pair of", p: "Two hydraulic steel gates", th: "ประตูเหล็กสองบาน", note: "ช่องว่างเติมด้วย gates เพราะ Two hydraulic steel gates ถูกยกขึ้นเพื่อกั้นน้ำ" },
      ],
      8: [
        { q: "taken out", p: "is removed", th: "ถูกนำออก" },
        { q: "enabling the Wheel to rotate", p: "allowing the Wheel to turn", th: "ทำให้ล้อหมุนได้", note: "ช่องว่างเติมด้วย clamp เพราะ hydraulic clamp ถูกนำออกเพื่อให้ล้อหมุนได้" },
      ],
      9: [
        { q: "Hydraulic motors", p: "ten hydraulic motors", th: "มอเตอร์ไฮดรอลิก" },
        { q: "begin to rotate the central", p: "begins to rotate the central axle", th: "เริ่มหมุนแกนกลาง", note: "ช่องว่างเติมด้วย axle เพราะมอเตอร์เริ่มหมุน central axle" },
      ],
      10: [
        { q: "Different-sized", p: "eight-metre-wide cogs ... two smaller cogs", th: "ขนาดต่างกัน (เฟืองใหญ่และเฟืองเล็ก)" },
        { q: "keep the gondola upright", p: "the gondolas always remain level", th: "ทำให้กอนโดลาตั้งตรง", note: "ช่องว่างเติมด้วย cogs เพราะเฟืองขนาดต่าง ๆ ทำให้กอนโดลาคงระดับตั้งตรง" },
      ],
      11: [
        { q: "The boat passes onto", p: "the boat passes straight onto", th: "เรือเคลื่อนเข้าสู่" },
        { q: "above the canal basin", p: "24 metres above the canal basin", th: "เหนืออ่างคลอง", note: "ช่องว่างเติมด้วย aqueduct เพราะเรือเคลื่อนเข้าสู่ aqueduct ที่อยู่เหนืออ่างคลอง" },
      ],
      12: [
        { q: "travel through a tunnel", p: "travel under this wall via a tunnel", th: "เดินทางผ่านอุโมงค์" },
        { q: "beneath the Roman", p: "Antonine Wall, which was built by the Romans", th: "ใต้กำแพงของชาวโรมัน", note: "ช่องว่างเติมด้วย wall เพราะเรือลอดใต้กำแพง (Antonine Wall ของชาวโรมัน) ผ่านอุโมงค์" },
      ],
      13: [
        { q: "A pair of", p: "a pair of locks", th: "ชุดละสอง (ประตูน้ำคู่หนึ่ง)" },
        { q: "raise the boat to the Union Canal level", p: "The remaining 11 metres of lift needed to reach the Union Canal", th: "ยกเรือขึ้นสู่ระดับคลอง Union", note: "ช่องว่างเติมด้วย locks เพราะประตูน้ำคู่หนึ่งยกเรือขึ้น 11 เมตรสุดท้ายสู่คลอง Union" },
      ],
    },
  },
}
