import type { IntensiveQuestionSolution } from './intensiveJourneyQuestionSolutions.ts'
const s = (passageKeyword: string, questionKeyword: string, thaiMeaning: string): IntensiveQuestionSolution => ({
  passageKeyword, questionKeyword, thaiMeaning
})
export const INTENSIVE_SOLUTIONS_STAGE_8_12: Record<number, { 1: Record<number, IntensiveQuestionSolution>; 2: Record<number, IntensiveQuestionSolution> }> = {

  8: {
    1: {
      1: s('Alexander spent much of his childhood in the area', 'alexander childhood', 'FALSE'),
      2: s('Although he never liked the prospect of a business career, he stayed with it to please his family', 'although prospect business career', 'TRUE'),
      3: s('The two men made a photographic excursion to Niagara Falls in 1860 and they cooperated on experiments with magnesium flares as a source of artificial light in 1865', 'photographic excursion niagara cooperated', 'NOT GIVEN'),
      4: s('their styles of photography were quite different', 'styles photography different', 'FALSE'),
      5: s('In 1866, he gave up his business to open a photographic studio, advertising himself as a portrait and landscape photographer', 'business photographic studio advertising', 'NOT GIVEN'),
      6: s('he dropped portraiture to specialize in landscape photography and other views', 'dropped portraiture specialize landscape', 'TRUE'),
      7: s('the almost-completed line connecting Montreal to Halifax', 'almost-completed connecting montreal halifax', 'FALSE'),
      8: s('He continued in this post until 1897, when he retired completely from photography.', 'continued retired completely photography', 'TRUE'),
      9: s('Alexander Henderson was born in Scotland in 1831 and was the son of a successful merchant', 'Alexander Henderson was born in Scotland in 1831 and was the…', 'merchant'),
      10: s('There was little competing hobby or amateur photography before the late 1880s because of the time-consuming techniques involved and the weight of equipment', 'little competing amateur photography', 'equipment'),
      11: s('People wanted to buy photographs as souvenirs of a trip or as gifts', 'wanted photographs souvenirs', 'gifts'),
      12: s('often travelled by canoe on the Blanche, du Lièvre, and other noted eastern rivers', 'often travelled by canoe on the Blanche, du Lièvre, and othe…', 'canoe'),
      13: s('In 1885 he went west along the Canadian Pacific Railway (CPR) as far as Rogers Pass in British Columbia, where he took photographs of the mountains and the progress of construction.', 'canadian pacific railway rogers', 'mountains'),
    },
    2: {
      1: s('Foul air, rather than germs, was believed to be the main driver of ‘hospital fever’, leading to disease and frequent death. The prosperous steered clear of hospitals.', 'rather believed driver hospital', 'F'),
      2: s('Short regards glass, steel and air-conditioned skyscrapers as symbols of status, rather than practical ways of meeting our requirements.', 'regards air-conditioned skyscrapers symbols', 'C'),
      3: s('We discovered that 19th-century hospital wards could generate up to 24 air changes an hour – that’s similar to the performance of a modern-day, computer-controlled operating theatre', 'discovered 19th-century hospital generate', 'E'),
      4: s('‘We put pathogens* in the airstreams, modelled for someone with tuberculosis (TB) coughing in the wards and we found the ventilation systems in the room would have kept other patients safe from harm.', 'pathogens airstreams modelled someone', 'D'),
      5: s('the widespread introduction of air conditioning systems, which were ‘relentlessly and aggressively marketed’ by their inventors', 'widespread introduction conditioning systems', 'B'),
      6: s('Short’s book highlights a developing and sophisticated art and science of ventilating buildings through the 19th and earlier-20th centuries, including the design of ingeniously ventilated hospitals. Of particular interest were those built to the designs of John Shaw Billings', 'highlights developing sophisticated science', 'designs'),
      7: s('We put pathogens* in the airstreams', 'airstreams', 'pathogens'),
      8: s('modelled for someone with tuberculosis', 'modelled someone', 'tuberculosis'),
      9: s('19th-century hospital wards could generate up to 24 air changes an hour', '19th-century hospital generate changes', 'wards'),
      10: s('Communal wards appropriate for certain patients – older people with dementia, for example – would work just as well in today’s hospitals, at a fraction of the energy cost', 'appropriate certain patients dementia', 'communal'),
      11: s('Much of the ingenuity present in 19th-century hospital and building design was driven by a panicked public', 'ingenuity present 19th-century hospital', 'public'),
      12: s('protect against what was thought to be the lethal threat of miasmas', 'protect against thought lethal', 'miasmas'),
      13: s('the spread of infection from the Middle Ages right through to the cholera outbreaks in London and Paris during the 1850s', 'spread infection middle outbreaks', 'cholera'),
    },
  },
  9: {
    1: {
      1: s('implicit theories of intelligence drive the way in which people perceive and evaluate their own intelligence and that of others', 'implicit theories intelligence perceive', 'B'),
      2: s('In other words, people all have unconscious notions – known as ‘implicit theories’ – of intelligence, but no one knows for certain what it actually is.', 'unconscious notions implicit theories', 'A'),
      3: s('implicit theories can be useful when an investigator suspects that existing explicit theories are wrong or misleading. If an investigation of implicit theories reveals little correspondence between the extant implicit and explicit theories, the implicit theories may be wrong.', 'implicit theories useful investigator', 'D'),
      4: s('parents’ implicit theories of their children’s language development will determine at what ages they will be willing to make various corrections in their children’s speech', 'parents implicit theories children', 'NOT GIVEN'),
      5: s('people have expectations for intellectual performances that differ for children of different ages. How these expectations differ is in part a function of culture.', 'expectations intellectual performances differ', 'NO'),
      6: s('Until scholars are able to discuss their implicit theories and thus their assumptions, they are likely to miss the point of what others are saying', 'scholars discuss implicit theories', 'YES'),
      7: s('The Jeffersonian view is that people should have equal opportunities', 'jeffersonian should opportunities', 'B'),
      8: s('In this view, we do not need or want any institutions that might lead to favoring one group over another.', 'institutions favoring another', 'C'),
      9: s('People are rewarded for what they accomplish', 'rewarded accomplish', 'B'),
      10: s('people are born with different levels of intelligence', 'different levels intelligence', 'A'),
      11: s('those who are less intelligent need the good offices of the more intelligent to keep them in line', 'intelligent offices intelligent', 'A'),
      12: s('The Jacksonian view is that all people are equal, not only as human beings but in terms of their competencies', 'jacksonian beings competencies', 'C'),
      13: s('Left to themselves, the unintelligent would create, as they always have created, a kind of chaos', 'themselves unintelligent create always', 'A'),
    },
    2: {
      1: s('This realisation, together with several looming health crises, such as antibiotic resistance, has put bioprospecting – the search for useful compounds in nature – firmly back on the map.', 'realization together several looming', 'C'),
      2: s('it is now possible to snip out the stretches of the insect\'s DNA that carry the codes for the interesting compounds and insert them into cell lines that allow larger quantities to be produced.', 'possible stretches insect interesting', 'H'),
      3: s('the capuchin monkeys who rub themselves with toxin-oozing millipedes to deter mosquitoes, or the chimpanzees who use noxious forest plants to rid themselves of intestinal parasites', 'capuchin monkeys themselves toxin-oozing', 'A'),
      4: s('there are so many insects that, without some manner of targeted approach, investigating this huge variety of species is a daunting task.', 'insects received relatively little', 'F'),
      5: s('my main motivation for looking at insects in this way is conservation. I sincerely believe that all species, however small and seemingly insignificant, have a right to exist for their own sake.', 'motivation looking insects conservation', 'I'),
      6: s('although there are plenty of promising chemical compounds in nature, finding them is far from easy. Securing sufficient numbers of the organism in question, isolating and characterising the compounds of interest, and producing large quantities of these compounds are all significant hurdles.', 'modern pharmaceutical science nature', 'B'),
      7: s('alloferon, an antimicrobial compound produced by blow fly larvae, is used as an antiviral and antitumor agent in South Korea and Russia.', 'example alloferon antimicrobial compound', 'E'),
      8: s('they have a bewildering array of interactions with other organisms, something which has driven the evolution of an enormous range of very interesting compounds for defensive and offensive purposes.', 'bewildering interactions organisms something', 'C'),
      9: s('it is now possible to snip out the stretches of the insect\'s DNA that carry the codes for the interesting compounds and insert them into cell lines that allow larger quantities to be produced.', 'bewildering interactions organisms something', 'B'),
      10: s('we use our knowledge of ecology as a guide to target our efforts.', 'colleagues aberystwyth university developed', 'ecology'),
      11: s('the many insects that secrete powerful poison for subduing prey and keeping it fresh for future consumption.', 'creatures particularly interest insects', 'prey'),
      12: s('masters of exploiting filthy habitats, such as faeces and carcasses, where they are regularly challenged by thousands of micro-organisms.', 'insects masters exploiting filthy', 'habitats'),
      13: s('there is certainly potential to find many compounds that can serve as or inspire new antibiotics.', 'certainly potential compounds inspire', 'antibiotics'),
    },
  },
  10: {
    1: {
      1: s('Giraldo focused on ants at four age ranges', 'giraldo focused ranges', 'four'),
      2: s('Giraldo watched how well the ants took care of the young of the colony', 'giraldo watched colony', 'young'),
      3: s('followed the telltale scent that the insects usually leave to mark a trail to food', 'followed telltale insects usually', 'food'),
      4: s('She tested how ants responded to light', 'tested responded', 'light'),
      5: s('the older ants attacked the poor fruit fly just as aggressively as the young ones did', 'attacked', 'aggressively'),
      6: s('She saw no major differences with age, nor was there any difference in the location of the dying cells', 'differences difference', 'location'),
      7: s('She also wanted to see if aging affects the density of synaptic complexes within these structures – regions where neurons come together', 'wanted affects density synaptic', 'neurons'),
      8: s('the old ants didn’t experience any drop in the levels of either serotonin or dopamine – brain chemicals whose decline often coincides with aging.', 'experience levels either serotonin', 'chemicals'),
      9: s('Naked mole rats can live for almost 30 years and stay fit for nearly their entire lives', 'almost nearly entire', 'FALSE'),
      10: s('Unlike all previous studies, which only estimated how old the ants were, her work tracked the ants from the time the pupae became adults, so she knew their exact ages', 'unlike previous studies estimated', 'TRUE'),
      11: s('Giraldo expected the older ants to perform poorly in all these tasks. But the elderly insects were all good caretakers and trail-followers', 'giraldo expected perform poorly', 'FALSE'),
      12: s('the results of recent bee studies were mixed – some studies showed age-related declines, which biologists call senescence, and others didn’t.', 'results recent studies studies', 'NOT GIVEN'),
      13: s('Out in the wild, the ants probably don’t live for a full 140 days thanks to predators, disease and just being in an environment that’s much harsher than the comforts of the lab', 'probably thanks predators disease', 'TRUE'),
    },
    2: {
      1: s('Colossal numbers of species are becoming extinct across the world, and many more are increasingly threatened and therefore risk extinction. Moreover, some of these collapses have been sudden, dramatic and unexpected', 'colossal numbers species becoming', 'B'),
      2: s('Being able to undertake research on animals in zoos where there is less risk and fewer variables means real changes can be effected on wild populations', 'undertake research animals variables', 'E'),
      3: s('television documentaries are becoming ever more detailed and impressive, and many natural history specimens are on display in museums', 'television documentaries becoming detailed', 'C'),
      4: s('it is perfectly possible for many species of animals living in zoos or wildlife parks to have a quality of life as high as, or higher than, in the wild. Animals in good zoos get a varied and high-quality diet with all the supplements required, and any illnesses they might have will be treated.', 'perfectly possible species animals', 'A'),
      5: s('The average captive animal will have a greater life expectancy compared with its wild counterpart', 'average captive animal greater', 'TRUE'),
      6: s('A good number of species only exist in captivity, with many of these living in zoos', 'number species captivity living', 'TRUE'),
      7: s('television documentaries are becoming ever more detailed and impressive', 'television documentaries becoming detailed', 'NOT GIVEN'),
      8: s('This was an area where zoos used to be lacking, but they are now increasingly sophisticated in their communication and outreach work.', 'lacking increasingly sophisticated communication', 'FALSE'),
      9: s('Being able to undertake research on animals in zoos where there is less risk and fewer variables', 'undertake research animals variables', 'NOT GIVEN'),
      10: s('send their animal keepers abroad\nMany zoos also work directly to educate conservation workers in other countries', 'animal keepers abroad directly', 'D'),
      11: s('send their animal keepers abroad\nMany zoos also work directly to educate conservation workers in other countries', 'animal keepers abroad directly', 'B'),
      12: s('educating and informing the general population about these animals and their world so that they can assist or at least accept the need to be more environmentally conscious\nStill more only exist in the wild because they have been reintroduced from zoos, or have wild populations that have been boosted by captive bred animals', 'educating informing general population', 'E'),
      13: s('educating and informing the general population about these animals and their world so that they can assist or at least accept the need to be more environmentally conscious\nStill more only exist in the wild because they have been reintroduced from zoos, or have wild populations that have been boosted by captive bred animals', 'educating informing general population', 'B'),
    },
  },
  11: {
    1: {
      1: s('The tree is thickly branched with dense foliage of tough, dark green oval leaves', 'thickly branched foliage leaves', 'oval'),
      2: s('The fruit is encased in a fleshy husk. When the fruit is ripe, this husk splits into two halves along a ridge running the length of the fruit.', 'splits halves running length', 'husk'),
      3: s('These are the sources of the two spices nutmeg and mace, the former being produced from the dried seed', 'former produced latter', 'seed'),
      4: s('the latter from the aril', 'sources spices nutmeg', 'mace'),
      5: s('the Arabs were the exclusive importers of the spice to Europe', 'throughout period exclusive importers', 'Arabs'),
      6: s('thousands of people across Europe were dying of the plague, a highly contagious and deadly disease. Doctors were desperate for a way to stop the spread of this disease, and they decided nutmeg held the cure.', 'thousands across europe highly', 'plague'),
      7: s('all exported nutmeg was covered with lime to make sure there was no chance a fertile seed which could be grown elsewhere would leave the islands', 'addition exported nutmeg covered', 'lime'),
      8: s('One of the Banda Islands, a sliver of land called Run, only 3 km long by less than 1 km wide, was under the control of the British.', 'offered british island britain', 'Run'),
      9: s('in 1770, a Frenchman named Pierre Poivre successfully smuggled nutmeg plants to safety in Mauritius', 'frenchman pierre poivre successfully', 'Mauritius'),
      10: s('in 1778, a volcanic eruption in the Banda region caused a tsunami that wiped out half the nutmeg groves', 'volcanic eruption region caused', 'tsunami'),
      11: s('they never revealed the exact location of the source of this extremely valuable commodity', 'nutmeg prices merchants venice', 'FALSE'),
      12: s('By 1617, the VOC was the richest commercial operation in the world.', 'richest commercial operation', 'NOT GIVEN'),
      13: s('Intent on securing their hold over every nutmeg-producing island, the Dutch offered a trade: if the British would give them the island of Run, they would in turn give Britain a distant and much less valuable island in North America.', 'monopoly nutmeg another century', 'TRUE'),
    },
    2: {
      1: s('the average car spends more than 90 percent of its life parked', 'present average spends percent', 'C'),
      2: s('it may be possible to be productive, to socialise or simply to relax while automation systems have responsibility for safe control of the vehicle', 'another driving purposes', 'B'),
      3: s('drivers will have the freedom to select one that best suits their needs for a particular journey, rather than making a compromise across all their requirements', 'drivers freedom select particular', 'E'),
      4: s('these can most probably be conquered within the next 10 years', 'challenges addressed robust targeted', 'G'),
      5: s('This faster rate of turnover may mean that vehicle production will not necessarily decrease', 'faster turnover vehicle production', 'D'),
      6: s('more than 90 percent of road collisions involve human error as a contributory factor', 'research transport research laboratory', 'human error'),
      7: s('initiatives for car-sharing become much more viable, particularly in urban areas with significant travel demand', 'automation initiatives car-sharing become', 'car sharing'),
      8: s('automated vehicles might reduce vehicle ownership by 43 percent', 'modelling university michigan transportation', 'ownership'),
      9: s('vehicles\' average annual mileage double as a result', 'vehicles average annual double', 'mileage'),
      10: s('it may be possible to be productive, to socialise or simply to relax … those who are challenged by existing mobility models – such as older or disabled travellers – may be able to enjoy significantly greater travel autonomy', 'vehicle driving possible productive', 'D'),
      11: s('it may be possible to be productive, to socialise or simply to relax … those who are challenged by existing mobility models – such as older or disabled travellers – may be able to enjoy significantly greater travel autonomy', 'vehicle driving possible productive', 'C'),
      12: s('the societal changes that may be required for communities to trust and accept automated vehicles … the technical difficulties in ensuring that the vehicle works reliably in the infinite range of traffic, weather and road situations it might encounter', 'societal changes required communities', 'E'),
      13: s('the societal changes that may be required for communities to trust and accept automated vehicles … the technical difficulties in ensuring that the vehicle works reliably in the infinite range of traffic, weather and road situations it might encounter', 'societal changes required communities', 'A'),
    },
  },
  12: {
    1: {
      1: s('That is not to suggest everyone should dance their way to work, however healthy and happy it might make us, but rather that the techniques used by choreographers to experiment with and design movement in dance could provide engineers with tools to stimulate new ideas in city-making', 'suggest everyone should however', 'B'),
      2: s('Whereas medieval builders improvised and adapted construction through their intimate knowledge of materials and personal experience of the conditions on a site, building designs are now conceived and stored in media technologies that detach the designer from the physical and social realities they are creating', 'whereas medieval builders improvised', 'C'),
      3: s('Choreography may not seem an obvious choice for tackling this problem. Yet it shares with engineering the aim of designing patterns of movement within limitations of space', 'choreography obvious choice tackling', 'F'),
      4: s('They failed to take into account that purpose-built street cafés could not operate in the hot sun without the protective awnings common in older buildings', 'failed account purpose-built street', 'D'),
      5: s('Designs that seem logical in models appear counter-intuitive in the actual experience of their users', 'designs logical models appear', 'E'),
      6: s('The way we travel around cities has a major impact on whether they are sustainable', 'travel around cities impact', 'A'),
      7: s('The guard rails that will be familiar to anyone who has attempted to cross a British road, for example, were an engineering solution to pedestrian safety', 'familiar anyone attempted british', 'safety'),
      8: s('based on models that prioritise the smooth flow of traffic', 'models prioritise smooth', 'traffic'),
      9: s('On wide major roads, they often guide pedestrians to specific crossing points and slow down their progress across the road by using staggered access points divide the crossing into two – one for each carriageway', 'pedestrians specific crossing points', 'carriageway'),
      10: s('In doing so they make crossings feel longer, introducing psychological barriers greatly impacting those that are the least mobile', 'crossings longer introducing psychological', 'mobile'),
      11: s('and encouraging others to make dangerous crossings to get around the guard rails', 'encouraging others crossings around', 'dangerous'),
      12: s('These barriers don’t just make it harder to cross the road: they divide communities', 'barriers harder divide', 'communities'),
      13: s('and decrease opportunities for healthy transport', 'decrease opportunities transport', 'healthy'),
    },
    2: {
      1: s('how we could use it to make genetic modifications which could prevent mass extinctions in the future', 'genetic modifications prevent extinctions', 'F'),
      2: s('The basic premise involves using cloning technology to turn the DNA of extinct animals into a fertilised embryo, which is carried by the nearest relative still in existence – in this case, the abundant band-tailed pigeon – before being born as a living, breathing animal.', 'premise involves cloning technology', 'A'),
      3: s('Since the disappearance of this key species, ecosystems in the eastern US have suffered, as the lack of disturbance caused by thousands of passenger pigeons wrecking trees and branches means there has been minimal need for regrowth.', 'Since the disappearance of this key species, ecosystems in t…', 'D'),
      4: s('Sadly, the passenger pigeon’s existence came to an end on 1 September 1914, when the last living specimen died at Cincinnati Zoo.', 'passenger pigeon existence september', 'A'),
      5: s('By pinpointing which genetic traits made it possible for mammoths to survive the icy climate of the tundra, the project’s goal is to return mammoths, or a mammoth-like species, to the area', 'pinpointing genetic traits possible', 'genetic traits'),
      6: s('all for the purpose of reducing heat loss in the tundra', 'purpose reducing tundra', 'heat loss'),
      7: s('Necessary adaptations would include smaller ears', 'necessary adaptations include smaller', 'ears'),
      8: s('extra insulating fat', 'insulating', 'insulating fat'),
      9: s('This grass growth would reduce temperature, and mitigate emissions from melting permafrost', 'growth reduce temperature mitigate', 'emissions'),
      10: s('The return of thylacines to Tasmania could help to ensure that devils are never again subjected to risks of this kind', 'return thylacines tasmania ensure', 'B'),
      11: s('She prefers to focus the debate on how this emerging technology could be used to fully understand why various species went extinct in the first place', 'prefers debate emerging technology', 'C'),
      12: s('According to Novak, a hybridized band-tailed pigeon, with the added nesting habits of a passenger pigeon, could, in theory, re-establish that forest disturbance, thereby creating a habitat necessary for a great many other native species to thrive', 'according hybridized band-tailed pigeon', 'A'),
      13: s('We know that what we are doing today is not enough', 'enough', 'C'),
    },
  },
}
