// AUTO-GENERATED by scripts/assembleIntensivePairs.mjs — do not edit by hand.
// Word-level paraphrase pairs for Normal-Reading, keyed by stage -> slot -> local question number.
import type { ReadingVocabBridgePair } from './readingPassage3VocabBridge.ts'

export const INTENSIVE_PAIRS_STAGE_16_20: Record<number, Record<1 | 2, Record<number, ReadingVocabBridgePair[]>>> = {
  16: {
    1: {
      1: [
        { q: "industrial processes", p: "iron-ore smelting process", th: "กระบวนการทางอุตสาหกรรม (การถลุงแร่เหล็ก)", note: "G อธิบายว่า iron-ore slag เป็น byproduct ของกระบวนการถลุงแร่เหล็ก จึงตอบ G" },
        { q: "raw materials for concrete", p: "alternatives to cement in a concrete mix", th: "วัตถุดิบทดแทนสำหรับส่วนผสมคอนกรีต" },
        { q: "create", p: "byproduct", th: "สิ่งที่เกิดขึ้น/ผลพลอยได้จากกระบวนการ" },
      ],
      2: [
        { q: "various locations", p: "Vancouver, Vienna and Brumunddal in Norway", th: "หลายสถานที่/หลายเมือง", note: "D ระบุชื่อเมืองหลายแห่งที่มีอาคารไม้สูง จึงตอบ D" },
        { q: "high-rise wooden buildings", p: "tall, wooden buildings", th: "อาคารไม้สูง" },
        { q: "can be found", p: "are all home to", th: "เป็นที่ตั้งของ/พบได้ที่" },
      ],
      3: [
        { q: "how widely available", p: "found in abundance in most places around the globe", th: "หาได้ทั่วไปอย่างอุดมสมบูรณ์", note: "C บอกว่าวัตถุดิบของคอนกรีตหาได้มากมายทั่วโลก จึงตอบ C" },
        { q: "raw materials of concrete", p: "ingredients of concrete", th: "วัตถุดิบ/ส่วนผสมของคอนกรีต" },
      ],
      4: [
        { q: "more high-rise wooden buildings are needed", p: "only when a wider range of construction projects has been proven in practice", th: "ต้องมีโครงการก่อสร้างมากขึ้นและพิสูจน์แล้วก่อน", note: "F บอกว่าต้องมีโครงการมากขึ้นก่อนจึงจะมองไม้เป็นทางเลือกแทนคอนกรีตได้ จึงตอบ F" },
        { q: "wood can be regarded as", p: "see wood as a real alternative to concrete", th: "มองไม้เป็นทางเลือกแทนคอนกรีตที่แท้จริง" },
      ],
      5: [
        { q: "modern construction projects", p: "treated timber as a possible resource", th: "วัสดุก่อสร้างสมัยใหม่ (ไม้ที่ผ่านการบำบัด)", note: "ผู้ที่หันมาใช้ไม้คือ architects จึงเติมคำตอบ \"architects\"" },
        { q: "to use wood", p: "driving architects to turn to treated timber", th: "ผลักดันให้สถาปนิกหันมาใช้ไม้" },
      ],
      6: [
        { q: "in the atmosphere", p: "from the air", th: "จากอากาศ/ในบรรยากาศ" },
        { q: "enters wood, it increases in size", p: "Wood expands as it absorbs", th: "ไม้ขยายตัวเมื่อดูดซับ", note: "สิ่งที่ไม้ดูดซับจากอากาศแล้วทำให้ขยายตัวคือ moisture จึงตอบ \"moisture\"" },
        { q: "wood is prone to pests", p: "susceptible to pests", th: "เสี่ยงต่อแมลงศัตรู" },
      ],
      7: [
        { q: "solid wood are glued together", p: "stick layers of solid-sawn timber together", th: "นำไม้แท้มาติดกาวประกบกัน", note: "สิ่งที่ถูกนำมาประกบกันคือ layers (ชั้นไม้) จึงตอบ \"layers\"" },
        { q: "create building blocks", p: "to form building blocks", th: "สร้างเป็นบล็อกก่อสร้าง" },
        { q: "glued together", p: "An adhesive is used to stick", th: "ใช้กาวยึดติดกัน" },
      ],
      8: [
        { q: "with which they can be constructed", p: "constructed at a greater speed", th: "ความเร็วในการก่อสร้าง", note: "ข้อได้เปรียบด้านความเร็วในการก่อสร้างคือ speed จึงตอบ \"speed\"" },
        { q: "how much noise is generated", p: "the process, it seems, is quieter", th: "เสียงที่เกิดจากกระบวนการ (เงียบกว่า)" },
      ],
      9: [
        { q: "environmental advantage", p: "overall carbon reduction perspective", th: "ข้อดีด้านสิ่งแวดล้อม/การลดคาร์บอน", note: "Surgenor (C) ชี้ว่าหากขนส่งไกลด้วยเชื้อเพลิงฟอสซิล ข้อดีด้านคาร์บอนอาจไม่คุ้ม จึงตอบ C" },
        { q: "may not be as great as initially assumed", p: "might not make sense", th: "อาจไม่คุ้ม/ไม่สมเหตุสมผลอย่างที่คิด" },
        { q: "cement alternatives", p: "use of alternative materials", th: "วัสดุทางเลือกแทนซีเมนต์" },
      ],
      10: [
        { q: "hard to create a material", p: "Making anything", th: "การสร้างวัสดุขึ้นมา" },
        { q: "similar properties to concrete", p: "similar properties", th: "คุณสมบัติที่คล้ายกัน", note: "Cheeseman (อ้างใน paragraph A คือ answer A) บอกว่าทำสิ่งที่มีคุณสมบัติคล้ายคอนกรีตยากมาก จึงตอบ A" },
        { q: "It would be hard", p: "is going to be very difficult", th: "จะเป็นเรื่องยากมาก" },
      ],
      11: [
        { q: "Worries about the environment", p: "climate change concerns", th: "ความกังวลด้านสิ่งแวดล้อม/การเปลี่ยนแปลงสภาพภูมิอากาศ", note: "Mannstrom รายงานว่าความกังวลเรื่องสภาพภูมิอากาศเป็นตัวขับเคลื่อนความสนใจในไม้ จึงตอบ B" },
        { q: "increased interest in wood", p: "the key driver", th: "ปัจจัยหลักที่กระตุ้นความต้องการ" },
      ],
      12: [
        { q: "Expense", p: "cost-effective", th: "ต้นทุน/ความคุ้มค่าด้านราคา", note: "Preston และ Lehne บอกว่าวัสดุทางเลือกมักไม่คุ้มค่าเท่าซีเมนต์ทั่วไป จึงตอบ D" },
        { q: "factor inhibiting the use of new materials", p: "resistance from customers", th: "ปัจจัยที่ขัดขวางการใช้วัสดุใหม่" },
        { q: "new materials", p: "these alternatives", th: "วัสดุทางเลือกใหม่" },
      ],
      13: [
        { q: "produced in large quantities", p: "the sheer scale of manufacture is so huge", th: "ผลิตในปริมาณมหาศาล", note: "Cheeseman (paragraph B/answer A) บอกว่าที่ทำให้คอนกรีตปล่อยคาร์บอนสูงคือขนาดการใช้/ผลิตที่มหาศาล จึงตอบ A" },
        { q: "environmental damage", p: "high carbon", th: "ผลกระทบต่อสิ่งแวดล้อม (คาร์บอนสูง)" },
        { q: "due to it being", p: "it is the scale on which it is used that makes it", th: "เป็นเพราะขนาดการใช้งานที่ทำให้เป็นเช่นนั้น" },
      ],
    },
    2: {
      1: [
        { q: "successes failures", p: "successes and failures", th: "ความสำเร็จและความล้มเหลว", note: "หัวข้อ iii พูดถึงทั้งความสำเร็จและความล้มเหลวของพี่น้องโดเบิล ตรงกับย่อหน้า A พอดี จึงตอบ iii" },
        { q: "doble brothers", p: "Doble brothers", th: "พี่น้องตระกูลโดเบิล" },
        { q: "steam cars", p: "steam cars", th: "รถยนต์พลังไอน้ำ" },
      ],
      2: [
        { q: "inherited", p: "inherited", th: "สืบทอด/ได้รับมา", note: "ย่อหน้า B ระบุว่ารถยุคแรกรับเอาทั้งจุดอ่อนและจุดแข็งของไอน้ำมา จึงตรงกับหัวข้อ iii" },
        { q: "weaknesses", p: "weaknesses", th: "จุดอ่อน/ข้อด้อย" },
        { q: "strengths", p: "strengths", th: "จุดแข็ง/ข้อดี" },
      ],
      3: [
        { q: "technology called internal combustion", p: "technology called the Internal Combustion Engine", th: "เทคโนโลยีที่เรียกว่าเครื่องยนต์สันดาปภายใน", note: "ย่อหน้า C แนะนำเครื่องยนต์สันดาปภายในที่เข้ามาแทนพลังไอน้ำ จึงตอบหัวข้อ viii" },
        { q: "appeared", p: "soon appeared", th: "ปรากฏขึ้น/เกิดขึ้น" },
      ],
      4: [
        { q: "attention automobile magazines", p: "drew the attention of automobile trade magazines", th: "ดึงดูดความสนใจของนิตยสารรถยนต์", note: "ย่อหน้า D บอกว่า Model B ได้รับความสนใจจากนิตยสารเพราะมีการปรับปรุงมากมายและเหนือกว่ารถน้ำมัน จึงตอบ vi" },
        { q: "numerous", p: "numerous improvements", th: "การปรับปรุงจำนวนมาก" },
      ],
      5: [
        { q: "general engineering company", p: "General Engineering Company", th: "บริษัทเจเนอรัลเอนจิเนียริง", note: "ย่อหน้า E เล่าว่าบริษัทได้รับเงินมัดจำ 5,390 รายการ ตรงกับหัวข้อ v จึงตอบ v" },
        { q: "received", p: "received 5,390 deposits", th: "ได้รับ (เงินมัดจำ)" },
      ],
      6: [
        { q: "buyers received", p: "buyers who received", th: "ผู้ซื้อที่ได้รับ", note: "ย่อหน้า F บอกว่าผู้ซื้อที่ได้รับรถบ่นว่ารถมีปัญหา จึงตรงกับหัวข้อ vii" },
        { q: "completed", p: "completed cars", th: "รถที่ผลิตเสร็จ" },
        { q: "handful", p: "handful", th: "จำนวนเล็กน้อย" },
      ],
      7: [
        { q: "sitting overnight", p: "sitting overnight", th: "จอดทิ้งไว้ข้ามคืน", note: "ย่อหน้า G เล่าการทดสอบรถที่จอดข้ามคืนในอากาศหนาวเย็นจัด จึงตอบหัวข้อ i" },
        { q: "freezing temperatures", p: "freezing temperatures", th: "อุณหภูมิเยือกแข็ง" },
      ],
      8: [
        { q: "point does the writer make about the steam car", p: "the glory days of steam cars were few", th: "ช่วงรุ่งเรืองของรถไอน้ำนั้นสั้นมาก", note: "ผู้เขียนชี้ว่ายุครุ่งโรจน์ของรถไอน้ำมีอยู่ไม่นาน ตรงกับตัวเลือก A จึงตอบ A" },
        { q: "steam car", p: "steam cars", th: "รถยนต์พลังไอน้ำ" },
      ],
      9: [
        { q: "first steam car", p: "first steam car", th: "รถไอน้ำคันแรก" },
        { q: "did not run well", p: "did not run well", th: "วิ่งได้ไม่ดี/ทำงานไม่ดี", note: "รถคันแรกวิ่งได้ไม่ดี แต่พี่น้องก็เดินหน้าสร้างต้นแบบคันที่สองและสามต่อ ตรงกับตัวเลือก C จึงตอบ C" },
        { q: "second prototype", p: "second and third prototype", th: "ต้นแบบคันที่สอง" },
      ],
      10: [
        { q: "produce the Model C", p: "seek investment in his automobile design", th: "เพื่อผลิตรถรุ่น Model C จึงไปหาเงินลงทุน", note: "เพื่อสร้าง Model C อับเนอร์ขับรถไปหานักลงทุนในแบบรถของเขา ตรงกับตัวเลือก B จึงตอบ B" },
        { q: "investment", p: "investment", th: "การลงทุน/เงินลงทุน" },
        { q: "automobile design", p: "automobile design", th: "แบบ/การออกแบบรถยนต์" },
      ],
      11: [
        { q: "while keeping its emissions extremely low", p: "a virtually silent powerplant", th: "พร้อมข้อดีอื่น ๆ ที่บริษัทโฆษณาไว้", note: "บริษัทสัญญาว่ารถจะมีความสะดวกเท่ารถน้ำมันแต่ 'speed' (ความเร็ว) สูงกว่ามาก ช่องว่างจึงเติม speed" },
        { q: "much greater", p: "much greater speed", th: "เร็วกว่ามาก" },
        { q: "convenience of a gasoline car", p: "convenience of a gasoline car", th: "ความสะดวกของรถน้ำมัน" },
      ],
      12: [
        { q: "cars were produced", p: "Model E steam cars had been produced", th: "รถที่ถูกผลิตออกมา", note: "มีการผลิตรถ Model E น้อยกว่าห้าสิบคันก่อนบริษัทปิดตัว ช่องว่างจึงเติม 50" },
        { q: "went out of business", p: "the company folded", th: "บริษัทเลิกกิจการ" },
      ],
      13: [
        { q: "satisfy California's emissions laws", p: "pass the emissions laws in California", th: "ผ่านกฎหมายควบคุมไอเสียของแคลิฟอร์เนีย", note: "แม้ไม่ดัดแปลง รถ Model E ก็ผ่านกฎหมายไอเสียที่ 'strict' (เข้มงวด) ของแคลิฟอร์เนีย ช่องว่างจึงเติม strict" },
        { q: "even today", p: "California today", th: "แม้ในปัจจุบัน" },
      ],
    },
  },
  17: {
    1: {
      1: [
        { q: "challenges to be overcome", p: "Other considerations include", th: "อุปสรรค/ประเด็นที่ต้องจัดการก่อน" },
        { q: "challenges", p: "planning restrictions and disruption", th: "ข้อจำกัดและการรบกวนที่เป็นอุปสรรค", note: "ย่อหน้า D ระบุอุปสรรคหลายอย่าง (ทักษะใหม่, ระบบระบายน้ำ, ข้อกำหนดความปลอดภัย, ข้อจำกัดการวางผัง) จึงตอบ D" },
        { q: "before", p: "during installation", th: "ก่อน/ระหว่างการติดตั้ง" },
      ],
      2: [
        { q: "a city", p: "San Francisco, USA", th: "เมืองหนึ่ง" },
        { q: "a formal set of rules", p: "created a policy", th: "การออกกฎ/นโยบายอย่างเป็นทางการ", note: "ซานฟรานซิสโกออกนโยบายบังคับอาคารใหม่ให้มี green roof ตรงกับ 'formal set of rules' จึงตอบ C" },
        { q: "green roof installation", p: "new buildings to have green roofs", th: "การติดตั้ง green roof" },
      ],
      3: [
        { q: "a belief", p: "the evidence so far indicates", th: "ความเชื่อ/หลักฐานที่บ่งชี้" },
        { q: "existing green roofs", p: "green roofs have the potential", th: "green roof ที่มีอยู่" },
        { q: "should be used as", p: "studied and replicated elsewhere", th: "ควรนำไปใช้/ทำซ้ำที่อื่น", note: "ย่อหน้า E ระบุว่าควรศึกษาและทำซ้ำเรื่องราวความสำเร็จ สื่อว่า green roof ที่มีอยู่ควรใช้เป็นต้นแบบ จึงตอบ E" },
      ],
      4: [
        { q: "work in combination with", p: "can integrate with", th: "ทำงานร่วมกับ/ผสานเข้ากับ", note: "ย่อหน้า B ยกตัวอย่าง green roof ผสานกับ 'living walls' และระบบระบายน้ำ ตรงกับ 'in combination with other green urban initiatives' จึงตอบ B" },
        { q: "other green urban initiatives", p: "‘living walls’", th: "โครงการสีเขียวในเมืองอื่น ๆ" },
        { q: "examples", p: "drainage systems on the ground, such as street trees", th: "ตัวอย่างประกอบ" },
      ],
      5: [
        { q: "make the financial benefits ... obvious", p: "economic arguments are still the most important", th: "ทำให้ประโยชน์ทางการเงินชัดเจน", note: "ย่อหน้า D ระบุว่าต้องใช้เหตุผลทางเศรษฐกิจเพื่อโน้มน้าวนักลงทุน ตรงกับการทำให้ประโยชน์ทางการเงินชัดเจน จึงตอบ D" },
        { q: "developers", p: "investors and developers", th: "นักพัฒนา/ผู้ลงทุน" },
        { q: "the need to", p: "To convince", th: "ความจำเป็นที่จะต้องโน้มน้าว" },
      ],
      6: [
        { q: "environments that are suitable for wildlife", p: "making habitats for urban wildlife", th: "สร้างที่อยู่อาศัยให้สัตว์ป่าในเมือง" },
        { q: "producing", p: "saving on energy costs", th: "การผลิต/ประหยัด (พลังงาน)", note: "ช่องว่างต่อจาก benefit ต่าง ๆ ตรงกับ 'saving on energy costs' จึงเติม 'energy'" },
      ],
      7: [
        { q: "social benefits", p: "making habitats for urban wildlife", th: "ประโยชน์ต่าง ๆ ของ green roof" },
        { q: "producing", p: "growing food", th: "การผลิต/ปลูกอาหาร", note: "รายการ benefit จบด้วย 'even growing food' จึงเติมคำตอบ 'food'" },
      ],
      8: [
        { q: "the medical profession recommends", p: "Doctors are increasingly prescribing", th: "แพทย์แนะนำ/สั่งให้ทำ", note: "แพทย์ 'prescribing time spent gardening' เพื่อช่วยผู้ป่วยวิตกกังวล/ซึมเศร้า จึงเติมคำตอบ 'gardening'" },
        { q: "cope with mental health issues", p: "anxiety and depression", th: "รับมือกับปัญหาสุขภาพจิต" },
        { q: "activity", p: "time spent gardening outdoors", th: "กิจกรรม (การทำสวน)" },
      ],
      9: [
        { q: "the availability of green spaces", p: "access to even the most basic green spaces", th: "การเข้าถึงพื้นที่สีเขียว" },
        { q: "prevent physical problems", p: "help people avoid", th: "ป้องกันปัญหาทางกาย", note: "บทความระบุว่าพื้นที่สีเขียวช่วยให้ผู้คน 'avoid obesity' จึงเติมคำตอบ 'obesity'" },
      ],
      10: [
        { q: "advantages of using newer buildings", p: "can typically hold greater weight", th: "ข้อดีของอาคารใหม่ (รับน้ำหนักได้มากกว่า)", note: "อาคารใหม่ 'hold greater weight' รับน้ำหนักได้มากกว่า เป็นข้อดีหนึ่ง จึงเลือก D" },
        { q: "newer buildings", p: "newer buildings, which can typically hold greater weight", th: "อาคารที่ใหม่กว่า" },
      ],
      11: [
        { q: "advantages of using newer buildings", p: "easier to grow a greater variety of plants", th: "ข้อดี: ปลูกพืชได้หลากหลายกว่า", note: "หลังคาที่แข็งแรงทำให้ดินลึกขึ้นและ 'grow a greater variety of plants' เป็นอีกข้อดี จึงเลือก C" },
        { q: "newer buildings", p: "the soil can be deeper", th: "อาคารใหม่ (ดินลึกกว่า)" },
      ],
      12: [
        { q: "aims of new variations", p: "hold water over longer periods of time", th: "เป้าหมายของรูปแบบใหม่ (เก็บน้ำได้นานขึ้น)", note: "'blue roofs' เก็บน้ำได้นานขึ้นช่วงฝนหนัก เป็นเป้าหมายหนึ่งของรูปแบบใหม่ จึงเลือก D" },
        { q: "new variations on the concept of green roofs", p: "new variations in the concept", th: "รูปแบบใหม่ของ green roof" },
      ],
      13: [
        { q: "aims of new variations", p: "maximise biodiversity", th: "เป้าหมาย: เพิ่มความหลากหลายทางชีวภาพ", note: "'brown roofs' ที่เป็นธรรมชาติมากขึ้นเพื่อ 'maximise biodiversity' เป็นอีกเป้าหมาย จึงเลือก A" },
        { q: "new variations", p: "‘brown roofs’ which are wilder in nature", th: "รูปแบบใหม่ (brown roofs)" },
      ],
    },
    2: {
      1: [
        { q: "educators", p: "educators such as John Dewey", th: "นักการศึกษา" },
        { q: "argued", p: "argued", th: "ให้เหตุผล/โต้แย้งว่า" },
        { q: "intelligence", p: "every child's intelligence could be developed", th: "สติปัญญา (พัฒนาได้)", note: "ย่อหน้า A กล่าวว่า นักการศึกษาอย่าง John Dewey โต้แย้งว่าสติปัญญาของเด็กพัฒนาได้ ตรงกับสิ่งที่เรียนรู้จากย่อหน้าแรก จึงตอบ A" },
      ],
      2: [
        { q: "schools", p: "the growth mindset in schools", th: "โรงเรียน" },
        { q: "encourage students to", p: "coaxing students away from", th: "ชักจูง/กระตุ้นนักเรียนให้" },
        { q: "growth mindset", p: "growth mindset", th: "กรอบความคิดแบบเติบโต", note: "ย่อหน้า B อธิบายว่าโรงเรียนชักจูงนักเรียนให้มองความล้มเหลวเป็นโอกาสพัฒนา ตรงกับ \"how schools encourage students to\" จึงตอบ B" },
      ],
      3: [
        { q: "students with", p: "the former", th: "นักเรียนกลุ่มนั้น (กลุ่มแรก)" },
        { q: "third paragraph", p: "Meanwhile, the former took on only those tasks", th: "ย่อหน้าที่สาม", note: "ย่อหน้า C ระบุว่ากลุ่มแรก (ที่ถูกชมเรื่องความฉลาด) เลือกทำเฉพาะงานที่ไม่เสี่ยงต่อคุณค่าในตัวเอง ตรงกับสิ่งที่ผู้เขียนเสนอ จึงตอบ C" },
        { q: "suggests", p: "took on only those tasks that would not risk their sense of worth", th: "บ่งชี้/ชี้ให้เห็น" },
      ],
      4: [
        { q: "methodology", p: "their research designs", th: "ระเบียบวิธีวิจัย/การออกแบบงานวิจัย" },
        { q: "not strict enough", p: "enough degrees of freedom that they could take their data to support just about any theory at all", th: "ไม่รัดกุมพอ", note: "ย่อหน้า E อ้าง Andrew Gelman ว่าการออกแบบวิจัยหลวมจนสนับสนุนทฤษฎีใดก็ได้ ตรงกับ \"methodology...not strict enough\" จึงตอบ E" },
        { q: "growth mindset studies", p: "research designs", th: "การศึกษาเรื่องกรอบความคิดแบบเติบโต" },
      ],
      5: [
        { q: "incorrectly interpreted", p: "misunderstood and misapplied", th: "ถูกตีความ/นำไปใช้อย่างผิด ๆ", note: "ย่อหน้า F ระบุว่า Dweck โต้แย้งว่างานของเธอถูกเข้าใจผิดและนำไปใช้ผิด ตรงกับ \"incorrectly interpreted\" จึงตอบ F" },
        { q: "the growth mindset", p: "her work", th: "กรอบความคิดแบบเติบโต/งานของเธอ" },
      ],
      6: [
        { q: "unchangeable", p: "inherent ability is destiny", th: "เปลี่ยนแปลงไม่ได้/ติดตัวมาแต่กำเนิด" },
        { q: "Intellectual ability", p: "inherent ability", th: "ความสามารถทางปัญญา", note: "ย่อหน้า A กล่าวถึงแนวคิดที่ว่าความสามารถติดตัวคือชะตากรรม (ที่นักคิดก้าวหน้าต่อต้าน) ตรงกับ \"intellectual ability is unchangeable\" จึงตอบ A" },
        { q: "feature of each individual", p: "inherent", th: "คุณลักษณะติดตัวของแต่ละคน" },
      ],
      7: [
        { q: "promoted without students being aware of it", p: "delivered in a subtle way", th: "ส่งเสริมแบบแนบเนียนโดยนักเรียนไม่รู้ตัว", note: "ย่อหน้า G ระบุว่า Yeager และ Walton แนะให้แทรกแซงอย่างแนบเนียน เพราะถ้านักเรียนรู้ตัวจะลดผล ตรงกับ \"without students being aware\" จึงตอบ G" },
        { q: "growth mindset", p: "interventions", th: "กรอบความคิดแบบเติบโต/การแทรกแซง" },
      ],
      8: [
        { q: "not simply about boosting students' morale", p: "conflated with the self-esteem movement", th: "ไม่ใช่แค่การปลุกขวัญกำลังใจนักเรียน", note: "ย่อหน้า F ระบุว่า Dweck กังวลว่าทฤษฎีถูกนำไปปนกับขบวนการเสริมความภาคภูมิใจ ตรงกับ \"not simply about boosting morale\" จึงตอบ F" },
        { q: "growth mindset", p: "her theories", th: "กรอบความคิดแบบเติบโต/ทฤษฎีของเธอ" },
      ],
      9: [
        { q: "no effect on academic achievement", p: "results are repeatedly null", th: "ไม่มีผลต่อผลสัมฤทธิ์ทางการเรียน", note: "ย่อหน้า E ระบุว่า Timothy Bates ทำซ้ำงานของ Dweck แล้วได้ผลเป็นศูนย์ซ้ำ ๆ ตรงกับ \"no effect on achievement\" จึงตอบ E" },
        { q: "Research shows", p: "trying to replicate Dweck's work, is finding", th: "งานวิจัยแสดงให้เห็น" },
      ],
      10: [
        { q: "handled criticisms", p: "responding to it and adapting her work", th: "รับมือกับคำวิจารณ์" },
        { q: "in an admirable way", p: "deserves great credit", th: "อย่างน่าชื่นชม", note: "ย่อหน้า F ระบุว่า Dweck สมควรได้รับการยกย่องที่ตอบรับคำวิจารณ์และปรับงาน ตรงกับมุมมองในข้อ จึงตอบ YES" },
        { q: "her work", p: "her work", th: "งานของเธอ" },
      ],
      11: [
        { q: "self-perception", p: "self-perception", th: "การรับรู้ตนเอง" },
        { q: "Students'", p: "achievement on self-perception", th: "ของนักเรียน/ผลสัมฤทธิ์", note: "ย่อหน้า H ระบุว่าผลของความสำเร็จต่อการรับรู้ตนเองแรงกว่าทางกลับกัน ขัดกับข้อความที่ให้น้ำหนักการรับรู้ตนเองเป็นตัวขับ จึงตอบ NO" },
      ],
      12: [
        { q: "Recent evidence", p: "Recent evidence", th: "หลักฐานล่าสุด" },
        { q: "growth mindset interventions", p: "growth mindset interventions", th: "การแทรกแซงด้วยกรอบความคิดแบบเติบโต" },
        { q: "unfair coverage in the media", p: "are not the elixir of student learning", th: "การนำเสนอข่าวอย่างไม่เป็นธรรม", note: "บทความพูดถึงหลักฐานล่าสุดเรื่องการแทรกแซง แต่ไม่ได้กล่าวถึงการนำเสนอข่าวในสื่ออย่างไม่เป็นธรรมเลย จึงตอบ NOT GIVEN" },
      ],
      13: [
        { q: "Deliberate attempts to encourage students", p: "Motivational posters and talks", th: "ความพยายามจงใจกระตุ้นนักเรียน" },
        { q: "may have", p: "might well give students a deluded notion of what success actually means", th: "อาจส่งผล (ในทางลบ)", note: "ย่อหน้า J ระบุว่าโปสเตอร์และคำพูดสร้างแรงจูงใจมักเสียเวลาและทำให้นักเรียนเข้าใจความสำเร็จผิด ตรงกับมุมมองในข้อ จึงตอบ YES" },
      ],
    },
  },
}
