import type { IntensiveQuestionSolution } from './intensiveJourneyQuestionSolutions.ts'
const s = (passageKeyword: string, questionKeyword: string, thaiMeaning: string): IntensiveQuestionSolution => ({
  passageKeyword, questionKeyword, thaiMeaning
})
export const INTENSIVE_SOLUTIONS_STAGE_1_5: Record<number, { 1: Record<number, IntensiveQuestionSolution>; 2: Record<number, IntensiveQuestionSolution> }> = {

  1: {
    1: {
      1: s('ancient stepwells found', 'unique region stepwells architecturally', 'ข้อความในข้อว่า "Examples of ancient stepwells can be found all over the world." ไม่ตรงกับบทความ เพราะบทความระบุว่า "Unique to the region, stepwells are often architecturally complex and vary widely in size and s…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      2: s('heyday places gathering leisure', 'stepwells gathering leisure worship', 'ข้อความในข้อตรงกับบทความ เพราะระบุว่า During their heyday, they were places of gathering, of leisure, of relaxation and of worship จึงตอบ TRUE'),
      3: s('found elsewhere', 'survive', 'ข้อความในข้อว่า "The few existing stepwells in Delhi are more attractive than those found elsewhere." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "a few also survive in Delhi.") จึงตอบ NOT GIVEN'),
      4: s('workers years build', 'suggests stepwells comprise series', 'ข้อความในข้อว่า "It took workers many years to build the stone steps characteristic of stepwells." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "As their name suggests, stepwells comprise a series of stone steps descending from ground level…") จึงตอบ NOT GIVEN'),
      5: s('number steps above', 'needed descend several levels', 'ข้อความในข้อว่า "The number of steps above the water level in" ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "When the water level was high, the user needed only to descend a few steps to reach it; when it…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      6: s('stepwells provided shade', 'included sheltered visitors relentless', 'จึงคำตอบคือ "pavilions" (paraphrase จากข้อความใน passage)'),
      7: s('serious climatic event', 'condition helped recent spells', 'จึงคำตอบคือ "drought" (paraphrase จากข้อความใน passage)'),
      8: s('frequent visitors stepwells', 'far-flung corners northwestern wonder', 'จึงคำตอบคือ "tourists" (paraphrase จากข้อความใน passage)'),
      9: s('… of 2001.', 'Incredibly, in January 2001, this ancient structure survived…', 'จึงคำตอบคือ "Earthquake" (paraphrase จากข้อความใน passage)'),
      10: s('produce', 'including descend bottom stunning', 'จึงคำตอบคือ "four sides" (paraphrase จากข้อความใน passage)'),
      11: s('well', 'actually resembles reservoir rather', 'จึงคำตอบคือ "Tank" (paraphrase จากข้อความใน passage)'),
      12: s('provide', 'fourth verandas supported ornate', 'จึงคำตอบคือ "verandahs" (paraphrase จากข้อความใน passage)'),
      13: s('levels public today', 'constructed around storeys', 'จึงคำตอบคือ "underwater" (paraphrase จากข้อความใน passage)'),
    },
    2: {
      1: s('heading', 'passenger transport determining factor', 'จึงคำตอบคือ "viii" (paraphrase จากข้อความใน passage)'),
      2: s('heading', 'transport concerned growth extent', 'จึงคำตอบคือ "iii" (paraphrase จากข้อความใน passage)'),
      3: s('heading', 'ambitious objective achieved proposed', 'จึงคำตอบคือ "i" (paraphrase จากข้อความใน passage)'),
      4: s('heading', 'energy consumption transport sector', 'จึงคำตอบคือ "v" (paraphrase จากข้อความใน passage)'),
      5: s('heading', 'approach consist focusing transport', 'จึงคำตอบคือ "x" (paraphrase จากข้อความใน passage)'),
      6: s('heading', 'second approach concentrates transport', 'จึงคำตอบคือ "ii" (paraphrase จากข้อความใน passage)'),
      7: s('heading', 'integrated approach market shares', 'จึงคำตอบคือ "iv" (paraphrase จากข้อความใน passage)'),
      8: s('heading', 'strong economic growth expected', 'จึงคำตอบคือ "xi" (paraphrase จากข้อความใน passage)'),
      9: s('transport growing despite', 'although modern technologies reduce', 'ข้อความในข้อว่า "The need for transport is growing, despite technological developments." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "Although modern information technologies can reduce the demand for physical transport by facili…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      10: s('reduce production costs', 'phenomenon emphasised relocation industries', 'ข้อความในข้อว่า "To reduce production costs, some industries have been moved closer to their relevant consumers." ไม่ตรงกับบทความ เพราะบทความระบุว่า "This phenomenon has been emphasised by the relocation of some industries, particularly those wh…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      11: s('prohibitively expensive candidate', 'strong economic growth expected', 'ข้อความในข้อว่า "Cars are prohibitively expensive in some EU candidate countries." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "The strong economic growth expected in countries which are candidates for entry to the EU will …") จึงตอบ NOT GIVEN'),
      12: s('council years', 'ambitious objective achieved proposed', 'ข้อความในข้อว่า "The Gothenburg European Council was set up 30 years ago." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "The ambitious objective can only be fully achieved by 2020, but proposed measures are nonethele…") จึงตอบ NOT GIVEN'),
      13: s('decade emissions transport', 'emissions transport expected increase', 'ข้อความในข้อว่า "By the end of this decade, CO2 emissions from transport are predicted to reach 739 billion tonnes." ไม่ตรงกับบทความ เพราะบทความระบุว่า "CO2 emissions from transport can be expected to increase by around 50% to 1,113 billion tonnes …" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
    },
  },
  2: {
    1: {
      1: s('heading', 'particular world-changing industry-happen britain', 'จึงคำตอบคือ "iv" (paraphrase จากข้อความใน passage)'),
      2: s('heading', 'different factors present revolution', 'จึงคำตอบคือ "viii" (paraphrase จากข้อความใน passage)'),
      3: s('heading', 'nation favourite drinks fuelled', 'จึงคำตอบคือ "vii" (paraphrase จากข้อความใน passage)'),
      4: s('heading', 'efforts explain sudden reduction', 'จึงคำตอบคือ "i" (paraphrase จากข้อความใน passage)'),
      5: s('heading', 'century introduced ingredient turned', 'จึงคำตอบคือ "vi" (paraphrase จากข้อความใน passage)'),
      6: s('heading', 'macfarlane looked developing cities', 'จึงคำตอบคือ "ix" (paraphrase จากข้อความใน passage)'),
      7: s('heading', 'turned essence work-based revolution', 'จึงคำตอบคือ "ii" (paraphrase จากข้อความใน passage)'),
      8: s('china\'s transport system', 'relatively expensive britain started', 'ข้อความในข้อว่า "China\'s transport system was not suitable for industry in the 18th century." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "Tea was relatively expensive until Britain started a direct clipper trade with China in the ear…") จึงตอบ NOT GIVEN'),
      9: s('beer helped prevent', 'antiseptic properties tannin active', 'ข้อความในข้อว่า "Tea and beer both helped to prevent dysentery in Britain." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "The antiseptic properties of tannin, the active ingredient in tea, and of hops in beer – plus t…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      10: s('porter disagrees professor', 'macfarlanes strengthened support notable', 'ข้อความในข้อว่า "Roy Porter disagrees with Professor Macfarlane\'s findings." ไม่ตรงกับบทความ เพราะบทความระบุว่า "Macfarlanes case has been strengthened by support from notable quarters – Roy Porter, the disti…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      11: s('After 1740，there was', 'Between about 1650 and 1740, the population in Britain was s…', 'ข้อความในข้อว่า "After 1740，there was" ไม่ตรงกับบทความ เพราะบทความระบุว่า "Between about 1650 and 1740, the population in Britain was static. But then there was a burst i…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      12: s('britain', 'english protected strong antibacterial', 'ข้อความในข้อว่า "People in Britain used to make beer at home." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "We drank beer. For a long time, the English were protected by the strong antibacterial agent in…") จึงตอบ NOT GIVEN'),
      13: s('indirectly caused', 'century introduced ingredient turned', 'ข้อความในข้อว่า "The tax on malt indirectly caused" ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "But in the late 17th century a tax was introduced on malt, the basic ingredient of beer. The po…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
    },
    2: {
      1: s('influence domestic background', 'higher children scores especially', 'คำถาม: "a reference to the influence of the domestic background on the gifted child. … … … … … …" หลักฐานในบทความคือ "The higher the children’s IQ scores, especially over IQ 130, the better the quality of their ed…" ซึ่งสนับสนุนตัวเลือก A มากที่สุด จึงตอบ A'),
      2: s('lost learners guidance', 'conversely teachers tendency overdirect', 'คำถาม: "reference to what can be lost if learners are given too much guidance. … … … … … …" หลักฐานในบทความคือ "Conversely, teachers who have a tendency to ‘overdirect’ can diminish their gifted pupils’ lear…" ซึ่งสนับสนุนตัวเลือก D มากที่สุด จึงตอบ D'),
      3: s('damaging effects anxiety', 'example development curiosity strong', 'คำถาม: "a reference to the damaging effects of anxiety. … … … … … …" หลักฐานในบทความคือ "Fear, for example, can limit the development of curiosity, which is a strong force in scientifi…" ซึ่งสนับสนุนตัวเลือก F มากที่สุด จึงตอบ F'),
      4: s('classroom techniques favour', 'number methods child- initiated', 'คำถาม: "examples of classroom techniques which favour socially-disadvantaged children." หลักฐานในบทความคือ "There are quite a number of new methods which can help, such as child- initiated learning, ability-peer tutoring, etc." ซึ่งสนับสนุนตัวเลือก D มากที่สุด จึงตอบ D'),
      5: s('spent exercises gifted', 'kanevsky instructor problem succinctly', 'คำถาม: "Less time can be spent on exercises with gifted pupils who produce accurate work. … … … … …" หลักฐานในบทความคือ "(Shore and Kanevsky, 1993) put the instructor’s problem succinctly: ‘If they [the gifted] merel…" ซึ่งสนับสนุนตัวเลือก B มากที่สุด จึงตอบ B'),
      6: s('self-reliance valuable quality', 'simonton independence contribute expertise', 'คำถาม: "Self-reliance is a valuable quality that gifted young people benefit from developing." หลักฐาน: "characteristics such as independence seemed to contribute more to reaching the highest levels of expertise" จึงตอบ D'),
      7: s('gifted children channel', 'boekaerts review emotion learning', 'คำถาม: "Gifted children know how to channel their feelings to assist their learning. … … … … …" หลักฐานในบทความคือ "In Boekaerts’ (1991) review of emotion the learning of very high IQ and highly achieving childr…" ซึ่งสนับสนุนตัวเลือก E มากที่สุด จึงตอบ E'),
      8: s('gifted child benefits', 'example positive relationship children', 'คำถาม: "The very gifted child benefits from appropriate support from close relatives. … … … … …" หลักฐานในบทความคือ "For example, a very close positive relationship was found when children’s IQ scores were compar…" ซึ่งสนับสนุนตัวเลือก A มากที่สุด จึงตอบ A'),
      9: s('really successful students', 'individuals specific domain achieve', 'คำถาม: "Really successful students have learnt a considerable amount about their subject." หลักฐาน: "individuals who know a great deal about a specific domain will achieve at a higher level than those who do not (Elshout, 1995)." จึงตอบ C'),
      10: s('study found', 'higher children scores especially', 'จึงคำตอบคือ "activities" (paraphrase จากข้อความใน passage)'),
      11: s('children average ability', 'appears qualitative difference intellectually', 'จึงคำตอบคือ "internal regulation" (paraphrase จากข้อความใน passage)'),
      12: s('meta-cognition involves children', 'emotional awareness metacognition children', 'จึงคำตอบคือ "emotional awareness" (paraphrase จากข้อความใน passage)'),
      13: s('teachers known often', 'although produce extremely examination', 'จึงคำตอบคือ "spoon-feeding" (paraphrase จากข้อความใน passage)'),
    },
  },
  3: {
    1: {
      1: s('heading', 'tourism distinctly twentieth-century phenomenon', 'จึงคำตอบคือ "ii" (paraphrase จากข้อความใน passage)'),
      2: s('heading', 'tourism significantly economic social', 'จึงคำตอบคือ "i" (paraphrase จากข้อความใน passage)'),
      3: s('heading', 'however problems travel tourism', 'จึงคำตอบคือ "v" (paraphrase จากข้อความใน passage)'),
      4: s('heading', 'mcintosh goeldner suggest tourism', 'จึงคำตอบคือ "vii" (paraphrase จากข้อความใน passage)'),
      5: s('largest employment figures', 'according travel tourism council', 'ข้อความในข้อว่า "The largest employment figures in the world are found in the travel and tourism industry." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "According to the World Travel and Tourism Council (1992), Travel and tourism is the largest ind…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      6: s('gross national product', 'industry leading industrial contributor', 'ข้อความในข้อว่า "Tourism contributes over six per cent of the Australian gross national product." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "This industry is the world’s leading industrial contributor, producing over 6 per cent of the w…") จึงตอบ NOT GIVEN'),
      7: s('tourism', 'tourism profound impact economy', 'ข้อความในข้อว่า "Tourism has" บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "Thus, tourism has a profound impact both on the world economy and, because of the educative eff…") จึงตอบ NOT GIVEN'),
      8: s('features travel tourism', 'however problems travel tourism', 'ข้อความในข้อว่า "Two main features of the travel and tourism industry make its economic significance difficult to ascertain." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "However, the major problems of the travel and tourism industry that have hidden, or obscured, i…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      9: s('spending residents tourist', 'businesses residents impact spending', 'ข้อความในข้อว่า "Visitor spending is always greater than the spending of residents in tourist areas." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "Since many of these businesses also serve local residents, the impact of spending by visitors c…") จึงตอบ NOT GIVEN'),
      10: s('statistically tourism affects', 'however because problems definition', 'ข้อความในข้อว่า "It is easy to show statistically how tourism affects individual economies." ไม่ตรงกับบทความ เพราะบทความระบุว่า "However, because of problems of definition, which directly affect statistical measurement, it i…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      11: s('greece tourism important', 'example tourism source income', 'จึงคำตอบคือ "source of income" (paraphrase จากข้อความใน passage)'),
      12: s('major', 'suggest travel tourism industry', 'จึงคำตอบคือ "employer" (paraphrase จากข้อความใน passage)'),
      13: s('problems associated measuring', 'similar difficulties attempts measure', 'จึงคำตอบคือ "domestic tourism" (paraphrase จากข้อความใน passage)'),
    },
    2: {
      1: s('description substance responsible', 'source widely created anthocyanins', 'คำถาม: "a description of the substance responsible for the red colouration of leaves … … … … … … … … …" หลักฐานในบทความคือ "The source of the red is widely known: it is created by anthocyanins, water-soluble plant pigme…" ซึ่งสนับสนุนตัวเลือก C มากที่สุด จึงตอบ C'),
      2: s('reason trees leaves', 'evergreen conifers exception strategy', 'คำถาม: "the reason why trees drop their leaves in autumn … … … … … … … … …" หลักฐานในบทความคือ "For many trees – evergreen conifers being an exception – the best strategy is to abandon photos…" ซึ่งสนับสนุนตัวเลือก B มากที่สุด จึงตอบ B'),
      3: s('evidence confirm theory', 'straightforward leaves reddest', 'คำถาม: "some evidence to confirm a theory about the purpose of the red leaves" หลักฐาน: "One is straightforward: on many trees, the leaves that are the reddest are those on the side of the tree which gets most sun." จึงตอบ H'),
      4: s('explanation function chlorophyll', 'summer leaves because chlorophyll', 'คำถาม: "an explanation of the function of chlorophyll … … … … … … … … …" หลักฐานในบทความคือ "Summer leaves are green because they are full of chlorophyll, the molecule that captures sunlig…" ซึ่งสนับสนุนตัวเลือก B มากที่สุด จึงตอบ B'),
      5: s('proposed vivid red colours convince insects', 'red colouration warning signal', 'ย่อหน้า E อ้างถึงแนวคิดที่ใบไม้สีแดงอาจเตือนหรือหลอกใจแมลง จึงตอบ E'),
      6: s('vividly coloured leaves', 'straightforward leaves reddest', 'จึงคำตอบคือ "sunlight" (paraphrase จากข้อความใน passage)'),
      7: s('surfaces leaves contain', 'brighter', 'จึงคำตอบคือ "upper" (paraphrase จากข้อความใน passage)'),
      8: s('leaves abundant daytime', 'recognised decades conditions intense', 'จึงคำตอบคือ "dry" (paraphrase จากข้อความใน passage)'),
      9: s('intensity colour leaves', 'finally maples usually redder', 'จึงคำตอบคือ "north" (paraphrase จากข้อความใน passage)'),
      10: s('likely pigments protect', 'because behind hypothesis pigment', 'ข้อความในข้อว่า "It is likely that the red pigments help to protect the leaf from freezing temperatures." ไม่ตรงกับบทความ เพราะบทความระบุว่า "because the idea behind this hypothesis is that the red pigment is made in autumn leaves to pro…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      11: s('\'light screen\' hypothesis', 'sounds paradoxical', 'ข้อความในข้อว่า "The \'light screen\' hypothesis would initially seem to contradict what is known about chlorophyll." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "It sounds paradoxical" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      12: s('likely damaged sunlight', 'understood however resort producing', 'ข้อความในข้อว่า "Leaves which turn colours other than red are more likely to be damaged by sunlight." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "What is still not fully understood, however, is why some trees resort to producing red pigments…") จึงตอบ NOT GIVEN'),
      13: s('explanation', 'chlorophyll depleted colours dominated', 'คำถาม: "For which of the following questions does the writer offer an explanation?" หลักฐานในบทความคือ "As chlorophyll is depleted, other colours that have been dominated by it throughout the summer …" ซึ่งสนับสนุนตัวเลือก B มากที่สุด จึงตอบ B'),
    },
  },
  4: {
    1: {
      1: s('movement unpredictably', 'wildfires themselves experts generally', 'จึงคำตอบคือ "spread" (paraphrase จากข้อความใน passage)'),
      2: s('decades', 'average forest', 'จึงคำตอบคือ "10 times" (paraphrase จากข้อความใน passage)'),
      3: s('rainfall average', 'significantly normal precipitation recent', 'จึงคำตอบคือ "below" (paraphrase จากข้อความใน passage)'),
      4: s('brush', 'natural eradication underbrush primary', 'จึงคำตอบคือ "fuel" (paraphrase จากข้อความใน passage)'),
      5: s('extended', 'second average longer', 'จึงคำตอบคือ "seasons" (paraphrase จากข้อความใน passage)'),
      6: s('building vulnerable places', 'increasingly building fire-prone ecosystems', 'จึงคำตอบคือ "housing" (paraphrase จากข้อความใน passage)'),
      7: s('diminished last years', 'residential providing greater intensity', 'ข้อความในข้อว่า "The amount of open space in California has diminished over the last ten years." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "What once was open space is now residential homes providing fuel to make fires burn with greate…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      8: s('little progress readying', 'experts california making progress', 'ข้อความในข้อว่า "Many experts believe California has made little progress in readying itself to fight fires." ไม่ตรงกับบทความ เพราะบทความระบุว่า "That said, many experts give California high marks for making progress on preparedness in recen…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      9: s('personnel criticised mishandling', 'criticism bungling allowed spread', 'ข้อความในข้อว่า "Personnel in the past have been criticised for mishandling fire containment." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "Stung in the past by criticism of bungling that allowed fires to spread when they might have be…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      10: s('promises up-to-date engines planes helicopters fulfilled', 'california replaced fire-fighting tools', 'บทความระบุว่าคำมั่นจัดหาเครื่องมือดับไฟที่ทันสมัยได้ดำเนินการแล้ว สอดคล้องกับข้อ จึงตอบ TRUE'),
      11: s('firefighters hired improve', 'besides providing upgrade engines', 'ข้อความในข้อว่า "More firefighters have been hired to improve fire-fighting capacity." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "Besides providing money to upgrade the fire engines that must traverse the mammoth state and wi…") จึงตอบ NOT GIVEN'),
      12: s('citizens government groups', 'government officials residents dedication', 'ข้อความในข้อว่า "Citizens and government groups disapprove of the efforts of different states and agencies working together." ไม่ตรงกับบทความ เพราะบทความระบุว่า "There is a sense among both government officials and residents that the speed, dedication, and …" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      13: s('randy jacobs believes', 'notwithstanding damage continue caused', 'ข้อความในข้อว่า "Randy Jacobs believes that loss of life from fires will continue at the same levels, despite changes made." ไม่ตรงกับบทความ เพราะบทความระบุว่า "Notwithstanding all the damage that will continue to be caused by wildfires, we will no longer …" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
    },
    2: {
      1: s('impossible', 'psychologists person character cannot', 'จึงคำตอบคือ "transformation" (paraphrase จากข้อความใน passage)'),
      2: s('person character tends', 'traits personality determined', 'จึงคำตอบคือ "young age" (paraphrase จากข้อความใน passage)'),
      3: s('however regardless quality', 'qualities challenging develop others', 'จึงคำตอบคือ "optimism" (paraphrase จากข้อความใน passage)'),
      4: s('order', 'however developing qualities requires', 'จึงคำตอบคือ "techniques" (paraphrase จากข้อความใน passage)'),
      5: s('order increase happiness', 'example passion experiencing negative', 'จึงคำตอบคือ "negative emotions" (paraphrase จากข้อความใน passage)'),
      6: s('accept trying something', 'psychologist kashdan advice taking', 'คำถาม: "People must accept that they do not know much when first trying something new. … … … … … … …" หลักฐานในบทความคือ "Psychologist Todd Kashdan has this advice for those people taking up a new passion: ‘As a newco…" ซึ่งสนับสนุนตัวเลือก E มากที่สุด จึงตอบ E'),
      7: s('important actively notice', 'recommends yourself attention fortune', 'คำถาม: "It is important for people to actively notice when good things happen. … … … … … … …" หลักฐานในบทความคือ "She recommends you train yourself to pay attention to good fortune by writing down three positi…" ซึ่งสนับสนุนตัวเลือก C มากที่สุด จึงตอบ C'),
      8: s('learned once origins', 'according cynthia psychologist clemson', 'คำถาม: "Courage can be learned once its origins in" หลักฐานในบทความคือ "According to Cynthia Pury, a psychologist at Clemson University, Pedeleose’s story proves the p…" ซึ่งสนับสนุนตัวเลือก G มากที่สุด จึงตอบ G'),
      9: s('possible overcome shyness', 'inherently introverted realised academic', 'ย่อหน้า A มีเนื้อหาที่ตรงกับหัวข้อในข้อมากที่สุด (It is possible to overcome shyness when faced with the need to speak in public.) โดยเฉพาะประโยค "Inherently introverted, he realised early on that as an academic, his reticence would prove disastrous in the lecture hall." จึงเลือก A'),
      10: s('rational thinking enabled', 'physical stamina required intense', 'คำถาม: "a mention of how rational thinking enabled someone to achieve physical goals … … … … … … … …" หลักฐานในบทความคือ "The physical stamina required for this sport is intense but the psychological demands are even …" ซึ่งสนับสนุนตัวเลือก E มากที่สุด จึงตอบ E'),
      11: s('account someone overcame', 'action despite typical response', 'คำถาม: "an account of how someone overcame" หลักฐานในบทความคือ "He took action despite his own pain – a typical response of an optimist." ซึ่งสนับสนุนตัวเลือก C มากที่สุด จึงตอบ C'),
      12: s('description someone decided', 'switched cerebrospinal nourishes developing', 'คำถาม: "a description of how someone decided to rethink their academic career path … … … … … … … …" หลักฐานในบทความคือ "When he got back, he switched labs to study how cerebrospinal fluid nourishes the developing ne…" ซึ่งสนับสนุนตัวเลือก G มากที่สุด จึงตอบ G'),
      13: s('example someone risked', 'pedeleose carefully recorded instance', 'คำถาม: "an example of how someone risked his career out of" หลักฐานในบทความคือ "Pedeleose carefully recorded each instance of bullying and eventually took the evidence to a se…" ซึ่งสนับสนุนตัวเลือก H มากที่สุด จึงตอบ H'),
    },
  },
  5: {
    1: {
      1: s('plants including already', 'concept indoor farming hothouse', 'จึงคำตอบคือ "tomatoes" (paraphrase จากข้อความใน passage)'),
      2: s('vertical farms located', 'situated centres drastically reduce', 'จึงคำตอบคือ "centers" (paraphrase จากข้อความใน passage)'),
      3: s('vertical farms methane', 'although system consume return', 'จึงคำตอบคือ "energy" (paraphrase จากข้อความใน passage)'),
      4: s('consumption because agricultural', 'dramatically reduce fossil cutting', 'จึงคำตอบคือ "fossil fuel" (paraphrase จากข้อความใน passage)'),
      5: s('vertical farms light', 'drawback vertical farming however', 'จึงคำตอบคือ "artificial" (paraphrase จากข้อความใน passage)'),
      6: s('vertical farming involves', 'variation vertical farming developed', 'จึงคำตอบคือ "trays" (paraphrase จากข้อความใน passage)'),
      7: s('probable development grown', 'possible skyscrapers future experts', 'จึงคำตอบคือ "rooftops" (paraphrase จากข้อความใน passage)'),
      8: s('methods predicting earth\'s', 'applying conservative estimates current', 'ข้อความในข้อว่า "Methods for predicting the Earth\'s population have recently changed." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "Applying the most conservative estimates to current demographic trends, the human population wi…") จึงตอบ NOT GIVEN'),
      9: s('beings responsible destruction', 'historically management practices', 'ข้อความในข้อว่า "Human beings are responsible for some of the destruction to food-producing land." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "Historically, some 15% of that has been laid waste by poor management practices." ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      10: s('crops produced vertical', 'instance produced artificially controlled', 'ข้อความในข้อว่า "The crops produced in vertical farms will depend on the season." ไม่ตรงกับบทความ เพราะบทความระบุว่า "For instance, crops would be produced all year round, as they would be kept in artificially con…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      11: s('damage crops caused', 'however rapidly changing climate', 'ข้อความในข้อว่า "Some damage to food crops is caused by climate change." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "However, more often than not now, due to a rapidly changing climate, that is not what happens." ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      12: s('fertilisers needed certain', 'organically eliminating herbicides pesticides', 'ข้อความในข้อว่า "Fertilisers will be needed for certain crops in vertical farms." ไม่ตรงกับบทความ เพราะบทความระบุว่า "All the food could be grown organically, eliminating the need for herbicides, pesticides and fe…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      13: s('vertical farming plants', 'system greatly reduce incidence', 'ข้อความในข้อว่า "Vertical farming will make plants less likely to be affected by infectious diseases." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "The system would greatly reduce the incidence of many infectious diseases that are acquired at …" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
    },
    2: {
      1: s('falkirk wheel linked', 'historically canals joined falkirk', 'ข้อความในข้อว่า "The Falkirk Wheel has linked the Forth & Clyde Canal with the Union Canal for the first time in their history." ไม่ตรงกับบทความ เพราะบทความระบุว่า "Historically, the two canals had been joined near the town of Falkirk by a sequence of 11 locks…" ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      2: s('opposition design falkirk', 'numerous submitted project including', 'ข้อความในข้อว่า "There was some opposition to the design of the Falkirk Wheel at first." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "Numerous ideas were submitted for the project, including concepts ranging from rolling eggs to …") จึงตอบ NOT GIVEN'),
      3: s('falkirk wheel initially', 'various falkirk constructed assembled', 'ข้อความในข้อว่า "The Falkirk Wheel was initially put together at the location where its components were manufactured." ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "The various parts of The Falkirk Wheel were all constructed and assembled, like one giant toy b…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      4: s('falkirk wheel steel', 'withstand immense constantly changing', 'ข้อความในข้อว่า "The Falkirk Wheel is the only boat lift in the world which has steel sections bolted together by hand." บทความไม่ได้ให้รายละเอียดเพียงพอที่จะยืนยันหรือปฏิเสธข้อนี้โดยตรง (อ้างอิงใกล้เคียง: "The Wheel would need to withstand immense and constantly changing stresses as it rotated, so to…") จึงตอบ NOT GIVEN'),
      5: s('weight gondolas varies', 'gondolas always whether carrying', 'ข้อความในข้อว่า "The weight of the gondolas varies according to the size of boat being carried." ไม่ตรงกับบทความ เพราะบทความระบุว่า "These gondolas always weigh the same, whether or not they are carrying boats." ซึ่งขัดกับสิ่งที่ข้ออ้าง (หรือให้ข้อมูลตรงข้าม) จึงตอบ FALSE'),
      6: s('construction falkirk wheel', 'constructed elevate 35-metre difference', 'ข้อความในข้อว่า "The construction of the Falkirk Wheel site took into account the presence of" ตรงกับข้อมูลในบทความ เพราะบทความระบุว่า "The Wheel could not be constructed to elevate boats over the full 35-metre difference between t…" ซึ่งยืนยันสิ่งที่ข้อกล่าวถึงได้ชัดเจน จึงตอบ TRUE'),
      7: s('label diagram questions', 'hydraulic raised gondola', 'จึงคำตอบคือ "gates" (paraphrase จากข้อความใน passage)'),
      8: s('label diagram questions', 'hydraulic prevents moving gondola', 'จึงคำตอบคือ "clamp" (paraphrase จากข้อความใน passage)'),
      9: s('label diagram questions', 'central machine hydraulic motors', 'จึงคำตอบคือ "axle" (paraphrase จากข้อความใน passage)'),
      10: s('label diagram questions', 'eight-metre-wide connected smaller travelling', 'จึงคำตอบคือ "cogs" (paraphrase จากข้อความใน passage)'),
      11: s('label diagram questions', 'gondola reaches passes straight', 'จึงคำตอบคือ "aqueduct" (paraphrase จากข้อความใน passage)'),
      12: s('label diagram questions', 'travel tunnel finally', 'จึงคำตอบคือ "wall" (paraphrase จากข้อความใน passage)'),
      13: s('questions 27-29 eight', 'remaining metres needed achieved', 'จึงคำตอบคือ "locks" (paraphrase จากข้อความใน passage)'),
    },
  },
}
