import type { ListeningBuilderExamSet } from './listeningBuilderCambridge18Section2'

export const CAMBRIDGE_11_SECTION_4_EXAM_SET: ListeningBuilderExamSet = {
  id: 'cambridge-11-section-4',
  bookNumber: 11,
  sectionNumber: 4,
  title: 'Cambridge 11 · Section 4',
  tests: [
    {
      id: 'cam11-sec4-test1',
      testNumber: 1,
      title: '',
      scriptParagraphs: [
        'I’ve been looking at ocean biodiversity, that’s the diversity of species that live in the world’s oceans.',
        'About 20 years ago biologists developed the idea of what they called ‘biodiversity hotspots’.',
        'These are the areas which have the greatest mixture of species, so one example is Madagascar.',
        'These hotspots are significant because they allow us to locate key areas for focusing efforts at conservation.',
        '31 Biologists can identify hotspots on land, fairly easily, but until recently, very little was known about species distribution and diversity in the oceans, and no one even knew if hotspots existed there.',
        'Then a Canadian biologist called Boris Worm did some research in 2005 on data on ocean species that he got from the fishing industry.',
        'Worm located five hotspots for large ocean predators like sharks, and looked at what they had in common.',
        'The main thing he’d expected to find was that they had very high concentrations of food, but to his surprise that was only true for four of the hotspots – the remaining hotspots was quite badly off in that regard 32.',
        'But what he did find was that in all cases, the water at the surface of the ocean had relatively high temperatures, even when it was cool at greater depths 33, so this seemed to be a factor in supporting a diverse range of these large predators.',
        'However, this wasn’t enough on its own, because he also found that the water needed to have enough oxygen in it 34 – so these two factors seemed necessary to support the high metabolic rate of these large fish.',
        'A couple of years later, in 2007, a researcher called Lisa Balance, who was working in California, also started looking for ocean hotspots, but not for fish – what she was interested in was marine mammals, things like seals 35.',
        'And she found three places in the oceans which were hotspots, and what these had in common was that these hotspots were all located at boundaries between ocean currents, and this seems to be the sort of place that has lots of the plankton that some of these species feed on.',
        'So now people who want to protect the species that are endangered need to get as much information as possible.',
        'For example, there’s an international project called the Census of Marine Life.',
        'They’ve been surveying oceans all over the world, including the Arctic.',
        'One thing they found there which stunned other researchers was that there were large numbers of species which live below the ice 36 – sometimes under a layer up to 20 metres thick.',
        'Some of these species had never been seen before.',
        'They’ve even found species of octopus living in these conditions.',
        'And other scientists working on the same project, but researching very different habitats on the ocean floor, have found large numbers of species congregating around volcanoes, attracted to them by the warmth and nutrients there.',
        'However, biologists still don’t know how serious the threat to their survival is for each individual species.',
        'So a body called the Global Marine Species Assessment is now creating a list of endangered species on land, so they consider things like the size of the population – how many members of one species there are in a particular place – and then they look at their distribution in geographical terms, although this is quite difficult when you’re looking at fish, because they’re so mobile, and then thirdly they calculate the rate at which the decline of the species is happening 37.',
        'So far only 1,500 species have been assessed, but they want to increase this figure to 20,000.',
        'For each one they assess, they use the data they collect on that species to produce a map showing its distribution 38.',
        'Ultimately they will be able to use these to figure out not only where most species are located but also where they are most threatened.',
        'So finally, what can be done to retain the diversity of species in the world’s oceans?',
        'Firstly, we need to set up more reserves in our oceans, places where marine species are protected.',
        'We have some, but not enough.',
        'In addition, to preserve species such as leatherback turtles, which live out in the high seas but have their nesting sites on the American coast, we need to create corridors for migration, so they can get from one area to another safely 39.',
        'As well as this, action needs to be taken to lower the levels of fishing quotas to prevent overfishing of endangered species.',
        'And finally, there’s the problem of ‘by-catch’.',
        'This prefers to the catching of unwanted fish by fishing boats – they’re returned to the sea, but they’re often dead or dying.',
        'If these commercial fishing boats used equipment which was more selective, so that only the fish wanted for consumption were caught, this problem could be overcome.',
        '40 OK.',
        'So does anyone have any …',
      ],
      tasks: [
        {
          id: 'cam11-s4-t1-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nOcean Biodiversity\\n31 important for locating targets for ____',
          questionWordPhrase: 'important for locating targets for',
          targetText: 'conservation',
          thaiMeaning: 'การอนุรักษ์',
          explanationThai: '\'important for locating targets for\' ในโจทย์เติมด้วย \'conservation\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nOcean Biodiversity\\n32 – were not always rich in ____ – had higher temperatures at the',
          questionWordPhrase: '– were not always rich in',
          targetText: 'food',
          thaiMeaning: 'อาหาร',
          explanationThai: '\'– were not always rich in\' ในโจทย์เติมด้วย \'food\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nOcean Biodiversity\\n33 – were not always rich in ____ – had sufficient',
          questionWordPhrase: '– were not always rich in',
          targetText: 'surface',
          thaiMeaning: 'พื้นผิว',
          explanationThai: '\'– were not always rich in\' ในโจทย์เติมด้วย \'surface\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nOcean Biodiversity\\n34 – were not always rich in ____ in the water',
          questionWordPhrase: '– were not always rich in',
          targetText: 'oxygen',
          thaiMeaning: 'ออกซิเจน',
          explanationThai: '\'– were not always rich in\' ในโจทย์เติมด้วย \'oxygen\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nOcean Biodiversity\\n35 looked for hotspots for marine ____',
          questionWordPhrase: 'looked for hotspots for marine',
          targetText: 'mammals',
          thaiMeaning: 'สัตว์เลี้ยงลูกด้วยนม',
          explanationThai: '\'looked for hotspots for marine\' ในโจทย์เติมด้วย \'mammals\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nOcean Biodiversity\\n36 – under the ____ – near volcanoes on the ocean floor',
          questionWordPhrase: '– under the',
          targetText: 'ice',
          thaiMeaning: 'น้ำแข็ง',
          explanationThai: '\'– under the\' ในโจทย์เติมด้วย \'ice\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\n–   geographical distribution\\n37 – rate of ____',
          questionWordPhrase: '– rate of',
          targetText: 'decline',
          thaiMeaning: 'ปฏิเสธ',
          explanationThai: '\'– rate of\' ในโจทย์เติมด้วย \'decline\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\n–   geographical distribution\\n38 Aim: to assess 20,000 species and make a distribution ____ for each one',
          questionWordPhrase: 'Aim: to assess 20,000 species and make a distribution',
          targetText: 'map',
          thaiMeaning: 'แผนที่',
          explanationThai: '\'Aim: to assess 20,000 species and make a distribution\' ในโจทย์เติมด้วย \'map\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\n–   geographical distribution\\n39 establish ____ corridors (e.g. for turtles)',
          questionWordPhrase: 'establish',
          targetText: 'migration',
          thaiMeaning: 'การโยกย้าย',
          explanationThai: '\'establish\' ในโจทย์เติมด้วย \'migration\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t1-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\n–   geographical distribution\\n40 catch fish only for the purpose of ____',
          questionWordPhrase: 'catch fish only for the purpose of',
          targetText: 'consumption',
          thaiMeaning: 'การบริโภค',
          explanationThai: '\'catch fish only for the purpose of\' ในโจทย์เติมด้วย \'consumption\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam11-sec4-test2',
      testNumber: 2,
      title: '',
      scriptParagraphs: [
        'We’ve been discussing the factors the architect has to consider when designing domestic buildings.',
        'I’m going to move on now to consider the design of public buildings, and I’ll illustrate this by referring to the new Taylor Concert Hall that’s recently been completed here in the city.',
        'So, as with a domestic building, when designing a public building, an architect needs to consider the function of the building – for example, is it to be used primarily for entertainment, or for education, or for administration?',
        'The second thing the architect needs to think about is the context of the building, this includes its physical location obviously, but it also includes the social meaning of the building how it relates to the people it’s built for 31.',
        'And finally, for important public buildings, the architect may also be looking for a central symbolic idea on which to base the design, a sort of metaphor for the building and the way in which it is used.',
        'Let’s look at the new Taylor Concert Hall in relation to these ideas.',
        'The location chosen was a site in a run-down district that has been ignored in previous redevelopment plans.',
        'It was occupied by a factory that had been empty for some years.',
        '32 The whole area was some distance from the high-rise office blocks of the central business district and shopping centre, but it was only one kilometre from the ring road.',
        'The side itself was bordered to the north by a canal 33 which had once been used by boats bringing in raw materials when the area was used for manufacturing.',
        'The architect chosen for the project was Tom Harrison.',
        'He found the main design challenge was the location of the site in an area that had no neighbouring buildings of any importance.',
        'To reflect the fact that the significance of the building in this quite run-down location was as yet unknown, he decided to create a building centred around the idea of a mystery – something whose meaning still has to be discovered.',
        'So how was this reflected in the design of the building?',
        'Well, Harrison decided to create pedestrian access to the building and to make use of the presence of water on the site.',
        'As people approach the entrance, they therefore have to cross over a bridge.',
        '34 He wanted to give people a feeling of suspense as they see the building first from a distance, and then close-up, and the initial impression he wanted to create from the shape of the building as a whole was that of a box.',
        '35 The first side that people see, the southern wall, is just a high, flat wall uninterrupted by any windows.',
        'This might sound off-putting, but it supports Harrison’s concept of the building – that the person approaching is intrigued and wonders what will be inside.',
        'And this flat wall also has another purpose.',
        'At night-time, projectors are switched on and it functions as a huge screen, onto which images are projected.',
        '36 The auditorium itself seats 1500 people.',
        'The floor’s supported by ten massive pads.',
        'These are constructed from rubber 37, and so are able to absorb any vibrations from outside and prevent them from affecting the auditorium.',
        'The walls are made of several layers of hony-coloured wood, all sourced from local beech trees.',
        'In order to improve the acoustic properties of the auditorium and to amplify the sound, they are not straight, they are curved.',
        '38 The acoustics are also adjustable according to the size of orchestra and the type of music being played.',
        'In order to achieve this, there are nine movable panels in the ceiling above the orchestra which are all individually motorized, and the walls also have curtains which can be opened or closed to change the acoustics.',
        '39 The reaction of the public to the new building has generally been positive.',
        'However, the evaluation of some critics has been less enthusiastic.',
        'In spite of Harrison’s efforts to use local materials, they criticise the style of the design as being international rather than local 40, and say it doesn’t reflect features of the landscape or society for which it is built.',
      ],
      tasks: [
        {
          id: 'cam11-s4-t2-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nSection 4\\n31 Question 31 ____',
          questionWordPhrase: 'Question 31',
          targetText: 'social',
          thaiMeaning: 'ทางสังคม',
          explanationThai: '\'Question 31\' ในโจทย์เติมด้วย \'social\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nIntroduction\\n32 On the site of a disused ____ Beside a',
          questionWordPhrase: 'On the site of a disused',
          targetText: 'factory',
          thaiMeaning: 'โรงงาน',
          explanationThai: '\'On the site of a disused\' ในโจทย์เติมด้วย \'factory\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nIntroduction\\n33 On the site of a disused ____ The design is based on the concept of a mystery',
          questionWordPhrase: 'On the site of a disused',
          targetText: 'canal',
          thaiMeaning: 'คลอง',
          explanationThai: '\'On the site of a disused\' ในโจทย์เติมด้วย \'canal\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nBuilding design\\n34 It’s approached by a ____ for pedestrians',
          questionWordPhrase: 'It’s approached by a',
          targetText: 'bridge',
          thaiMeaning: 'สะพาน',
          explanationThai: '\'It’s approached by a\' ในโจทย์เติมด้วย \'bridge\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nBuilding design\\n35 The building is the shape of a ____ One exterior wall acts as a large',
          questionWordPhrase: 'The building is the shape of a',
          targetText: 'box',
          thaiMeaning: 'กล่อง',
          explanationThai: '\'The building is the shape of a\' ในโจทย์เติมด้วย \'box\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nBuilding design\\n36 The building is the shape of a ____',
          questionWordPhrase: 'The building is the shape of a',
          targetText: 'screen',
          thaiMeaning: 'หน้าจอ',
          explanationThai: '\'The building is the shape of a\' ในโจทย์เติมด้วย \'screen\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nIn the auditorium\\n37 the floor is built on huge pads made of ____',
          questionWordPhrase: 'the floor is built on huge pads made of',
          targetText: 'rubber',
          thaiMeaning: 'ยาง',
          explanationThai: '\'the floor is built on huge pads made of\' ในโจทย์เติมด้วย \'rubber\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nIn the auditorium\\n38 the walls are made of local wood and are ____ in shape',
          questionWordPhrase: 'the walls are made of local wood and are',
          targetText: 'curved',
          thaiMeaning: 'โค้ง',
          explanationThai: '\'the walls are made of local wood and are\' ในโจทย์เติมด้วย \'curved\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nIn the auditorium\\n39 ceiling panels and ____ on walls allow adjustment of acoustics',
          questionWordPhrase: 'ceiling panels and',
          targetText: 'curtains',
          thaiMeaning: 'ผ้าม่าน',
          explanationThai: '\'ceiling panels and\' ในโจทย์เติมด้วย \'curtains\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t2-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nEvaluation\\n40 Some critics say the ____ style of the building is inappropriate',
          questionWordPhrase: 'Some critics say the',
          targetText: 'international',
          thaiMeaning: 'ระหว่างประเทศ',
          explanationThai: '\'Some critics say the\' ในโจทย์เติมด้วย \'international\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam11-sec4-test3',
      testNumber: 3,
      title: '',
      scriptParagraphs: [
        'So what I’m going to talk about to you today is something called Ethnography.',
        'This is a type of research aimed at exploring the way human cultures work.',
        'It was first developed for use in anthropology, and it’s also been used in sociology and communication studies.',
        'So what’s it got to do with business, you may ask.',
        'Well, businesses are finding that ethnography can offer them deeper insight into the possible needs of customers, either present or future, as well as providing valuable information about their attitudes towards existing products.',
        '31 And ethnography can also help companies to design new products or services that customers really want.',
        'Let’s look at some examples of how ethnographic research works in business.',
        'One team of researchers did a project for a company manufacturing kitchen equipment.',
        'They watched how cooks used measuring cups to measure out things like sugar and flour.',
        'They saw that the cooks had to check and recheck the contents, because although the measuring cups had numbers inside them, the cooks couldn’t see these easily.',
        '32 So a new design of cup was developed to overcome this problem, and it was a top seller.',
        'Another team of ethnographic researchers looked at how cell phones were used in Uganda, in Africa.',
        'They found that people who didn’t have their own phones could pay to use the phones of local entrepreneurs.',
        'Because these customers paid in advance for their calls, they were eager to know how much time they’d spent on the call so far.',
        '33 So the phone company designed phones for use globally with this added feature.',
        'Ethnographic research has also been carried out in computer companies.',
        'In one company, IT systems administrators were observed for several weeks.',
        'It was found that a large amount of their work involved communicating with colleagues in order to solve problems, but that they didn’t have a standard way of exchanging information from spreadsheets and so on.',
        'So the team came up with an idea for software that would help them to do this.',
        '34 In another piece of research, a team observed and talked to nurses working in hospitals.',
        'This led to the recognition that the nurses needed to access the computer records of their patients, no matter where they were 35.',
        'This led to the development of a portable computer tablet that allowed the nurses to check records in locations throughout the hospital.',
        'Occasionally, research can be done even in environments where the researchers can’t be present.',
        'For example, in one project done for an airline, respondents used their smartphones to record information during airline trips, in a study aiming at tracking the emotions of passengers during a flight.',
        '36',
        'So what makes studies like these different from ordinary research?',
        'Let’s look at some of the general principles behind ethnographic research in business.',
        'First of all, the researcher has to be completely open-minded – he or she hasn’t thought up a hypothesis to be tested, as is the case in other types of research.',
        'Instead they wait for the participants in the research to inform them.',
        'As far as choosing the participants themselves is concerned, that’s not really all that different from ordinary research – the criteria according to which the participants are chosen may be something as simple as the age bracket they fall into, or the researchers may select them according to their income 37, or they might try to find a set of people who all use a particular product, for example.',
        'But it’s absolutely crucial to recruit the right people as participants.',
        'As well as the criteria I’ve mentioned, they have to be comfortable talking about themselves and being watched as they go about their activities.',
        '38 Actually, most researchers say that people open up pretty easily, maybe because they’re often in their own home of workplace.',
        'So what makes this type of research special is that it’s not just a matter of sending a questionnaire to the participants, instead the research is usually based on first-hand observation of what they are doing at the time.',
        '39 But that doesn’t mean that the researcher never talks to the participants.',
        'However, unlike in traditional research, in this case it’s the participant rather than the researchers who decides what direction the interview will follow.',
        'This means that there’s less likelihood of the researcher imposing his or her own ideas on the participant.',
        'But after they’ve said goodbye to their participants and got back to their office, the researchers’ work isn’t finished.',
        'Most researchers estimate that 70 to 80 per cent of their time is spent not on the collecting of data but on its analysis – looking at photos listening to recording and transcribing them and so on.',
        '40 The researchers may end up with hundreds of pages of notes.',
        'And to determine what’s significant, they don’t focus on the sensational things or the unusual things, instead they try to identify a pattern of some sort in all this data, and to discern the meaning behind it.',
        'This can result in some compelling insights that can in turn feed back to the whole design process.',
      ],
      tasks: [
        {
          id: 'cam11-s4-t3-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nIt can be used in business\\n31 to investigate customer needs and ____',
          questionWordPhrase: 'to investigate customer needs and',
          targetText: 'attitudes',
          thaiMeaning: 'ทัศนคติ',
          explanationThai: '\'to investigate customer needs and\' ในโจทย์เติมด้วย \'attitudes\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nIt can be used in business\\n32 Researchers found that cooks could not easily see the ____ in measuring cups',
          questionWordPhrase: 'Researchers found that cooks could not easily see the',
          targetText: 'numbers',
          thaiMeaning: 'ตัวเลข',
          explanationThai: '\'Researchers found that cooks could not easily see the\' ในโจทย์เติมด้วย \'numbers\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nIt can be used in business\\n33 These customers wanted to check the ____ used',
          questionWordPhrase: 'These customers wanted to check the',
          targetText: 'time',
          thaiMeaning: 'เวลา',
          explanationThai: '\'These customers wanted to check the\' ในโจทย์เติมด้วย \'time\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nIt can be used in business\\n34 There was a need to develop ____ to improve communication between system administrators and colleagues',
          questionWordPhrase: 'There was a need to develop',
          targetText: 'software',
          thaiMeaning: 'ซอฟต์แวร์',
          explanationThai: '\'There was a need to develop\' ในโจทย์เติมด้วย \'software\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nHospitals\\n35 Nurses needed to access information about ____ in different parts of the hospital',
          questionWordPhrase: 'Nurses needed to access information about',
          targetText: 'patients',
          thaiMeaning: 'ผู้ป่วย',
          explanationThai: '\'Nurses needed to access information about\' ในโจทย์เติมด้วย \'patients\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nAirlines\\n36 Respondents recorded information about their ____ while travelling',
          questionWordPhrase: 'Respondents recorded information about their',
          targetText: 'emotions',
          thaiMeaning: 'อารมณ์',
          explanationThai: '\'Respondents recorded information about their\' ในโจทย์เติมด้วย \'emotions\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nAirlines\\n37 Participants may be selected by criteria such as age, ____ or product used',
          questionWordPhrase: 'Participants may be selected by criteria such as age,',
          targetText: 'income',
          thaiMeaning: 'รายได้',
          explanationThai: '\'Participants may be selected by criteria such as age,\' ในโจทย์เติมด้วย \'income\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nAirlines\\n38 The participants must feel ____ about taking part in the research',
          questionWordPhrase: 'The participants must feel',
          targetText: 'comfortable',
          thaiMeaning: 'สะดวกสบาย',
          explanationThai: '\'The participants must feel\' ในโจทย์เติมด้วย \'comfortable\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nAirlines\\n39 There is usually direct ____ of the participants',
          questionWordPhrase: 'There is usually direct',
          targetText: 'observation',
          thaiMeaning: 'การสังเกต',
          explanationThai: '\'There is usually direct\' ในโจทย์เติมด้วย \'observation\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t3-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nAirlines\\n40 A lot of time is needed for the ____ of the data',
          questionWordPhrase: 'A lot of time is needed for the',
          targetText: 'analysis',
          thaiMeaning: 'การวิเคราะห์',
          explanationThai: '\'A lot of time is needed for the\' ในโจทย์เติมด้วย \'analysis\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam11-sec4-test4',
      testNumber: 4,
      title: 'The use of soil to reduce carbon dioxide (CO2) in the atmosphere',
      scriptParagraphs: [
        'As we saw in the last lecture, a major cause of climate change is the rapid rise in the level of carbon dioxide in the atmosphere over the last century.',
        'If we could reduce the amount of CO2, perhaps the rate of climate change could also be slowed down.',
        'One potential method involves enhancing the role of the soil that plants grow in, with regard to absorbing CO2.',
        'Rattan Lal, a soil scientist from Ohio Stage University, in the USA, claims that the world’s agricultural soils could potentially absorb 13 per cent of the carbon dioxide in the atmosphere – the equivalent of the amount released in the last 3o years.',
        'And research is going on into how this might be achieved.',
        'Lal first came to the idea that soil might be valuable in this way not through an interest in climate change, but rather out of concern for the land itself and the people dependent on it.',
        'Carbon-rich soil is dark, crumbly and fertile, and retains some water.',
        'But erosion can occur if soil is dry 31, which is a likely effect if it contains inadequate amounts of carbon.',
        'Erosion is of course bad for people trying to grow crops or breed animals on that terrain.',
        'In the 1970s and ‘80s, Lal was studying soils in Africa so devoid of organic matter that the ground had become extremely hard 32, like cement.',
        'There he met a pioneer in the study of global warming, who suggested that carbon from the soil had moved into the atmosphere.',
        'This is now looking increasingly likely.',
        'Let me explain.',
        'For millions of years, carbon dioxide levels in the atmosphere have been regulated, in part, by a natural partnership between plants and microbes – tiny organisms in the soil.',
        'Plants absorb CO2 from the air and transform it into sugars and other carbon-based substance.',
        '33 While a proportion of these carbon products remain in the plant, some transfer from the roots to fungi and soil microbes 34, which store the carbon in the soil.',
        'The invention of agriculture some 10,000 years ago disrupted these ancient soil-building processes and led to the loss of carbon from the soil.',
        'When humans started draining the natural topsoil, and ploughing it up for planting, they exposed the buried carbon to oxygen.',
        'This created carbon dioxide and released it into the air.',
        'And in some places, grazing by domesticated animals has removed all vegetation, releasing carbon into the air.',
        'Tons of carbon have been stripped from the world’s soils – where it’s needed – and pumped into the atmosphere.',
        'So what can be done?',
        'Researchers are now coming up with evidence that even modest changes to farming can significantly help to reduce the amount of carbon in the atmosphere.',
        'Some growers have already started using an approach known as regenerative agriculture.',
        'This aims to boost the fertility of soil and keep it moist through established practices.',
        '35 These include keeping fields planted all year round, and increasing the variety of plants being grown 36.',
        'Strategies like these can significantly increase the amount of carbon stored in the soil, so agricultural researchers are now building a case for their use in combating climate change.',
        'One American investigation into the potential for storing CO2 on agricultural lands is taking place in California.',
        'Soil scientist Whendee Silver of the University of California, Berkeley, is conducting a first-of-its-kind study on a large cattle farm in the state 37.',
        'She and her students are testing the effects on carbon storage of the compost that is created from waste – both agricultural, including manure and cornstalks, and waste produced in gardens 38, such as leaves, branches, and lawn trimmings.',
        'In Australia, soil ecologist Christine Jones is testing another promising soil-enrichment strategy.',
        'Jones and 12 farmers are working to build up soil carbon by cultivating grasses that stay green all year round.',
        '39 Like composting, the approach has already been proved experimentally; Jones now hopes to show that it can be applied on working farms and that the resulting carbon capture can be accurately measured.',
        'It’s hoped in the future that projects such as these will demonstrate the role that farmers and other land managers can play in reducing the harmful effects of greenhouse gases.',
        'For example, in countries like the United States, where most farming operations use large applications of fertiliser, changing such long-standing habits will require a change of system.',
        'Rattan Lal argues that farmers should receive payment not just for the corn or beef they produce but also for the carbon they can store in their soil.',
        '40 Another study being carried out …',
      ],
      tasks: [
        {
          id: 'cam11-s4-t4-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nRattan Lal\\n31 Erosion is more likely in soil that is ____',
          questionWordPhrase: 'Erosion is more likely in soil that is',
          targetText: 'dry',
          thaiMeaning: 'แห้ง',
          explanationThai: '\'Erosion is more likely in soil that is\' ในโจทย์เติมด้วย \'dry\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nRattan Lal\\n32 Lai found soil in Africa that was very ____',
          questionWordPhrase: 'Lai found soil in Africa that was very',
          targetText: 'hard',
          thaiMeaning: 'แข็ง',
          explanationThai: '\'Lai found soil in Africa that was very\' ในโจทย์เติมด้วย \'hard\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nSoil and carbon\\n33 plants turn CO2 from the air into carbon-based substances such as ____',
          questionWordPhrase: 'plants turn CO2 from the air into carbon-based substances such as',
          targetText: 'sugars',
          thaiMeaning: 'น้ำตาล',
          explanationThai: '\'plants turn CO2 from the air into carbon-based substances such as\' ในโจทย์เติมด้วย \'sugars\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nSoil and carbon\\n34 some CO2 moves from the ____ of plants to microbes in the soil',
          questionWordPhrase: 'some CO2 moves from the',
          targetText: 'roots',
          thaiMeaning: 'ราก',
          explanationThai: '\'some CO2 moves from the\' ในโจทย์เติมด้วย \'roots\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nRegenerative agriculture\\n35 uses established practices to make sure soil remains fertile and ____',
          questionWordPhrase: 'uses established practices to make sure soil remains fertile and',
          targetText: 'moist',
          thaiMeaning: 'ชื้น',
          explanationThai: '\'uses established practices to make sure soil remains fertile and\' ในโจทย์เติมด้วย \'moist\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nRegenerative agriculture\\n36 e.g. through year-round planting and increasing the ____ of plants that are grown',
          questionWordPhrase: 'e.g. through year-round planting and increasing the',
          targetText: 'variety',
          thaiMeaning: 'ความหลากหลาย',
          explanationThai: '\'e.g. through year-round planting and increasing the\' ในโจทย์เติมด้วย \'variety\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nCalifornia study\\n37 taking place on a big ____ farm',
          questionWordPhrase: 'taking place on a big',
          targetText: 'cattle',
          thaiMeaning: 'วัว',
          explanationThai: '\'taking place on a big\' ในโจทย์เติมด้วย \'cattle\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nCalifornia study\\n38 uses compost made from waste from agriculture and ____',
          questionWordPhrase: 'uses compost made from waste from agriculture and',
          targetText: 'gardens',
          thaiMeaning: 'สวน',
          explanationThai: '\'uses compost made from waste from agriculture and\' ในโจทย์เติมด้วย \'gardens\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nAustralia study\\n39 aims to increase soil carbon by using ____ that are always green',
          questionWordPhrase: 'aims to increase soil carbon by using',
          targetText: 'grasses',
          thaiMeaning: 'หญ้า',
          explanationThai: '\'aims to increase soil carbon by using\' ในโจทย์เติมด้วย \'grasses\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam11-s4-t4-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nFuture developments may include\\n40 giving farmers ____ for carbon storage, as well as their produce',
          questionWordPhrase: 'giving farmers',
          targetText: 'payment',
          thaiMeaning: 'การชำระเงิน',
          explanationThai: '\'giving farmers\' ในโจทย์เติมด้วย \'payment\' ตามที่พูดในสคริปต์'
        },
      ]
    }
  ]
}
