import type { ListeningBuilderExamSet } from './listeningBuilderCambridge18Section2'

export const CAMBRIDGE_10_SECTION_4_EXAM_SET: ListeningBuilderExamSet = {
  id: 'cambridge-10-section-4',
  bookNumber: 10,
  sectionNumber: 4,
  title: 'Cambridge 10 · Section 4',
  tests: [
    {
      id: 'cam10-sec4-test1',
      testNumber: 1,
      title: '',
      scriptParagraphs: [
        'Today we continue our series on ecology and conservation with a look at a particularly endangered member of the black bear family.',
        'One in ten black bears is actually born with a white coat, which is the result of a special gene that surfaces in a few.',
        'Local people have named it ‘the spirit bear’.',
        'And according to the legends of these communities, its snowy fur brings with it a special power.',
        'Because of this, it has always been highly regarded by them – so much that they do not speak of seeing it to anyone else.',
        'It is their way of protecting it when strangers visit the area.',
        'The white bear’s habitat is quite interesting.',
        'The bear’s strong relationship with the old-growth rainforest is a complex one.',
        'The white bear relies on the huge centuries-old trees in the forest in many ways.',
        'For example, the old-growth trees have extremely long roots that help prevent erosion of the soil along the banks of the many fish streams.',
        'Keeping these banks intact is important because these streams are home to salmon, which are the bear’s main food source.',
        'In return, the bear’s feeding habits nurture the forest.',
        'As the bears eat the salmon, they discard the skin and bones in great amounts on the forest floor, which provide vital nutrients.',
        'These produce lush vegetation that sustains thousands of other types of life forms, from birds to insects and more.',
        'Today, the spirit bear lives off the coast of the province of British Columbia on a few islands.',
        'There is great concern for their survival since it is estimated that less than two hundred of these white bears remain.',
        'The best way to protect them is to make every effort to preserve the delicate balance of their forest environment – in other words, their ecosystem.',
        '– The greatest threat to the bear’s existence is the loss of its habitat.',
        'Over many years, logging companies have stripped the land by cutting down a large number of trees.',
        'In addition, they have built roads which have fractured the areas where the bear usually feeds, and many hibernation sites have also been lost.',
        'The logging of the trees along the streams has damaged the places where the bears fish.',
        'To make matters worse, the number of salmon in those streams is declining because there is no legal limit on fishing at the moment.',
        'all these influences have a negative impact on the spirit bear’s very existence, which is made all the more fragile by the fact that reproduction among these bears has always been disappointingly low.',
        'And so, what’s the situation going forward?',
        'Community organizations, environmental groups and the British Columbia government are now working together on the problem.',
        'The government is now requiring logging companies to adopt a better logging method, which is a positive step.',
        'However, these measures alone may not be sufficient to ensure a healthy population of the spirit bear in the future.',
        'Other steps also need to be taken.',
        'While it is important to maintain the spirit bear’s habitat, there also needs to be more emphasis on its expansion.',
        'The move is justified as it will also create space for other bears that are losing their homes …',
      ],
      tasks: [
        {
          id: 'cam10-s4-t1-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nTHE SPIRIT BEAR\\n31 Its colour comes from an uncommon ____',
          questionWordPhrase: 'Its colour comes from an uncommon',
          targetText: 'gene',
          thaiMeaning: 'ยีน',
          explanationThai: '\'Its colour comes from an uncommon\' ในโจทย์เติมด้วย \'gene\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nTHE SPIRIT BEAR\\n32 Local people believe that it has unusual ____',
          questionWordPhrase: 'Local people believe that it has unusual',
          targetText: 'power',
          thaiMeaning: 'พลัง',
          explanationThai: '\'Local people believe that it has unusual\' ในโจทย์เติมด้วย \'power\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nTHE SPIRIT BEAR\\n33 They protect the bear from ____',
          questionWordPhrase: 'They protect the bear from',
          targetText: 'strangers',
          thaiMeaning: 'คนแปลกหน้า',
          explanationThai: '\'They protect the bear from\' ในโจทย์เติมด้วย \'strangers\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nHabitat\\n34 Tree roots stop ____ along salmon streams',
          questionWordPhrase: 'Tree roots stop',
          targetText: 'erosion',
          thaiMeaning: 'การกัดเซาะ',
          explanationThai: '\'Tree roots stop\' ในโจทย์เติมด้วย \'erosion\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nHabitat\\n35 It is currently found on a small number of ____',
          questionWordPhrase: 'It is currently found on a small number of',
          targetText: 'islands',
          thaiMeaning: 'หมู่เกาะ',
          explanationThai: '\'It is currently found on a small number of\' ในโจทย์เติมด้วย \'islands\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nThreats\\n36 Habitat is being lost due to deforestation and construction of ____ by logging companies',
          questionWordPhrase: 'Habitat is being lost due to deforestation and construction of',
          targetText: 'roads',
          thaiMeaning: 'ถนน',
          explanationThai: '\'Habitat is being lost due to deforestation and construction of\' ในโจทย์เติมด้วย \'roads\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nThreats\\n37 Unrestricted ____ is affecting the salmon supply',
          questionWordPhrase: 'Unrestricted',
          targetText: 'fishing',
          thaiMeaning: 'ตกปลา',
          explanationThai: '\'Unrestricted\' ในโจทย์เติมด้วย \'fishing\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nThreats\\n38 The bears’ existence is also threatened by their low rate of ____ Going forward',
          questionWordPhrase: 'The bears’ existence is also threatened by their low rate of',
          targetText: 'reproduction',
          thaiMeaning: 'การสืบพันธุ์',
          explanationThai: '\'The bears’ existence is also threatened by their low rate of\' ในโจทย์เติมด้วย \'reproduction\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nThreats\\n39 Logging companies must improve their ____ of logging',
          questionWordPhrase: 'Logging companies must improve their',
          targetText: 'method',
          thaiMeaning: 'วิธี',
          explanationThai: '\'Logging companies must improve their\' ในโจทย์เติมด้วย \'method\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t1-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nThreats\\n40 Maintenance and ____ of the spirit bears’ territory is needed',
          questionWordPhrase: 'Maintenance and',
          targetText: 'expansion',
          thaiMeaning: 'การขยายตัว',
          explanationThai: '\'Maintenance and\' ในโจทย์เติมด้วย \'expansion\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam10-sec4-test2',
      testNumber: 2,
      title: '',
      scriptParagraphs: [
        'Well, I’ve been talking to managers in a number of businesses, and reading surveys about the future of management.',
        'And what I’m going to present in this seminar is a few ideas about how the activity is likely to change in the next ten years.',
        'It isn’t a scientific, statistical analysis – just some ideas for us to discuss.',
        'One area I want to mention is business markets, and I’m sure a really significant development will be a major increase in competition, with companies from all round the world trying to sell similar products.',
        'Consumers will have much more choice – for instance, food products sold in Australia might be manufactured in the USA, China, Finland and dozens of other countries.',
        'At the same time, mergers and takeovers mean that governments are actually losing power to major global corporations.',
        'We can probably all think of companies that exert a great deal of influence, which may be good for consumers.',
        'A third point I want to make about markets is that in the rapidly expanding economies, such as India, China, Brazil and Russia, demand is growing very fast.',
        'This is putting pressure on resources all over the world.',
        'I think businesses are becoming more open to external influences.',
        'In particular, companies are consulting customers more and more before making their business decisions.',
        'Companies are finding out what they want and providing it, instead of making products and then trying to sell them, which is the model of years ago.',
        'Another influence is that concerns about the environment will force manufacturers to extend product lifecycles, to reduce the amount of pollution and waste.',
        'And in some cases, regulation will need to be strengthened.',
        'Many societies are much more fluid and democratic, and the structure of companies is changing to reflect that.',
        'I think we’re going to see a greater emphasis within companies on teams created with a specific project in mind.',
        'And when they’re completed, the teams will be disbanded and new ones formed.',
        'Typical examples that will attract and retain staff are traditional ones like flexible hours and – something that has been made possible by advances in technology – remote working, with people based at their home, abroad, or almost anywhere they choose.',
        '- Management styles will almost certainly continue to change.',
        'Senior managers will require a lot more than the efficiency that they’ve always needed.',
        'Above all they’ll need great skills in leadership, so that their organisation can initiate and respond to change in a fast-moving world, where they face lots of competing requirements and potential conflicts.',
        'In most of the world, the senior managers of large businesses are mainly men in their fifties and sixties.',
        'The predominant style of management will almost certainly become more consultative and collaborative, caused above all, by more women moving into senior management positions.',
        'Many of the changes are influenced by developments in the wider economy.',
        'The traditional emphasis of business was manufacturing, and of course the service sector is very important.',
        'But we shouldn’t overlook the growing financial contribution of IP, that is, intellectual property.',
        'Some books and films generate enormous sums from the sale of related DVDs, music, games, clothes, and so on.',
        'Another point I’d like to make is that although I’ve been talking about companies, one trend that they have to face is the move away from people working for the same employer for years.',
        'Instead, more and more people are becoming self-employed, to gain the freedom and control over their lives that they’re unlikely to get from being employed.',
        'OK, well that’s all I want to say, so let’s open it up for discussion.',
      ],
      tasks: [
        {
          id: 'cam10-s4-t2-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n31 greater ____ among companies',
          questionWordPhrase: 'greater',
          targetText: 'competition',
          thaiMeaning: 'การแข่งขัน',
          explanationThai: '\'greater\' ในโจทย์เติมด้วย \'competition\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n32 increase in power of large ____ Companies',
          questionWordPhrase: 'increase in power of large',
          targetText: 'global',
          thaiMeaning: 'ทั่วโลก',
          explanationThai: '\'increase in power of large\' ในโจทย์เติมด้วย \'global\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n33 rising ____ in certain countries',
          questionWordPhrase: 'rising',
          targetText: 'demand',
          thaiMeaning: 'ความต้องการ',
          explanationThai: '\'rising\' ในโจทย์เติมด้วย \'demand\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n34 more discussion with ____ before making business decisions',
          questionWordPhrase: 'more discussion with',
          targetText: 'customers',
          thaiMeaning: 'ลูกค้า',
          explanationThai: '\'more discussion with\' ในโจทย์เติมด้วย \'customers\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n35 environmental concerns which may lead to more ____ Business structures',
          questionWordPhrase: 'environmental concerns which may lead to more',
          targetText: 'regulation',
          thaiMeaning: 'ระเบียบข้อบังคับ',
          explanationThai: '\'environmental concerns which may lead to more\' ในโจทย์เติมด้วย \'regulation\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n36 more teams will be formed to work on a particular ____',
          questionWordPhrase: 'more teams will be formed to work on a particular',
          targetText: 'project',
          thaiMeaning: 'โครงการ',
          explanationThai: '\'more teams will be formed to work on a particular\' ในโจทย์เติมด้วย \'project\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n37 businesses may need to offer hours that are ____ , or the chance to work remotely',
          questionWordPhrase: 'businesses may need to offer hours that are',
          targetText: 'flexible',
          thaiMeaning: 'ยืดหยุ่นได้',
          explanationThai: '\'businesses may need to offer hours that are\' ในโจทย์เติมด้วย \'flexible\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n38 increasing need for managers to provide good ____',
          questionWordPhrase: 'increasing need for managers to provide good',
          targetText: 'leadership',
          thaiMeaning: 'ความเป็นผู้นำ',
          explanationThai: '\'increasing need for managers to provide good\' ในโจทย์เติมด้วย \'leadership\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n39 changes influenced by ____ taking senior roles',
          questionWordPhrase: 'changes influenced by',
          targetText: 'women',
          thaiMeaning: 'ผู้หญิง',
          explanationThai: '\'changes influenced by\' ในโจทย์เติมด้วย \'women\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t2-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nTHE FUTURE OF MANAGEMENT\\n40 more and more ____ workers',
          questionWordPhrase: 'more and more',
          targetText: 'self-employed',
          thaiMeaning: 'อาชีพอิสระ',
          explanationThai: '\'more and more\' ในโจทย์เติมด้วย \'self-employed\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam10-sec4-test3',
      testNumber: 3,
      title: '‘Self-regulatory focus theory’ and leadership',
      scriptParagraphs: [
        'Today, I want to talk about self-regulatory focus theory and how the actions of leaders can affect the way followers approach different situations.',
        'Self-regulatory focus theory is a theory developed by Tori Higgins.',
        'He says that a person’ focus at any given time is to either approach pleasure or avoid pain.',
        'These are two basic motivations that each and every one of us has, and they cause us to have different kinds of goals.',
        'Promotion goals in different life situations emphasise achievement.',
        'Prevention goals are oriented towards the avoidance of punishment.',
        'In a specific situation, our thoughts might focus more on promotion goals or more on prevention goals.',
        'The theory suggests that two factors affect which goals we are focusing on.',
        'First, there is a chronic factor.',
        'This factor is connected to a person’s personality and says that each person has a basic tendency to either focus more on promotion goals or focus more on prevention goals as part of his or her personality.',
        'Second, there is a situational factor which means that the context we are in can make us more likely to focus on one set of goals or the other.',
        'For example, we are more likely to be thinking about pleasure and to have promotion goals when we are spending time with a friend.',
        'In contrast, if we are working on an important project for our boss, we are more likely to try to avoid making mistakes and therefore have more prevention goals in our mind.',
        'Research has shown that the goals we are focusing on at a given time affect the way we think.',
        'For example, when focusing on promotion goals, people consider their ideal self, their aspirations and gains.',
        'They don’t think about what they can lose, so they think in a happier mode.',
        'They feel more inspired to change.',
        'When people are focusing on prevention goals, they think about their “ought” self.',
        'What are they supposed to be?',
        'What are people expecting from them?',
        'They consider their obligations to others.',
        'As a result, they experience more anxiety and try to avoid situations where they could lose.',
        '– Now that I have talked about the two focuses and how they affect people, I want to look at the idea that the way leaders behave, or their style of leading, can affect the focus that followers adopt in a specific situation.',
        'In talking about leadership, we often mention transformational leaders and transactional leaders.',
        'Transformational leaders, when interacting with their followers, focus on their development.',
        'In their words and actions transformational leaders highlight change.',
        'Their speech is passionate and conveys a definitive vision.',
        'All of these things can encourage followers to think about what could be.',
        'In other words, they inspire a promotion focus in their followers.',
        'In contrast, transactional leaders focus on developing clear structures that tell their followers exactly what is expected of them.',
        'While they do explain the rewards people will get for following orders, they emphasise more how a follower will be punished or that a follower won’t get rewarded if his or her behaviour doesn’t change.',
        'In short, they emphasise the consequences of making a mistake.',
        'This emphasis will clearly lead followers to focus on avoiding punishment and problems.',
        'This is clearly a prevention focus.',
        'In conclusion, it is important to understand that one focus is not necessarily better than the other one.',
        'For a designer who works in a field where a lot of innovation is needed, a promotion focus is probably better.',
        'In contrast, a prevention focus which causes people to work more cautiously and produce higher quality work might be very appropriate for a job like a surgeon, for example.',
        'The main point of the research, though, is that the actions of leaders can greatly influence whether people approach a situation with more of a promotion focus or more of a prevention focus.',
      ],
      tasks: [
        {
          id: 'cam10-s4-t3-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nSelf-regulatory focus theory\\n31 Promotion goals focus on ____ Prevention goals emphasise avoiding punishment',
          questionWordPhrase: 'Promotion goals focus on',
          targetText: 'achievement',
          thaiMeaning: 'ความสำเร็จ',
          explanationThai: '\'Promotion goals focus on\' ในโจทย์เติมด้วย \'achievement\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nSelf-regulatory focus theory\\n32 comes from one’s ____',
          questionWordPhrase: 'comes from one’s',
          targetText: 'personality',
          thaiMeaning: 'บุคลิกภาพ',
          explanationThai: '\'comes from one’s\' ในโจทย์เติมด้วย \'personality\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nFactors that affect people’s focus\\n33 The ____ Factor',
          questionWordPhrase: 'The',
          targetText: 'Situational',
          thaiMeaning: 'สถานการณ์',
          explanationThai: '\'The\' ในโจทย์รวมกับช่องว่างเป็น The Situational Factor ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nFactors that affect people’s focus\\n34 we are more likely to focus on promotion goals when with a ____',
          questionWordPhrase: 'we are more likely to focus on promotion goals when with a',
          targetText: 'friend',
          thaiMeaning: 'เพื่อน',
          explanationThai: '\'we are more likely to focus on promotion goals when with a\' ในโจทย์เติมด้วย \'friend\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nHow people’s focus affects them\\n35 Promotion Focus: People think about an ideal version of themselves, their ____ and their gains',
          questionWordPhrase: 'Promotion Focus: People think about an ideal version of themselves, their',
          targetText: 'aspirations',
          thaiMeaning: 'แรงบันดาลใจ',
          explanationThai: '\'Promotion Focus: People think about an ideal version of themselves, their\' ในโจทย์เติมด้วย \'aspirations\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nLeaders\\n36 Leadership behaviour and ____ affects people’s focus',
          questionWordPhrase: 'Leadership behaviour and',
          targetText: 'style',
          thaiMeaning: 'สไตล์',
          explanationThai: '\'Leadership behaviour and\' ในโจทย์เติมด้วย \'style\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nTransformational Leaders\\n37 pay special attention to the ____ of their followers',
          questionWordPhrase: 'pay special attention to the',
          targetText: 'development',
          thaiMeaning: 'การพัฒนา',
          explanationThai: '\'pay special attention to the\' ในโจทย์เติมด้วย \'development\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nTransformational Leaders\\n38 passionately communicate a clear ____',
          questionWordPhrase: 'passionately communicate a clear',
          targetText: 'vision',
          thaiMeaning: 'วิสัยทัศน์',
          explanationThai: '\'passionately communicate a clear\' ในโจทย์เติมด้วย \'vision\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nTransactional Leaders\\n39 create ____ to make expectations clear',
          questionWordPhrase: 'create',
          targetText: 'structures',
          thaiMeaning: 'โครงสร้าง',
          explanationThai: '\'create\' ในโจทย์เติมด้วย \'structures\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t3-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nConclusion\\n40 Promotion Focus is good for jobs requiring ____ Prevention Focus is good for work such as a surgeon',
          questionWordPhrase: 'Promotion Focus is good for jobs requiring',
          targetText: 'innovation',
          thaiMeaning: 'นวัตกรรม',
          explanationThai: '\'Promotion Focus is good for jobs requiring\' ในโจทย์เติมด้วย \'innovation\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam10-sec4-test4',
      testNumber: 4,
      title: '',
      scriptParagraphs: [
        'Today we’re going to look at an important area of science, namely nanotechnology.',
        'So what is it?',
        'Nano means tiny, so it’s science and engineering on the scale of atoms and molecules.',
        'The idea is that by controlling and rearranging atoms, you can literally create anything.',
        'However, as we’ll see, the science of the small has some big implications affecting us in many ways.',
        'There’s no doubt that nanotechnology promises so much for civilisation.',
        'However, all new technologies have their teething problems.',
        'And with nanotechnology, society often gets the wrong idea about its capabilities.',
        'Numerous science-fiction books and movies have raised people’s fears about nanotechnology – with scenarios such as inserting little nano-robots into your body that monitor everything you do without you realising it, or self-replicating nano-robots that eventually take over the world.',
        'So how do we safeguard such a potentially powerful technology?',
        'Some scientists recommend that nano-particles be treated as new chemicals with separate safety tests and clear labelling.',
        'They believe that greater care should also be taken with nano-particles in laboratories and factories.',
        'Others have called for a withdrawal of new nano products such as cosmetics and a temporary halt to many kinds of nanotech research.',
        'But as far as I’m concerned there’s a need to plough ahead with the discoveries and applications of nanotechnology.',
        'I really believe that most scientists would welcome a way to guard against unethical uses of such technology.',
        'We can’t go around thinking that all innovation is bad, all advancement is bad.',
        'As with the debate about any new technology, it is how you use it that’s important.',
        'So let’s look at some of its possible uses.',
        'Thanks to nanotechnology, there could be a major breakthrough in the field of transportation with the production of more durable metals.',
        'These could be virtually unbreakable, lighter and much more pliable leading to planes that are 50 times lighter than at present.',
        'Those same improved capabilities will dramatically reduce the cost of travelling into space making it more accessible to ordinary people and opening up to totally new holiday destination.',
        'In terms of technology, the computer industry will be able to shrink computer parts down to minute sizes.',
        'We need nanotechnology in order to create a new generation of computers that will work even faster and will have a million times more memory but will be about the size of a sugar cube.',
        'Nanotechnology could also revolutionise the way that we generate power.',
        'The cost of solar cells will be drastically reduced so harnessing this energy will be far more economical than at present.',
        'But nanotechnology has much wider applications than this and could have an enormous impact on our environment.',
        'For instance, tiny airborne nano-robots could be programmed to actually rebuild the ozone layer, which could lessen the impact of global warming on our planet.',
        'That’s a pretty amazing thought, isn’t it?',
        'On a more local scale, this new technology could help with the clean-up of environmental disasters as nanotechnology will allow us to remove oil and other contaminants from the water far more effectively.',
        'And, if nanotechnology progresses as expected – as a sort of building block set of about 90 atoms – then you could build anything you wanted from the bottom up.',
        'In terms of production, this means that you only use what you need and so there wouldn’t be any waste.',
        'The notion that you could create anything at all has major implications for our health.',
        'It means that we’ll eventually be able to replicate anything.',
        'This would have a phenomenal effect on our society.',
        'In time it could even lead to the eradication of famine through the introduction of machines that produce food to feed the hungry.',
        'But it’s in the area of medicine that nanotechnology may have its biggest impact.',
        'How we detect disease will change as tiny biosensors are developed to analyse tests in minutes rather than days.',
        'There’s even speculation nano-robots could be used to slow the ageing process, lengthening life expectancy.',
        'As you can see, I’m very excited by the implications that could be available to us in the next few decades.',
        'Just how long it’ll take, I honestly don’t know.',
      ],
      tasks: [
        {
          id: 'cam10-s4-t4-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nSection 4\\n31 Question 31 ____',
          questionWordPhrase: 'Question 31',
          targetText: 'C',
          thaiMeaning: 'ค',
          explanationThai: '\'Question 31\' ในโจทย์เติมด้วย \'C\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nSection 4\\n32 Question 32 ____',
          questionWordPhrase: 'Question 32',
          targetText: 'B',
          thaiMeaning: 'บี',
          explanationThai: '\'Question 32\' ในโจทย์เติมด้วย \'B\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nSection 4\\n33 Question 33 ____',
          questionWordPhrase: 'Question 33',
          targetText: 'C',
          thaiMeaning: 'ค',
          explanationThai: '\'Question 33\' ในโจทย์เติมด้วย \'C\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nTransport\\n34 Nanotechnology could allow the development of stronger ____',
          questionWordPhrase: 'Nanotechnology could allow the development of stronger',
          targetText: 'metals',
          thaiMeaning: 'โลหะ',
          explanationThai: '\'Nanotechnology could allow the development of stronger\' ในโจทย์เติมด้วย \'metals\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nSection 4\\n35 Question 35 ____',
          questionWordPhrase: 'Question 35',
          targetText: 'space',
          thaiMeaning: 'ช่องว่าง',
          explanationThai: '\'Question 35\' ในโจทย์เติมด้วย \'space\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nTechnology\\n36 Computers will be even smaller, faster, and will have a greater ____',
          questionWordPhrase: 'Computers will be even smaller, faster, and will have a greater',
          targetText: 'memory',
          thaiMeaning: 'หน่วยความจำ',
          explanationThai: '\'Computers will be even smaller, faster, and will have a greater\' ในโจทย์เติมด้วย \'memory\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nSection 4\\n37 Question 37 ____',
          questionWordPhrase: 'Question 37',
          targetText: 'solar',
          thaiMeaning: 'พลังงานแสงอาทิตย์',
          explanationThai: '\'Question 37\' ในโจทย์เติมด้วย \'solar\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nTechnology\\n38 Pollutants such as ____ could be removed from water',
          questionWordPhrase: 'Pollutants such as',
          targetText: 'oil',
          thaiMeaning: 'น้ำมัน',
          explanationThai: '\'Pollutants such as\' ในโจทย์เติมด้วย \'oil\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nTechnology\\n39 There will be no ____ from manufacturing',
          questionWordPhrase: 'There will be no',
          targetText: 'waste',
          thaiMeaning: 'ของเสีย',
          explanationThai: '\'There will be no\' ในโจทย์เติมด้วย \'waste\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam10-s4-t4-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nTechnology\\n40 Analysis of medical ____ will be speeded up',
          questionWordPhrase: 'Analysis of medical',
          targetText: 'tests',
          thaiMeaning: 'การทดสอบ',
          explanationThai: '\'Analysis of medical\' ในโจทย์เติมด้วย \'tests\' ตามที่พูดในสคริปต์'
        },
      ]
    }
  ]
}
