import type { ListeningBuilderExamSet } from './listeningBuilderCambridge18Section2'

export const CAMBRIDGE_12_SECTION_4_EXAM_SET: ListeningBuilderExamSet = {
  id: 'cambridge-12-section-4',
  bookNumber: 12,
  sectionNumber: 4,
  title: 'Cambridge 12 · Section 4',
  tests: [
    {
      id: 'cam12-sec4-test1',
      testNumber: 1,
      title: '',
      scriptParagraphs: [
        'In public discussion of business, we take certain values for granted.',
        'Today I’m going to talk about four of them: collaboration, hard work, creativity and excellence.',
        'Most people would say they’re all ‘good things’.',
        'I’m going to suggest that’s an over-simple view.',
        'The trouble with these values is that they’re theoretical concepts, removed from the reality of day-to-day business.',
        'Pursue values by all means, but be prepared for what may happen as a result.',
        'They can actually cause damage, which is not at all the intention.',
        '31 Business leaders generally try to do the right thing.',
        'But all too often the right thing backfires, if those leaders adopt values without understanding and managing the side effects that arise.',
        '32 The values can easily get in the way of what’s actually intended.',
        'OK.',
        'So the first value I’m going to discuss is collaboration.',
        'Er, let me give you an example.',
        'On a management training course I once attended, we were put into groups and had to construct a bridge across a stream 33, using building blocks that we were given.',
        'The rule was that everyone in the team had to move at least one building block during the construction.',
        'This was intended to encourage teamwork.',
        'But it was really a job best done by one person.',
        'The other teams tried to collaborate on building the structure, and descended into confusion 34, with everyone getting in each other’s way.',
        'Our team leader solved the challenge brilliantly.',
        'She simply asked everyone in the team to move a piece a few centimetres, to comply with the rule, and then let the person in the team with an aptitude for puzzles like this build it alone.',
        'We finished before any other team.',
        'My point is that the task wasn’t really suited to teamworking, so why make it one?',
        'Teamwork can also lead to inconsistency – a common cause of poor sales.',
        'In the case of a smartphone that a certain company launched, one director wanted to target the business market, and another demanded it was aimed at consumers.',
        'The company wanted both directors to be involved, so gave the product a consumer-friendly name, but marketed it to companies.',
        'The result was that it met the needs of neither group.',
        'It would have been better to let one director or the other have his way, not both.',
        '35 Now industriousness, or hard work.',
        'It’s easy to mock people who say they work hard: after all, a hamster running around in a wheel is working hard – and getting nowhere.',
        'Of course hard work is valuable, but only when properly targeted.',
        'Otherwise it wastes the resources that companies value most – time and energy.',
        'And that’s bad for the organisation.',
        '36 There’s a management model that groups people according to four criteria: clever, hard-working, stupid and lazy.',
        'Here ‘lazy’ means having a rational determination not to carry out unnecessary tasks.',
        '37 It doesn’t mean trying to avoid work altogether.',
        'Most people display two of these characteristics, and the most valuable people are those who are both clever and lazy: they possess intellectual clarity, and they don’t rush into making decisions.',
        'They come up with solutions to save the time and energy spent by the stupid and hard-working group.',
        'Instead of throwing more man-hours at a problem, the clever and lazy group looks for a more effective solution.',
        'Next we come to creativity.',
        'This often works well – creating an attention-grabbing TV commercial, for example, might lead to increased sales.',
        'But it isn’t always a good thing.',
        'Some advertising campaigns are remembered for their creativity, without having any effect on sales.',
        'This happened a few years ago with the launch of a chocolate bar: subsequent research showed that plenty of consumers remembered the adverts, but had no idea what was being advertised 38.',
        'The trouble is that the creator derives pleasure from coming up with the idea, and wrongly assumes the audience for the campaign will share that feeling.',
        'A company that brings out thousands of new products may seem more creative than a company that only has a few, but it may be too creative, and make smaller profits.',
        'Creativity needs to be targeted, to solve a problem that the company has identified 39.',
        'Just coming up with more and more novel products isn’t necessarily a good thing.',
        'And finally, excellence.',
        'We all know companies that claim they ‘strive for excellence’, but it takes a long time to achieve excellence.',
        'In business, being first with a product is more profitable than having the best product.',
        'A major study of company performance compared pioneers – that is, companies bringing out the first version of a particular product – with followers, the companies that copied and improved on that product.',
        'The study found that the pioneers commanded an average market share of 29 percent, while the followers achieved less than half that, only 13 percent 40 – even though their product might have been better.',
        'Insisting on excellence in everything we do is time-consuming, wastes energy and leads to losing out on opportunities.',
        'Sometimes, second-rate work is more worthwhile than excellence.',
        '‘Make sure it’s excellent’ sounds like a good approach to business, but the ‘just-get-started’ approach is likely to be more successful.',
      ],
      tasks: [
        {
          id: 'cam12-s4-t1-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nFour business values\\n31 Many business values can result in ____ Senior managers need to understand and deal with the potential',
          questionWordPhrase: 'Many business values can result in',
          targetText: 'damage',
          thaiMeaning: 'ความเสียหาย',
          explanationThai: '\'Many business values can result in\' ในโจทย์เติมด้วย \'damage\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nFour business values\\n32 Many business values can result in ____ that may result',
          questionWordPhrase: 'Many business values can result in',
          targetText: 'side effects',
          thaiMeaning: 'ผลข้างเคียง',
          explanationThai: '\'Many business values can result in\' ในโจทย์เติมด้วย \'side effects\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nCollaboration\\n33 During a training course, the speaker was in a team that had to build a ____ Other teams experienced',
          questionWordPhrase: 'During a training course, the speaker was in a team that had to build a',
          targetText: 'bridge',
          thaiMeaning: 'สะพาน',
          explanationThai: '\'During a training course, the speaker was in a team that had to build a\' ในโจทย์เติมด้วย \'bridge\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nCollaboration\\n34 During a training course, the speaker was in a team that had to build a ____ from trying to collaborate',
          questionWordPhrase: 'During a training course, the speaker was in a team that had to build a',
          targetText: 'confusion',
          thaiMeaning: 'ความสับสน',
          explanationThai: '\'During a training course, the speaker was in a team that had to build a\' ในโจทย์เติมด้วย \'confusion\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nCollaboration\\n35 Sales of a ____ were poor because of collaboration',
          questionWordPhrase: 'Sales of a',
          targetText: 'smartphone',
          thaiMeaning: 'สมาร์ทโฟน',
          explanationThai: '\'Sales of a\' ในโจทย์เติมด้วย \'smartphone\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nIndustriousness\\n36 Hard work may be a bad use of various company ____ The word ‘lazy’ in this context refers to people who avoid doing tasks that are',
          questionWordPhrase: 'Hard work may be a bad use of various company',
          targetText: 'resources',
          thaiMeaning: 'ทรัพยากร',
          explanationThai: '\'Hard work may be a bad use of various company\' ในโจทย์เติมด้วย \'resources\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nIndustriousness\\n37 Hard work may be a bad use of various company ____',
          questionWordPhrase: 'Hard work may be a bad use of various company',
          targetText: 'unnecessary',
          thaiMeaning: 'ไม่จำเป็น',
          explanationThai: '\'Hard work may be a bad use of various company\' ในโจทย์เติมด้วย \'unnecessary\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nCreativity\\n38 An advertising campaign for a ____ was memorable but failed to boost sales',
          questionWordPhrase: 'An advertising campaign for a',
          targetText: 'chocolate bar',
          thaiMeaning: 'ช็อคโกแลตบาร์',
          explanationThai: '\'An advertising campaign for a\' ในโจทย์เติมด้วย \'chocolate bar\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nCreativity\\n39 Creativity should be used as a response to a particular ____',
          questionWordPhrase: 'Creativity should be used as a response to a particular',
          targetText: 'problem',
          thaiMeaning: 'ปัญหา',
          explanationThai: '\'Creativity should be used as a response to a particular\' ในโจทย์เติมด้วย \'problem\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t1-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nExcellence\\n40 According to one study, on average, pioneers had a ____ that was far higher than that of followers',
          questionWordPhrase: 'According to one study, on average, pioneers had a',
          targetText: 'market share',
          thaiMeaning: 'ส่วนแบ่งการตลาด',
          explanationThai: '\'According to one study, on average, pioneers had a\' ในโจทย์เติมด้วย \'market share\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam12-sec4-test2',
      testNumber: 2,
      title: '',
      scriptParagraphs: [
        'Over the years, attitudes towards workers have changed considerably.',
        'After all, there was a time when workers had no rights at all, and laboured in appalling conditions.',
        'Conditions have improved a lot, but conflict in the workplace is still common.',
        'And human resources managers nowadays need to be able to deal with it when necessary.',
        'What is conflict in the workplace?',
        'Definitions vary, but I’m taking it to refer to a whole range of behaviours that the victim finds unacceptable, from minor, harmless arguments to – at the opposite extreme – physical violence.',
        'Much of this is covered by the term bullying 31, by which I mean one or more people behaving abusively or aggressively against another who is in a weaker position.',
        'Although all behaviour like this is a form of conflict, not all conflict can be described in these terms.',
        'As with all human behaviour, there are numerous reasons for it.',
        'But often it’s caused by someone who feels the need to show their superiority over someone else 32, in order to feel that they aren’t at the lowest level in a hierarchy or a group of people.',
        'In some cases one person simply dislikes the other, on the basis that the personality of one is in some way incompatible with that of the other person 33.',
        'A general habit of optimism in one person could make them intolerant of a colleague who’s constantly pessimistic – not that that justifies treating them badly, of course.',
        'Some conflicts arise when people are more interested in promoting themselves and their team than in the company as a whole.',
        'These conflicts are called ‘structural’ 34, and could come about, for example, when a sales team believe they are the only people in the business who do any useful work, and look down on behind-the-scenes administrators.',
        'Conflict obviously affects the individuals concerned – the situation is likely to be very stressful for victims, resulting in their absence from work, possibly for months 35.',
        'For the company, if no effort is made to deal with conflict, it can spiral out of control, and even lead to the breakdown of the business.',
        'Some interesting work with chief executives – CEOs – has uncovered some of the reasons why they may treat colleagues badly.',
        'Many CEOs combine two opposing characteristics: confidence – that is, the belief that they’re capable of great achievements – with a high level of anxiety 36, a fear of missing targets, whether set by themselves or by the directors of the company.',
        'This combination can make them respond badly to anyone who questions their decisions.',
        'In a high pressure work environment, such characteristics become problematic.',
        'And it’s particularly difficult to tackle the situation where colleagues, managers and board members are all trying to achieve their own visions.',
        'When they can’t agree on strategic issues and on where they see the business going, there are real problems.',
        '37 For managers at lower levels within the organisation, it might seem that an autocratic form of management – where the chief executive gives orders and everyone else has to obey – would see more conflict than others.',
        'Interestingly, though, a company with a more democratic business model, can suffer more, when uncertainly about who to report to leads to conflicting demands.',
        '38 Now I’ll say a little about dealing with the type of conflict that has harmful effects.',
        'Of course the ideal is to prevent it arising in the first place.',
        'A good manager, at any level, will make efforts to earn the respect of the people they work with 39, particularly those who report to them.',
        'That will involve politeness in all communications, and treating them as equals who happen to have a different role within the organisation.',
        'Sometimes, of course, conflict does occur, and can get out of hand.',
        'In such cases the human resources department often gets involved.',
        'However, if one of the parties in a conflict sees human resources as simply a mouthpiece for the chief executive, then an external mediator might be able to help 40.',
        'By talking to both sides, and trying to find the truth of what’s been happening, they can build a clear picture of the situation, and give feedback that both sides will accept, precisely because they’re independent.',
      ],
      tasks: [
        {
          id: 'cam12-s4-t2-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nConflict at work\\n31 Conflict mostly consists of behaviour in the general category of ____ Often a result of people wanting to prove their',
          questionWordPhrase: 'Conflict mostly consists of behaviour in the general category of',
          targetText: 'bullying',
          thaiMeaning: 'กลั่นแกล้ง',
          explanationThai: '\'Conflict mostly consists of behaviour in the general category of\' ในโจทย์เติมด้วย \'bullying\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nConflict at work\\n32 Conflict mostly consists of behaviour in the general category of ____ Also caused by differences in',
          questionWordPhrase: 'Conflict mostly consists of behaviour in the general category of',
          targetText: 'superiority',
          thaiMeaning: 'ความเหนือกว่า',
          explanationThai: '\'Conflict mostly consists of behaviour in the general category of\' ในโจทย์เติมด้วย \'superiority\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nConflict at work\\n33 Conflict mostly consists of behaviour in the general category of ____ between people',
          questionWordPhrase: 'Conflict mostly consists of behaviour in the general category of',
          targetText: 'personality',
          thaiMeaning: 'บุคลิกภาพ',
          explanationThai: '\'Conflict mostly consists of behaviour in the general category of\' ในโจทย์เติมด้วย \'personality\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nConflict at work\\n34 Conflict mostly consists of behaviour in the general category of ____ ’ conflicts: people more concerned about own team than about company',
          questionWordPhrase: 'Conflict mostly consists of behaviour in the general category of',
          targetText: 'structural',
          thaiMeaning: 'โครงสร้าง',
          explanationThai: '\'Conflict mostly consists of behaviour in the general category of\' ในโจทย์เติมด้วย \'structural\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nConflict at work\\n35 Conflict-related stress can cause ____ that may last for months',
          questionWordPhrase: 'Conflict-related stress can cause',
          targetText: 'absence',
          thaiMeaning: 'ขาด',
          explanationThai: '\'Conflict-related stress can cause\' ในโจทย์เติมด้วย \'absence\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nChief Executives (CEOs)\\n36 Many have both ____ and anxiety',
          questionWordPhrase: 'Many have both',
          targetText: 'confidence',
          thaiMeaning: 'ความมั่นใจ',
          explanationThai: '\'Many have both\' ในโจทย์เติมด้วย \'confidence\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nChief Executives (CEOs)\\n37 There may be conflict between people who have different ____',
          questionWordPhrase: 'There may be conflict between people who have different',
          targetText: 'visions',
          thaiMeaning: 'นิมิต',
          explanationThai: '\'There may be conflict between people who have different\' ในโจทย์เติมด้วย \'visions\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nOther managers\\n38 A structure that is more ____ may create a feeling of uncertainly about who staff should report to',
          questionWordPhrase: 'A structure that is more',
          targetText: 'democratic',
          thaiMeaning: 'ประชาธิปไตย',
          explanationThai: '\'A structure that is more\' ในโจทย์เติมด้วย \'democratic\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nMinimising conflict\\n39 Bosses need to try hard to gain ____ Someone from outside the company may be given the role of',
          questionWordPhrase: 'Bosses need to try hard to gain',
          targetText: 'respect',
          thaiMeaning: 'เคารพ',
          explanationThai: '\'Bosses need to try hard to gain\' ในโจทย์เติมด้วย \'respect\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t2-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nMinimising conflict\\n40 Bosses need to try hard to gain ____ in order to resolve conflicts',
          questionWordPhrase: 'Bosses need to try hard to gain',
          targetText: 'mediator',
          thaiMeaning: 'คนกลาง',
          explanationThai: '\'Bosses need to try hard to gain\' ในโจทย์เติมด้วย \'mediator\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam12-sec4-test3',
      testNumber: 3,
      title: 'The effects of environmental change on birds Mercury (Hg)',
      scriptParagraphs: [
        'OK, so we’ve been looking at how man-made changes in our environment can affect wildlife.',
        'Now I’ll discuss a particular example.',
        'Let’s take a look at mercury.',
        'Mercury’s one of the 120 or so elements that make up all matter, and it has the symbol Hg.',
        'It’s a shiny, silvery substance.',
        'You may have seen it in old-fashioned thermometers, but it’s not used much for domestic purposes now because it’s highly toxic.',
        'But the problem is that the amount of mercury in the environment’s increasing.',
        'The main reason for this is the power plants used to produce electricity.',
        'The main source of energy that most of them use is still coal, and when it’s burned it releases mercury into the atmosphere.',
        'Some of this gets deposited into lakes and rivers, and if it’s ingested by a fish it’s not excreted, it stays in the fish’s body and it enters the food chain.',
        'So it’s been known for some time that birds which eat fish may be affected, but what wasn’t known until quite recently is that those that eat insects can also be affected.',
        'So a woman called Claire Varian-Ramos is doing some research on how this is affecting birds.',
        'And rather than looking at how many birds are actually killed by mercury poisoning, she’s looking for more subtle sub-effects.',
        'And these may be to do with the behaviour of the birds, or with the effect of mercury on the way their brain works, so whether it leads to problems with memory, for example.',
        'And she’s particularly focusing on the effects of mercury on bird song.',
        'Now, the process of song learning happens at a particular stage in the birds’ development, and what you may not know is that a young bird seems to acquire this skill by listening to the songs produced by its father, rather than by any other bird.',
        'And Varian-Ramos has already found in her research that if young male birds are exposed to mercury, if they eat food contaminated with mercury, then the songs they produce aren’t as complex as those produced by other birds.',
        'So quite low-level exposure to mercury is likely to have an impact on male birds in a natural situation, because it can mean that they’re less attractive to female birds, and so it can affect their chances of reproduction.',
        'Now the way she’s carrying out this research is worth thinking about.',
        'She’s using a mixture of studies using birds kept in laboratories, and studies carried out outdoors in the wild.',
        'The lab-based studies have the advantage that you don’t get all the variables you would in a natural setting, so the experimenter has a much higher level of control, and that means they can be more confident about their results in some ways.',
        'And of course they don’t have to worry about going out and finding the birds in order to observe them.',
        'So what are the implications here for humans?',
        'Well, because many birds are migratory, they may be transporting mercury far from contaminated sites.',
        'For example, it’s been found that ducks who’d been feeding at a contaminated site were later shot by hunters over a thousand kilometres away, and presumably eaten.',
        'But these birds likely had mercury levels high enough to warrant concern for human consumption.',
        'In addition, going back to song learning by birds, we saw that this may be affected by mercury contamination.',
        'Well, we also know that in humans, mercury causes developmental delays in the acquisition of language, and in fact this process is very similar in the brain regions it involves and even the genes that are involved.',
        'But mercury contamination has other important implication for humans as well.',
        'It’s now known that an unborn child can be affected if the food eaten by its mother contains high levels of mercury, and these effects can be quite substantial.',
        'In the end, it comes down to whether more value is placed on human economic wellbeing or environmental wellbeing.',
        'It’s true there are new regulations for mercury emissions from power plants, but these will need billions of dollars to implement, and increase costs for everyone.',
        'Some argue that’s too much to pay to protect wildlife.',
        'But as we’ve seen, the issues go beyond that, and I think it’s an issue we need to consider very carefully.',
      ],
      tasks: [
        {
          id: 'cam12-s4-t3-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\n\\n31 It has also recently been found to affect birds which feed on ____ Research on effects of mercury on birds',
          questionWordPhrase: 'It has also recently been found to affect birds which feed on',
          targetText: 'insects',
          thaiMeaning: 'แมลง',
          explanationThai: '\'It has also recently been found to affect birds which feed on\' ในโจทย์เติมด้วย \'insects\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\n\\n32 – the effects on birds’ ____ or mental processes, e.g. memory',
          questionWordPhrase: '– the effects on birds’',
          targetText: 'behaviour',
          thaiMeaning: 'พฤติกรรม',
          explanationThai: '\'– the effects on birds’\' ในโจทย์เติมด้วย \'behaviour\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\n\\n33 – the effects on bird song (usually learned from a bird’s ____ )',
          questionWordPhrase: '– the effects on bird song (usually learned from a bird’s',
          targetText: 'father',
          thaiMeaning: 'พ่อ',
          explanationThai: '\'– the effects on bird song (usually learned from a bird’s\' ในโจทย์เติมด้วย \'father\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\n\\n34 – songs learned by birds exposed to mercury are less ____ – this may have a negative effect on birds’',
          questionWordPhrase: '– songs learned by birds exposed to mercury are less',
          targetText: 'complex',
          thaiMeaning: 'ซับซ้อน',
          explanationThai: '\'– songs learned by birds exposed to mercury are less\' ในโจทย์เติมด้วย \'complex\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\n\\n35 – songs learned by birds exposed to mercury are less ____',
          questionWordPhrase: '– songs learned by birds exposed to mercury are less',
          targetText: 'reproduction',
          thaiMeaning: 'การสืบพันธุ์',
          explanationThai: '\'– songs learned by birds exposed to mercury are less\' ในโจทย์เติมด้วย \'reproduction\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\n\\n36 – allow more ____ for the experimenter',
          questionWordPhrase: '– allow more',
          targetText: 'control',
          thaiMeaning: 'ควบคุม',
          explanationThai: '\'– allow more\' ในโจทย์เติมด้วย \'control\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\n\\n37 Migrating birds such as ____ containing mercury may be eaten by humans',
          questionWordPhrase: 'Migrating birds such as',
          targetText: 'duck(s)',
          thaiMeaning: 'เป็ด',
          explanationThai: '\'Migrating birds such as\' ในโจทย์เติมด้วย \'duck(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\n\\n38 Mercury also causes problems in learning ____',
          questionWordPhrase: 'Mercury also causes problems in learning',
          targetText: 'language',
          thaiMeaning: 'ภาษา',
          explanationThai: '\'Mercury also causes problems in learning\' ในโจทย์เติมด้วย \'language\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\n\\n39 Mercury in a mother’s body from ____ may affect the unborn child',
          questionWordPhrase: 'Mercury in a mother’s body from',
          targetText: 'food',
          thaiMeaning: 'อาหาร',
          explanationThai: '\'Mercury in a mother’s body from\' ในโจทย์เติมด้วย \'food\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t3-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\n\\n40 New regulations for mercury emissions will affect everyone’s energy ____',
          questionWordPhrase: 'New regulations for mercury emissions will affect everyone’s energy',
          targetText: 'cost(s)',
          thaiMeaning: 'ต้นทุน',
          explanationThai: '\'New regulations for mercury emissions will affect everyone’s energy\' ในโจทย์เติมด้วย \'cost(s)\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam12-sec4-test4',
      testNumber: 4,
      title: '',
      scriptParagraphs: [
        'This lecture will be about the science of acoustics, the study of sound, in relation to urban environments such as cities.',
        'As an acoustic engineer myself, I think this is an area where we’re likely to see great changes.',
        'In the past, researching urban soundscapes was simple.',
        'We measured levels of sound in decibels, so I used to take my sound meter and I measured the noise somewhere, and then I might ask a sample of people to say at what level the sound became annoying.',
        'With data like this, acoustic engineers have been able to build up what we call noise maps, maps of the sound environment.',
        'But actually these aren’t a lot of use.',
        'What they do show is that the highest noise levels are generally on roads – well, that’s not really very surprising.',
        'But there’s quite a lot going on that these maps don’t show, because they can’t capture the complex way that sound varies over time.',
        'So they ignore important issues such as the noise someone might hear from the open windows or gardens of their neighbours, and this sort of noise can be quite significant in summer.',
        'We don’t have any databases on this sort of information.',
        'As well as that, these records of sound levels take no account of the fact that people vary in their perceptions of noise – so someone like me with years of working in acoustics might be very different from you in that regard.',
        'But anyway, even though these noise maps are fairly crude, they’ve been useful in providing information and raising awareness that noise matters, we need to deal with it and so it’s a political matter.',
        'And that’s important – we need rules and regulation because noise can cause all sorts of problems.',
        'Those of you who are city-dwellers know that things go on 24 hours a day, so city-dwellers often suffer from interrupted sleep.',
        'It’s also known that noise can lead to a rise in levels of stress, due to physical changes in the body affecting the composition of the blood.',
        'And there are other problems as well, for instance if schoolchildren don’t have a quiet place to study, their work will suffer.',
        'Now, one problem with decibel measurement is that it doesn’t differentiate between different types of noise.',
        'Some types of sounds that most people would probably think of as nice and relaxing might well score quite highly in decibel levels – think of the sound made by a fountain in a town square, for example.',
        'That’s not necessarily something that we’d want to control or reduce.',
        'So maybe researchers should consider these sorts of sounds in urban design.',
        'This is going to be tricky because just measuring decibel levels isn’t going to help us here.',
        'Instead, many researchers are using social science techniques, studying people’s emotional response to sound by using questionnaires and so on.',
        'So what exactly do people want to hear in an urban environment?',
        'Some recent interdisciplinary research has come out with results that at first sight seem contradictory – a city needs to have a sense of activity, so it needs to be lively, with sounds like the clack of high heels on a pavement or the hiss of a coffee machine, but these mustn’t be too intrusive, because at the same time we need to be able to relax.',
        'One of the major problems in achieving this will be getting architects and town planners to use the research.',
        'Apart from studying the basics of acoustics, these people receive very little training in this area.',
        'But in fact they should be regarding sound as an opportunity to add to the experience of urban living, whereas at present they tend to see it as something to be avoided or reduced as far as possible, or something that’s just a job for engineers like the street drainage system.',
        'What’s needed is for noise in cities to be regarded as an aesthetic quality, as something that has the qualities of an art form.',
        'If we acknowledge this, then we urgently need to know what governs it and how designers can work with it.',
        'We need to develop a complex understanding of many factors.',
        'What is the relationship between sound and culture?',
        'What can we learn from disciplines such as psychology about the way that sound interacts with human development and social relationships, and the way that sound affects our thought and feelings?',
        'Can we learn anything from physics about the nature of sound itself?',
        'Today’s powerful technologies can also help us.',
        'To show us their ideas and help us to imagine the effect their buildings will have, architects and town planners already use virtual reality – but these programs are silent.',
        'In the future such programs could use realistic sounds, meaning that soundscapes could be explored before being built.',
        'So hopefully, using the best technology we can lay our hands on, the city of the future will be a pleasure to the ears as well as the eyes.',
      ],
      tasks: [
        {
          id: 'cam12-s4-t4-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nNoise in Cities\\n31 do not show other sources of noise, e.g. when windows are open or people’s neighbours are in their ____',
          questionWordPhrase: 'do not show other sources of noise, e.g. when windows are open or people’s neighbours are in their',
          targetText: 'garden(s)',
          thaiMeaning: 'สวน',
          explanationThai: '\'do not show other sources of noise, e.g. when windows are open or people’s neighbours are in their\' ในโจทย์เติมด้วย \'garden(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nNoise in Cities\\n32 have made people realize that the noise is a ____ issue that must be dealt with',
          questionWordPhrase: 'have made people realize that the noise is a',
          targetText: 'political',
          thaiMeaning: 'ทางการเมือง',
          explanationThai: '\'have made people realize that the noise is a\' ในโจทย์เติมด้วย \'political\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nNoise in Cities\\n33 effect on the ____ of schoolchildren',
          questionWordPhrase: 'effect on the',
          targetText: 'study',
          thaiMeaning: 'ศึกษา',
          explanationThai: '\'effect on the\' ในโจทย์เติมด้วย \'study\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nDifferent types of noise\\n34 Some noises can be considered pleasant e.g. the sound of a ____ in a town',
          questionWordPhrase: 'Some noises can be considered pleasant e.g. the sound of a',
          targetText: 'fountain',
          thaiMeaning: 'น้ำพุ',
          explanationThai: '\'Some noises can be considered pleasant e.g. the sound of a\' ในโจทย์เติมด้วย \'fountain\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nDifferent types of noise\\n35 To investigate this, researchers may use methods from ____ sciences e.g. questionnaires',
          questionWordPhrase: 'To investigate this, researchers may use methods from',
          targetText: 'social',
          thaiMeaning: 'ทางสังคม',
          explanationThai: '\'To investigate this, researchers may use methods from\' ในโจทย์เติมด้วย \'social\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nWhat people want\\n36 Plenty of activity in urban environments which are ____ , but also allow people to relax',
          questionWordPhrase: 'Plenty of activity in urban environments which are',
          targetText: 'lively',
          thaiMeaning: 'มีชีวิตชีวา',
          explanationThai: '\'Plenty of activity in urban environments which are\' ในโจทย์เติมด้วย \'lively\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nWhat people want\\n37 do not get much ____ in acoustics',
          questionWordPhrase: 'do not get much',
          targetText: 'training',
          thaiMeaning: 'การฝึกอบรม',
          explanationThai: '\'do not get much\' ในโจทย์เติมด้วย \'training\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nWhat people want\\n38 how sound relates to ____',
          questionWordPhrase: 'how sound relates to',
          targetText: 'culture',
          thaiMeaning: 'วัฒนธรรม',
          explanationThai: '\'how sound relates to\' ในโจทย์เติมด้วย \'culture\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nWhat people want\\n39 whether physics can help us understand the ____ of sound',
          questionWordPhrase: 'whether physics can help us understand the',
          targetText: 'nature',
          thaiMeaning: 'ธรรมชาติ',
          explanationThai: '\'whether physics can help us understand the\' ในโจทย์เติมด้วย \'nature\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam12-s4-t4-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nWhat people want\\n40 current disadvantage: they are ____',
          questionWordPhrase: 'current disadvantage: they are',
          targetText: 'silent',
          thaiMeaning: 'เงียบ',
          explanationThai: '\'current disadvantage: they are\' ในโจทย์เติมด้วย \'silent\' ตามที่พูดในสคริปต์'
        },
      ]
    }
  ]
}
