import type { ListeningBuilderExamSet } from './listeningBuilderCambridge18Section2'

export const CAMBRIDGE_13_SECTION_4_EXAM_SET: ListeningBuilderExamSet = {
  id: 'cambridge-13-section-4',
  bookNumber: 13,
  sectionNumber: 4,
  title: 'Cambridge 13 · Section 4',
  tests: [
    {
      id: 'cam13-sec4-test1',
      testNumber: 1,
      title: 'Effects of urban environments on animals',
      scriptParagraphs: [
        'Hi.',
        'Today we’re going to be looking at animals in urban environments and I’m going to be telling you about some research on how they’re affected by these environments.',
        'Now, in evolutionary terms, urban environments represent huge upheavals, the sorts of massive changes that usually happen over millions of years.',
        'And we used to think that only a few species could adapt to this new environment.',
        'One species which is well known as being highly adaptable is the crow, and there’ve been various studies about how they manage to learn new skills.',
        'Another successful species is the pigeon, because they’re able to perch on ledges on the walls of city buildings, just like they once perched on cliffs by the sea..',
        'But in fact, we’re now finding that these early immigrants were just the start of a more general movement of animals into cities, and of adaptation by these animals to city life.',
        'And one thing that researchers are finding especially interesting is the speed with which they’re doing this – we’re not talking about gradual evolution here – these animals are changing fast.',
        'Let me tell you about some of the studies that have been carried out in this area.',
        'So, in the University of Minnesota, a biologist called Emilie Snell-Rood and her colleagues looked at specimens of urbanised small mammals such as mice and gophers that had been collected in Minnesota, and that are now kept in museums there.',
        'And she looked at specimens that had been collected over the last hundred years, which is a very short time in evolutionary terms.',
        'And she found that during that time, these small mammals had experienced a jump in brain size when compared to rural mammals.',
        'Now, we can’t be sure this means they’re more intelligent, but since the sizes of other parts of the body didn’t change, it does suggest that something cognitive was going on.',
        'And Snell-Rood thinks that this change might reflect the cognitive demands of adjusting to city life – having to look in different places to find food, for example, and coping with a whole new set of dangers.',
        'Then over in Germany at the Max Planck Institute, there’s another biologist called Catarina Miranda who’s done some experiments with blackbirds living in urban and rural areas.',
        'And she’s been looking not at their anatomy but at their behaviour.',
        'So as you might expect, she’s found that the urban blackbirds tend to be quite bold – they’re prepared to face up to a lot of threats that would frighten away their country counterparts.',
        'But there’s one type of situation that does seem to frighten the urban blackbirds, and that’s anything new – anything they haven’t experienced before.',
        'And if you think about it, that’s quite sensible for a bird living in the city.',
        'Jonathan Atwell, in Indiana University, is looking at how a range of animals respond to urban environments.',
        'He’s found that when they’re under stress, their endocrine systems react by reducing the amount of hormones such as corticosterone into their blood.',
        'It’s a sensible-seeming adaptation.',
        'A rat that gets scared every time a subway train rolls past won’t be very successful.',
        'There’s just one more study I’d like to mention which is by Sarah Partan and her team, and they’ve been looking at how squirrels communicate in an urban environment, and they’ve found that a routine part of their communication is carried out by waving their tails.',
        'You do also see this in the country, but it’s much more prevalent in cities, possibly because it’s effective in a noisy environment.',
        'So what are the long-term implications of this?',
        'One possibility is that we may see completely new species developing in cities.',
        'But on the other hand, it’s possible that not all of these adaptations will be permanent.',
        'Once the animal’s got accustomed to its new environment, it may no longer need the features it’s developed.',
        'So, now we’ve had a look…',
      ],
      tasks: [
        {
          id: 'cam13-s4-t1-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nIntroduction\\n31 the ____ – because of its general adaptability',
          questionWordPhrase: 'the',
          targetText: 'crow',
          thaiMeaning: 'อีกา',
          explanationThai: '\'the\' ในโจทย์เติมด้วย \'crow\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nIntroduction\\n32 the pigeon – because walls of city buildings are similar to ____ In fact, many urban animals are adapting with unusual',
          questionWordPhrase: 'the pigeon – because walls of city buildings are similar to',
          targetText: 'cliffs',
          thaiMeaning: 'หน้าผา',
          explanationThai: '\'the pigeon – because walls of city buildings are similar to\' ในโจทย์เติมด้วย \'cliffs\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nIntroduction\\n33 the pigeon – because walls of city buildings are similar to ____ Recent research',
          questionWordPhrase: 'the pigeon – because walls of city buildings are similar to',
          targetText: 'speed',
          thaiMeaning: 'ความเร็ว',
          explanationThai: '\'the pigeon – because walls of city buildings are similar to\' ในโจทย์เติมด้วย \'speed\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nIntroduction\\n34 – She found the size of their ____ had increased',
          questionWordPhrase: '– She found the size of their',
          targetText: 'brain(s)',
          thaiMeaning: 'สมอง)',
          explanationThai: '\'– She found the size of their\' ในโจทย์เติมด้วย \'brain(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nIntroduction\\n35 – She suggests this may be due to the need to locate new sources of ____ and to deal with new dangers',
          questionWordPhrase: '– She suggests this may be due to the need to locate new sources of',
          targetText: 'food',
          thaiMeaning: 'อาหาร',
          explanationThai: '\'– She suggests this may be due to the need to locate new sources of\' ในโจทย์เติมด้วย \'food\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nIntroduction\\n36 Catarina Miranda focused on the ____ of urban and rural blackbirds',
          questionWordPhrase: 'Catarina Miranda focused on the',
          targetText: 'behaviour(s)',
          thaiMeaning: 'พฤติกรรม',
          explanationThai: '\'Catarina Miranda focused on the\' ในโจทย์เติมด้วย \'behaviour(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nIntroduction\\n37 – She found urban birds were often braver, but were afraid of situations that were ____',
          questionWordPhrase: '– She found urban birds were often braver, but were afraid of situations that were',
          targetText: 'anything they haven’t experienced before',
          thaiMeaning: 'สิ่งใหม่',
          explanationThai: 'afraid of situations that were new ในโจทย์ถูกพูดว่า anything they haven’t experienced before'
        },
        {
          id: 'cam13-s4-t1-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nIntroduction\\n38 – He found that some animals respond to ____ by producing lower levels of hormones',
          questionWordPhrase: '– He found that some animals respond to',
          targetText: 'when they’re under stress, their endocrine systems react by reducing the amount of hormones',
          thaiMeaning: 'ความเครียด',
          explanationThai: 'respond to stress ในโจทย์ถูกอธิบายว่า when they’re under stress, their endocrine systems react'
        },
        {
          id: 'cam13-s4-t1-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nIntroduction\\n39 Sarah Partan’s team found urban squirrels use their ____ to help them communicate',
          questionWordPhrase: 'Sarah Partan’s team found urban squirrels use their',
          targetText: 'tail(s)',
          thaiMeaning: 'หาง',
          explanationThai: '\'Sarah Partan’s team found urban squirrels use their\' ในโจทย์เติมด้วย \'tail(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t1-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nLong-term possibilities\\n40 Species of animals may develop which are unique to cities. However, some changes may not be ____',
          questionWordPhrase: 'Species of animals may develop which are unique to cities. However, some changes may not be',
          targetText: 'permanent',
          thaiMeaning: 'ถาวร',
          explanationThai: '\'Species of animals may develop which are unique to cities. However, some changes may not be\' ในโจทย์เติมด้วย \'permanent\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam13-sec4-test2',
      testNumber: 2,
      title: 'Episodic memory',
      scriptParagraphs: [
        'Today, we’ll be continuing the series of lectures on memory by focusing on what is called episodic memory and what can happen if this is not working properly.',
        'Episodic memory refers to the memory of an event or ‘episode’.',
        'Episodic memories allow us to mentally travel back in time to an event from the past.',
        'Episodic memories include various details about these events, for example, when an event happened and other information such as the location.',
        'To help understand this concept, try to remember the last time you ate dinner at a restaurant.',
        'The ability to remember where you ate, who you were with and the items you ordered are all features of an episodic memory.',
        'Episodic memory is distinct from another type of memory called semantic memory.',
        'This is the type of factual memory that we have in common with everyone else – that is your general knowledge of the world.',
        'To build upon a previous example, remembering where you parked your car is an example of episodic memory, but your understanding of what a car is and how an engine works are examples of sematic memory.',
        'Unlike episodic memory, semantic memory isn’t dependent on recalling personal experiences.',
        'Episodic memory can be thought of as a process with several different steps of memory processing: encoding, consolidation and retrieval.',
        'The initial step is called encoding.',
        'This involves the process of receiving and registering information, which is necessary for creating memories of information or events that you experience.',
        'The degree to which you can successfully encode information depends on the level of attention you give to an event while it’s actually happening.',
        'Being distracted can make effective encoding very difficult.',
        'Encoding of episodic memories is also influenced by how you process the event.',
        'For example, if you were introduced to someone called Charlie, you might make the connection that your uncle has the same name.',
        'Future recollection of Charlie’s name is much easier if you have a strategy to help you encode it.',
        'Memory consolidation, the next step in forming an episodic memory, is the process by which memories of encoded information are strengthened, stabilised and stored to facilitate later retrieval.',
        'Consolidation is most effective when the information being stored can be linked to an existing network of information.',
        'Consolidation makes it possible for you to store memories for later retrieval indefinitely.',
        'Forming strong memories depends on the frequency with which you try to retrieve them.',
        'Memories can fade or become harder to retrieve if they aren’t used very often.',
        'The last step in forming episodic memories is called retrieval, which is the conscious recollection of encoded information.',
        'Retrieving information from episodic memory depends upon semantic, olfactory, auditory and visual factors.',
        'These help episodic memory retrieval by acting as a prompt.',
        'For example, when recalling where you parked your car you may use the colour of a sign close to where you parked.',
        'You actually have to mentally travel back to the moment you parked.',
        'There are a wide range of neurological diseases and conditions that can affect episodic memory.',
        'These range from Alzheimer’s to schizophrenia to autism.',
        'An impairment of episodic memory can have a profound effect on individuals’ lives.',
        'For example, the symptoms of schizophrenia can be reasonably well controlled by medication; however, patients’ episodic memory may still be impaired and so they are often unable to return to university or work.',
        'Recent studies have shown that computer- assisted games designed to keep the brain active can help improve their episodic memory.',
        'Episodic memories can help people connect with others, for instance by sharing intimate details about their past; something individuals with autism often have problems with.',
        'This may be caused by an absence of a sense of self.',
        'This is essential for the storage of episodic memory, and has been found to be impaired in children with autism.',
        'Research has shown that treatments that improve memory may also have a positive impact on children’s social development.',
        'One study looked at a …',
      ],
      tasks: [
        {
          id: 'cam13-s4-t2-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\n\\n31 the ability to recall details, e.g. the time and ____ of past events',
          questionWordPhrase: 'the ability to recall details, e.g. the time and',
          targetText: 'location',
          thaiMeaning: 'ที่ตั้ง',
          explanationThai: '\'the ability to recall details, e.g. the time and\' ในโจทย์เติมด้วย \'location\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\n\\n32 different to semantic memory – the ability to remember general information about the ____ , which does not involve recalling',
          questionWordPhrase: 'different to semantic memory – the ability to remember general information about the',
          targetText: 'world',
          thaiMeaning: 'โลก',
          explanationThai: '\'different to semantic memory – the ability to remember general information about the\' ในโจทย์เติมด้วย \'world\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\n\\n33 different to semantic memory – the ability to remember general information about the ____ information',
          questionWordPhrase: 'different to semantic memory – the ability to remember general information about the',
          targetText: 'personal',
          thaiMeaning: 'ส่วนตัว',
          explanationThai: '\'different to semantic memory – the ability to remember general information about the\' ในโจทย์เติมด้วย \'personal\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nEncoding\\n34 the more ____ Given to an event, the more successfully it can be encoded',
          questionWordPhrase: 'the more',
          targetText: 'attention',
          thaiMeaning: 'ความสนใจ',
          explanationThai: '\'the more\' ในโจทย์เติมด้วย \'attention\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nEncoding\\n35 to remember a ____ , it is useful to have a strategy for encoding such information',
          questionWordPhrase: 'to remember a',
          targetText: 'name',
          thaiMeaning: 'ชื่อ',
          explanationThai: '\'to remember a\' ในโจทย์เติมด้วย \'name\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nConsolidation\\n36 most effective when memories can be added to a ____ Of related information',
          questionWordPhrase: 'most effective when memories can be added to a',
          targetText: 'network',
          thaiMeaning: 'เครือข่าย',
          explanationThai: '\'most effective when memories can be added to a\' ในโจทย์เติมด้วย \'network\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nConsolidation\\n37 the ____ Of retrieval affects the strength of memories',
          questionWordPhrase: 'the',
          targetText: 'frequency',
          thaiMeaning: 'ความถี่',
          explanationThai: '\'the\' ในโจทย์เติมด้วย \'frequency\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nRetrieval\\n38 memory retrieval often depends on using a prompt, e.g. the ____ Of an object near to the place where you left your car',
          questionWordPhrase: 'memory retrieval often depends on using a prompt, e.g. the',
          targetText: 'colour',
          thaiMeaning: 'สี',
          explanationThai: '\'memory retrieval often depends on using a prompt, e.g. the\' ในโจทย์เติมด้วย \'colour\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nRetrieval\\n39 games which stimulate the ____ have been found to help people with schizophrenia',
          questionWordPhrase: 'games which stimulate the',
          targetText: 'brain',
          thaiMeaning: 'สมอง',
          explanationThai: '\'games which stimulate the\' ในโจทย์เติมด้วย \'brain\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t2-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nRetrieval\\n40 children with autism may have difficulty forming episodic memories – possibly because their concept of the ____ may be absent',
          questionWordPhrase: 'children with autism may have difficulty forming episodic memories – possibly because their concept of the',
          targetText: 'self',
          thaiMeaning: 'ตัวเอง',
          explanationThai: '\'children with autism may have difficulty forming episodic memories – possibly because their concept of the\' ในโจทย์เติมด้วย \'self\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam13-sec4-test3',
      testNumber: 3,
      title: '',
      scriptParagraphs: [
        'Last week, we started looking at reptiles, including crocodiles and snakes.',
        'Today, I’d like us to have a look at another reptile – the lizard – and in particular, at some studies that have been done on a particular type of lizard whose Latin name is tiliqua rugosa.',
        'This is commonly known as the sleepy lizard, because it’s quite slow in its movements and spends quite a lot of its time dozing under rocks or lying in the sun.',
        'I’ll start with a general description.',
        'Sleepy lizards live in Western and South Australia, where they’re quite common.',
        'Unlike European lizards, which are mostly small, green and fast-moving, sleepy lizards are brown, but what’s particularly distinctive about them is the colour of their tongue, which is dark blue, in contrast with the lining of their mouth which is bright pink.',
        'And they’re much bigger than most European lizards.',
        'They have quite a varied diet, including insects and even small animals, but they mostly eat plants of varying kinds.',
        'Even though they’re quite large and powerful, with strong jaws that can crush beetles and snail shells, they still have quite a few predators.',
        'Large birds like cassowaries were one of the main ones in the past, but nowadays they’re more likely to be caught and killed by snakes.',
        'Actually, another threat to their survival isn’t a predator at all, but is man-made – quite a large number of sleepy lizards are killed by cars when they’re trying to cross highways.',
        'One study carried out by Michael Freake at Flinders University investigated the methods of navigation of these lizards.',
        'Though they move slowly, they can travel quite long distances.',
        'And he found that even if they were taken some distance away from their home territory, they could usually find their way back home as long as they could see the sky – they didn’t need any other landmarks on the ground.',
        'Observations of these lizards in the wild have also revealed that their mating habits are quite unusual.',
        'Unlike most animals, it seems that they’re relatively monogamous, returning to the same partner year after year.',
        'And the male and female also stay together for a long time, both before and after the birth of their young.',
        'It’s quite interesting to think about the possible reasons for this.',
        'It could be that it’s to do with protecting their young – you’d expect them to have a much better chance of survival if they have both parents around.',
        'But in fact observers have noted that once the babies have hatched out of their eggs, they have hardly any contact with their parents.',
        'So, there’s not really any evidence to support that idea.',
        'Another suggestion’s based on the observation that male lizards in monogamous relationships tend to be bigger and stronger than other males.',
        'So maybe the male lizards stay around so they can give the female lizards protection from other males.',
        'But again, we’re not really sure.',
        'Finally, I’d like to mention another study that involved collecting data by tracking the lizards.',
        'I was actually involved in this myself.',
        'So we caught some lizards in the wild and we developed a tiny GPS system that would allow us to track them, and we fixed this onto their tails.',
        'Then we set the lizards free again, and we were able to track them for twelve days and gather data, not just about their location, but even about how many steps they took during this period.',
        'One surprising thing we discovered from this is that there were far fewer meetings between lizards than we expected – it seems that they were actually trying to avoid one another.',
        'So why would that be?',
        'Well, again we have no clear evidence, but one hypothesis is that male lizards can cause quite serious injuries to one another, so maybe this avoidance is a way of preventing this – of self-preservation, if you like.',
        'But we need to collect a lot more data before we can be sure of any of this.',
      ],
      tasks: [
        {
          id: 'cam13-s4-t3-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nDescription\\n31 They are brown, but recognisable by their blue ____',
          questionWordPhrase: 'They are brown, but recognisable by their blue',
          targetText: 'tongue(s)',
          thaiMeaning: 'ลิ้น',
          explanationThai: '\'They are brown, but recognisable by their blue\' ในโจทย์เติมด้วย \'tongue(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nDescription\\n32 Their diet consists mainly of ____',
          questionWordPhrase: 'Their diet consists mainly of',
          targetText: 'plants',
          thaiMeaning: 'พืช',
          explanationThai: '\'Their diet consists mainly of\' ในโจทย์เติมด้วย \'plants\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nDescription\\n33 Their main predators are large birds and ____ Navigation study',
          questionWordPhrase: 'Their main predators are large birds and',
          targetText: 'snakes',
          thaiMeaning: 'งู',
          explanationThai: '\'Their main predators are large birds and\' ในโจทย์เติมด้วย \'snakes\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nDescription\\n34 One study found that lizards can use the ____ to help them navigate',
          questionWordPhrase: 'One study found that lizards can use the',
          targetText: 'sky',
          thaiMeaning: 'ท้องฟ้า',
          explanationThai: '\'One study found that lizards can use the\' ในโจทย์เติมด้วย \'sky\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nDescription\\n35 Observations show that these lizards keep the same ____ for several years',
          questionWordPhrase: 'Observations show that these lizards keep the same',
          targetText: 'partner(s)',
          thaiMeaning: 'พันธมิตร',
          explanationThai: '\'Observations show that these lizards keep the same\' ในโจทย์เติมด้วย \'partner(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nDescription\\n36 (but little ____ has been noted between parents and children)',
          questionWordPhrase: '(but little',
          targetText: 'contact',
          thaiMeaning: 'ติดต่อ',
          explanationThai: '\'(but little\' ในโจทย์เติมด้วย \'contact\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nDescription\\n37 – to provide ____ for female lizards',
          questionWordPhrase: '– to provide',
          targetText: 'protection',
          thaiMeaning: 'การป้องกัน',
          explanationThai: '\'– to provide\' ในโจทย์เติมด้วย \'protection\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nTracking study\\n38 – A study was carried out using GPS systems attached to the ____ of the lizards',
          questionWordPhrase: '– A study was carried out using GPS systems attached to the',
          targetText: 'tail(s)',
          thaiMeaning: 'หาง',
          explanationThai: '\'– A study was carried out using GPS systems attached to the\' ในโจทย์เติมด้วย \'tail(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nTracking study\\n39 – This provided information on the lizards’ location and even the number of ____ taken',
          questionWordPhrase: '– This provided information on the lizards’ location and even the number of',
          targetText: 'steps',
          thaiMeaning: 'ขั้นตอน',
          explanationThai: '\'– This provided information on the lizards’ location and even the number of\' ในโจทย์เติมด้วย \'steps\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t3-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nTracking study\\n40 – This may be in order to reduce chances of ____',
          questionWordPhrase: '– This may be in order to reduce chances of',
          targetText: 'injuries',
          thaiMeaning: 'การบาดเจ็บ',
          explanationThai: '\'– This may be in order to reduce chances of\' ในโจทย์เติมด้วย \'injuries\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam13-sec4-test4',
      testNumber: 4,
      title: '',
      scriptParagraphs: [
        'In my presentation, I’m going to talk about coffee, and its importance both in economic and social terms.',
        'We think it was first drunk in the Arab world, but there’s hardly any documentary evidence of it before the 1500s, although of course that doesn’t mean that people didn’t know about it before then.',
        'However, there is evidence that coffee was originally gathered from bushes growing wild in Ethiopia, in the northeast of Africa.',
        'In the early sixteenth century, it was being bought by traders, and gradually its use as a drink spread throughout the Middle East.',
        'It’s also known that in 1522, in the Turkish city of Constantinople, which was the centre of the Ottoman Empire, the court physician approved its use as a medicine.',
        'By the mid-1500s, coffee bushes were being cultivated in the Yemen and for the next hundred years this region produced most of the coffee drunk in Africa and the Arab world.',
        'What’s particularly interesting about coffee is its effect on social life.',
        'It was rarely drunk at home, but instead people went to coffee houses to drink it.',
        'These people, usually men, would meet to drink coffee and chat about issues of the day.',
        'But at the time, this chance to share ideas and opinions was seen as something that was potentially dangerous, and in 1623 the ruler of Constantinople demanded the destruction of all the coffee houses in the city, although after his death many new ones opened, and coffee consumption continued.',
        'In the seventeenth century, coffee drinking spread to Europe, and here too coffee shops became places where ordinary people, nearly always men, could meet to exchange ideas.',
        'Because of this, some people said that these places performed a similar function to universities.',
        'The opportunity they provided for people to meet together outside their own homes and to discuss the topics of the day had an enormous impact on social life, and many social movements and political developments had their origins in coffee house discussions.',
        'In the late 1600s, the Yemeni monopoly on coffee production broke down and coffee production started to spread around the world, helped by European colonization.',
        'Europeans set up coffee plantations in Indonesia and the Caribbean and production of coffee in the colonies skyrocketed.',
        'Different types of coffee were produced in different areas, and it’s interesting that the names given to these different types, like Mocha or Java coffee, were often taken from the port they were shipped to Europe from.',
        'But if you look at the labour system in the different colonies, there were some significant differences.',
        'In Brazil and the various Caribbean colonies, coffee was grown in huge plantations and the workers there were almost all slaves.',
        'But this wasn’t the same in all colonies; for example in Java, which had been colonized by the Dutch, the peasants grew coffee and passed a proportion of this on to the Dutch, so it was used as a means of taxation.',
        'But whatever system was used, under the European powers of the eighteenth century, coffee production was very closely linked to colonisation.',
        'Coffee was grown in ever-increasing quantities to satisfy the growing demand from Europe, and it became nearly as important as sugar production, which was grown under very similar conditions.',
        'However, coffee prices were not yet low enough for people to drink it regularly at home, so most coffee consumption still took place in public coffee houses and it still remained something of a luxury item.',
        'In Britain, however, a new drink was introduced from China, and started to become popular, gradually taking over from coffee, although at first it was so expensive that only the upper classes could afford it.',
        'This was tea, and by the late 1700s it was being widely drunk.',
        'However, when the USA gained independence from Britain in 1766, they identified this drink with Britain, and coffee remained the preferred drink in the USA, as it still is today.',
        'So, by the early nineteenth century, coffee was already being widely produced and consumed.',
        'But during this century, production boomed and coffee prices started to fall.',
        'This was partly because new types of transportation had been developed which were cheaper and more efficient.',
        'So now, working people could afford to buy coffee – it wasn’t just a drink for the middle classes.',
        'And this was at a time when large parts of Europe were starting to work in industries.',
        'And sometimes this meant their work didn’t stop when it got dark; they might have to continue throughout the night.',
        'So, the use of coffee as a stimulant became important – it wasn’t just a drink people drank in the morning, for breakfast.',
        'There were also changes in cultivation …',
      ],
      tasks: [
        {
          id: 'cam13-s4-t4-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n31 1623: In Constantinople, the ruler ordered the ____ of every coffee house',
          questionWordPhrase: '1623: In Constantinople, the ruler ordered the',
          targetText: 'destruction',
          thaiMeaning: 'การทำลาย',
          explanationThai: '\'1623: In Constantinople, the ruler ordered the\' ในโจทย์เติมด้วย \'destruction\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n32 Coffee shops were compared to ____',
          questionWordPhrase: 'Coffee shops were compared to',
          targetText: 'universities',
          thaiMeaning: 'มหาวิทยาลัย',
          explanationThai: '\'Coffee shops were compared to\' ในโจทย์เติมด้วย \'universities\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n33 They played an important part in social and ____ changes',
          questionWordPhrase: 'They played an important part in social and',
          targetText: 'political',
          thaiMeaning: 'ทางการเมือง',
          explanationThai: '\'They played an important part in social and\' ในโจทย์เติมด้วย \'political\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n34 Types of coffee were often named according to the ____ they came from',
          questionWordPhrase: 'Types of coffee were often named according to the',
          targetText: 'port (s)',
          thaiMeaning: 'พอร์ต',
          explanationThai: '\'Types of coffee were often named according to the\' ในโจทย์เติมด้วย \'port (s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n35 In Brazil and the Caribbean, most cultivation depended on ____',
          questionWordPhrase: 'In Brazil and the Caribbean, most cultivation depended on',
          targetText: 'slaves',
          thaiMeaning: 'ทาส',
          explanationThai: '\'In Brazil and the Caribbean, most cultivation depended on\' ในโจทย์เติมด้วย \'slaves\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n36 In Java, coffee was used as a form of ____',
          questionWordPhrase: 'In Java, coffee was used as a form of',
          targetText: 'taxation',
          thaiMeaning: 'การเก็บภาษี',
          explanationThai: '\'In Java, coffee was used as a form of\' ในโจทย์เติมด้วย \'taxation\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n37 Coffee became almost as important as ____',
          questionWordPhrase: 'Coffee became almost as important as',
          targetText: 'sugar',
          thaiMeaning: 'น้ำตาล',
          explanationThai: '\'Coffee became almost as important as\' ในโจทย์เติมด้วย \'sugar\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n38 The move towards the consumption of ____ in Britain did not also take place in the USA',
          questionWordPhrase: 'The move towards the consumption of',
          targetText: 'tea',
          thaiMeaning: 'ชา',
          explanationThai: '\'The move towards the consumption of\' ในโจทย์เติมด้วย \'tea\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n39 Prices dropped because of improvements in ____',
          questionWordPhrase: 'Prices dropped because of improvements in',
          targetText: 'transportation',
          thaiMeaning: 'การขนส่ง',
          explanationThai: '\'Prices dropped because of improvements in\' ในโจทย์เติมด้วย \'transportation\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam13-s4-t4-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n40 Industrial workers found coffee helped them to work at ____',
          questionWordPhrase: 'Industrial workers found coffee helped them to work at',
          targetText: 'night',
          thaiMeaning: 'กลางคืน',
          explanationThai: '\'Industrial workers found coffee helped them to work at\' ในโจทย์เติมด้วย \'night\' ตามที่พูดในสคริปต์'
        },
      ]
    }
  ]
}
