// GENERATED by scripts/build-listening-audio-map.mjs — do not edit by hand.
//
// Cambridge listening audio is hotlinked from two public sites. Neither uses a
// predictable URL scheme — engnovate.com varies its upload folder by book, and
// ieltstrainingonline.com uses six different filename shapes across six folders —
// so these URLs are scraped, not computed.
//
// Each entry lists sources in priority order; the player tries them in turn, so a
// single host going down or renaming files no longer takes listening offline.
// Re-run the script when audio starts failing.
//
// Keys are `${book}-${test}-${part}`.

export const CAMBRIDGE_LISTENING_AUDIO_URLS: Record<string, string[]> = {
  '10-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/ielts-listening-testscambridge-ielts-10-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test1-Section1.mp3'
  ],
  '10-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/ielts-listening-testscambridge-ielts-10-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test1-Section2.mp3'
  ],
  '10-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/ielts-listening-testscambridge-ielts-10-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test1-Section3.mp3'
  ],
  '10-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/ielts-listening-testscambridge-ielts-10-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test1-Section4.mp3'
  ],
  '10-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test2-Section1.mp3'
  ],
  '10-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test2-Section2.mp3'
  ],
  '10-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test2-Section3.mp3'
  ],
  '10-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test2-Section4.mp3'
  ],
  '10-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test3-Section1.mp3'
  ],
  '10-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test3-Section2.mp3'
  ],
  '10-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test3-Section3.mp3'
  ],
  '10-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test3-Section4.mp3'
  ],
  '10-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test4-Section1.mp3'
  ],
  '10-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test4-Section2.mp3'
  ],
  '10-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test4-Section3.mp3'
  ],
  '10-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-10-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam10-Test4-Section4.mp3'
  ],
  '11-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test1-Section1.mp3'
  ],
  '11-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test1-Section2.mp3'
  ],
  '11-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test1-Section3.mp3'
  ],
  '11-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test1-Section4.mp3'
  ],
  '11-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test2-Section1.mp3'
  ],
  '11-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test2-Section2.mp3'
  ],
  '11-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test2-Section3.mp3'
  ],
  '11-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test2-Section4.mp3'
  ],
  '11-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test3-Section1.mp3'
  ],
  '11-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test3-Section2.mp3'
  ],
  '11-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test3-Section3.mp3'
  ],
  '11-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test3-Section4.mp3'
  ],
  '11-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test4-Section1.mp3'
  ],
  '11-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test4-Section2.mp3'
  ],
  '11-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test4-Section3.mp3'
  ],
  '11-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-11-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam11-Test4-Section4.mp3'
  ],
  '12-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test1-Section1.mp3'
  ],
  '12-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test1-Section2.mp3'
  ],
  '12-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test1-Section3.mp3'
  ],
  '12-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test1-Section4.mp3'
  ],
  '12-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test2-Section1.mp3'
  ],
  '12-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test2-Section2.mp3'
  ],
  '12-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test2-Section3.mp3'
  ],
  '12-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test2-Section4.mp3'
  ],
  '12-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test3-Section1.mp3'
  ],
  '12-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test3-Section2.mp3'
  ],
  '12-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test3-Section3.mp3'
  ],
  '12-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test3-Section4.mp3'
  ],
  '12-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test4-Section1.mp3'
  ],
  '12-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test4-Section2.mp3'
  ],
  '12-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test4-Section3.mp3'
  ],
  '12-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-12-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam12-Test4-Section4.mp3'
  ],
  '13-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test1-Section1.mp3'
  ],
  '13-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test1-Section2.mp3'
  ],
  '13-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test1-Section3.mp3'
  ],
  '13-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test1-Section4.mp3'
  ],
  '13-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test2-Section1.mp3'
  ],
  '13-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test2-Section2.mp3'
  ],
  '13-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test2-Section3.mp3'
  ],
  '13-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test2-Section4.mp3'
  ],
  '13-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test3-Section1.mp3'
  ],
  '13-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test3-Section2.mp3'
  ],
  '13-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test3-Section3.mp3'
  ],
  '13-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test3-Section4.mp3'
  ],
  '13-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test4-Section1.mp3'
  ],
  '13-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test4-Section2.mp3'
  ],
  '13-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test4-Section3.mp3'
  ],
  '13-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-13-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam13-Test4-Section4.mp3'
  ],
  '14-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test1-Section1.mp3'
  ],
  '14-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test1-Section2.mp3'
  ],
  '14-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test1-Section3.mp3'
  ],
  '14-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test1-Section4.mp3'
  ],
  '14-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test2-Section1.mp3'
  ],
  '14-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test2-Section2.mp3'
  ],
  '14-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test2-Section3.mp3'
  ],
  '14-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test2-Section4.mp3'
  ],
  '14-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test3-Section1.mp3'
  ],
  '14-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test3-Section2.mp3'
  ],
  '14-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test3-Section3.mp3'
  ],
  '14-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test3-Section4.mp3'
  ],
  '14-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test4-Section1.mp3'
  ],
  '14-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test4-Section2.mp3'
  ],
  '14-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test4-Section3.mp3'
  ],
  '14-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-14-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam14-Test4-Section4.mp3'
  ],
  '15-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test1-Part1.m4a'
  ],
  '15-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test1-Part2.m4a'
  ],
  '15-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test1-Part3.m4a'
  ],
  '15-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test1-Part4.m4a'
  ],
  '15-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test2-Part1.m4a'
  ],
  '15-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test2-Part2.m4a'
  ],
  '15-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test2-Part3.m4a'
  ],
  '15-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test2-Part4.m4a'
  ],
  '15-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test3-Part1.m4a'
  ],
  '15-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test3-Part2.m4a'
  ],
  '15-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test3-Part3.m4a'
  ],
  '15-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test3-Part4.m4a'
  ],
  '15-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test4-Part1.m4a'
  ],
  '15-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test4-Part2.m4a'
  ],
  '15-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test4-Part3.m4a'
  ],
  '15-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/12/cambridge-ielts-15-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam15-Test4-Part4.m4a'
  ],
  '16-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test1-Part1.mp3'
  ],
  '16-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test1-Part2.mp3'
  ],
  '16-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test1-Part3.mp3'
  ],
  '16-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test1-Part4.mp3'
  ],
  '16-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test2-Part1.mp3'
  ],
  '16-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test2-Part2.mp3'
  ],
  '16-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test2-Part3.mp3'
  ],
  '16-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test2-Part4.mp3'
  ],
  '16-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test3-Part1.mp3'
  ],
  '16-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test3-Part2.mp3'
  ],
  '16-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test3-Part3.mp3'
  ],
  '16-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test3-Part4.mp3'
  ],
  '16-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test4-Part1.mp3'
  ],
  '16-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test4-Part2.mp3'
  ],
  '16-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test4-Part3.mp3'
  ],
  '16-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-16-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2021/07/Cam16-Test4-Part4.mp3'
  ],
  '17-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test1-part1.mp3'
  ],
  '17-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test1-part2.mp3'
  ],
  '17-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test1-part3.mp3'
  ],
  '17-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test1-part4.mp3'
  ],
  '17-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test2-part1.mp3'
  ],
  '17-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test2-part2.mp3'
  ],
  '17-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test2-part3.mp3'
  ],
  '17-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test2-part4.mp3'
  ],
  '17-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test3-part1.mp3'
  ],
  '17-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test3-part2.mp3'
  ],
  '17-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test3-part3.mp3'
  ],
  '17-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test3-part4.mp3'
  ],
  '17-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test4-part1.mp3'
  ],
  '17-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test4-part2.mp3'
  ],
  '17-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test4-part3.mp3'
  ],
  '17-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/07/cambridge-ielts-17-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2022/06/cam17-test4-part4.mp3'
  ],
  '18-1-1': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test1-part1.mp3'
  ],
  '18-1-2': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test1-part2.mp3'
  ],
  '18-1-3': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test1-part3.mp3'
  ],
  '18-1-4': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test1-part4.mp3'
  ],
  '18-2-1': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test2-part1.mp3'
  ],
  '18-2-2': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test2-part2.mp3'
  ],
  '18-2-3': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test2-part3.mp3'
  ],
  '18-2-4': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test2-part4.mp3'
  ],
  '18-3-1': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test3-part1.mp3'
  ],
  '18-3-2': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test3-part2.mp3'
  ],
  '18-3-3': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test3-part3.mp3'
  ],
  '18-3-4': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test3-part4.mp3'
  ],
  '18-4-1': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test4-part1.mp3'
  ],
  '18-4-2': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-4-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test4-part2.mp3'
  ],
  '18-4-3': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test4-part3.mp3'
  ],
  '18-4-4': [
    'https://engnovate.com/wp-content/uploads/2023/08/cambridge-ielts-18-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2023/06/cam18-test4-part4.mp3'
  ],
  '19-1-1': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test1-part1.m4a'
  ],
  '19-1-2': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test1-part2.m4a'
  ],
  '19-1-3': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test1-part3.m4a'
  ],
  '19-1-4': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test1-part4.m4a'
  ],
  '19-2-1': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-2-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test2-part1.m4a'
  ],
  '19-2-2': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-2-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test2-part2.m4a'
  ],
  '19-2-3': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test2-part3.m4a'
  ],
  '19-2-4': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-2-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test2-part4.m4a'
  ],
  '19-3-1': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test3-part1.m4a'
  ],
  '19-3-2': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-3-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test3-part2.m4a'
  ],
  '19-3-3': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-3-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test3-part3.m4a'
  ],
  '19-3-4': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-3-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test3-part4.m4a'
  ],
  '19-4-1': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-4-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test4-part1.m4a'
  ],
  '19-4-2': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-4-audio-2-.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test4-part2.m4a'
  ],
  '19-4-3': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-4-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test4-part3.m4a'
  ],
  '19-4-4': [
    'https://engnovate.com/wp-content/uploads/2024/08/cambridge-ielts-19-academic-listening-4-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2024/07/cam19-test4-part4.m4a'
  ],
  '20-1-1': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-1-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test1-part1.MP3'
  ],
  '20-1-2': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-1-audio-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test1-part2.MP3'
  ],
  '20-1-3': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-1-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test1-part3.MP3'
  ],
  '20-1-4': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-1-audio-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test1-part4.MP3'
  ],
  '20-2-1': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-2-audio1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test2-part1.MP3'
  ],
  '20-2-2': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-2-audio-part-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test2-part2.MP3'
  ],
  '20-2-3': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-2-audio-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test2-part3.MP3'
  ],
  '20-2-4': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-2-audio-part-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test2-part4.MP3'
  ],
  '20-3-1': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-3-audio-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test3-part1.MP3'
  ],
  '20-3-2': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-3-audio-part-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test3-part2.MP3'
  ],
  '20-3-3': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-3-audio-part-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test3-part3.MP3'
  ],
  '20-3-4': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-3-audio-part-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test3-part4.MP3'
  ],
  '20-4-1': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-4-audio-part-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test4-part1.MP3'
  ],
  '20-4-2': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-4-audio-part-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test4-part2.MP3'
  ],
  '20-4-3': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-4-audio-part-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test4-part3.MP3'
  ],
  '20-4-4': [
    'https://engnovate.com/wp-content/uploads/2025/07/cambridge-ielts-20-academic-listening-4-audio-part-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2025/07/cam20-test4-part4.MP3'
  ],
  '21-1-1': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-1-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test1-part1.MP3'
  ],
  '21-1-2': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-1-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test1-part2.MP3'
  ],
  '21-1-3': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-1-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test1-part3.MP3'
  ],
  '21-1-4': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-1-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test1-part4.MP3'
  ],
  '21-2-1': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-2-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test2-part1.MP3'
  ],
  '21-2-2': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-2-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test2-part2.MP3'
  ],
  '21-2-3': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-2-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test2-part3.MP3'
  ],
  '21-2-4': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-2-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test2-part4.MP3'
  ],
  '21-3-1': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-3-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test3-part1.MP3'
  ],
  '21-3-2': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-3-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test3-part2.MP3'
  ],
  '21-3-3': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-3-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test3-part3.MP3'
  ],
  '21-3-4': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-3-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test3-part4.MP3'
  ],
  '21-4-1': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-4-1.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test4-part1.MP3'
  ],
  '21-4-2': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-4-2.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test4-part2.MP3'
  ],
  '21-4-3': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-4-3.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test4-part3.MP3'
  ],
  '21-4-4': [
    'https://engnovate.com/wp-content/uploads/2026/06/cambridge-ielts-21-academic-listening-test-4-4.mp3',
    'https://ieltstrainingonline.com/wp-content/uploads/2026/07/cam21-test4-part4.MP3'
  ]
}

export const getCambridgeListeningAudioUrls = (book: number, test: number, part: number): string[] =>
  CAMBRIDGE_LISTENING_AUDIO_URLS[`${book}-${test}-${part}`] || []

/** First known source, or '' when the set has no audio mapped. */
export const getCambridgeListeningAudioUrl = (book: number, test: number, part: number): string =>
  getCambridgeListeningAudioUrls(book, test, part)[0] || ''

const ALTERNATIVES_BY_URL: Record<string, string[]> = {}
for (const sources of Object.values(CAMBRIDGE_LISTENING_AUDIO_URLS)) {
  for (const source of sources) ALTERNATIVES_BY_URL[source] = sources
}

/**
 * Given any known audio URL, returns every mirror of the same recording (that URL
 * first). Lets callers that only carry a single audioUrl string still fall back to
 * the other host. Unknown URLs are returned unchanged.
 */
export const getCambridgeListeningAudioAlternatives = (url: string): string[] => {
  if (!url) return []
  const sources = ALTERNATIVES_BY_URL[url]
  if (!sources) return [url]
  return [url, ...sources.filter((source) => source !== url)]
}
