import type { ListeningBuilderExamSet } from './listeningBuilderCambridge18Section2'

export const CAMBRIDGE_14_SECTION_4_EXAM_SET: ListeningBuilderExamSet = {
  id: 'cambridge-14-section-4',
  bookNumber: 14,
  sectionNumber: 4,
  title: 'Cambridge 14 · Section 4',
  tests: [
    {
      id: 'cam14-sec4-test1',
      testNumber: 1,
      title: 'Marine renewable energy (ocean energy)',
      scriptParagraphs: [
        'Producing enough energy to meet our needs has become a serious problem.',
        'Demand is rising rapidly, because of the world’s increasing population and expanding industry.',
        'Burning fossil fuels, like gas, coal and oil, seriously damages the environment and they’ll eventually run out.',
        'For a number of years now, scientists have been working out how we can derive energy from renewable sources, such as the sun and wind, without causing pollution.',
        'Today I’ll outline marine renewable energy – also called ocean energy – which harnesses the movement of the oceans.',
        'Marine renewable energy can be divided into three main categories: wave energy, tidal energy and ocean thermal energy conversion, and I’ll say a few words about each one.',
        'First, wave energy.',
        'Numerous devices have been invented to harvest wave energy, with names such as Wave Dragon, the Penguin and Mighty Whale, and research is going on to try and come up with a really efficient method.',
        'This form of energy has plenty of potential, as the source is constant, and there’s no danger of waves coming to s standstill.',
        'Electricity can be generated using onshore systems, using a reservoir, or offshore systems.',
        'But the problem with ocean waves is that they’re erratic, with the wind making them travel in every direction.',
        'This adds to the difficulty of creating efficient technology: ideally all the waves would travel smoothly and regularly along the same straight line.',
        'Another drawback is that sand and other sediment on the ocean floor might be stopped from flowing normally, which can lead to environmental problems.',
        'The second category of marine energy that I’ll mention is tidal energy.',
        'One major advantage of using the tide, rather than waves, as a source of energy is that it’s predictable: we know the exact time of high and low tides for years to come.',
        'For tidal energy to be effective, the difference between high and low tides needs to be at least five metres, and this occurs naturally in only about forty places on Earth.',
        'But the right conditions can be created by constructing a tidal lagoon, an area of sea water separated from the sea.',
        'One current plan is to create a tidal lagoon on the coast of Wales.',
        'This will be an area of water within a bay at Swansea, sheltered by a U-shaped breakwater, or dam, built out from the coast.',
        'The breakwater will contain sixteen hydro turbines, and as the tide rises, water rushes through the breakwater, activating the turbines, which turn a generator to produce electricity.',
        'Then, for three hours as the tide goes out, the water is held back within the breakwater, increasing the difference in water level, until it’s several metres higher within the lagoon than in the open sea.',
        'Then, in order to release the stored water, gates in the breakwater are opened.',
        'It pours powerfully out of the lagoon, driving the turbines in the breakwater in the opposite direction and again generating thousands of megawatts of electricity.',
        'As there are two high tides a day, this lagoon scheme would generate electricity four times a day, every day, for a total of around 14 hours in every 24 – and enough electricity for over 150,000 homes.',
        'This system has quite a lot in its favour: unlike solar and wind energy it doesn’t depend on the weather; the turbines are operated without the need for fuel, so it doesn’t create any greenhouse gas emissions; and very little maintenance is needed.',
        'It’s estimated that electricity generated in this way will be relatively cheap, and that manufacturing the components would create than 2,000 jobs, a big boost to the local economy.',
        'On the other hand, there are fears that lagoons might harm both fish and birds, for example by disturbing migration patterns, and causing a build-up of silt, affecting local ecosystems.',
        'There are other forms of tidal energy, but I’ll go on to the third category of marine energy: ocean thermal energy conversion.',
        'This depends on there being a big difference in temperature between surface water and the water a couple of kilometres below the surface, and this occurs in tropical coastal areas.',
        'The idea is to bring cold water up to the surface using a submerged pipe.',
        'The concept dates back to 1881, when …',
      ],
      tasks: [
        {
          id: 'cam14-s4-t1-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nIntroduction\\n31 More energy required because of growth in population and ____',
          questionWordPhrase: 'More energy required because of growth in population and',
          targetText: 'industry',
          thaiMeaning: 'อุตสาหกรรม',
          explanationThai: '\'More energy required because of growth in population and\' ในโจทย์เติมด้วย \'industry\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nWave energy\\n32 Advantage: waves provide a ____ source of renewable energy',
          questionWordPhrase: 'Advantage: waves provide a',
          targetText: 'constant',
          thaiMeaning: 'คงที่',
          explanationThai: '\'Advantage: waves provide a\' ในโจทย์เติมด้วย \'constant\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nProblems\\n33 waves can move in any ____',
          questionWordPhrase: 'waves can move in any',
          targetText: 'direction',
          thaiMeaning: 'ทิศทาง',
          explanationThai: '\'waves can move in any\' ในโจทย์เติมด้วย \'direction\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nProblems\\n34 movement of sand, etc. on the ____ of the ocean may be affected',
          questionWordPhrase: 'movement of sand, etc. on the',
          targetText: 'floor',
          thaiMeaning: 'พื้น',
          explanationThai: '\'movement of sand, etc. on the\' ในโจทย์เติมด้วย \'floor\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nTidal energy\\n35 Tides are more ____ than waves',
          questionWordPhrase: 'Tides are more',
          targetText: 'predictable',
          thaiMeaning: 'คาดเดาได้',
          explanationThai: '\'Tides are more\' ในโจทย์เติมด้วย \'predictable\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nPlanned tidal lagoon in Wales\\n36 will be created in a ____ at Swansea',
          questionWordPhrase: 'will be created in a',
          targetText: 'bay',
          thaiMeaning: 'อ่าว',
          explanationThai: '\'will be created in a\' ในโจทย์เติมด้วย \'bay\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nPlanned tidal lagoon in Wales\\n37 stored water is released through ____ , driving the turbines in the reverse direction',
          questionWordPhrase: 'stored water is released through',
          targetText: 'gates',
          thaiMeaning: 'ประตู',
          explanationThai: '\'stored water is released through\' ในโจทย์เติมด้วย \'gates\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nAdvantages\\n38 no ____ is required to make it work',
          questionWordPhrase: 'no',
          targetText: 'fuel',
          thaiMeaning: 'เชื้อเพลิง',
          explanationThai: '\'no\' ในโจทย์เติมด้วย \'fuel\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nAdvantages\\n39 likely to create a number of ____',
          questionWordPhrase: 'likely to create a number of',
          targetText: 'jobs',
          thaiMeaning: 'งาน',
          explanationThai: '\'likely to create a number of\' ในโจทย์เติมด้วย \'jobs\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t1-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nProblem\\n40 may ham fish and birds, e.g. by affecting ____ and building up silt',
          questionWordPhrase: 'may ham fish and birds, e.g. by affecting',
          targetText: 'migration',
          thaiMeaning: 'การโยกย้าย',
          explanationThai: '\'may ham fish and birds, e.g. by affecting\' ในโจทย์เติมด้วย \'migration\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam14-sec4-test2',
      testNumber: 2,
      title: 'The history of weather forecasting',
      scriptParagraphs: [
        'In this series of lectures about the history of weather forecasting, I’ll start by examining its early history – that’ll be the subject of today’s talk.',
        'Ok, so we’ll start by going back thousands of years.',
        'Most ancient cultures had weather gods, and weather catastrophes, such as floods, played an important role in many creation myths.',
        'Generally, weather was attributed to the whims of the gods, as the wide range of weather gods in various cultures shows.',
        'For instance, there’s the Egyptian sun god Ra, and Thor, the Norse god of thunder and lightning.',
        'Many ancient civilisations developed rites such as dances in order to make the weather gods look kindly on them.',
        'But the weather was of daily importance: observing the skies and drawing the correct conclusions from these observations was really important, in fact their survival depended on it.',
        'It isn’t known when people first started to observe the skies, but at around 650 BC, the Babylonians produced the first short-range weather forecasts, based on their observations of clouds and other phenomena.',
        'The Chinese also recognised weather patterns, and by 300 BC, astronomers had developed a calendar which divided the year into 24 festivals, each associated with a different weather phenomenon.',
        'The ancient Greeks were the first to develop a more scientific approach to explaining the weather.',
        'The work of the philosopher and scientist Aristotle, in the fourth century BC, is especially noteworthy, as his ideas held sway for nearly 2,000 years.',
        'In 340 BC, he wrote a book in which he attempted to account for the formation of rain, clouds, wind and storms.',
        'He also described celestial phenomena such as haloes – that is, bright circles of light around the sun, the moon and bright stars – and comets.',
        'Many of his observations were surprisingly accurate.',
        'For example, he believed that heat could cause water to evaporate.',
        'But he also jumped to quite a few wrong conclusions, such as that winds are breathed out by the Earth.',
        'Errors like this were rectified from the Renaissance onwards.',
        'For nearly 2,000 years, Aristotle’s work was accepted as the chief authority on weather theory.',
        'Alongside this, though, in the Middle Ages weather observations were passed on in the form of proverbs, such as ‘Red sky at night, shepherd’s delight; red sky in the morning, shepherd’s warning’.',
        'Many of these are based on very good observations and are accurate, as contemporary meteorologists have discovered.',
        'For centuries, any attempt to forecast the weather could only be based on personal observation, but in the fifteenth century scientists began to see the need for instruments.',
        'Until then, the only ones available were weather vanes – to determine the wind direction – and early versions of rain gauges.',
        'One of the first, invented in the fifteenth century, was a hygrometer, which measured humidity.',
        'This was one of many inventions that contributed to the development of weather forecasting.',
        'In 1592, the Italian scientist and inventor Galileo developed the world’s first thermometer.',
        'His student Torricelli later invented the barometer, which allowed people to measure atmospheric pressure.',
        'In 1648, the French philosopher Pascal proved that pressure decreases with altitude.',
        'This discovery was verified by English astronomer Halley in 1686, and Halley was also the first person to map trade winds.',
        'This increasing ability to measure factors related to weather helped scientists to understand the atmosphere and its processes better, and they started collecting weather observation data systematically.',
        'In the eighteenth century, the scientist and politician Benjamin Franklin carried out work on electricity and lightning in particular, but he was also very interested in weather and studied it throughout most of his life.',
        'It was Franklin who discovered that storms generally travel from west to east.',
        'In addition to new meteorological instruments, other developments contributed to our understanding of the atmosphere.',
        'People in different locations began to keep records, and in the mid-nineteenth century, the invention of the telegraph made it possible for these records to be collated.',
        'This led, by the end of the nineteenth century, to the first weather services.',
        'It was not until the early twentieth century that mathematics and physics became part of meteorology, and we’ll continue from that point next week.',
      ],
      tasks: [
        {
          id: 'cam14-s4-t2-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nAncient cultures\\n31 many cultures invented ____ and other ceremonies to make the weather gods friendly',
          questionWordPhrase: 'many cultures invented',
          targetText: 'dances',
          thaiMeaning: 'เต้นรำ',
          explanationThai: '\'many cultures invented\' ในโจทย์เติมด้วย \'dances\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nAncient cultures\\n32 people needed to observe and interpret the sky to ensure their ____ around 650 BC, Babylonians started forecasting, using weather phenomena such as',
          questionWordPhrase: 'people needed to observe and interpret the sky to ensure their',
          targetText: 'survival',
          thaiMeaning: 'ความอยู่รอด',
          explanationThai: '\'people needed to observe and interpret the sky to ensure their\' ในโจทย์เติมด้วย \'survival\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nAncient cultures\\n33 people needed to observe and interpret the sky to ensure their ____ by 300 BC, the Chinese had a calendar made up of a number of',
          questionWordPhrase: 'people needed to observe and interpret the sky to ensure their',
          targetText: 'clouds',
          thaiMeaning: 'เมฆ',
          explanationThai: '\'people needed to observe and interpret the sky to ensure their\' ในโจทย์เติมด้วย \'clouds\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nAncient cultures\\n34 people needed to observe and interpret the sky to ensure their ____ connected with the weather',
          questionWordPhrase: 'people needed to observe and interpret the sky to ensure their',
          targetText: 'festivals',
          thaiMeaning: 'เทศกาล',
          explanationThai: '\'people needed to observe and interpret the sky to ensure their\' ในโจทย์เติมด้วย \'festivals\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\na more scientific approach\\n35 Aristotle also described haloes and ____',
          questionWordPhrase: 'Aristotle also described haloes and',
          targetText: 'comets',
          thaiMeaning: 'ดาวหาง',
          explanationThai: '\'Aristotle also described haloes and\' ในโจทย์เติมด้วย \'comets\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nAristotle’s work considered accurate\\n36 many proverbs, e.g. about the significance of the colour of the ____ , passed on accurate information',
          questionWordPhrase: 'many proverbs, e.g. about the significance of the colour of the',
          targetText: 'sky',
          thaiMeaning: 'ท้องฟ้า',
          explanationThai: '\'many proverbs, e.g. about the significance of the colour of the\' ในโจทย์เติมด้วย \'sky\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\n15th-19th centuries\\n37 15th century: scientists recognised value of ____ for the first time',
          questionWordPhrase: '15th century: scientists recognised value of',
          targetText: 'instruments',
          thaiMeaning: 'เครื่องมือ',
          explanationThai: '\'15th century: scientists recognised value of\' ในโจทย์เติมด้วย \'instruments\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\n15th-19th centuries\\n38 Galileo invented the ____ Pascal showed relationship between atmospheric pressure and altitude',
          questionWordPhrase: 'Galileo invented the',
          targetText: 'thermometer',
          thaiMeaning: 'เครื่องวัดอุณหภูมิ',
          explanationThai: '\'Galileo invented the\' ในโจทย์เติมด้วย \'thermometer\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\n15th-19th centuries\\n39 18th century: Franklin identified the movement of ____ 19th century: data from different locations could be sent to the same place by',
          questionWordPhrase: '18th century: Franklin identified the movement of',
          targetText: 'storms',
          thaiMeaning: 'พายุ',
          explanationThai: '\'18th century: Franklin identified the movement of\' ในโจทย์เติมด้วย \'storms\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t2-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\n15th-19th centuries\\n40 18th century: Franklin identified the movement of ____',
          questionWordPhrase: '18th century: Franklin identified the movement of',
          targetText: 'telegraph',
          thaiMeaning: 'โทรเลข',
          explanationThai: '\'18th century: Franklin identified the movement of\' ในโจทย์เติมด้วย \'telegraph\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam14-sec4-test3',
      testNumber: 3,
      title: 'Concerts in university arts festival',
      scriptParagraphs: [
        'As you all know, the university is planning an arts festival for later this year, and here in the music department we’ve planned three concerts.',
        'These will be public performances, and the programme has just been finalised.',
        'The theme of the festival is links between the UK and Australia, and this is reflected in the music: each concert will feature both British and Australian composers.',
        'I’ll tell you briefly about the Australian music, as you probably won’t be familiar with that.',
        'The first concert will include music by Liza Lim, who was born in Perth, Western Australia, in 1966.',
        'As a child, Lim originally learned to play the piano – like so many children – and also the violin.',
        'But when she was 11 her teachers encouraged her to start composing.',
        'She found this was her real strength, and she studied and later taught composition, both in Australia and in other countries.',
        'As a composer, she has received commissions from numerous orchestras, other performers and festivals in several countries.',
        'Liza Lim’s compositions are vibrant and full of energy, and she often explores Asian and Australian Aboriginal cultural sources, including the native instrument, the didgeridoo: this is featured in a work called The Compass.',
        'Her music is very expressive, so although it is complex, it has the power of connecting with audiences and performers alike.',
        'In the festival we’re going to give a semi-staged performance of The Oresteia.',
        'This is an opera in seven parts, based on the trilogy of ancient Greek tragedies by Aeschylus.',
        'Lim composed this when she was in her mid-20s, and she also wrote the text, along with Barrie Kosky.',
        'It’s performed by six singers, a dancer, and an orchestra that, as well as standard orchestral instruments, includes electric guitar, and a traditional Turkish stringed instrument.',
        'Lim wrote that because the stories in the tragedies are not easy to tell, the sounds she creates are also disturbing, and they include breathing, sobbing, laughing and whistling.',
        'The work lasts around 75 minutes, and the rest of the concert will consist of orchestral works by the British composers Ralph Vaughan Williams and Frederick Delius.',
        'Moving on now to our second concert, this will begin with instrumental music by British composers – Benjamin Britten and Judith Weir.',
        'After the interval we’ll go to Australia for a piece by Ross Edwards: The Tower of Remoteness.',
        'According to Edwards, the inspiration for this piece came from nature, when he was sitting alone in the dry bed of a creek, overshadowed by the leaves of palm trees, listening to the birds and insects.',
        'The Tower of Remoteness is scored for piano and clarinet.',
        'Edwards says he realised years after writing the piece that he had subconsciously modelled its opening phrase on a bird call.',
        'Ross Edwards was born in 1943 in Sydney, Australia, and studied at the Sydney Conservatorium of Music and the universities of Adelaide and Sydney.',
        'He’s well known in Australia, and in fact he’s one of the country’s most performed composers.',
        'He’s written a wide range of music, from symphonies and concertos to some composed specifically for children.',
        'Edward’s music has been described as being ‘deeply connected to Australia’, and it can be regarded as a celebration of the diversity of cultures that Australia can be proud of.',
        'The last of the three Australian composers to be represented in our festival is Carl Vine.',
        'Born in 1954, Vine, like Liza Lim, comes from Perth, Western Australia.',
        'He took up the cornet at the age of five, switching to the piano five years later.',
        'However, he went to university to study physics, before changing to composition.',
        'After graduating he moved to Sydney and worked as a freelance pianist and composer.',
        'Before long he had become prominent in Australia as a composer for dance, and in fact has written 25 scores of that type.',
        'In our third concert, Vine will be represented by his music for the flag hand-over ceremony of the Olympics held in 1996.',
        'This seven-minute orchestral piece was of course heard by millions of people worldwide, and we’ll hear it alongside works written by British composers Edward Elgar and, more recently, Thomas Adès.',
      ],
      tasks: [
        {
          id: 'cam14-s4-t3-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nAustralian composer: Liza Lim\\n31 studied piano and ____ before turning to composition',
          questionWordPhrase: 'studied piano and',
          targetText: 'violin',
          thaiMeaning: 'ไวโอลิน',
          explanationThai: '\'studied piano and\' ในโจทย์เติมด้วย \'violin\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nAustralian composer: Liza Lim\\n32 compositions show a great deal of ____ and are drawn from various cultural sources',
          questionWordPhrase: 'compositions show a great deal of',
          targetText: 'energy',
          thaiMeaning: 'พลังงาน',
          explanationThai: '\'compositions show a great deal of\' ในโจทย์เติมด้วย \'energy\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nAustralian composer: Liza Lim\\n33 her music is very expressive and also ____ festival will include her',
          questionWordPhrase: 'her music is very expressive and also',
          targetText: 'complex',
          thaiMeaning: 'ซับซ้อน',
          explanationThai: '\'her music is very expressive and also\' ในโจทย์เติมด้วย \'complex\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nAustralian composer: Liza Lim\\n34 her music is very expressive and also ____ called',
          questionWordPhrase: 'her music is very expressive and also',
          targetText: 'opera',
          thaiMeaning: 'โอเปร่า',
          explanationThai: '\'her music is very expressive and also\' ในโจทย์เติมด้วย \'opera\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nThe Oresteia\\n35 as ____ British composers: Ralph Vaughan Williams, Frederick Delius',
          questionWordPhrase: 'as',
          targetText: 'disturbing',
          thaiMeaning: 'รบกวน',
          explanationThai: '\'as\' ในโจทย์เติมด้วย \'disturbing\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nThe Tower of Remoteness\\n36 is performed by piano and ____ compositions include music for children',
          questionWordPhrase: 'is performed by piano and',
          targetText: 'clarinet',
          thaiMeaning: 'คลาริเน็ต',
          explanationThai: '\'is performed by piano and\' ในโจทย์เติมด้วย \'clarinet\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nThe Tower of Remoteness\\n37 celebrates Australia’s cultural ____',
          questionWordPhrase: 'celebrates Australia’s cultural',
          targetText: 'diversity',
          thaiMeaning: 'ความหลากหลาย',
          explanationThai: '\'celebrates Australia’s cultural\' ในโจทย์เติมด้วย \'diversity\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nplayed cornet then piano\\n38 studied ____ before studying music',
          questionWordPhrase: 'studied',
          targetText: 'physics',
          thaiMeaning: 'ฟิสิกส์',
          explanationThai: '\'studied\' ในโจทย์เติมด้วย \'physics\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nplayed cornet then piano\\n39 became well known as composer of music for ____ festival will include his music for the 1996',
          questionWordPhrase: 'became well known as composer of music for',
          targetText: 'dance',
          thaiMeaning: 'เต้นรำ',
          explanationThai: '\'became well known as composer of music for\' ในโจทย์เติมด้วย \'dance\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t3-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nplayed cornet then piano\\n40 became well known as composer of music for ____ British composers: Edward Elgar, Thomas Adès',
          questionWordPhrase: 'became well known as composer of music for',
          targetText: 'Olympics',
          thaiMeaning: 'โอลิมปิก',
          explanationThai: '\'became well known as composer of music for\' ในโจทย์เติมด้วย \'Olympics\' ตามที่พูดในสคริปต์'
        },
      ]
    },
    {
      id: 'cam14-sec4-test4',
      testNumber: 4,
      title: '',
      scriptParagraphs: [
        'In today’s class I’m going to talk about marine archaeology, the branch of archaeology focusing on human interaction with the sea, lakes and rivers.',
        'It’s the study of ships, cargoes, shipping facilities, and other physical remains.',
        'I’ll give you an example, then go on to show how this type of research is being transformed by the use of the latest technology.',
        'Atlit-Yam was a village on the coast of the eastern Mediterranean, which seems to have been thriving until around 7,000 BC.',
        'The residents kept cattle, caught fish and stored grain.',
        'They had wells for fresh water, many of their houses were built around a courtyard and were constructed of stone.',
        'The village contained an impressive monument: seven half-tonne stones standing in a semicircle around a spring, that might have been used for ceremonial purposes.',
        'Atlit-Yam may have been destroyed swiftly by a tsunami, or climate change may have caused glaciers to melt and sea levels to rise, flooding the village gradually.',
        'Whatever the cause, it now lies ten metres below the surface of the Mediterranean, buried under sand at the bottom of the sea.',
        'It’s been described as the largest and best preserved prehistoric settlement ever found on the seabed.',
        'For marine archaeologists, Atlit-Yam is a treasure trove.',
        'Research on the buildings, tools and the human remains has revealed how the bustling village once functioned, and even what diseases some of its residents suffered from.',
        'But of course this is only one small village, one window into a lost world.',
        'For a fuller picture, researchers need more sunken settlements, but the hard part is finding them.',
        'Underwater research used to require divers to find shipwrecks or artefacts, but in the second half of the twentieth century, various types of underwater vehicles were developed, some controlled from a ship on the surface, and some of them autonomous, which means they don’t need to be operated by a person.',
        'Autonomous underwater vehicles, or AUVs, are used in the oil industry, for instance, to create maps of the seabed before rigs and pipelines are installed.',
        'To navigate they use sensors, such as compasses and sonar.',
        'Until relatively recently they were very expensive, and so heavy that they had to be launched from a large vessel with a winch.',
        'But the latest AUVs are much easier to manoeuvre – they can be launched from the shore or a small ship.',
        'And they’re much cheaper, which makes them more accessible to research teams.',
        'They’re also very sophisticated.',
        'They can communicate with each other and, for example, work out the most efficient way to survey a site, or to find particular objects on the seabed.',
        'Field tests show the approach can work.',
        'For example, in a trial in 2015, three AUVs searched for wrecks at Marzamemi, off the coast of Sicily.',
        'The site is the final resting place of an ancient Roman ship, which sank in the sixth century AD while ferrying prefabricated marble elements for the construction of an early church.',
        'The AUVs mapped the area in detail, finding other ships carrying columns of the same material.',
        'Creating an internet in the sea for AUVs to communicate is no easy matter.',
        'Wifi networks on land use electromagnetic waves, but in water these will only travel a few centimetres.',
        'Instead, a more complex mix of technologies is required.',
        'For short distances, AUVs can share date using light, while acoustic waves are used to communicate over long distances.',
        'But more creative solutions are also being developed, where an AUV working on the seabed offloads data to a second AUV, which then surfaces and beams the data home to the research team using a satellite.',
        'There’s also a system that enables AUVs to share information from seabed scans, and other data.',
        'So if an AUV surveying the seabed finds an intriguing object, it can share the coordinates of the object – that is, its position – with a nearby AUV that carries superior cameras, and arrange for that AUV to make a closer inspection of the object.',
        'Marine archaeologists are excited about the huge potential of these AUVs for their discipline.',
        'One site where they’re going to be deployed is the Gulf of Baratti, off the Italian coast.',
        'In 1974, a 2,000-year-old Roman vessel was discovered here, in 18 metres of water.',
        'When it sank, it was carrying medical goods, in wooden or tin receptacles.',
        'Its cargo gives us insight into the treatments available all those years ago, including tablets that are thought to have been dissolved to form a cleansing liquid for the eyes.',
        'Other Roman ships went down nearby, taking their cargoes with them.',
        'Some held huge pots made of terracotta.',
        'Some were used for transporting cargoes of olive oil, and others held wine.',
        'In many cases it’s only these containers that remain, while the wooden ships have been buried under silt on the seabed.',
        'Another project that’s about to …',
      ],
      tasks: [
        {
          id: 'cam14-s4-t4-q31',
          questionNumber: 31,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n31 1623: In Constantinople, the ruler ordered the ____ of every coffee house',
          questionWordPhrase: '1623: In Constantinople, the ruler ordered the',
          targetText: 'spring',
          thaiMeaning: 'ฤดูใบไม้ผลิ',
          explanationThai: '\'1623: In Constantinople, the ruler ordered the\' ในโจทย์เติมด้วย \'spring\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q32',
          questionNumber: 32,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n32 Coffee shops were compared to ____',
          questionWordPhrase: 'Coffee shops were compared to',
          targetText: 'tools',
          thaiMeaning: 'เครื่องมือ',
          explanationThai: '\'Coffee shops were compared to\' ในโจทย์เติมด้วย \'tools\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q33',
          questionNumber: 33,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n33 They played an important part in social and ____ changes',
          questionWordPhrase: 'They played an important part in social and',
          targetText: 'maps',
          thaiMeaning: 'แผนที่',
          explanationThai: '\'They played an important part in social and\' ในโจทย์เติมด้วย \'maps\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q34',
          questionNumber: 34,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n34 Types of coffee were often named according to the ____ they came from',
          questionWordPhrase: 'Types of coffee were often named according to the',
          targetText: 'heavy',
          thaiMeaning: 'หนัก',
          explanationThai: '\'Types of coffee were often named according to the\' ในโจทย์เติมด้วย \'heavy\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q35',
          questionNumber: 35,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n35 In Brazil and the Caribbean, most cultivation depended on ____',
          questionWordPhrase: 'In Brazil and the Caribbean, most cultivation depended on',
          targetText: 'marble',
          thaiMeaning: 'หินอ่อน',
          explanationThai: '\'In Brazil and the Caribbean, most cultivation depended on\' ในโจทย์เติมด้วย \'marble\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q36',
          questionNumber: 36,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n36 In Java, coffee was used as a form of ____',
          questionWordPhrase: 'In Java, coffee was used as a form of',
          targetText: 'light',
          thaiMeaning: 'แสงสว่าง',
          explanationThai: '\'In Java, coffee was used as a form of\' ในโจทย์เติมด้วย \'light\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q37',
          questionNumber: 37,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n37 Coffee became almost as important as ____',
          questionWordPhrase: 'Coffee became almost as important as',
          targetText: 'camera(s)',
          thaiMeaning: 'กล้อง',
          explanationThai: '\'Coffee became almost as important as\' ในโจทย์เติมด้วย \'camera(s)\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q38',
          questionNumber: 38,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n38 The move towards the consumption of ____ in Britain did not also take place in the USA',
          questionWordPhrase: 'The move towards the consumption of',
          targetText: 'medical',
          thaiMeaning: 'ทางการแพทย์',
          explanationThai: '\'The move towards the consumption of\' ในโจทย์เติมด้วย \'medical\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q39',
          questionNumber: 39,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n39 Prices dropped because of improvements in ____',
          questionWordPhrase: 'Prices dropped because of improvements in',
          targetText: 'eyes',
          thaiMeaning: 'ดวงตา',
          explanationThai: '\'Prices dropped because of improvements in\' ในโจทย์เติมด้วย \'eyes\' ตามที่พูดในสคริปต์'
        },
        {
          id: 'cam14-s4-t4-q40',
          questionNumber: 40,
          questionText: 'Complete the notes below.\\nThe history of coffee\\n40 Industrial workers found coffee helped them to work at ____',
          questionWordPhrase: 'Industrial workers found coffee helped them to work at',
          targetText: 'wine',
          thaiMeaning: 'ไวน์',
          explanationThai: '\'Industrial workers found coffee helped them to work at\' ในโจทย์เติมด้วย \'wine\' ตามที่พูดในสคริปต์'
        },
      ]
    }
  ]
}
