export type CustomJourneyPassageInput = {
  title: string
  paragraphs: Array<[string, string]>
  fill: Array<{ prompt: string; answer: string; evidence: string; acceptedAnswers?: string[] }>
  judgement: Array<{ prompt: string; answer: 'TRUE' | 'FALSE' | 'NOT GIVEN'; evidence: string }>
  headings: {
    options: string[]
    questions: Array<{ prompt: string; answer: string; evidence: string }>
  }
}

export const EXTRA_CUSTOM_JOURNEY_PASSAGE_INPUTS: Record<number, Partial<Record<1 | 2, CustomJourneyPassageInput>>> = {
  1: {
    1: {
      title: '1. The Origins and Expansion of Coffee',
      paragraphs: [
        ['A', `The global fascination with roasted botanical brews has obscure historical roots. According to ancient oral traditions, a solitary Ethiopian herdsman named Kaldi first observed the energizing effects of a specific wild shrub when his flock began acting erratically after consuming its red berries, creating an enduring mythos around the plant's discovery. While impossible to verify, this legend underscores the geographical truth that the highlands of East Africa served as the undisputed evolutionary cradle for the arabica species. From these remote forests, the seeds of a global phenomenon were quietly sown.`],
        ['B', `The transition from raw berry to roasted drink required centuries of experimentation. Arab merchants exported the beans across the Red Sea into Yemen. By the 15th century, Sufi monks in Yemeni monasteries had perfected the technique of roasting and boiling the seeds to create a potent dark liquid, utilizing the resulting stimulation to sustain their arduous nocturnal prayers. This innovation transformed a simple agricultural product into a vital cultural cornerstone of the Islamic world, rapidly spreading to bustling trade hubs like Cairo and Damascus.`],
        ['C', `As trade routes expanded, European travelers encountered this unusual dark concoction. Initially, Catholic authorities in Italy viewed the foreign drink with intense suspicion, fearing it was a spiritual threat. However, following a papal endorsement in 1600, the drink rapidly permeated European culture, fundamentally altering the fabric of urban society. The subsequent establishment of public venues dedicated entirely to the consumption of this brew caused a dramatic shift in how city dwellers socialized and exchanged information.`],
        ['D', `These newly established venues proved to be profound catalysts for social transformation. In 17th-century London, these gathering places were colloquially known as "penny universities." Because they charged a minimal entrance fee, they actively fostered open intellectual debate among patrons from diverse economic backgrounds. Patrons could sit for hours, discussing politics, science, and philosophy, effectively laying the groundwork for the modern Enlightenment and democratizing access to academic discourse.`],
        ['E', `Recognizing the massive financial potential of the product, European colonial powers sought to break the Arabian monopoly. European colonists cleared massive forests to establish vast agricultural estates in the Caribbean and South America. This aggressive agricultural expansion relied heavily on exploitative labor practices, dramatically shifting the epicenter of global production to the Western Hemisphere. The environmental and human cost of this geographic transition was immense, forever altering the ecological landscape of the tropics.`],
        ['F', `Today, the commodity remains a cornerstone of international trade. The widespread cultivation and export of the beans currently supports the fragile economy of numerous developing nations across the equatorial belt. Despite the emergence of synthetic energy drinks and modern alternatives, the timeless appeal of the roasted seed continues to dominate morning routines worldwide.`]
      ],
      fill: [
        { prompt: 'The enduring folklore surrounding the discovery features an Ethiopian herdsman and a specific wild ________.', answer: 'shrub', evidence: `According to ancient oral traditions, a solitary Ethiopian herdsman named Kaldi first observed the energizing effects of a specific wild shrub when his flock began acting erratically after consuming its red berries, creating an enduring mythos around the plant's discovery.` },
        { prompt: 'Sufi monks processed the seeds into a dark ________ to stay awake during religious practices.', answer: 'liquid', evidence: 'By the 15th century, Sufi monks in Yemeni monasteries had perfected the technique of roasting and boiling the seeds to create a potent dark liquid, utilizing the resulting stimulation to sustain their arduous nocturnal prayers.' },
        { prompt: 'After gaining religious approval, the beverage deeply impacted the structure of European urban ________.', answer: 'society', evidence: 'However, following a papal endorsement in 1600, the drink rapidly permeated European culture, fundamentally altering the fabric of urban society.' },
        { prompt: 'The accessible nature of London venues encouraged widespread intellectual ________ among different classes.', answer: 'debate', evidence: 'Because they charged a minimal entrance fee, they actively fostered open intellectual debate among patrons from diverse economic backgrounds.' },
        { prompt: 'In the modern era, the trade of these beans sustains the vulnerable ________ of many equatorial countries.', answer: 'economy', evidence: 'The widespread cultivation and export of the beans currently supports the fragile economy of numerous developing nations across the equatorial belt.' }
      ],
      judgement: [
        { prompt: 'Arab merchants exported the beans across the Red Sea into Yemen exclusively during the summer months.', answer: 'NOT GIVEN', evidence: 'Arab merchants exported the beans across the Red Sea into Yemen.' },
        { prompt: 'Catholic leaders in Italy immediately embraced the foreign drink as a valuable spiritual tool.', answer: 'FALSE', evidence: 'Initially, Catholic authorities in Italy viewed the foreign drink with intense suspicion, fearing it was a spiritual threat.' },
        { prompt: 'Venues in 17th-century London were frequently referred to as penny universities by the local population.', answer: 'TRUE', evidence: 'In 17th-century London, these gathering places were colloquially known as "penny universities."' },
        { prompt: 'European colonists cleared massive forests using advanced mechanical logging equipment.', answer: 'NOT GIVEN', evidence: 'European colonists cleared massive forests to establish vast agricultural estates in the Caribbean and South America.' }
      ],
      headings: {
        options: [`The enduring mythos around the plant's discovery`, 'The relocation of cultivation centers and labor systems', 'Arab merchants exported the beans', 'The origin of botanical legends', 'The transformation into a vital cultural cornerstone', 'Democratizing access to academic discourse', 'European colonists cleared massive forests', 'The evolution from raw agricultural goods to brewed fluids'],
        questions: [
          { prompt: 'Paragraph E', answer: 'ii', evidence: 'This aggressive agricultural expansion relied heavily on exploitative labor practices, dramatically shifting the epicenter of global production to the Western Hemisphere.' },
          { prompt: 'Paragraph A', answer: 'iv', evidence: `According to ancient oral traditions, a solitary Ethiopian herdsman named Kaldi first observed the energizing effects of a specific wild shrub when his flock began acting erratically after consuming its red berries, creating an enduring mythos around the plant's discovery.` },
          { prompt: 'Paragraph D', answer: 'vi', evidence: 'Patrons could sit for hours, discussing politics, science, and philosophy, effectively laying the groundwork for the modern Enlightenment and democratizing access to academic discourse.' },
          { prompt: 'Paragraph B', answer: 'viii', evidence: 'The transition from raw berry to roasted drink required centuries of experimentation.' }
        ]
      }
    },
    2: {
      title: '2. The Engineering of the Colosseum',
      paragraphs: [
        ['A', `The architectural legacy of the Roman Empire continues to dominate the modern imagination. Constructed entirely from travertine stone and concrete, the massive amphitheater was commissioned by a prominent emperor to appease the restless citizens of the capital. By gifting the public a monumental space for free entertainment, the ruling elite effectively distracted the impoverished masses from ongoing political corruption and economic instability, utilizing monumental architecture as an instrument of social control.`],
        ['B', `The logistical complexity of the construction was unprecedented in the ancient world. Thousands of skilled artisans and laborers worked tirelessly to erect the outer walls. To facilitate the rapid movement of enormous crowds, architects designed a sophisticated network of vaulted corridors and precisely angled staircases. This ingenious circulatory system allowed over fifty thousand individuals to safely enter and exit the massive venue in a matter of minutes, a feat of crowd management that modern stadium designers still study today.`],
        ['C', `Beneath the sand-covered wooden arena floor lay a hidden world of mechanical wonder. The hypogeum consisted of a vast subterranean network of tunnels and holding cells. This elaborate basement housed wild exotic animals and heavily armed gladiators prior to their deadly public appearances. Using a complex system of wooden elevators and counterweights, stagehands could dramatically hoist beasts and combatants directly onto the arena floor, creating shocking theatrical surprises for the screaming audiences above.`],
        ['D', `Protection from the harsh Mediterranean climate was essential for maintaining crowd morale during all-day events. Roman engineers deployed a massive retractable canvas awning known as the velarium. Operated by specialized sailors recruited from the imperial fleet, this gigantic suspended canopy provided cooling shade to the thousands of sweltering spectators. The rigging required immense physical strength and exact coordination to adjust the heavy fabric in response to shifting winds.`],
        ['E', `Following the eventual collapse of the Western Roman Empire, the grand structure suffered intense neglect. Successive generations of local citizens stripped the outer facades of their valuable iron clamps and decorative marble. Over several centuries, natural disasters and systemic looting reduced the once-glorious venue to a crumbling, overgrown shell. Despite this severe degradation, the immense foundational arches refused to yield entirely, standing as a defiant testament to superior ancient masonry.`],
        ['F', `In the contemporary era, the monument requires constant intervention to survive. Ongoing pollution from city traffic poses a severe threat to the structural integrity of the ancient ruins. Consequently, Italian conservationists are currently utilizing advanced chemical treatments and laser cleaning technologies to halt the corrosive decay and preserve the iconic silhouette for future generations.`]
      ],
      fill: [
        { prompt: 'A Roman ________ ordered the building of the amphitheater to pacify the public.', answer: 'emperor', evidence: 'Constructed entirely from travertine stone and concrete, the massive amphitheater was commissioned by a prominent emperor to appease the restless citizens of the capital.' },
        { prompt: 'The designers utilized specialized corridors and angled ________ to move large crowds quickly.', answer: 'staircases', evidence: 'To facilitate the rapid movement of enormous crowds, architects designed a sophisticated network of vaulted corridors and precisely angled staircases.' },
        { prompt: 'The subterranean area contained dangerous beasts and armed ________ before the fights.', answer: 'gladiators', evidence: 'This elaborate basement housed wild exotic animals and heavily armed gladiators prior to their deadly public appearances.' },
        { prompt: 'A large canvas covering was manipulated by sailors to offer shade to the ________.', answer: 'spectators', evidence: 'Operated by specialized sailors recruited from the imperial fleet, this gigantic suspended canopy provided cooling shade to the thousands of sweltering spectators.' },
        { prompt: 'Today, urban pollution severely damages the physical stability of the historical ________.', answer: 'ruins', evidence: 'Ongoing pollution from city traffic poses a severe threat to the structural integrity of the ancient ruins.' }
      ],
      judgement: [
        { prompt: 'Thousands of skilled artisans and laborers worked tirelessly to erect the outer walls within exactly three years.', answer: 'NOT GIVEN', evidence: 'Thousands of skilled artisans and laborers worked tirelessly to erect the outer walls.' },
        { prompt: 'The hypogeum consisted of a vast subterranean network of tunnels and holding cells beneath the arena.', answer: 'TRUE', evidence: 'The hypogeum consisted of a vast subterranean network of tunnels and holding cells.' },
        { prompt: 'Roman engineers deployed a massive retractable canvas awning that was frequently blown away by strong storms.', answer: 'NOT GIVEN', evidence: 'Roman engineers deployed a massive retractable canvas awning known as the velarium.' },
        { prompt: 'Successive generations of local citizens carefully preserved the outer facades of the building.', answer: 'FALSE', evidence: 'Successive generations of local citizens stripped the outer facades of their valuable iron clamps and decorative marble.' }
      ],
      headings: {
        options: ['The political motivations behind monumental construction', 'Thousands of skilled artisans and laborers', 'Advanced architectural crowd dynamics', 'Successive generations of local citizens', 'The gradual destruction and pillaging of the monument', 'Subterranean network of tunnels', 'Theatrical surprises for the screaming audiences', 'Environmental shielding mechanisms'],
        questions: [
          { prompt: 'Paragraph E', answer: 'v', evidence: 'Over several centuries, natural disasters and systemic looting reduced the once-glorious venue to a crumbling, overgrown shell.' },
          { prompt: 'Paragraph A', answer: 'i', evidence: 'By gifting the public a monumental space for free entertainment, the ruling elite effectively distracted the impoverished masses from ongoing political corruption and economic instability, utilizing monumental architecture as an instrument of social control.' },
          { prompt: 'Paragraph D', answer: 'viii', evidence: 'Protection from the harsh Mediterranean climate was essential for maintaining crowd morale during all-day events.' },
          { prompt: 'Paragraph B', answer: 'iii', evidence: 'To facilitate the rapid movement of enormous crowds, architects designed a sophisticated network of vaulted corridors and precisely angled staircases.' }
        ]
      }
    }
  },
  2: {
    1: {
      title: '3. The Science of Sleep Cycles',
      paragraphs: [
        ['A', `For centuries, human slumber was mistakenly viewed as a completely passive state, a period where the body and mind simply shut down to rest. However, the invention of the electroencephalogram (EEG) revealed that the sleeping human brain is actually a hub of intense neurological activity. By monitoring electrical impulses, scientists discovered that our nighttime rest is highly structured, composed of distinct oscillating rhythms rather than a uniform blankness.`],
        ['B', `This structured nocturnal activity is divided into two primary categories: Non-REM and REM sleep. Non-REM sleep dominates the first half of the night. Throughout a typical eight-hour period, an individual cycles through four distinct biological stages approximately every ninety minutes. The initial light phases gradually deepen into slow-wave sleep, where the body significantly drops its core temperature and heart rate, entering a profound state of physical restoration and cellular repair that is incredibly difficult to awaken from.`],
        ['C', `Following these deep phases, the brain drastically shifts gears into Rapid Eye Movement (REM) sleep. During REM sleep, the eyes dart rapidly beneath closed eyelids. This specific phase is critically responsible for the consolidation of short-term information into long-term memory. While the muscles remain entirely paralyzed to prevent individuals from physically acting out their vivid dreams, the cerebral cortex burns glucose at a rate comparable to intense daytime concentration, organizing emotional experiences and learned skills.`],
        ['D', `The delicate timing of these internal cycles is governed by a master biological clock located within the hypothalamus. This tiny cluster of cells responds directly to environmental light cues. As daylight fades, the optic nerves signal the pineal gland to release specific hormones, primarily melatonin, which chemically induce drowsiness. Conversely, exposure to bright morning sunlight aggressively suppresses this chemical production, effectively waking the body up and resetting the circadian rhythm for the new day.`],
        ['E', `Unfortunately, modern lifestyles are actively sabotaging this deeply ingrained evolutionary mechanism. Artificial blue light emitted by smartphones and computer screens heavily suppresses melatonin production. Consequently, widespread technological overstimulation has led to a global epidemic of chronic insomnia and fragmented resting patterns. When the brain is denied sufficient slow-wave and REM cycles, individuals experience severe cognitive deficits, mood instability, and weakened immune responses.`],
        ['F', `Medical professionals are increasingly alarmed by the long-term consequences of this systemic deprivation. Prolonged disruption of the natural circadian rhythm is highly correlated with the development of severe metabolic disorders. By prioritizing sleep hygiene and maintaining consistent nighttime routines, individuals can protect their neurological health and drastically reduce their risk of obesity and cardiovascular disease.`]
      ],
      fill: [
        { prompt: 'The use of EEG technology proved that the sleeping ________ remains highly active.', answer: 'brain', evidence: 'However, the invention of the electroencephalogram (EEG) revealed that the sleeping human brain is actually a hub of intense neurological activity.' },
        { prompt: 'A resting person navigates through four distinct biological ________ during a standard night.', answer: 'stages', evidence: 'Throughout a typical eight-hour period, an individual cycles through four distinct biological stages approximately every ninety minutes.' },
        { prompt: 'The REM phase plays a crucial role in transforming recent information into permanent ________.', answer: 'memory', evidence: 'This specific phase is critically responsible for the consolidation of short-term information into long-term memory.' },
        { prompt: 'The fading of natural light triggers the release of sleep-inducing ________.', answer: 'hormones', evidence: 'As daylight fades, the optic nerves signal the pineal gland to release specific hormones, primarily melatonin, which chemically induce drowsiness.' },
        { prompt: 'Chronic disruption of sleep patterns is strongly linked to various physical ________.', answer: 'disorders', evidence: 'Prolonged disruption of the natural circadian rhythm is highly correlated with the development of severe metabolic disorders.' }
      ],
      judgement: [
        { prompt: 'Non-REM sleep dominates the first half of the night in both humans and large mammals.', answer: 'NOT GIVEN', evidence: 'Non-REM sleep dominates the first half of the night.' },
        { prompt: 'During REM sleep, the eyes dart rapidly beneath closed eyelids.', answer: 'TRUE', evidence: 'During REM sleep, the eyes dart rapidly beneath closed eyelids.' },
        { prompt: 'This tiny cluster of cells responds directly to environmental light cues faster than any other organ.', answer: 'NOT GIVEN', evidence: 'This tiny cluster of cells responds directly to environmental light cues.' },
        { prompt: 'Artificial blue light emitted by smartphones and computer screens accelerates melatonin production.', answer: 'FALSE', evidence: 'Artificial blue light emitted by smartphones and computer screens heavily suppresses melatonin production.' }
      ],
      headings: {
        options: ['The technological disruption of natural resting patterns', 'Artificial blue light emitted by smartphones', 'Unveiling the hidden electrical dynamics of slumber', 'The chemical regulation of the circadian rhythm', 'Specific hormones, primarily melatonin', 'The progression through deep physical restoration phases', 'Intense neurological activity', 'Master biological clock located within the hypothalamus'],
        questions: [
          { prompt: 'Paragraph E', answer: 'i', evidence: 'Consequently, widespread technological overstimulation has led to a global epidemic of chronic insomnia and fragmented resting patterns.' },
          { prompt: 'Paragraph A', answer: 'iii', evidence: 'However, the invention of the electroencephalogram (EEG) revealed that the sleeping human brain is actually a hub of intense neurological activity.' },
          { prompt: 'Paragraph D', answer: 'iv', evidence: 'As daylight fades, the optic nerves signal the pineal gland to release specific hormones, primarily melatonin, which chemically induce drowsiness.' },
          { prompt: 'Paragraph B', answer: 'vi', evidence: 'The initial light phases gradually deepen into slow-wave sleep, where the body significantly drops its core temperature and heart rate, entering a profound state of physical restoration and cellular repair that is incredibly difficult to awaken from.' }
        ]
      }
    },
    2: {
      title: '4. The Rosetta Stone Decipherment',
      paragraphs: [
        ['A', `The ability to read the ancient writings of the Pharaohs was completely lost for over a thousand years. In 1799, during Napoleon's military campaign in Egypt, a group of French soldiers accidentally unearthed a large block of granodiorite while reinforcing a ruined fort. The dark stone fragment, heavily inscribed with text, was immediately recognized by commanding officers as an artifact of immense potential significance, eventually making its way into the hands of eager European academics.`],
        ['B', `The crucial feature of the artifact was its unique structural formatting. The heavy slab contained the exact same message written in three different scripts. The top section featured classical Egyptian hieroglyphs, the middle utilized a cursive everyday script called Demotic, and the bottom was a royal decree written in ancient Greek. Because classical Greek was widely understood by 19th-century linguists, the stone provided the first tangible translation key for unlocking the mysterious pictorial language of the ancient Nile valley.`],
        ['C', `Translating the stone, however, proved to be a grueling intellectual marathon rather than a quick sprint. English polymath Thomas Young made the first significant breakthrough in 1814. He deduced that the phonetic oval enclosures, known as cartouches, consistently spelled out the names of foreign leaders, proving the hieroglyphs represented sounds rather than just whole words or esoteric ideas. Despite this, Young ultimately abandoned the project, frustrated by the overwhelming complexity of the shifting grammatical rules.`],
        ['D', `It was a brilliant, obsessive French linguist who finally cracked the complete code. Jean-Francois Champollion heavily utilized his deep knowledge of Coptic, a late descendant of the Egyptian tongue. By rigorously comparing the sounds to the carved symbols, this dedicated scholar published the first comprehensive translation in 1822, permanently breaking the linguistic silence of the ancient monuments. His realization that the system was a complex hybrid of phonetic signs and ideograms completely revolutionized the field of Egyptology.`],
        ['E', `The impact of this academic victory cannot be overstated. Prior to the translation, historians possessed only heavily biased Greek and Roman accounts of Egyptian culture. The ability to read original texts allowed modern researchers to understand the religion, poetry, and daily life of the ancient civilization directly from their own primary sources. Myths were clarified, historical timelines were corrected, and the true immense scale of Egyptian bureaucratic achievement was finally recognized.`],
        ['F', `Today, the stone resides under heavy glass in the British Museum, having been surrendered by the French following their military defeat. It remains one of the most visited artifacts in the world, symbolizing the triumph of human intellect and our enduring desire to connect with forgotten eras of human history.`]
      ],
      fill: [
        { prompt: 'The crucial artifact was accidentally discovered by French ________ working on military fortifications.', answer: 'soldiers', evidence: `In 1799, during Napoleon's military campaign in Egypt, a group of French soldiers accidentally unearthed a large block of granodiorite while reinforcing a ruined fort.` },
        { prompt: 'The lowest section of the stone displayed a formal ________ inscribed in ancient Greek.', answer: 'decree', evidence: 'The top section featured classical Egyptian hieroglyphs, the middle utilized a cursive everyday script called Demotic, and the bottom was a royal decree written in ancient Greek.' },
        { prompt: 'Young realized the carved shapes inside cartouches represented the sounds of foreign ________.', answer: 'leaders', evidence: 'He deduced that the phonetic oval enclosures, known as cartouches, consistently spelled out the names of foreign leaders, proving the hieroglyphs represented sounds rather than just whole words or esoteric ideas.' },
        { prompt: 'In 1822, a French ________ successfully published the full methodology for reading the text.', answer: 'scholar', evidence: 'By rigorously comparing the sounds to the carved symbols, this dedicated scholar published the first comprehensive translation in 1822, permanently breaking the linguistic silence of the ancient monuments.' },
        { prompt: 'The translation gave historians a direct window into the daily life of the ancient ________.', answer: 'civilization', evidence: 'The ability to read original texts allowed modern researchers to understand the religion, poetry, and daily life of the ancient civilization directly from their own primary sources.' }
      ],
      judgement: [
        { prompt: 'The heavy slab contained the exact same message written in three different scripts flawlessly.', answer: 'NOT GIVEN', evidence: 'The heavy slab contained the exact same message written in three different scripts.' },
        { prompt: 'English polymath Thomas Young made the first significant breakthrough in 1814 with the help of French academics.', answer: 'NOT GIVEN', evidence: 'English polymath Thomas Young made the first significant breakthrough in 1814.' },
        { prompt: 'Jean-Francois Champollion heavily utilized his deep knowledge of Latin to decode the texts.', answer: 'FALSE', evidence: 'Jean-Francois Champollion heavily utilized his deep knowledge of Coptic, a late descendant of the Egyptian tongue.' },
        { prompt: 'Prior to the translation, historians possessed only heavily biased Greek and Roman accounts of Egyptian culture.', answer: 'TRUE', evidence: 'Prior to the translation, historians possessed only heavily biased Greek and Roman accounts of Egyptian culture.' }
      ],
      headings: {
        options: ['The unexpected unearthing of a crucial linguistic artifact', 'The heavy slab contained the exact same message', 'Accessing primary sources of a lost culture', 'Group of French soldiers accidentally unearthed', 'The structural formatting providing a translation key', 'Published the first comprehensive translation', 'The definitive methodological breakthrough', 'Heavily biased Greek and Roman accounts'],
        questions: [
          { prompt: 'Paragraph E', answer: 'iii', evidence: 'The ability to read original texts allowed modern researchers to understand the religion, poetry, and daily life of the ancient civilization directly from their own primary sources.' },
          { prompt: 'Paragraph A', answer: 'i', evidence: `In 1799, during Napoleon's military campaign in Egypt, a group of French soldiers accidentally unearthed a large block of granodiorite while reinforcing a ruined fort.` },
          { prompt: 'Paragraph D', answer: 'vii', evidence: 'By rigorously comparing the sounds to the carved symbols, this dedicated scholar published the first comprehensive translation in 1822, permanently breaking the linguistic silence of the ancient monuments.' },
          { prompt: 'Paragraph B', answer: 'v', evidence: 'The crucial feature of the artifact was its unique structural formatting.' }
        ]
      }
    }
  },
  3: {
    1: {
      title: '5. Deep Sea Exploration Technologies',
      paragraphs: [
        ['A', `The deepest trenches of the world's oceans remain one of the most hostile and unexplored frontiers on the planet. For decades, scientists were physically barred from entering the abyssal zones because the crushing hydrostatic pressure would instantly implode any standard diving equipment. At depths exceeding 20,000 feet, the weight of the water column above exerts forces capable of buckling thick steel, demanding a completely new paradigm in nautical engineering to safely transport humans into the abyss.`],
        ['B', `The breakthrough arrived with the development of spherical titanium pressure hulls. Engineers realized that a sphere evenly distributes external physical stress. By encasing pilots inside a thick titanium ball, specially designed deep-sea submarines could successfully dive to the bottom of the Mariana Trench. These pioneering submersibles, equipped with heavy acrylic viewports and robotic manipulator arms, finally allowed researchers to conduct direct visual observations of the seabed for extended periods.`],
        ['C', `The discoveries made by these submersibles completely overturned existing biological paradigms. Biologists previously assumed that all life ultimately relied on solar energy. However, researchers discovered thriving ecosystems clustered around scalding hydrothermal vents, completely detached from the sun's influence. Here, strange tube worms and blind crabs survived via chemosynthesis, metabolizing toxic sulfur compounds emitted from the Earth's crust, proving that life could flourish in environments entirely devoid of light.`],
        ['D', `Unmanned technology is now rapidly replacing human-occupied vehicles. Remotely Operated Vehicles (ROVs) are connected to surface ships via long fiber-optic tethers. These nimble robotic drones can remain submerged indefinitely, capturing high-definition video and collecting fragile physical samples without putting human lives at risk. The continuous stream of data provided by ROVs has exponentially increased our catalog of deep-sea marine species in a remarkably short timeframe.`],
        ['E', `As our mapping capabilities improve, commercial interests are beginning to look toward the ocean floor. Mining corporations are designing massive aquatic bulldozers to harvest potato-sized nodules. These metallic rocks, scattered across the abyssal plains, are incredibly rich in rare earth minerals essential for manufacturing modern smartphone batteries and electric vehicle engines. The impending rush to extract these valuable resources has sparked intense international debate regarding the jurisdiction of international waters.`],
        ['F', `Environmentalists warn that deep-sea mining could cause irreversible ecological devastation. Because deep ocean organisms grow and reproduce incredibly slowly, industrial disturbances could permanently destroy habitats, highlighting the urgent need for strict international conservation treaties. Balancing the transition to green energy technologies with the protection of these pristine underwater biomes represents one of the greatest environmental challenges of the 21st century.`]
      ],
      fill: [
        { prompt: 'Early attempts to reach the ocean floor failed due to the extreme physical ________.', answer: 'pressure', evidence: 'For decades, scientists were physically barred from entering the abyssal zones because the crushing hydrostatic pressure would instantly implode any standard diving equipment.' },
        { prompt: 'The use of spherical titanium cabins allowed deep-sea ________ to reach the deepest trenches.', answer: 'submarines', evidence: 'By encasing pilots inside a thick titanium ball, specially designed deep-sea submarines could successfully dive to the bottom of the Mariana Trench.' },
        { prompt: 'Scientists found vibrant biological ________ existing entirely without sunlight.', answer: 'ecosystems', evidence: `However, researchers discovered thriving ecosystems clustered around scalding hydrothermal vents, completely detached from the sun's influence.` },
        { prompt: 'Tethered robotic drones are highly effective at retrieving delicate physical ________ from the seabed.', answer: 'samples', evidence: 'These nimble robotic drones can remain submerged indefinitely, capturing high-definition video and collecting fragile physical samples without putting human lives at risk.' },
        { prompt: 'The slow growth rates of deep-sea life make international ________ agreements incredibly necessary.', answer: 'conservation', evidence: 'Because deep ocean organisms grow and reproduce incredibly slowly, industrial disturbances could permanently destroy habitats, highlighting the urgent need for strict international conservation treaties.' }
      ],
      judgement: [
        { prompt: 'Engineers realized that a sphere evenly distributes external physical stress better than a cube.', answer: 'NOT GIVEN', evidence: 'Engineers realized that a sphere evenly distributes external physical stress.' },
        { prompt: 'Biologists previously assumed that all life ultimately relied on solar energy.', answer: 'TRUE', evidence: 'Biologists previously assumed that all life ultimately relied on solar energy.' },
        { prompt: 'Remotely Operated Vehicles (ROVs) are connected to surface ships via thick steel chains.', answer: 'FALSE', evidence: 'Remotely Operated Vehicles (ROVs) are connected to surface ships via long fiber-optic tethers.' },
        { prompt: 'Mining corporations are designing massive aquatic bulldozers to harvest potato-sized nodules rapidly.', answer: 'NOT GIVEN', evidence: 'Mining corporations are designing massive aquatic bulldozers to harvest potato-sized nodules.' }
      ],
      headings: {
        options: ['Crushing hydrostatic pressure', 'The impending commercial extraction of seabed resources', 'The transition to risk-free robotic data collection', 'Mining corporations are designing massive aquatic bulldozers', 'The engineering barriers to abyssal entry', 'Remotely Operated Vehicles (ROVs)', 'The development of spherical titanium pressure hulls', 'The implementation of structurally resilient manned vessels'],
        questions: [
          { prompt: 'Paragraph E', answer: 'ii', evidence: 'As our mapping capabilities improve, commercial interests are beginning to look toward the ocean floor.' },
          { prompt: 'Paragraph A', answer: 'v', evidence: 'For decades, scientists were physically barred from entering the abyssal zones because the crushing hydrostatic pressure would instantly implode any standard diving equipment.' },
          { prompt: 'Paragraph D', answer: 'iii', evidence: 'These nimble robotic drones can remain submerged indefinitely, capturing high-definition video and collecting fragile physical samples without putting human lives at risk.' },
          { prompt: 'Paragraph B', answer: 'viii', evidence: 'By encasing pilots inside a thick titanium ball, specially designed deep-sea submarines could successfully dive to the bottom of the Mariana Trench.' }
        ]
      }
    },
    2: {
      title: '6. The Migration of the Monarch Butterfly',
      paragraphs: [
        ['A', `The animal kingdom is filled with spectacular seasonal movements, but few rival the sheer improbability of the monarch butterfly's annual migration. Every autumn, millions of these fragile, orange-and-black insects embark on an epic, three-thousand-mile journey from the cooling forests of Canada to the remote volcanic mountains of central Mexico. Unlike migratory birds, which learn the route from older flock members, a migrating monarch has never made the journey before, relying entirely on innate genetic programming to navigate across the North American continent.`],
        ['B', `The biological mechanics of this journey are highly unusual. The migration cycle spans an entire calendar year. Because a typical adult butterfly only lives for a few weeks, it actually takes four successive generations of monarchs to complete a single, full round-trip circuit. The first three generations travel slowly northward during the spring and summer, breeding and dying along the way. However, the unique fourth generation, born in late summer, enters a specialized biological state that suspends aging, allowing them to live up to eight months to complete the massive southward flight.`],
        ['C', `The survival of the entire species is intrinsically linked to a single botanical resource. Monarch caterpillars are obligate feeders, meaning they possess a highly restricted diet. Female butterflies will exclusively lay their eggs on the leaves of the toxic milkweed plant, as the caterpillars have evolved to safely ingest and store the plant's harmful chemical compounds. This dietary exclusivity is a double-edged sword; while it makes the insects poisonous to consume, it completely tethers their population stability to the geographic availability of this specific weed.`],
        ['D', `By storing the milkweed's toxins within their brightly colored bodies, monarchs secure a vital layer of biological protection. The vibrant orange wings act as a stark visual warning system. Avian predators quickly learn that eating the bright insects causes severe nausea, leading them to actively avoid hunting the butterflies in the future. This evolutionary strategy, known as aposematism, allows the massive swarms to travel thousands of miles in broad daylight without being decimated by hungry birds.`],
        ['E', `Despite their ingenious biological defenses, the monarch population has plummeted in recent decades. Agricultural herbicides have aggressively eradicated milkweed plants across the Midwestern United States. Simultaneously, illegal logging in Mexico is rapidly destroying the specific microclimates where the butterflies hibernate, exposing the resting swarms to freezing winter temperatures. Conservationists argue that without immediate cross-border political cooperation, the migration could collapse entirely within a few generations.`],
        ['F', `In response to this ecological crisis, widespread grassroots initiatives have emerged. Citizens across North America are actively planting native vegetation in urban gardens to combat the loss of agricultural habitat and shifting climate conditions. These small, decentralized waystations provide essential nectar and breeding grounds, attempting to stitch back together the fragmented path of one of nature's most remarkable journeys.`]
      ],
      fill: [
        { prompt: 'Millions of insects undertake a massive ________ from Canada to Mexico every autumn.', answer: 'journey', evidence: 'Every autumn, millions of these fragile, orange-and-black insects embark on an epic, three-thousand-mile journey from the cooling forests of Canada to the remote volcanic mountains of central Mexico.' },
        { prompt: 'A complete migratory loop requires the lifespans of four distinct ________ to finish.', answer: 'generations', evidence: 'Because a typical adult butterfly only lives for a few weeks, it actually takes four successive generations of monarchs to complete a single, full round-trip circuit.' },
        { prompt: 'The insects require the toxic ________ plant to reproduce and survive.', answer: 'milkweed', evidence: 'Female butterflies will exclusively lay their eggs on the leaves of the toxic milkweed plant, as the caterpillars have evolved to safely ingest and store the plant\'s harmful chemical compounds.' },
        { prompt: 'The ingestion of toxins makes the butterflies highly unappealing to natural ________.', answer: 'predators', evidence: 'Avian predators quickly learn that eating the bright insects causes severe nausea, leading them to actively avoid hunting the butterflies in the future.' },
        { prompt: 'Urban gardens are being planted to offset habitat destruction caused by extreme ________ changes.', answer: 'climate', evidence: 'Citizens across North America are actively planting native vegetation in urban gardens to combat the loss of agricultural habitat and shifting climate conditions.' }
      ],
      judgement: [
        { prompt: 'The migration cycle spans an entire calendar year seamlessly.', answer: 'NOT GIVEN', evidence: 'The migration cycle spans an entire calendar year.' },
        { prompt: 'Monarch caterpillars are obligate feeders, meaning they possess a highly restricted diet.', answer: 'TRUE', evidence: 'Monarch caterpillars are obligate feeders, meaning they possess a highly restricted diet.' },
        { prompt: 'The vibrant orange wings act as a stark visual warning system to other butterfly species.', answer: 'NOT GIVEN', evidence: 'The vibrant orange wings act as a stark visual warning system.' },
        { prompt: 'Agricultural herbicides have actually increased the growth of milkweed plants across the Midwestern United States.', answer: 'FALSE', evidence: 'Agricultural herbicides have aggressively eradicated milkweed plants across the Midwestern United States.' }
      ],
      headings: {
        options: ['The multi-generational mechanics of the travel cycle', 'The migration cycle spans an entire calendar year', 'Visual signaling as a protective evolutionary tactic', 'The incredible innate navigation of fragile insects', 'Vibrant orange wings act as a stark visual warning', 'Human activities threatening hibernation and breeding', 'Illegal logging in Mexico is rapidly destroying', 'Three-thousand-mile journey from Canada'],
        questions: [
          { prompt: 'Paragraph E', answer: 'vi', evidence: 'Agricultural herbicides have aggressively eradicated milkweed plants across the Midwestern United States.' },
          { prompt: 'Paragraph A', answer: 'iv', evidence: 'Unlike migratory birds, which learn the route from older flock members, a migrating monarch has never made the journey before, relying entirely on innate genetic programming to navigate across the North American continent.' },
          { prompt: 'Paragraph D', answer: 'iii', evidence: 'The vibrant orange wings act as a stark visual warning system.' },
          { prompt: 'Paragraph B', answer: 'i', evidence: 'Because a typical adult butterfly only lives for a few weeks, it actually takes four successive generations of monarchs to complete a single, full round-trip circuit.' }
        ]
      }
    }
  },
  4: {
    1: {
      title: '7. The Invention of Photography',
      paragraphs: [
        ['A', `For millennia, capturing the precise likeness of the physical world required the skilled hand of a painter or sculptor. The desire to automate this process culminated in the early 19th century with the invention of the camera obscura, a simple dark box that projected an inverted image through a pinhole. However, while artists frequently used this optical trick as a tracing aid, the projected image was entirely fleeting; once the light source shifted, the picture vanished instantly, leaving early inventors desperate to find a way to make the image permanent.`],
        ['B', `The crucial breakthrough required bridging the gap between optical physics and chemical reactivity. In 1826, French inventor Joseph Nicephore Niepce successfully captured the first permanent photograph. By coating a pewter plate with bitumen--a light-sensitive asphalt--and exposing it to the sun for eight hours, he recorded a blurry view from his laboratory window, utilizing raw chemicals to fix the transient light. While incredibly rudimentary, Niepce had fundamentally proven that light could be forced to draw its own picture.`],
        ['C', `The technology rapidly accelerated through the collaborative efforts of Louis Daguerre. Daguerre discovered that exposing silver-plated copper to iodine vapor created a highly reactive surface. This new method, known as the daguerreotype, slashed exposure times from hours to mere minutes, suddenly making incredibly detailed, lifelike portraits practically available to the burgeoning middle class. The immediate popularity of these shimmering, one-of-a-kind images sparked a global sensation, democratizing visual history for the first time.`],
        ['D', `However, the daguerreotype had a severe limitation: it could not be easily duplicated. English scientist William Henry Fox Talbot solved this by inventing the calotype process. Talbot created a translucent paper negative from which an infinite number of positive prints could be made, heavily influencing the future trajectory of mass media and early photo journalism. This negative-positive paradigm became the absolute foundation of all analog photography for the next century and a half.`],
        ['E', `As exposure times shrank to fractions of a second, the camera began to alter human perception itself. In the 1870s, Eadweard Muybridge used a battery of cameras to capture a galloping horse. His sequential images proved that all four of the animal's hooves leave the ground simultaneously, revealing high-speed biomechanical truths that were entirely invisible to the naked human eye. Photography transitioned from a static memorial tool into an active scientific instrument.`],
        ['F', `The subsequent introduction of flexible celluloid film by George Eastman finally placed the technology into the hands of amateurs. By simplifying the complex darkroom chemistry into a portable cartridge, the Kodak company initiated a new visual era where everyday citizens could instantly document their own lives, forever changing how humanity records its memories.`]
      ],
      fill: [
        { prompt: 'Early artists used a dark box known as a ________ obscura to help trace projections.', answer: 'camera', evidence: 'The desire to automate this process culminated in the early 19th century with the invention of the camera obscura, a simple dark box that projected an inverted image through a pinhole.' },
        { prompt: 'Niepce succeeded in making the first lasting image by using light-sensitive ________ on a metal plate.', answer: 'chemicals', evidence: 'By coating a pewter plate with bitumen--a light-sensitive asphalt--and exposing it to the sun for eight hours, he recorded a blurry view from his laboratory window, utilizing raw chemicals to fix the transient light.' },
        { prompt: 'Daguerre\'s faster exposure method allowed regular middle-class people to commission personal ________.', answer: 'portraits', evidence: 'This new method, known as the daguerreotype, slashed exposure times from hours to mere minutes, suddenly making incredibly detailed, lifelike portraits practically available to the burgeoning middle class.' },
        { prompt: 'Talbot\'s reproducible paper negative system was vital for the development of printed ________.', answer: 'journalism', evidence: 'Talbot created a translucent paper negative from which an infinite number of positive prints could be made, heavily influencing the future trajectory of mass media and early photo journalism.' },
        { prompt: 'Eastman\'s simplified roll film ushered in a modern ________ of casual, amateur documentation.', answer: 'era', evidence: 'By simplifying the complex darkroom chemistry into a portable cartridge, the Kodak company initiated a new visual era where everyday citizens could instantly document their own lives, forever changing how humanity records its memories.' }
      ],
      judgement: [
        { prompt: 'In 1826, French inventor Joseph Nicephore Niepce successfully captured the first permanent photograph quickly.', answer: 'NOT GIVEN', evidence: 'In 1826, French inventor Joseph Nicephore Niepce successfully captured the first permanent photograph.' },
        { prompt: 'Daguerre discovered that exposing silver-plated copper to iodine vapor created an entirely inert, unreactive surface.', answer: 'FALSE', evidence: 'Daguerre discovered that exposing silver-plated copper to iodine vapor created a highly reactive surface.' },
        { prompt: 'English scientist William Henry Fox Talbot solved this by inventing the calotype process without help.', answer: 'NOT GIVEN', evidence: 'English scientist William Henry Fox Talbot solved this by inventing the calotype process.' },
        { prompt: 'In the 1870s, Eadweard Muybridge used a battery of cameras to capture a galloping horse.', answer: 'TRUE', evidence: 'In the 1870s, Eadweard Muybridge used a battery of cameras to capture a galloping horse.' }
      ],
      headings: {
        options: ['Eadweard Muybridge used a battery of cameras', 'The early optical pursuit of automated image tracing', 'A blurry view from his laboratory window', 'The establishment of reproducible mass printing', 'Expanding human vision through high-speed capture', 'Translucent paper negative', 'Exposing a pewter plate with bitumen', 'The foundational combination of optics and material reactivity'],
        questions: [
          { prompt: 'Paragraph E', answer: 'v', evidence: 'His sequential images proved that all four of the animal\'s hooves leave the ground simultaneously, revealing high-speed biomechanical truths that were entirely invisible to the naked human eye.' },
          { prompt: 'Paragraph A', answer: 'ii', evidence: 'The desire to automate this process culminated in the early 19th century with the invention of the camera obscura, a simple dark box that projected an inverted image through a pinhole.' },
          { prompt: 'Paragraph D', answer: 'iv', evidence: 'Talbot created a translucent paper negative from which an infinite number of positive prints could be made, heavily influencing the future trajectory of mass media and early photo journalism.' },
          { prompt: 'Paragraph B', answer: 'viii', evidence: 'The crucial breakthrough required bridging the gap between optical physics and chemical reactivity.' }
        ]
      }
    },
    2: {
      title: '8. The Science of Earthquakes',
      paragraphs: [
        ['A', `For millennia, the sudden, violent shaking of the ground was attributed to the wrath of displeased deities or mythical beasts moving beneath the soil. Modern seismology, however, explains these terrifying events through plate tectonics, revealing that the Earth's solid outer crust is actually fractured into massive, continuously shifting puzzle pieces. Floating upon a layer of semi-liquid molten rock, these colossal continental and oceanic plates grind against one another, creating immense geological stress at their invisible borders.`],
        ['B', `The mechanics of a tremor are fundamentally driven by the buildup and sudden release of kinetic energy. When rough plate edges snag against each other, they lock into place. Despite being locked together, the subterranean forces keep pushing, causing massive friction to build over centuries until the rock violently snaps, releasing stored energy outward. The precise subterranean location where this rock fractures is known as the hypocenter, while the corresponding point directly above on the surface is called the epicenter.`],
        ['C', `When the rock breaks, the released energy travels outward in the form of powerful seismic ripples. Primary (P) waves are the fastest, compressing and expanding the ground like an accordion. Secondary (S) waves arrive shortly after, violently shifting the ground up and down, causing the majority of the severe structural damage observed during major quakes. Sensitive seismographs detect the time delay between these specific waves, allowing scientists to triangulate exactly where the fracture occurred.`],
        ['D', `The sheer destructive capability of these events heavily depends on the local geography. If an earthquake occurs beneath the ocean floor, it can displace massive columns of water. This sudden aquatic displacement generates devastating tsunamis capable of obliterating coastal infrastructure hundreds of miles away from the initial epicenter. Furthermore, cities built on loose, water-saturated soils face the terrifying threat of liquefaction, where the violent shaking temporarily turns solid ground into quicksand, swallowing entire buildings whole.`],
        ['E', `Mitigating this immense threat has become a primary focus for modern civil engineers. Architects in highly active zones now design skyscrapers with deep subterranean shock absorbers. These massive rubber and steel base isolators decouple the building from the violently shaking earth, allowing the structure to safely sway rather than rigidly cracking and collapsing. Strict building codes in countries like Japan and Chile have proven that proactive engineering drastically reduces human casualties during severe seismic events.`],
        ['F', `Despite incredible advancements in structural engineering, the ultimate goal of seismology remains stubbornly out of reach. Currently, scientists have absolutely no reliable method for short-term prediction to warn citizens of an impending tremor. While geologists can calculate long-term probabilities based on historical fault lines, the exact day and hour a locked fault will finally snap remains a terrifying geological mystery.`]
      ],
      fill: [
        { prompt: 'The theory of plate tectonics shows that the Earth\'s rigid ________ is broken into moving sections.', answer: 'crust', evidence: 'Modern seismology, however, explains these terrifying events through plate tectonics, revealing that the Earth\'s solid outer crust is actually fractured into massive, continuously shifting puzzle pieces.' },
        { prompt: 'An earthquake is triggered when centuries of accumulated ________ forces the rock to snap.', answer: 'friction', evidence: 'Despite being locked together, the subterranean forces keep pushing, causing massive friction to build over centuries until the rock violently snaps, releasing stored energy outward.' },
        { prompt: 'The severe vertical shifting caused by secondary ________ is responsible for most structural destruction.', answer: 'waves', evidence: 'Secondary (S) waves arrive shortly after, violently shifting the ground up and down, causing the majority of the severe structural damage observed during major quakes.' },
        { prompt: 'Tsunamis generated by underwater quakes can easily destroy coastal ________ far from the source.', answer: 'infrastructure', evidence: 'This sudden aquatic displacement generates devastating tsunamis capable of obliterating coastal infrastructure hundreds of miles away from the initial epicenter.' },
        { prompt: 'The accurate, short-term ________ of an earthquake remains impossible for modern scientists.', answer: 'prediction', evidence: 'Currently, scientists have absolutely no reliable method for short-term prediction to warn citizens of an impending tremor.' }
      ],
      judgement: [
        { prompt: 'When rough plate edges snag against each other, they lock into place temporarily.', answer: 'NOT GIVEN', evidence: 'When rough plate edges snag against each other, they lock into place.' },
        { prompt: 'Primary (P) waves are the fastest, compressing and expanding the ground like an accordion.', answer: 'TRUE', evidence: 'Primary (P) waves are the fastest, compressing and expanding the ground like an accordion.' },
        { prompt: 'If an earthquake occurs beneath the ocean floor, it usually displaces small amounts of water.', answer: 'FALSE', evidence: 'If an earthquake occurs beneath the ocean floor, it can displace massive columns of water.' },
        { prompt: 'Architects in highly active zones now design skyscrapers with deep subterranean shock absorbers frequently.', answer: 'NOT GIVEN', evidence: 'Architects in highly active zones now design skyscrapers with deep subterranean shock absorbers.' }
      ],
      headings: {
        options: [`The fragmentation of the Earth's outer layer`, 'The accumulation and violent discharge of tectonic stress', 'Massive rubber and steel base isolators', `The Earth's solid outer crust is actually fractured`, 'Cities built on loose, water-saturated soils', 'Secondary (S) waves arrive shortly after', 'Implementing architectural buffers to minimize collapse', 'The devastating secondary effects of aquatic and soil displacement'],
        questions: [
          { prompt: 'Paragraph E', answer: 'vii', evidence: 'These massive rubber and steel base isolators decouple the building from the violently shaking earth, allowing the structure to safely sway rather than rigidly cracking and collapsing.' },
          { prompt: 'Paragraph A', answer: 'i', evidence: `Modern seismology, however, explains these terrifying events through plate tectonics, revealing that the Earth's solid outer crust is actually fractured into massive, continuously shifting puzzle pieces.` },
          { prompt: 'Paragraph D', answer: 'viii', evidence: 'This sudden aquatic displacement generates devastating tsunamis capable of obliterating coastal infrastructure hundreds of miles away from the initial epicenter.' },
          { prompt: 'Paragraph B', answer: 'ii', evidence: 'Despite being locked together, the subterranean forces keep pushing, causing massive friction to build over centuries until the rock violently snaps, releasing stored energy outward.' }
        ]
      }
    }
  },
  5: {
    1: {
      title: '9. The Rise of Artificial Intelligence',
      paragraphs: [
        ['A', `The concept of creating thinking machines has fascinated philosophers and inventors for centuries, long before the invention of the microchip. However, the true birth of modern artificial intelligence occurred in the mid-20th century, driven by the rapid development of complex mathematical algorithms capable of processing massive datasets. Early computer scientists envisioned a future where giant mainframes could mimic human reasoning, fundamentally shifting technology from mere calculators to systems capable of autonomous decision-making.`],
        ['B', `Initially, researchers focused entirely on symbolic AI, a highly rigid programming approach. These early systems relied on massive databases of hard-coded rules. By feeding a computer thousands of specific "if-then" statements, programmers successfully taught machines to play chess and solve basic algebra using sheer computational logic. While impressive in strictly controlled environments, this rule-based approach failed miserably when attempting to navigate the messy, unpredictable nuances of real-world human language and visual recognition.`],
        ['C', `The monumental shift toward contemporary AI occurred with the widespread adoption of machine learning. Instead of writing explicit rules, engineers began designing artificial neural networks inspired by the human brain. By passing millions of labeled images through these interconnected digital nodes, the software essentially trained itself to independently recognize patterns without direct human instruction. This paradigm shift allowed software to master highly subjective tasks, such as translating conversational speech and accurately diagnosing medical X-rays.`],
        ['D', `As these self-learning models become increasingly sophisticated, their integration into the commercial sector has been swift and highly disruptive. Corporate industries are rapidly deploying AI to optimize logistics and customer service. However, this aggressive push for corporate automation has sparked severe anxieties regarding widespread workforce displacement, as intelligent software threatens to replace not just manual labor, but highly skilled administrative and creative professions. Economists warn that society must aggressively adapt educational systems to prepare for a rapidly shifting employment landscape.`],
        ['E', `Beyond economic concerns, the rapid proliferation of artificial intelligence presents unprecedented philosophical challenges. Advanced models can now generate hyper-realistic fake videos and perfectly mimic human writing. This capacity for digital deception necessitates the immediate development of robust technological ethics to prevent the mass spread of political misinformation and protect personal privacy. Regulators are struggling to draft legislation that can keep pace with an intelligence that evolves daily.`],
        ['F', `Ultimately, the future trajectory of intelligent machines depends entirely on the guardrails humanity chooses to implement today. If developed with transparency and a strict adherence to human-centric principles, AI possesses the unparalleled potential to solve complex global crises, from accelerating medical discoveries to optimizing sustainable energy grids.`]
      ],
      fill: [
        { prompt: 'Modern AI was heavily reliant on the creation of complex mathematical ________.', answer: 'algorithms', evidence: 'However, the true birth of modern artificial intelligence occurred in the mid-20th century, driven by the rapid development of complex mathematical algorithms capable of processing massive datasets.' },
        { prompt: 'Early programs utilized strict computational ________ to play board games like chess.', answer: 'logic', evidence: 'By feeding a computer thousands of specific "if-then" statements, programmers successfully taught machines to play chess and solve basic algebra using sheer computational logic.' },
        { prompt: 'Modern systems utilize artificial ________ networks modeled after human brain structures.', answer: 'neural', evidence: 'Instead of writing explicit rules, engineers began designing artificial neural networks inspired by the human brain.' },
        { prompt: 'The rapid corporate push for ________ has created fears of massive job losses.', answer: 'automation', evidence: 'However, this aggressive push for corporate automation has sparked severe anxieties regarding widespread workforce displacement, as intelligent software threatens to replace not just manual labor, but highly skilled administrative and creative professions.' },
        { prompt: 'Society must implement strict technological ________ to prevent the spread of deceptive media.', answer: 'ethics', evidence: 'This capacity for digital deception necessitates the immediate development of robust technological ethics to prevent the mass spread of political misinformation and protect personal privacy.' }
      ],
      judgement: [
        { prompt: 'These early systems relied on massive databases of hard-coded rules exclusively.', answer: 'NOT GIVEN', evidence: 'These early systems relied on massive databases of hard-coded rules.' },
        { prompt: 'Instead of writing explicit rules, engineers began designing artificial neural networks modeled after birds.', answer: 'FALSE', evidence: 'Instead of writing explicit rules, engineers began designing artificial neural networks inspired by the human brain.' },
        { prompt: 'Corporate industries are rapidly deploying AI to optimize logistics and customer service globally.', answer: 'NOT GIVEN', evidence: 'Corporate industries are rapidly deploying AI to optimize logistics and customer service.' },
        { prompt: 'Advanced models can now generate hyper-realistic fake videos and perfectly mimic human writing.', answer: 'TRUE', evidence: 'Advanced models can now generate hyper-realistic fake videos and perfectly mimic human writing.' }
      ],
      headings: {
        options: ['Early systems relied on massive databases', 'The foundational shift from calculators to autonomous logic', 'The limitations of strict rule-based programming paradigms', 'Artificial neural networks inspired by the human brain', 'The moral dilemmas posed by hyper-realistic deception', 'Hyper-realistic fake videos and perfectly mimic human writing', 'The threat to employment caused by intelligent systems', 'Aggressive push for corporate automation'],
        questions: [
          { prompt: 'Paragraph E', answer: 'v', evidence: 'Advanced models can now generate hyper-realistic fake videos and perfectly mimic human writing.' },
          { prompt: 'Paragraph A', answer: 'ii', evidence: 'Early computer scientists envisioned a future where giant mainframes could mimic human reasoning, fundamentally shifting technology from mere calculators to systems capable of autonomous decision-making.' },
          { prompt: 'Paragraph D', answer: 'vii', evidence: 'However, this aggressive push for corporate automation has sparked severe anxieties regarding widespread workforce displacement, as intelligent software threatens to replace not just manual labor, but highly skilled administrative and creative professions.' },
          { prompt: 'Paragraph B', answer: 'iii', evidence: 'While impressive in strictly controlled environments, this rule-based approach failed miserably when attempting to navigate the messy, unpredictable nuances of real-world human language and visual recognition.' }
        ]
      }
    },
    2: {
      title: '10. The Global History of Chocolate',
      paragraphs: [
        ['A', `The journey of chocolate from a bitter ancient beverage to a ubiquitous sweet treat spans thousands of years and multiple continents. Deep within the Mesoamerican rainforests, the ancient Maya and Aztec civilizations revered the cacao tree, utilizing its fermented seeds as a literal form of currency to pay regional taxes. Instead of eating it, they crushed the highly valued beans and mixed them with chili peppers and water to create a frothy, incredibly bitter drink that was strictly reserved for religious rituals and fierce warriors.`],
        ['B', `The arrival of Spanish conquistadors in the 16th century drastically altered the trajectory of the cacao bean. Spanish explorers brought the exotic recipe back to European shores. Appalled by its intense bitterness, the Spanish heavily modified the drink by removing the chili and adding expensive cane sugar and vanilla, transforming it into an indulgent luxury reserved exclusively for the European nobility. For centuries, drinking spiced chocolate remained a heavily guarded secret of the incredibly wealthy Spanish courts.`],
        ['C', `The industrial revolution forcefully dragged chocolate out of the elite palaces and into the hands of the working class. In 1828, a Dutch chemist invented the cocoa press, a machine capable of squeezing out the heavy fat from the roasted beans. This crucial mechanical invention allowed large factories to affordably mass-produce solid, smooth chocolate bars for the very first time. The sudden availability of cheap, sweet chocolate bars sparked a massive global craze, completely shifting the commodity from a liquid luxury to an everyday solid snack.`],
        ['D', `As massive confectionery empires emerged in Britain and Switzerland, selling the product became as important as making it. Corporations began packaging their sweets in highly decorative boxes. By associating their products with romance and holiday celebrations, brilliant corporate marketing campaigns successfully permanently embedded chocolate into global cultural traditions like Valentine's Day. These psychological advertising strategies turned a simple candy into a globally recognized symbol of affection and indulgence.`],
        ['E', `However, the massive global demand for cheap cocoa hides a dark modern reality. West African farmers struggle to maintain profitable yields. The aggressive expansion of cacao plantations continues to drive severe tropical deforestation and relies heavily on unregulated child labor to keep global prices artificially low. While the finished product represents luxury and joy, the agricultural supply chain remains deeply troubled by ongoing human rights violations and environmental degradation.`],
        ['F', `In response to these hidden costs, a powerful movement toward ethical consumption is attempting to reform the industry. Organizations are actively promoting fair trade certifications to ensure strict ecological sustainability and guarantee a living wage for rural farming communities. By purchasing ethically sourced bars, modern consumers are slowly forcing massive corporations to clean up their supply chains.`]
      ],
      fill: [
        { prompt: 'Mesoamerican civilizations used the valuable seeds as a physical ________ to settle debts.', answer: 'currency', evidence: 'Deep within the Mesoamerican rainforests, the ancient Maya and Aztec civilizations revered the cacao tree, utilizing its fermented seeds as a literal form of currency to pay regional taxes.' },
        { prompt: 'The sweetened version of the drink was initially restricted to the European ________.', answer: 'nobility', evidence: 'Appalled by its intense bitterness, the Spanish heavily modified the drink by removing the chili and adding expensive cane sugar and vanilla, transforming it into an indulgent luxury reserved exclusively for the European nobility.' },
        { prompt: 'Mechanical presses allowed large ________ to rapidly produce cheap solid bars.', answer: 'factories', evidence: 'This crucial mechanical invention allowed large factories to affordably mass-produce solid, smooth chocolate bars for the very first time.' },
        { prompt: 'Clever corporate ________ linked the eating of sweets to romantic holidays.', answer: 'marketing', evidence: `By associating their products with romance and holiday celebrations, brilliant corporate marketing campaigns successfully permanently embedded chocolate into global cultural traditions like Valentine's Day.` },
        { prompt: 'Fair trade groups advocate for environmental ________ and better wages for workers.', answer: 'sustainability', evidence: 'Organizations are actively promoting fair trade certifications to ensure strict ecological sustainability and guarantee a living wage for rural farming communities.' }
      ],
      judgement: [
        { prompt: 'Spanish explorers brought the exotic recipe back to European shores in secret.', answer: 'NOT GIVEN', evidence: 'Spanish explorers brought the exotic recipe back to European shores.' },
        { prompt: 'In 1828, a Dutch chemist invented the cocoa press to inject heavy fat into the roasted beans.', answer: 'FALSE', evidence: 'In 1828, a Dutch chemist invented the cocoa press, a machine capable of squeezing out the heavy fat from the roasted beans.' },
        { prompt: 'Corporations began packaging their sweets in highly decorative boxes.', answer: 'TRUE', evidence: 'Corporations began packaging their sweets in highly decorative boxes.' },
        { prompt: 'West African farmers struggle to maintain profitable yields during the rainy seasons.', answer: 'NOT GIVEN', evidence: 'West African farmers struggle to maintain profitable yields.' }
      ],
      headings: {
        options: ['The dark agricultural practices fueling global demand', 'The massive expansion of cacao plantations', 'Ancient Maya and Aztec civilizations', 'The transition from liquid luxury to mass-produced snack', 'The integration of sweets into cultural traditions', 'Associating their products with romance', 'Utilizing the seeds for regional taxation and rituals', 'The adaptation of the bitter recipe for elite European tastes'],
        questions: [
          { prompt: 'Paragraph E', answer: 'i', evidence: 'The aggressive expansion of cacao plantations continues to drive severe tropical deforestation and relies heavily on unregulated child labor to keep global prices artificially low.' },
          { prompt: 'Paragraph A', answer: 'vii', evidence: 'Deep within the Mesoamerican rainforests, the ancient Maya and Aztec civilizations revered the cacao tree, utilizing its fermented seeds as a literal form of currency to pay regional taxes.' },
          { prompt: 'Paragraph D', answer: 'v', evidence: `By associating their products with romance and holiday celebrations, brilliant corporate marketing campaigns successfully permanently embedded chocolate into global cultural traditions like Valentine's Day.` },
          { prompt: 'Paragraph B', answer: 'viii', evidence: 'Appalled by its intense bitterness, the Spanish heavily modified the drink by removing the chili and adding expensive cane sugar and vanilla, transforming it into an indulgent luxury reserved exclusively for the European nobility.' }
        ]
      }
    }
  }
}
