/**
 * Thai glosses for every letter-hint blank answer used in Writing Task 1, Task 2
 * and General Training that is not covered by COMMON_THAI_GLOSS or by authored
 * prompt vocab. Consulted as a fallback by resolveThaiMeaning so that *every*
 * blank can show a TH meaning and be saved to the Notebook.
 *
 * Keys are lowercase. Inflected forms are listed explicitly where they appear in
 * the data; writingLetterHint.ts also strips -s/-es/-ed/-ing/-ly as a last resort.
 */
export const WRITING_THAI_GLOSS_EXTRA: Record<string, string> = {
  ability: 'ความสามารถ',
  accelerate: 'เร่งให้เร็วขึ้น',
  accept: 'ยอมรับ',
  according: 'ตามที่ (according to = ตามข้อมูลจาก)',
  achievable: 'ที่ทำได้จริง',
  achieve: 'บรรลุผล, ทำสำเร็จ',
  across: 'ทั่ว, ข้าม',
  actively: 'อย่างกระตือรือร้น',
  actually: 'จริง ๆ แล้ว',
  addition: 'การเพิ่มเติม (in addition = นอกจากนี้)',
  address: 'จัดการกับ (ปัญหา)',
  advanced: 'ขั้นสูง',
  affect: 'ส่งผลกระทบต่อ',
  'age-appropriate': 'เหมาะกับวัย',
  aircraft: 'อากาศยาน, เครื่องบิน',
  allow: 'อนุญาต, ทำให้สามารถ',
  alongside: 'ควบคู่ไปกับ',
  alternative: 'ทางเลือก',
  although: 'แม้ว่า',
  among: 'ในบรรดา, ท่ามกลาง',
  amount: 'ปริมาณ',
  appearance: 'รูปลักษณ์ภายนอก',
  application: 'การนำไปใช้, ใบสมัคร',
  apply: 'สมัคร, นำไปใช้',
  argue: 'โต้แย้ง, ให้เหตุผลว่า',
  argues: 'โต้แย้ง, ให้เหตุผลว่า',
  around: 'ประมาณ, รอบ ๆ',
  artificial: 'ที่มนุษย์สร้างขึ้น, เทียม',
  assessing: 'การประเมิน',
  associate: 'เชื่อมโยง, เกี่ยวข้องกับ',
  associated: 'ที่เกี่ยวข้องกัน',
  attendance: 'การเข้าร่วม, การมาเรียน',
  attending: 'การเข้าร่วม',
  attention: 'ความสนใจ, ความใส่ใจ',
  attitudes: 'ทัศนคติ',
  attract: 'ดึงดูด',
  australia: 'ประเทศออสเตรเลีย',
  authorities: 'หน่วยงานรัฐ, ผู้มีอำนาจ',
  automatically: 'โดยอัตโนมัติ',
  available: 'ที่มีให้ใช้, หาได้',
  average: 'ค่าเฉลี่ย',
  avoid: 'หลีกเลี่ยง',
  avoiding: 'การหลีกเลี่ยง',
  balanced: 'ที่สมดุล',
  become: 'กลายเป็น',
  before: 'ก่อนหน้า',
  'beginner-friendly': 'เหมาะสำหรับผู้เริ่มต้น',
  behind: 'ตามหลัง, อยู่ข้างหลัง',
  believe: 'เชื่อว่า',
  beneficial: 'ที่เป็นประโยชน์',
  better: 'ดีกว่า',
  between: 'ระหว่าง',
  beyond: 'เกินกว่า',
  billion: 'พันล้าน',
  border: 'ชายแดน, พรมแดน',
  bottom: 'ล่างสุด',
  break: 'พัก, ทำให้แตก',
  bring: 'นำมาซึ่ง',
  british: 'ของอังกฤษ',
  building: 'อาคาร, การก่อสร้าง',
  buildings: 'อาคารหลายหลัง',
  business: 'ธุรกิจ',
  "cambodia's": 'ของประเทศกัมพูชา',
  cancer: 'โรคมะเร็ง',
  cannot: 'ไม่สามารถ',
  careful: 'ระมัดระวัง',
  carefully: 'อย่างระมัดระวัง',
  carry: 'ขนส่ง, ถือ',
  carrying: 'การขนส่ง, การถือ',
  categories: 'หมวดหมู่ (พหูพจน์)',
  category: 'หมวดหมู่',
  centre: 'ศูนย์กลาง, ใจกลาง',
  certain: 'บางอย่าง, แน่นอน',
  challenge: 'ความท้าทาย',
  chance: 'โอกาส',
  changing: 'ที่กำลังเปลี่ยนแปลง',
  cherries: 'ผลเชอร์รี (ของกาแฟ)',
  child: 'เด็ก',
  children: 'เด็ก ๆ',
  "children's": 'ของเด็ก ๆ',
  chinese: 'ของจีน, ชาวจีน',
  choose: 'เลือก',
  chulalongkorn: 'จุฬาลงกรณ์ (มหาวิทยาลัย)',
  cinemas: 'โรงภาพยนตร์',
  claim: 'อ้างว่า, กล่าวอ้าง',
  cleaner: 'สะอาดกว่า',
  clear: 'ชัดเจน',
  clinic: 'คลินิก',
  close: 'ใกล้, ปิด',
  closely: 'อย่างใกล้ชิด',
  'coca-cola': 'โคคา-โคลา (ยี่ห้อ)',
  collect: 'เก็บรวบรวม',
  collection: 'การเก็บรวบรวม',
  comfortably: 'อย่างสบาย',
  communication: 'การสื่อสาร',
  comparable: 'ที่เทียบเคียงกันได้',
  comparatively: 'โดยเปรียบเทียบแล้ว',
  compare: 'เปรียบเทียบ',
  compares: 'เปรียบเทียบ',
  compensate: 'ชดเชย',
  competition: 'การแข่งขัน',
  complete: 'ทำให้เสร็จสมบูรณ์',
  completed: 'ที่เสร็จสมบูรณ์แล้ว',
  completely: 'อย่างสมบูรณ์, โดยสิ้นเชิง',
  completion: 'การเสร็จสิ้น',
  computer: 'คอมพิวเตอร์',
  concentrated: 'ที่กระจุกตัว, เข้มข้น',
  concerned: 'ที่กังวล, ที่เกี่ยวข้อง',
  conscious: 'ที่ตระหนักรู้',
  consistently: 'อย่างสม่ำเสมอ',
  constant: 'คงที่, ต่อเนื่อง',
  construction: 'การก่อสร้าง',
  consume: 'บริโภค, ใช้ไป',
  context: 'บริบท',
  continue: 'ดำเนินต่อไป',
  contribute: 'มีส่วนช่วย',
  control: 'ควบคุม',
  controlled: 'ที่ถูกควบคุม',
  conversation: 'บทสนทนา',
  conversion: 'การเปลี่ยนสภาพ, การแปลง',
  convincing: 'ที่น่าเชื่อถือ',
  cooking: 'การทำอาหาร',
  costly: 'ที่มีราคาแพง',
  country: 'ประเทศ',
  crash: 'อุบัติเหตุชน',
  create: 'สร้าง',
  creating: 'การสร้าง',
  credit: 'เครดิต, หน่วยกิต',
  crisis: 'วิกฤต',
  crushed: 'ที่ถูกบดแล้ว',
  culminating: 'ที่ไปสิ้นสุดที่',
  currently: 'ในปัจจุบัน',
  customer: 'ลูกค้า',
  damages: 'ทำให้เสียหาย',
  decision: 'การตัดสินใจ',
  decisiveness: 'ความเด็ดขาด',
  defuse: 'คลี่คลาย (สถานการณ์)',
  deliberate: 'ที่ตั้งใจทำ',
  deliver: 'ส่งมอบ',
  demolition: 'การรื้อถอน',
  demonstrate: 'แสดงให้เห็น',
  departure: 'การออกเดินทาง',
  depend: 'ขึ้นอยู่กับ',
  dependable: 'ที่พึ่งพาได้',
  develop: 'พัฒนา',
  developed: 'ที่พัฒนาแล้ว',
  developmental: 'ด้านพัฒนาการ',
  diagram: 'แผนภาพ',
  differently: 'อย่างแตกต่างออกไป',
  dinner: 'อาหารเย็น',
  direct: 'โดยตรง',
  directly: 'อย่างตรงไปตรงมา, โดยตรง',
  disable: 'ปิดการใช้งาน',
  disagree: 'ไม่เห็นด้วย',
  discourage: 'ทำให้ไม่อยากทำ, บั่นทอนกำลังใจ',
  'distance-learning': 'การเรียนทางไกล',
  distract: 'ทำให้เสียสมาธิ',
  distribution: 'การกระจาย, การแจกจ่าย',
  districts: 'เขต, ย่าน',
  dominance: 'ความเป็นผู้นำ, การครองตลาด',
  driver: 'ผู้ขับขี่, ปัจจัยขับเคลื่อน',
  during: 'ในระหว่าง',
  earlier: 'ก่อนหน้านี้',
  earth: 'โลก, ดิน',
  eating: 'การรับประทาน',
  effective: 'ที่ได้ผล, มีประสิทธิภาพ',
  effects: 'ผลกระทบ',
  effortless: 'ที่ไม่ต้องออกแรง',
  elaborate: 'ขยายความ, อธิบายเพิ่มเติม',
  elaborated: 'ที่ขยายความแล้ว',
  electricity: 'ไฟฟ้า',
  ellen: 'เอลเลน (ชื่อคน)',
  embracing: 'การยอมรับ, การโอบรับ',
  emotionally: 'ในทางอารมณ์',
  employing: 'การจ้างงาน, การนำมาใช้',
  'employment-focused': 'ที่เน้นการมีงานทำ',
  encourage: 'สนับสนุน, กระตุ้นให้ทำ',
  encourages: 'สนับสนุน, กระตุ้นให้ทำ',
  encouraging: 'ที่ให้กำลังใจ',
  endangered: 'ที่ใกล้สูญพันธุ์',
  engineered: 'ที่ผ่านการดัดแปลงทางวิศวกรรม',
  english: 'ภาษาอังกฤษ',
  enjoy: 'เพลิดเพลินกับ',
  enjoyment: 'ความเพลิดเพลิน',
  enrolments: 'จำนวนผู้ลงทะเบียนเรียน',
  ensure: 'ทำให้มั่นใจว่า',
  entails: 'ทำให้ต้องมี, ประกอบด้วย',
  entirely: 'ทั้งหมด, โดยสิ้นเชิง',
  equip: 'ทำให้พร้อม, ติดตั้ง',
  essay: 'เรียงความ',
  establish: 'ก่อตั้ง, สร้างขึ้น',
  estimated: 'ที่ประมาณการไว้',
  event: 'เหตุการณ์, งาน',
  every: 'ทุก ๆ',
  everyday: 'ในชีวิตประจำวัน',
  everything: 'ทุกสิ่งทุกอย่าง',
  evident: 'ที่เห็นได้ชัด',
  evolve: 'วิวัฒนาการ, ค่อย ๆ เปลี่ยนไป',
  exceed: 'เกินกว่า',
  exceptionally: 'อย่างโดดเด่นเป็นพิเศษ',
  excessive: 'ที่มากเกินไป',
  exchange: 'แลกเปลี่ยน',
  exist: 'มีอยู่',
  expand: 'ขยายตัว',
  expectations: 'ความคาดหวัง',
  expected: 'ที่คาดว่าจะเกิดขึ้น',
  experiences: 'ประสบการณ์',
  explaining: 'การอธิบาย',
  exports: 'สินค้าส่งออก',
  expose: 'ทำให้ได้สัมผัส, เปิดเผย',
  extend: 'ขยายออกไป',
  extent: 'ระดับ, ขอบเขต',
  extreme: 'ที่รุนแรงสุดขั้ว',
  extremely: 'อย่างยิ่งยวด',
  facility: 'สถานที่, สิ่งอำนวยความสะดวก',
  factory: 'โรงงาน',
  family: 'ครอบครัว',
  farmers: 'เกษตรกร',
  farming: 'การทำเกษตรกรรม',
  favor: 'สนับสนุน, ชื่นชอบมากกว่า',
  fertiliser: 'ปุ๋ย',
  field: 'สาขา, ทุ่งนา',
  figure: 'ตัวเลข, จำนวน',
  financially: 'ในทางการเงิน',
  flights: 'เที่ยวบิน',
  focus: 'มุ่งเน้น',
  follow: 'ทำตาม, ติดตาม',
  following: 'ที่ตามมา',
  forces: 'บังคับ, แรงผลักดัน',
  foreign: 'ต่างประเทศ',
  forgets: 'ลืม',
  former: 'อดีต, อันแรก',
  freely: 'อย่างอิสระ',
  frequently: 'บ่อยครั้ง',
  fresh: 'สด, ใหม่',
  friendly: 'เป็นมิตร',
  fundamentally: 'โดยพื้นฐานแล้ว',
  future: 'อนาคต',
  garments: 'เสื้อผ้าเครื่องนุ่งห่ม',
  gender: 'เพศ',
  'gene-editing': 'การแก้ไขยีน',
  general: 'ทั่วไป',
  generally: 'โดยทั่วไป',
  generate: 'ผลิต, ก่อให้เกิด',
  genetic: 'ทางพันธุกรรม',
  genetically: 'ในทางพันธุกรรม',
  genuine: 'ที่แท้จริง',
  genuinely: 'อย่างแท้จริง',
  germany: 'ประเทศเยอรมนี',
  given: 'เมื่อพิจารณาจาก, ที่ให้ไว้',
  globally: 'ในระดับโลก',
  government: 'รัฐบาล',
  'government-controlled': 'ที่รัฐบาลควบคุม',
  gradual: 'ที่ค่อยเป็นค่อยไป',
  gradually: 'อย่างค่อยเป็นค่อยไป',
  "graduate's": 'ของบัณฑิต',
  graduation: 'การสำเร็จการศึกษา',
  granules: 'เม็ดเล็ก ๆ, เกล็ด',
  greater: 'มากกว่า',
  greatly: 'อย่างมาก',
  green: 'สีเขียว, ที่เป็นมิตรกับสิ่งแวดล้อม',
  greener: 'ที่เป็นมิตรกับสิ่งแวดล้อมมากขึ้น',
  guarantee: 'รับประกัน',
  guest: 'แขก, ผู้เข้าพัก',
  guide: 'แนะแนว, คู่มือ',
  happiness: 'ความสุข',
  harvesting: 'การเก็บเกี่ยว',
  having: 'การมี',
  healthy: 'ที่มีสุขภาพดี',
  helping: 'การช่วยเหลือ',
  'high-resolution': 'ความละเอียดสูง',
  'high-risk': 'ที่มีความเสี่ยงสูง',
  higher: 'สูงกว่า',
  highest: 'สูงที่สุด',
  historical: 'ทางประวัติศาสตร์',
  holiday: 'วันหยุด',
  hosting: 'การเป็นเจ้าภาพ',
  hotels: 'โรงแรม',
  household: 'ครัวเรือน',
  housework: 'งานบ้าน',
  'human-driven': 'ที่ขับเคลื่อนโดยมนุษย์',
  illness: 'ความเจ็บป่วย',
  immediate: 'ที่เกิดขึ้นทันที',
  impact: 'ผลกระทบ',
  important: 'สำคัญ',
  impossible: 'ที่เป็นไปไม่ได้',
  improve: 'ปรับปรุงให้ดีขึ้น',
  improved: 'ที่ดีขึ้น',
  improvement: 'การปรับปรุงให้ดีขึ้น',
  include: 'รวมถึง',
  increasingly: 'มากขึ้นเรื่อย ๆ',
  indeed: 'อันที่จริง',
  indicators: 'ตัวชี้วัด',
  indispensable: 'ที่ขาดไม่ได้',
  industrial: 'ทางอุตสาหกรรม',
  inevitably: 'อย่างหลีกเลี่ยงไม่ได้',
  influence: 'อิทธิพล, ส่งอิทธิพลต่อ',
  inherently: 'โดยเนื้อแท้',
  inherited: 'ที่สืบทอดมา',
  initial: 'ในช่วงแรก, เริ่มต้น',
  injuries: 'การบาดเจ็บ',
  innovate: 'สร้างนวัตกรรม',
  innovative: 'ที่เป็นนวัตกรรมใหม่',
  inspect: 'ตรวจสอบ',
  inspiration: 'แรงบันดาลใจ',
  instagram: 'อินสตาแกรม (แอปฯ)',
  instant: 'สำเร็จรูป, ทันที',
  instantly: 'ในทันที',
  instead: 'แทนที่จะ',
  institutions: 'สถาบัน',
  interactive: 'ที่มีการโต้ตอบ',
  introducing: 'การนำมาใช้, การแนะนำ',
  invention: 'สิ่งประดิษฐ์',
  invest: 'ลงทุน',
  invite: 'เชิญ',
  irreversible: 'ที่ย้อนกลับไม่ได้',
  japanese: 'ของญี่ปุ่น',
  journal: 'วารสาร',
  judgment: 'วิจารณญาณ, การตัดสิน',
  justified: 'ที่มีเหตุผลรองรับ',
  large: 'ขนาดใหญ่',
  largely: 'โดยส่วนใหญ่',
  larger: 'ใหญ่กว่า',
  largest: 'ใหญ่ที่สุด',
  lasting: 'ที่ยั่งยืน, คงอยู่นาน',
  leadership: 'ภาวะผู้นำ',
  learn: 'เรียนรู้',
  learners: 'ผู้เรียน',
  leave: 'ออกจาก, ทิ้งไว้',
  leaving: 'การออกจาก',
  leisure: 'เวลาว่าง, นันทนาการ',
  'life-saving': 'ที่ช่วยชีวิต',
  likely: 'มีแนวโน้มว่าจะ',
  limit: 'จำกัด, ขีดจำกัด',
  linked: 'ที่เชื่อมโยงกัน',
  liquid: 'ของเหลว',
  loneliness: 'ความเหงา',
  'long-term': 'ระยะยาว',
  'low-income': 'ที่มีรายได้น้อย',
  lowest: 'ต่ำที่สุด',
  machine: 'เครื่องจักร',
  'machine-learning': 'การเรียนรู้ของเครื่อง',
  major: 'สำคัญ, หลัก',
  majority: 'ส่วนใหญ่',
  mammal: 'สัตว์เลี้ยงลูกด้วยนม',
  manage: 'จัดการ',
  managed: 'ที่มีการจัดการ',
  mandatory: 'ที่บังคับ',
  manufacture: 'ผลิต',
  manufacturers: 'ผู้ผลิต',
  manufacturing: 'การผลิต',
  marked: 'ที่เห็นได้ชัด',
  markedly: 'อย่างเห็นได้ชัด',
  matter: 'มีความสำคัญ, เรื่อง',
  meaningful: 'ที่มีความหมาย',
  measurably: 'อย่างวัดผลได้',
  measured: 'ที่วัดได้, ซึ่งถูกวัด',
  memorable: 'ที่น่าจดจำ',
  merely: 'เพียงแค่',
  method: 'วิธีการ',
  might: 'อาจจะ',
  million: 'ล้าน',
  minimum: 'ขั้นต่ำ',
  minority: 'ส่วนน้อย',
  mission: 'ภารกิจ',
  modern: 'ทันสมัย',
  modified: 'ที่ถูกดัดแปลง',
  modify: 'ดัดแปลง, ปรับเปลี่ยน',
  moisture: 'ความชื้น',
  monthly: 'รายเดือน',
  mortality: 'อัตราการเสียชีวิต',
  'most-visited': 'ที่มีผู้มาเยือนมากที่สุด',
  motivated: 'ที่มีแรงจูงใจ',
  nationality: 'สัญชาติ',
  naturally: 'โดยธรรมชาติ',
  navigation: 'การนำทาง',
  nearby: 'ที่อยู่ใกล้เคียง',
  nearly: 'เกือบจะ',
  neglected: 'ที่ถูกละเลย',
  neighbourhood: 'ย่านที่อยู่อาศัย',
  neighbourly: 'อย่างเพื่อนบ้านที่ดี',
  networking: 'การสร้างเครือข่าย',
  'non-recycled': 'ที่ไม่ได้รีไซเคิล',
  notice: 'สังเกตเห็น',
  'notre-dame': 'น็อทร์-ดาม (มหาวิหาร)',
  nowhere: 'ไม่มีที่ไหนเลย',
  nuclear: 'นิวเคลียร์',
  number: 'จำนวน',
  numbers: 'ตัวเลข, จำนวน',
  numerous: 'จำนวนมาก',
  observed: 'ที่สังเกตพบ',
  occur: 'เกิดขึ้น',
  offered: 'ที่เสนอให้',
  office: 'สำนักงาน',
  often: 'บ่อยครั้ง',
  older: 'ที่มีอายุมากกว่า',
  'on-site': 'ที่หน้างาน, ในสถานที่จริง',
  opinion: 'ความคิดเห็น',
  optional: 'ที่เลือกได้, ไม่บังคับ',
  ordering: 'การสั่งซื้อ',
  original: 'ดั้งเดิม',
  others: 'คนอื่น ๆ',
  otherwise: 'มิฉะนั้น',
  outdated: 'ที่ล้าสมัย',
  outside: 'ภายนอก',
  outweigh: 'มีน้ำหนักมากกว่า',
  overspend: 'ใช้จ่ายเกินตัว',
  packaging: 'บรรจุภัณฑ์',
  pandemic: 'การระบาดใหญ่ทั่วโลก',
  paper: 'กระดาษ, บทความ',
  parking: 'ที่จอดรถ',
  'part-time': 'นอกเวลา, พาร์ทไทม์',
  particularly: 'โดยเฉพาะอย่างยิ่ง',
  partly: 'บางส่วน',
  pattern: 'รูปแบบ, แนวโน้ม',
  payment: 'การชำระเงิน',
  pedestrian: 'คนเดินเท้า',
  pellets: 'เม็ดวัสดุ',
  percent: 'เปอร์เซ็นต์',
  percentages: 'ค่าร้อยละ',
  perfect: 'สมบูรณ์แบบ',
  perform: 'ทำ, แสดง',
  permanently: 'อย่างถาวร',
  personalised: 'ที่ปรับให้เหมาะกับแต่ละคน',
  perspective: 'มุมมอง',
  pharmaceutical: 'ทางเภสัชกรรม',
  philosophy: 'ปรัชญา',
  police: 'ตำรวจ',
  popular: 'ที่ได้รับความนิยม',
  possess: 'ครอบครอง, มี',
  possible: 'ที่เป็นไปได้',
  possibly: 'อาจเป็นไปได้',
  powder: 'ผง',
  precision: 'ความแม่นยำ',
  predict: 'ทำนาย, คาดการณ์',
  preferable: 'ที่น่าเลือกมากกว่า',
  preoccupation: 'ความหมกมุ่น',
  prepare: 'เตรียม',
  'present-day': 'ในปัจจุบัน',
  presenting: 'การนำเสนอ',
  preserve: 'อนุรักษ์, รักษาไว้',
  prevent: 'ป้องกัน',
  prevention: 'การป้องกัน',
  previously: 'ก่อนหน้านี้',
  primarily: 'เป็นหลัก',
  private: 'ส่วนตัว, เอกชน',
  procedure: 'ขั้นตอนการดำเนินการ',
  process: 'กระบวนการ',
  product: 'ผลิตภัณฑ์',
  propose: 'เสนอ',
  protected: 'ที่ได้รับการคุ้มครอง',
  provide: 'จัดหาให้',
  providing: 'การจัดหาให้',
  publicly: 'อย่างเปิดเผยต่อสาธารณะ',
  publish: 'ตีพิมพ์, เผยแพร่',
  pupils: 'นักเรียน',
  pursue: 'ไล่ตาม, มุ่งศึกษาต่อ',
  pursuing: 'การมุ่งไล่ตาม',
  qualify: 'มีคุณสมบัติครบ',
  rapid: 'ที่รวดเร็ว',
  rapidly: 'อย่างรวดเร็ว',
  rarely: 'แทบไม่เคย',
  rated: 'ที่ถูกจัดอันดับ',
  rather: 'ค่อนข้าง, แทนที่จะ',
  readers: 'ผู้อ่าน',
  realistic: 'ที่สมจริง',
  realistically: 'ตามความเป็นจริง',
  reality: 'ความเป็นจริง',
  reason: 'เหตุผล',
  reasoning: 'การใช้เหตุผล',
  reasons: 'เหตุผล (พหูพจน์)',
  recall: 'นึกออก, ระลึกได้',
  receives: 'ได้รับ',
  reception: 'แผนกต้อนรับ, การตอบรับ',
  recorded: 'ที่บันทึกไว้',
  recover: 'ฟื้นตัว',
  recycling: 'การรีไซเคิล',
  reduce: 'ลดลง',
  reduced: 'ที่ลดลงแล้ว',
  'reduced-price': 'ราคาลดพิเศษ',
  reduction: 'การลดลง',
  regarding: 'เกี่ยวกับ',
  regular: 'สม่ำเสมอ, ปกติ',
  regularly: 'อย่างสม่ำเสมอ',
  rejection: 'การปฏิเสธ',
  relatively: 'ค่อนข้างจะ',
  relief: 'การบรรเทา, ความโล่งใจ',
  remain: 'ยังคง',
  removed: 'ที่ถูกนำออกไป',
  renewable: 'ที่หมุนเวียนใช้ใหม่ได้',
  renewables: 'พลังงานหมุนเวียน',
  rentals: 'การเช่า, ของให้เช่า',
  repeating: 'การทำซ้ำ',
  replace: 'แทนที่',
  represent: 'เป็นตัวแทนของ, คิดเป็น',
  require: 'ต้องการ, กำหนดให้ต้อง',
  required: 'ที่จำเป็นต้องมี',
  resist: 'ต่อต้าน, ทนต่อ',
  respect: 'เคารพ',
  respond: 'ตอบสนอง',
  response: 'การตอบสนอง',
  restaurants: 'ร้านอาหาร',
  result: 'ผลลัพธ์',
  retain: 'รักษาไว้, จดจำไว้',
  retention: 'การรักษาไว้ (เช่น พนักงาน)',
  retirement: 'การเกษียณอายุ',
  reveal: 'เปิดเผย',
  riverside: 'ริมแม่น้ำ',
  roasting: 'การคั่ว',
  robot: 'หุ่นยนต์',
  roughly: 'ราว ๆ, โดยประมาณ',
  routinely: 'เป็นกิจวัตร',
  salary: 'เงินเดือน',
  satisfaction: 'ความพึงพอใจ',
  saving: 'การประหยัด, การออม',
  scarcity: 'ความขาดแคลน',
  schedule: 'ตารางเวลา',
  scheduled: 'ที่กำหนดไว้ตามตาราง',
  schoolwork: 'งานที่โรงเรียน',
  science: 'วิทยาศาสตร์',
  scientific: 'ทางวิทยาศาสตร์',
  seafood: 'อาหารทะเล',
  season: 'ฤดูกาล',
  second: 'ที่สอง',
  'self-service': 'บริการตนเอง',
  sensible: 'ที่สมเหตุสมผล',
  seriously: 'อย่างจริงจัง',
  serve: 'ให้บริการ, เสิร์ฟ',
  setting: 'สภาพแวดล้อม, การตั้งค่า',
  several: 'หลาย ๆ',
  severe: 'ที่รุนแรง',
  shape: 'หล่อหลอม, รูปทรง',
  shared: 'ที่ใช้ร่วมกัน',
  shares: 'สัดส่วน, แบ่งปัน',
  sharp: 'ที่ชันหรือรุนแรง (การเปลี่ยนแปลง)',
  should: 'ควรจะ',
  similar: 'ที่คล้ายคลึงกัน',
  simple: 'เรียบง่าย',
  simpler: 'ง่ายกว่า',
  simply: 'เพียงแค่',
  slightly: 'เล็กน้อย',
  smaller: 'เล็กกว่า',
  smallest: 'เล็กที่สุด',
  smoothly: 'อย่างราบรื่น',
  snacks: 'ของว่าง',
  "society's": 'ของสังคม',
  southwest: 'ทิศตะวันตกเฉียงใต้',
  special: 'พิเศษ',
  species: 'สายพันธุ์',
  specifically: 'โดยเฉพาะเจาะจง',
  spend: 'ใช้จ่าย, ใช้เวลา',
  spoken: 'ที่เป็นการพูด',
  stages: 'ขั้นตอน',
  start: 'เริ่มต้น',
  stick: 'ยึดติด, ทำต่อเนื่อง',
  store: 'เก็บรักษา, ร้านค้า',
  strict: 'เข้มงวด',
  stricter: 'เข้มงวดขึ้น',
  strong: 'แข็งแกร่ง',
  strongest: 'แข็งแกร่งที่สุด',
  strongly: 'อย่างหนักแน่น',
  struggle: 'ดิ้นรน, มีความยากลำบาก',
  student: 'นักเรียน, นักศึกษา',
  successful: 'ที่ประสบความสำเร็จ',
  successfully: 'อย่างประสบความสำเร็จ',
  suddenly: 'อย่างกะทันหัน',
  suggesting: 'ซึ่งบ่งชี้ว่า',
  superior: 'ที่เหนือกว่า',
  supervised: 'ที่มีผู้ดูแล',
  supply: 'อุปทาน, จัดหาให้',
  supported: 'ที่ได้รับการสนับสนุน',
  supportive: 'ที่คอยสนับสนุน',
  supports: 'สนับสนุน',
  sustainable: 'ที่ยั่งยืน',
  table: 'ตาราง, โต๊ะ',
  taking: 'การเอา, การใช้เวลา',
  taught: 'สอน (ช่องสอง/สาม)',
  teach: 'สอน',
  technological: 'ทางเทคโนโลยี',
  television: 'โทรทัศน์',
  temperature: 'อุณหภูมิ',
  'ten-year': 'ระยะสิบปี',
  testing: 'การทดสอบ',
  thailand: 'ประเทศไทย',
  themselves: 'ตัวพวกเขาเอง',
  therefore: 'ดังนั้น',
  thinking: 'การคิด',
  'third-ranked': 'ที่อยู่อันดับสาม',
  thoughtful: 'ที่คิดอย่างรอบคอบ',
  thousands: 'หลายพัน',
  throughout: 'ตลอดทั่วทั้ง',
  'time-consuming': 'ที่กินเวลามาก',
  timetable: 'ตารางเวลา',
  together: 'ด้วยกัน',
  topics: 'หัวข้อ',
  tourist: 'นักท่องเที่ยว',
  towards: 'ไปในทิศทางของ',
  'town-centre': 'ใจกลางเมือง',
  'traffic-free': 'ที่ปลอดรถยนต์',
  track: 'ติดตาม, เส้นทาง',
  traded: 'ที่ซื้อขายกัน',
  train: 'ฝึกอบรม, รถไฟ',
  transformation: 'การเปลี่ยนแปลงครั้งใหญ่',
  transformations: 'การเปลี่ยนแปลงครั้งใหญ่ (พหูพจน์)',
  typically: 'โดยทั่วไปแล้ว',
  ultimately: 'ในที่สุด',
  unavailable: 'ที่ไม่พร้อมให้ใช้',
  unchanged: 'ที่ไม่เปลี่ยนแปลง',
  undeniable: 'ที่ปฏิเสธไม่ได้',
  underestimate: 'ประเมินต่ำเกินไป',
  understand: 'เข้าใจ',
  understandable: 'ที่พอเข้าใจได้',
  unfair: 'ที่ไม่ยุติธรรม',
  unfairly: 'อย่างไม่ยุติธรรม',
  unhealthy: 'ที่ไม่ดีต่อสุขภาพ',
  union: 'สหภาพ',
  unknown: 'ที่ไม่เป็นที่รู้จัก',
  unpaid: 'ที่ไม่ได้รับค่าจ้าง',
  unrecycled: 'ที่ไม่ได้รีไซเคิล',
  untidy: 'ที่ไม่เป็นระเบียบ',
  unverified: 'ที่ยังไม่ได้รับการยืนยัน',
  urgent: 'ที่เร่งด่วน',
  urgently: 'อย่างเร่งด่วน',
  useful: 'ที่มีประโยชน์',
  vietnam: 'ประเทศเวียดนาม',
  virtual: 'เสมือนจริง',
  visited: 'ที่มีผู้มาเยือน',
  vulnerable: 'ที่เปราะบาง',
  walking: 'การเดิน',
  watching: 'การดู',
  water: 'น้ำ',
  watering: 'การรดน้ำ',
  weaken: 'ทำให้อ่อนแอลง',
  weakest: 'อ่อนแอที่สุด',
  'well-documented': 'ที่มีหลักฐานบันทึกไว้ชัดเจน',
  whenever: 'เมื่อใดก็ตามที่',
  which: 'ซึ่ง',
  widely: 'อย่างกว้างขวาง',
  wiser: 'ฉลาดขึ้น, รอบคอบขึ้น',
  without: 'โดยปราศจาก',
  worldwide: 'ทั่วโลก',
  worthwhile: 'ที่คุ้มค่า',
  would: 'จะ (แสดงความน่าจะเป็น)',
  writing: 'การเขียน',
  young: 'ที่อายุน้อย',
  'younger-looking': 'ที่ดูอ่อนกว่าวัย',
  youth: 'เยาวชน',
  youthful: 'ที่ดูอ่อนเยาว์'
}

/**
 * Everyday vocabulary used in the General Training Task 1 letters. These are the
 * words the letter drill turns into letter-hint blanks, so each needs a Thai
 * gloss for the คำใบ้ chip and the Notebook save.
 */
export const GENERAL_TASK1_THAI_GLOSS: Record<string, string> = {
  already: 'เรียบร้อยแล้ว',
  afternoon: 'ช่วงบ่าย',
  afternoons: 'ช่วงบ่าย (หลายวัน)',
  ages: 'นานมาก (สำนวน)',
  agreed: 'เห็นพ้อง, ตกลง',
  always: 'เสมอ',
  angry: 'โกรธ',
  annual: 'ประจำปี',
  anyone: 'ใคร ๆ, ใครสักคน',
  anything: 'สิ่งใดก็ตาม',
  apologised: 'ขอโทษ (แล้ว)',
  appointment: 'การนัดหมาย',
  appreciate: 'ซาบซึ้ง, ขอบคุณ',
  area: 'พื้นที่, ย่าน',
  arrange: 'จัดการ, นัดแนะ',
  arrived: 'มาถึงแล้ว',
  assistance: 'ความช่วยเหลือ',
  assistant: 'ผู้ช่วย',
  attach: 'แนบไฟล์/เอกสาร',
  attached: 'ที่แนบมาด้วย',
  attend: 'เข้าร่วม',
  awful: 'แย่มาก',
  bathroom: 'ห้องน้ำ',
  beside: 'ข้าง ๆ',
  begin: 'เริ่มต้น',
  begins: 'เริ่มต้น',
  bills: 'ค่าใช้จ่าย, บิล',
  birthday: 'วันเกิด',
  blue: 'สีน้ำเงิน',
  boat: 'เรือ',
  boiler: 'เครื่องทำน้ำร้อน/หม้อต้ม',
  book: 'จอง, หนังสือ',
  booked: 'จองไว้แล้ว',
  borrowed: 'ยืมมา',
  breakfast: 'อาหารเช้า',
  bright: 'สว่าง, สดใส',
  broken: 'ที่พัง, เสีย',
  budget: 'งบประมาณ',
  cake: 'เค้ก',
  calmly: 'อย่างใจเย็น',
  cancelled: 'ที่ถูกยกเลิก',
  career: 'อาชีพการงาน',
  catch: 'จับ, ทัน (เช่น catch up)',
  caused: 'ก่อให้เกิด',
  chair: 'ทำหน้าที่ประธาน (การประชุม), เก้าอี้',
  change: 'เปลี่ยนแปลง',
  changes: 'การเปลี่ยนแปลง',
  check: 'ตรวจสอบ',
  chocolate: 'ช็อกโกแลต',
  chosen: 'ที่ถูกเลือก',
  city: 'เมือง',
  class: 'ชั้นเรียน',
  classes: 'ชั้นเรียน (พหูพจน์)',
  classmate: 'เพื่อนร่วมชั้น',
  client: 'ลูกค้า',
  cold: 'หนาว, เย็น',
  colder: 'หนาวขึ้น',
  colleague: 'เพื่อนร่วมงาน',
  comfortable: 'สบายใจ, สะดวก',
  communicate: 'สื่อสาร',
  company: 'บริษัท',
  complain: 'ร้องเรียน',
  confident: 'มั่นใจ',
  confirm: 'ยืนยัน',
  consideration: 'การพิจารณา',
  considerable: 'มากพอสมควร',
  contact: 'ติดต่อ',
  convenience: 'ความสะดวก (at your earliest convenience = เมื่อสะดวกที่สุด)',
  convenient: 'สะดวก',
  cost: 'ค่าใช้จ่าย, มีราคา',
  council: 'สภาท้องถิ่น, เทศบาล',
  course: 'หลักสูตร, คอร์ส',
  cover: 'ครอบคลุม, รับผิดชอบ',
  covered: 'ที่ครอบคลุมไว้',
  crime: 'อาชญากรรม',
  current: 'ปัจจุบัน',
  curriculum: 'หลักสูตร (curriculum vitae = ประวัติย่อ)',
  dangerous: 'อันตราย',
  dark: 'มืด',
  dates: 'วันที่ (พหูพจน์)',
  days: 'วัน (พหูพจน์)',
  deal: 'จัดการ (deal with = รับมือกับ)',
  degree: 'ปริญญา',
  delivery: 'การจัดส่ง',
  design: 'ออกแบบ, การออกแบบ',
  details: 'รายละเอียด',
  difficult: 'ยาก, ลำบาก',
  digital: 'ดิจิทัล',
  diploma: 'ประกาศนียบัตร',
  disappeared: 'หายไป',
  discuss: 'พูดคุยหารือ',
  documents: 'เอกสาร',
  doctor: 'แพทย์',
  draw: 'ดึงความสนใจ (draw attention), วาด',
  earliest: 'เร็วที่สุด',
  easily: 'อย่างง่ายดาย',
  economics: 'วิชาเศรษฐศาสตร์',
  elderly: 'ผู้สูงอายุ',
  electric: 'ที่ใช้ไฟฟ้า',
  email: 'อีเมล',
  embarrass: 'ทำให้อับอาย',
  emergency: 'เหตุฉุกเฉิน',
  energy: 'พลังงาน',
  engineer: 'ช่าง, วิศวกร',
  enormously: 'อย่างมหาศาล',
  enquire: 'สอบถาม',
  envelope: 'ซองจดหมาย',
  evening: 'ตอนเย็น',
  evenings: 'ตอนเย็น (หลายวัน)',
  everyone: 'ทุกคน',
  examples: 'ตัวอย่าง (พหูพจน์)',
  expect: 'คาดหวัง',
  expecting: 'กำลังคาดหวังว่า',
  expensive: 'ราคาแพง',
  experience: 'ประสบการณ์',
  explain: 'อธิบาย',
  facts: 'ข้อเท็จจริง',
  fails: 'ล้มเหลว, ไม่ทำงาน',
  fair: 'ยุติธรรม',
  fairly: 'ค่อนข้าง, อย่างยุติธรรม',
  faulty: 'ที่ชำรุด',
  feedback: 'ข้อเสนอแนะ',
  feel: 'รู้สึก',
  feeling: 'ความรู้สึก',
  fees: 'ค่าธรรมเนียม',
  felt: 'รู้สึก (ช่องสอง)',
  fifth: 'ที่ห้า',
  file: 'แฟ้ม, ไฟล์งาน',
  final: 'สุดท้าย',
  finish: 'ทำให้เสร็จ',
  finished: 'ที่เสร็จแล้ว',
  first: 'อันดับแรก, ก่อนอื่น',
  five: 'ห้า',
  flat: 'อพาร์ตเมนต์, แบน',
  forgot: 'ลืม (ช่องสอง)',
  form: 'แบบฟอร์ม',
  forward: 'ไปข้างหน้า (look forward to = ตั้งตารอ)',
  found: 'พบ, เจอ',
  fourteen: 'สิบสี่',
  front: 'ด้านหน้า (in front of = ต่อหน้า)',
  full: 'เต็ม',
  further: 'เพิ่มเติม',
  gave: 'ให้ (ช่องสอง)',
  giving: 'การให้',
  grandparents: 'ปู่ย่าตายาย',
  grateful: 'รู้สึกขอบคุณ',
  group: 'กลุ่ม',
  guesses: 'การเดา',
  handout: 'เอกสารประกอบ',
  happy: 'มีความสุข, ยินดี',
  harbour: 'ท่าเรือ',
  hate: 'เกลียด',
  hear: 'ได้ยิน',
  hearing: 'การได้ยิน/ได้ข่าว (look forward to hearing = รอฟังข่าว)',
  heater: 'เครื่องทำความร้อน',
  heating: 'ระบบทำความร้อน',
  held: 'จัดขึ้น (ช่องสาม)',
  help: 'ช่วยเหลือ',
  highly: 'อย่างสูง',
  hold: 'ถือครอง, มี (วุฒิ)',
  home: 'บ้าน',
  hope: 'หวัง',
  hoping: 'หวังว่า',
  hour: 'ชั่วโมง',
  house: 'บ้าน',
  ideas: 'ความคิด',
  ignored: 'เพิกเฉย, ไม่สนใจ',
  inconvenience: 'ความไม่สะดวก',
  inform: 'แจ้งให้ทราบ',
  instructions: 'คำแนะนำการใช้งาน',
  interrupt: 'ขัดจังหวะ',
  interview: 'การสัมภาษณ์',
  item: 'สินค้า, รายการ',
  itself: 'ตัวมันเอง',
  jacket: 'เสื้อแจ็กเก็ต',
  join: 'เข้าร่วม',
  judgement: 'วิจารณญาณ',
  keeping: 'การรักษาไว้ (keeping well = สบายดี)',
  kept: 'เก็บไว้ (ช่องสอง)',
  kerb: 'ขอบทางเท้า',
  lamps: 'โคมไฟ',
  lasts: 'กินเวลา, คงอยู่',
  late: 'สาย, ช้า',
  later: 'ภายหลัง',
  leather: 'หนัง (วัสดุ)',
  lecture: 'การบรรยาย',
  lighting: 'ระบบแสงสว่าง',
  local: 'ท้องถิ่น',
  looked: 'ดู, มอง (ช่องสอง)',
  lose: 'สูญเสีย, ทำหาย',
  loud: 'เสียงดัง',
  love: 'รัก',
  lovely: 'น่ารัก, ดีงาม',
  lunchtime: 'ช่วงพักกลางวัน',
  magazine: 'นิตยสาร',
  makes: 'ทำให้',
  making: 'การทำ',
  manager: 'ผู้จัดการ',
  mark: 'คะแนน',
  market: 'ตลาด',
  marketing: 'การตลาด',
  medicine: 'ยา',
  meet: 'พบ, เจอ',
  meeting: 'การประชุม',
  meetings: 'การประชุม (พหูพจน์)',
  memories: 'ความทรงจำ',
  minute: 'นาที',
  minutes: 'นาที (พหูพจน์)',
  missed: 'พลาด, คิดถึง',
  moment: 'ช่วงเวลาสั้น ๆ',
  month: 'เดือน',
  move: 'ย้าย',
  moved: 'ย้ายแล้ว',
  nasty: 'ร้ายแรง, น่ารังเกียจ',
  near: 'ใกล้',
  neighbour: 'เพื่อนบ้าน',
  night: 'กลางคืน',
  ninety: 'เก้าสิบ',
  nineteenth: 'ที่สิบเก้า',
  noise: 'เสียงรบกวน',
  notes: 'บันทึกย่อ',
  nothing: 'ไม่มีอะไร',
  offer: 'ข้อเสนอ, เสนอ',
  online: 'ออนไลน์',
  opportunity: 'โอกาส',
  order: 'คำสั่งซื้อ, สั่งซื้อ',
  organised: 'เป็นระเบียบ, มีการจัดการ',
  padded: 'ที่บุกันกระแทก',
  paid: 'จ่ายแล้ว',
  park: 'สวนสาธารณะ',
  particular: 'เฉพาะเจาะจง',
  passing: 'ที่ผ่านไป',
  pavement: 'ทางเท้า',
  people: 'ผู้คน',
  person: 'บุคคล (in person = ด้วยตนเอง)',
  personal: 'ส่วนตัว',
  photos: 'รูปถ่าย',
  place: 'สถานที่',
  plan: 'แผน, วางแผน',
  please: 'กรุณา',
  plenty: 'มากมาย (plenty of = เยอะแยะ)',
  position: 'ตำแหน่งงาน',
  post: 'ไปรษณีย์, ส่งไปรษณีย์',
  pounds: 'ปอนด์ (สกุลเงิน)',
  prefer: 'ชอบมากกว่า',
  present: 'ของขวัญ, ปัจจุบัน',
  price: 'ราคา',
  print: 'พิมพ์ออกมา',
  printer: 'เครื่องพิมพ์',
  probably: 'คงจะ, น่าจะ',
  problem: 'ปัญหา',
  project: 'โครงงาน',
  prospectus: 'สูจิบัตร/คู่มือหลักสูตร',
  purchased: 'ที่ซื้อมา',
  qualification: 'คุณวุฒิ',
  quick: 'รวดเร็ว',
  quickly: 'อย่างรวดเร็ว',
  quiet: 'เงียบสงบ',
  radiators: 'เครื่องทำความร้อน (แผง)',
  reachable: 'ที่ติดต่อได้',
  reading: 'การอ่าน',
  really: 'จริง ๆ',
  receive: 'ได้รับ',
  received: 'ได้รับ (ช่องสอง/สาม)',
  recently: 'เมื่อเร็ว ๆ นี้',
  record: 'บันทึกไว้',
  refund: 'การคืนเงิน',
  reference: 'จดหมายรับรอง, การอ้างอิง',
  relax: 'ผ่อนคลาย',
  remember: 'จำได้',
  reminds: 'ทำให้นึกถึง',
  remotely: 'จากระยะไกล',
  renting: 'การเช่า',
  repair: 'ซ่อมแซม',
  repeat: 'พูดซ้ำ, ทำซ้ำ',
  replacement: 'ของทดแทน',
  reply: 'ตอบกลับ',
  reports: 'รายงาน (พหูพจน์)',
  residents: 'ผู้อยู่อาศัย',
  resetting: 'การรีเซ็ต',
  resolved: 'ที่แก้ไขเรียบร้อย',
  rest: 'ส่วนที่เหลือ, พักผ่อน',
  restart: 'เริ่มใหม่',
  resurfaced: 'ที่ปูผิวใหม่',
  returning: 'การส่งคืน',
  risen: 'สูงขึ้น (ช่องสาม)',
  risk: 'ความเสี่ยง',
  road: 'ถนน',
  role: 'บทบาท, ตำแหน่ง',
  room: 'ห้อง',
  runs: 'จัดขึ้นเป็นประจำ, วิ่ง',
  sales: 'ยอดขาย',
  seem: 'ดูเหมือนว่า',
  seminar: 'สัมมนา',
  send: 'ส่ง',
  service: 'บริการ',
  session: 'คาบเรียน, ช่วงกิจกรรม',
  share: 'แบ่งปัน',
  short: 'สั้น',
  silver: 'สีเงิน',
  sink: 'อ่างล้าง',
  skills: 'ทักษะ',
  slides: 'สไลด์นำเสนอ',
  small: 'เล็ก',
  someone: 'ใครบางคน',
  sorry: 'เสียใจ, ขอโทษ',
  sound: 'ฟังดู, เสียง',
  sounded: 'ฟังดูเหมือน',
  spare: 'สำรอง, ว่าง',
  specific: 'เฉพาะเจาะจง',
  spoke: 'พูด (ช่องสอง)',
  stated: 'ที่ระบุไว้',
  statement: 'ข้อความ, เรียงความแนะนำตัว',
  station: 'สถานี',
  stay: 'พัก, อยู่ต่อ',
  stayed: 'พักอยู่ (ช่องสอง)',
  stopped: 'หยุด (ช่องสอง)',
  straightaway: 'ทันที',
  strap: 'สายรัด, สายนาฬิกา',
  street: 'ถนน',
  strengths: 'จุดแข็ง',
  studies: 'การเรียน',
  suggestions: 'ข้อเสนอแนะ',
  suit: 'เหมาะกับ',
  suits: 'เหมาะกับ',
  sunset: 'พระอาทิตย์ตก',
  suppliers: 'ซัพพลายเออร์, ผู้จัดส่งสินค้า',
  switch: 'สวิตช์, เปิด-ปิด',
  switches: 'สวิตช์ (พหูพจน์), สลับ',
  system: 'ระบบ',
  takes: 'ใช้เวลา, นำไป',
  taken: 'ถูกนำไป (ช่องสาม)',
  talk: 'พูดคุย',
  task: 'งานที่ได้รับมอบหมาย',
  tasks: 'งานที่ได้รับมอบหมาย (พหูพจน์)',
  team: 'ทีม',
  teams: 'ทีม (พหูพจน์)',
  tell: 'บอก',
  tenth: 'ที่สิบ',
  terrible: 'แย่มาก',
  thank: 'ขอบคุณ',
  third: 'ที่สาม',
  three: 'สาม',
  told: 'บอก (ช่องสอง)',
  total: 'ทั้งหมด, ยอดรวม',
  towels: 'ผ้าเช็ดตัว',
  transcript: 'ใบแสดงผลการเรียน',
  travelling: 'การเดินทาง',
  tried: 'พยายามแล้ว',
  trip: 'ทริป, การเดินทาง',
  trust: 'ไว้วางใจ',
  turn: 'ผลัดกัน, หมุน',
  twice: 'สองครั้ง',
  unable: 'ไม่สามารถ',
  unclear: 'ไม่ชัดเจน',
  uneven: 'ขรุขระ, ไม่เรียบ',
  university: 'มหาวิทยาลัย',
  unpacking: 'การเก็บของออกจากกล่อง',
  unreasonable: 'ไม่มีเหตุผล',
  unsafe: 'ไม่ปลอดภัย',
  unsure: 'ไม่แน่ใจ',
  upset: 'เสียใจ, ไม่พอใจ',
  urge: 'เรียกร้อง, กระตุ้น',
  urgency: 'ความเร่งด่วน',
  valuable: 'มีค่า',
  visit: 'มาเยี่ยม, การมาเยือน',
  vitae: 'ประวัติ (curriculum vitae = เรซูเม่)',
  waited: 'รอ (ช่องสอง)',
  walk: 'เดิน',
  wanted: 'ต้องการ (ช่องสอง)',
  watch: 'นาฬิกาข้อมือ, ดู',
  weather: 'สภาพอากาศ',
  website: 'เว็บไซต์',
  week: 'สัปดาห์',
  weekend: 'สุดสัปดาห์',
  weekly: 'รายสัปดาห์',
  welcome: 'ยินดีต้อนรับ, ยินดี',
  whether: 'ว่า…หรือไม่',
  window: 'หน้าต่าง',
  wireless: 'ไร้สาย',
  wish: 'ปรารถนา',
  worked: 'ทำงาน (ช่องสอง)',
  working: 'ที่ทำงานอยู่, การทำงาน',
  worn: 'สวมใส่แล้ว (ช่องสาม)',
  worried: 'กังวล',
  write: 'เขียน',
  year: 'ปี',
  years: 'ปี (พหูพจน์)'
}
